### ISSUE TITLE
Chinese can't download Pretrained-models

### ISSUE THREAD

**Issue by ljy-002** [CorentinJ/Real-Time-Voice-Cloning#1002]
[Pretrained-models](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models)
In this link, the download source is Google, but China has already implemented access to Google.
![image](https://user-images.githubusercontent.com/63292034/152285358-70787c4a-94e2-48a7-8e1f-93a8a8d9e51f.png)
![image](https://user-images.githubusercontent.com/63292034/152285375-002a267b-019b-4f5e-910f-a8bb21da9c5a.png)

**Comment by ljy-002** [comment]
So I would like to ask you guys to upload this package on GitHub

**Comment by raccoonML** [comment]
Pretrained models can be downloaded here.
https://github.com/raccoonML/Real-Time-Voice-Cloning/releases/tag/RTVC-7

**Comment by raccoonML** [comment]
I have uploaded model files and a complete working setup to Github. See this page for download links.
https://github.com/raccoonML/Real-Time-Voice-Cloning/releases/tag/rtvc_upstream_2-3-22

**Comment by ljy-002** [comment]
ok ,thank you very much
