### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by chaotianjiao** [CorentinJ/Real-Time-Voice-Cloning#101]
Hello~Firstly, It's a nice repo! Best wishes to you!
I have pip all the packages and the enviroment,But Mac doesn't have cuda and every time I click:
![image](https://user-images.githubusercontent.com/42534375/63909512-8261f700-ca55-11e9-9b60-0165c5de338f.png)
I got this error:
AssertionError: Torch not compiled with CUDA enabled
How can I fix it?

**Comment by CorentinJ** [comment]
Thank you. You need a GPU and torch installed with cuda. Otherwise you can try to look for help in #54.
