### ISSUE TITLE
Execution Speed on GPU or how to make it faster

### ISSUE THREAD

**Issue by Sameerhesta** [CorentinJ/Real-Time-Voice-Cloning#1013]
Hello,
I am trying to use this library but it takes lots of time for the text to speech in my own voice,
1. Can it perform faster on GPU?
2. If yes, how much can it be faster on which GPU?
3. Can it convert a sentence into audio within 1 sec?
sentence example:- I am trying to use this library but it takes lots of time for the text to speech in my own voice

If it is possible to perform faster please let me know the approach.

**Comment by raccoonML** [comment]
The vocoder is by far the slowest of the models. The one used in this repo (wavernn) has been surpassed by recent vocoders that are 2-3 orders of magnitude faster with better quality. If you need faster inference, swap out the vocoder model. However, it's much easier said than done and I lack the time to write detailed instructions on how to do it.

You can study the code of similar projects like [Mockingbird](https://github.com/babysor/Mockingbird), which has the option to use a hifi-gan vocoder. I also have an open task to integrate the same hifi-gan vocoder into a similar voice cloning TTS project. For updates, watch this issue. https://github.com/sveneschlbeck/Multi-Language-RTVC/issues/20
