### ISSUE TITLE
Dumb Question about a setup error

### ISSUE THREAD

**Issue by TheChillzed** [CorentinJ/Real-Time-Voice-Cloning#1014]
When I run the: `python demo_toolbox.py` command I get an error telling me that the download for _synthesizer.pt_ failed and I have to download it from a google drive link. When I have the file downloaded, can I just unzip the .zip and put the files in the: `Real-Tome-Voice-Cloning` directory? Or do I have to do something else to get the program to work?

**Comment by raccoonML** [comment]
Place the model files in this location:
```
File location                         Filesize
-----------------------------------------------
saved_models/default/encoder.pt         17 MB
saved_models/default/synthesizer.pt    370 MB
saved_models/default/vocoder.pt         53 MB
```

If you continue having trouble, you can try my RTVC_Windows.zip file that contains the repo's code, model files, and a standalone FFmpeg.exe in a ready-to-go package.
https://github.com/raccoonML/Real-Time-Voice-Cloning/releases/tag/rtvc_upstream_2-3-22
