### ISSUE TITLE
LibriSpeech samples produce near-excellent results but others don't

### ISSUE THREAD

**Issue by postacik** [CorentinJ/Real-Time-Voice-Cloning#102]
For example, when I record my own voice (I count from 1 to 10 in a 10 second recording), the result is not a bit close.

What may be the reason for this?

**Comment by CorentinJ** [comment]
VoxCeleb samples usually aren't too bad for the most part. Also, the synthesizer/vocoder are strictly trained on native English speakers, so if you have any kind of accent you can expect it to fail.

**Comment by postacik** [comment]
When I say "others", I mean for the recordings I supply.

I am not a native English speaker but I also tried with samples from Donald Trump's speech and it also does not give the same good results.

Did you use the following datasets for training? Can that be the reason?

        LibriSpeech/dev-clean
        LibriSpeech/dev-other
        LibriSpeech/test-clean
        LibriSpeech/test-other
        LibriSpeech/train-clean-100
        LibriSpeech/train-clean-360
        LibriSpeech/train-other-500
        LibriTTS/dev-clean
        LibriTTS/dev-other
        LibriTTS/test-clean
        LibriTTS/test-other
        LibriTTS/train-clean-100
        LibriTTS/train-clean-360
        LibriTTS/train-other-500
        LJSpeech-1.1
        VoxCeleb1/wav
        VoxCeleb1/test_wav
        VoxCeleb2/dev/aac
        VoxCeleb2/test/aac
        VCTK-Corpus/wav48

**Comment by CorentinJ** [comment]
Well yeah you can expect better performance on data used for training. The speaker encoder is trained on VoxCeleb1 & 2 + the LibriSpeech-other sets while the synthesizer/vocoder are trained on the Librispeech-clean sets.
