### ISSUE TITLE
Preprocess dataset

### ISSUE THREAD

**Issue by ireneb612** [CorentinJ/Real-Time-Voice-Cloning#1031]
Hi! I have already done a training with the english symbols on an italian dataset! What differes are some accented letters that now I would like to add. So I have changed the symbols and started a new training of the synthesizer! But accents are not pronunced, do I have to do the pre processing of the dataset again?? I cannot see where the symbols are used in the preprocessing part so I am confused!

**Comment by raccoonML** [comment]
In preprocess, the text is copied verbatim from the transcripts to the train.txt file. Check your transcripts and make sure they contain accented letters. The text processing functions are applied during training. In hparams, there is a line for selecting a text cleaner ([tts_cleaner_names](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/0713f860a3dd41afb56e83cff84dbdf589d5e11a/synthesizer/hparams.py#L45)). The selected [text cleaner](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/synthesizer/utils/cleaners.py) should not include `convert_to_ascii()` as that will remove accents from the letters.

**Comment by ireneb612** [comment]
@raccoonML  ok so I think I had some issues with the encoding of my txt file, Nayway I selected the basic_cleaners that do not have that function! Thank you a lot :)
