### ISSUE TITLE
Data used for pretraining speaker encoder?

### ISSUE THREAD

**Issue by cheulyop** [CorentinJ/Real-Time-Voice-Cloning#1032]
A similar question was asked in #78 but it was closed without an answer.

So, on which data is the provided speaker encoder pretrained? I looked through the wiki and issues but couldn't find an answer.
Was it pretrained on a combination of LibriSpeech and VoxCeleb 1 & 2, as mentioned in the thesis? @CorentinJ

![image](https://user-images.githubusercontent.com/36708385/156475962-2d9561e9-3fa2-45cd-a774-e7b82a121809.png)

In our case, we are taking the pretrained encoder (encoder.pt) and looking to fine-tune its last linear layer and similarity scaling parameters with a dataset of our interest.

Knowing on which data the encoder was pretrained would be of much help.

**Comment by CorentinJ** [comment]
The training data was the training set from LibriSpeech, VoxCeleb1 Dev A - D and VoxCeleb2, resulting into 3201 hours of data with 8371 different speakers.
