### ISSUE TITLE
No such file or directory: 'encoder/encoder.pt'

### ISSUE THREAD

**Issue by AntonTRX** [CorentinJ/Real-Time-Voice-Cloning#1033]
---------------# Initializing all the encoder libraries
from IPython.display import Audio
from IPython.utils import io
from synthesizer.inference import Synthesizer
from encoder import inference as encoder
from vocoder import inference as vocoder
from pathlib import Path
import numpy as np
import librosa
encoder_weights = Path("encoder/encoder.pt")
vocoder_weights = Path("vocoder/saved_models/pretrained/pretrained.pt")
syn_dir = Path("synthesizer/saved_models/logs-pretrained/taco_pretrained")
encoder.load_model(encoder_weights)
synthesizer = Synthesizer(syn_dir)
vocoder.load_model(vocoder_weights)
------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-27-38db2b658233>](https://localhost:8080/#) in <module>()
     11 vocoder_weights = Path("vocoder/saved_models/pretrained/pretrained.pt")
     12 syn_dir = Path("synthesizer/saved_models/logs-pretrained/taco_pretrained")
---> 13 encoder.load_model(encoder_weights)
     14 synthesizer = Synthesizer(syn_dir)
     15 vocoder.load_model(vocoder_weights)

3 frames
[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in __init__(self, name, mode)
    209 class _open_file(_opener):
    210     def __init__(self, name, mode):
--> 211         super(_open_file, self).__init__(open(name, mode))
    212 
    213     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'encoder/encoder.pt'

**Comment by andrew-fennell** [comment]
You will need to download the encoder.pt, synthesizer.pt, and vocoder.pt files [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models).

Make sure that the **paths** are correct. If you put your encoder model at "saved_models/default/encoder.pt", you need to change the path to that instead of encoder/encoder.pt.
