### ISSUE TITLE
Issue Exception:

### ISSUE THREAD

**Issue by Dawnology** [CorentinJ/Real-Time-Voice-Cloning#1055]
Hello
I've got an issue when trying to upload audio.

https://user-images.githubusercontent.com/104293532/164960133-db7902d7-3cd8-430b-999d-d53e69a68f8f.mp4

Did I wrong at something?

**Comment by Dawnology** [comment]
solved

**Comment by AhsanSarwar45** [comment]
@Dawnology Can you explain how you solved this?
