### ISSUE TITLE
VoxCeleb 1/2 dataset gone (takendown?)

### ISSUE THREAD

**Issue by TrycsPublic** [CorentinJ/Real-Time-Voice-Cloning#1070]
The dataset was available before February, went to "temporary unavailable" then the whole dataset vanished from the internet, no one talks about the disappearance of a such important dataset in the ML community, no records of it, some info I can find on the archive search engine was some deepfake related to facial impersonation with the FBI. Seems its wiped out from the internet.

can someone send me a private link if you still have the dataset? thank you very much!

**Comment by raccoonML** [comment]
Try this link: https://mm.kaist.ac.kr/datasets/voxceleb/

One of the Voxceleb authors previously worked at this lab which may explain why it's mirrored here.
