### ISSUE TITLE
spyder 3.3.6 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.13.0 which is incompatible

### ISSUE THREAD

**Issue by marcoippolito** [CorentinJ/Real-Time-Voice-Cloning#109]
(base) marco@pc:~/Real-Time-Voice-Cloning$ pip3 install -r requirements.txt
    Collecting tensorflow-gpu<=1.14.0,>=1.10.0 (from -r requirements.txt (line 1))
      Using cached https://files.pythonhosted.org/packages/32/67  
    /559ca8408431c37ad3a17e859c8c291ea82f092354074baef482b98ffb7b/tensorflow_gpu-1.14.0-  
    cp37-cp37m-manylinux1_x86_64.whl
    Collecting umap-learn (from -r requirements.txt (line 2))
    Collecting visdom (from -r requirements.txt (line 3))
    Requirement already satisfied: webrtcvad in /home/marco/anaconda3/lib/python3.7/site-packages 
    (from -r requirements.txt (line 4)) (2.0.10)
    Requirement already satisfied: librosa>=0.5.1 in /home/marco/anaconda3/lib/python3.7/site-
    packages (from -r requirements.txt (line 5)) (0.7.0)
    Requirement already satisfied: matplotlib>=2.0.2 in /home/marco/anaconda3/lib/python3.7/site-
    packages (from -r requirements.txt (line 6)) (3.1.1)
    Requirement already satisfied: numpy>=1.14.0 in /home/marco/anaconda3/lib/python3.7/site-
    packages (from -r requirements.txt (line 7)) (1.17.1)
    Requirement already satisfied: scipy>=1.0.0 in /home/marco/anaconda3/lib/python3.7/site-
    packages (from -r requirements.txt (line 8)) (1.3.1)
    Collecting tqdm (from -r requirements.txt (line 9))
      Downloading https://files.pythonhosted.org/packages/dc/88
    /d3213e2f3492daf09d8b41631ad6899f56db17ce83ea9c8a579902bafe5e/tqdm-4.35.0-py2.py3-
    none-any.whl (50kB)
         |████████████████████████████████| 51kB 6.0MB/s 
    Collecting sounddevice (from -r requirements.txt (line 10))
       Using cached https://files.pythonhosted.org/packages/d1/f2
    /7cb487ac7171dfade8af7a368bd8806ecff82016f4ac9894835cd7de9ecc/sounddevice-0.3.13- 
    py2.py3-none-any.whl
    Collecting Unidecode (from -r requirements.txt (line 11))
      Using cached https://files.pythonhosted.org/packages/d0/42
    /d9edfed04228bacea2d824904cae367ee9efd05e6cce7ceaaedd0b0ad964/Unidecode-1.1.1-
    py2.py3-none-any.whl
    Collecting inflect (from -r requirements.txt (line 12))
      Using cached https://files.pythonhosted.org/packages/86/02 
    /e6b11020a9c37d25b4767a1d0af5835629f6e75d6f51553ad07a4c73dc31/inflect-2.1.0-py2.py3-
    none-any.whl
    Collecting PyQt5 (from -r requirements.txt (line 13))
      Using cached https://files.pythonhosted.org/packages/85/bd
    /8a0c863802449f35ad9ca21a1b73190639c206758b4b5e2425617fc99ce9/PyQt5-5.13.0-5.13.0-
    cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl
    Collecting multiprocess (from -r requirements.txt (line 14))
    Requirement already satisfied: numba in /home/marco/anaconda3/lib/python3.7/site-packages 
    (from -r requirements.txt (line 15)) (0.45.1)
     Requirement already satisfied: absl-py>=0.7.0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (0.8.0)
    Requirement already satisfied: astor>=0.6.0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (0.8.0)
    Requirement already satisfied: google-pasta>=0.1.6 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (0.1.7)
    Requirement already satisfied: protobuf>=3.6.1 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (3.9.1)
    Requirement already satisfied: wrapt>=1.11.1 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (1.11.2)
    Requirement already satisfied: six>=1.10.0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (1.12.0)
    Requirement already satisfied: grpcio>=1.8.6 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (1.23.0)
    Requirement already satisfied: wheel>=0.26 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (0.33.4)
    Requirement already satisfied: gast>=0.2.0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (0.2.2)
    Requirement already satisfied: termcolor>=1.1.0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (1.1.0)
    Requirement already satisfied: keras-preprocessing>=1.0.5 in /home/marco/anaconda3
    /lib/python3.7/site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) 
    (1.1.0)
    Requirement already satisfied: keras-applications>=1.0.6 in /home/marco/anaconda3/lib/python3.7
    /site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (1.0.8)
    Requirement already satisfied: tensorboard<1.15.0,>=1.14.0 in /home/marco/anaconda3
    /lib/python3.7/site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) 
    (1.14.0)
    Requirement already satisfied: tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 in /home/marco
    /anaconda3/lib/python3.7/site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r 
    requirements.txt (line 1)) (1.14.0)
    Requirement already satisfied: scikit-learn>=0.16 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from umap-learn->-r requirements.txt (line 2)) (0.21.2)
    Requirement already satisfied: torchfile in /home/marco/anaconda3/lib/python3.7/site-packages 
     (from visdom->-r requirements.txt (line 3)) (0.1.0)
    Requirement already satisfied: pyzmq in /home/marco/anaconda3/lib/python3.7/site-packages 
     (from visdom->-r requirements.txt (line 3)) (18.0.0)
    Requirement already satisfied: requests in /home/marco/anaconda3/lib/python3.7/site-packages 
     (from visdom->-r requirements.txt (line 3)) (2.22.0)
    Requirement already satisfied: tornado in /home/marco/anaconda3/lib/python3.7/site-packages 
     (from visdom->-r requirements.txt (line 3)) (6.0.3)
    Requirement already satisfied: pillow in /home/marco/anaconda3/lib/python3.7/site-packages 
     (from visdom->-r requirements.txt (line 3)) (6.1.0)
    Requirement already satisfied: websocket-client in /home/marco/anaconda3/lib/python3.7/site-
     packages (from visdom->-r requirements.txt (line 3)) (0.56.0)
    Requirement already satisfied: decorator>=3.0.0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from librosa>=0.5.1->-r requirements.txt (line 5)) (4.4.0)
    Requirement already satisfied: audioread>=2.0.0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from librosa>=0.5.1->-r requirements.txt (line 5)) (2.1.8)
    Requirement already satisfied: resampy>=0.2.0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from librosa>=0.5.1->-r requirements.txt (line 5)) (0.2.2)
    Requirement already satisfied: soundfile>=0.9.0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from librosa>=0.5.1->-r requirements.txt (line 5)) (0.10.2)
    Requirement already satisfied: joblib>=0.12 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from librosa>=0.5.1->-r requirements.txt (line 5)) (0.13.2)
    Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/marco
     /anaconda3/lib/python3.7/site-packages (from matplotlib>=2.0.2->-r requirements.txt (line 6)) 
     (2.4.0)
    Requirement already satisfied: kiwisolver>=1.0.1 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from matplotlib>=2.0.2->-r requirements.txt (line 6)) (1.1.0)
    Requirement already satisfied: cycler>=0.10 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from matplotlib>=2.0.2->-r requirements.txt (line 6)) (0.10.0)
    Requirement already satisfied: python-dateutil>=2.1 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from matplotlib>=2.0.2->-r requirements.txt (line 6)) (2.8.0)
    Requirement already satisfied: CFFI>=1.0 in /home/marco/anaconda3/lib/python3.7/site-packages 
     (from sounddevice->-r requirements.txt (line 10)) (1.12.3)
    Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /home/marco/anaconda3/lib/python3.7
     /site-packages (from PyQt5->-r requirements.txt (line 13)) (4.19.18)
    Requirement already satisfied: dill>=0.3.0 in /home/marco/anaconda3/lib/python3.7/site-packages 
     (from multiprocess->-r requirements.txt (line 14)) (0.3.0)
    Requirement already satisfied: llvmlite>=0.29.0dev0 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from numba->-r requirements.txt (line 15)) (0.29.0)
    Requirement already satisfied: setuptools in /home/marco/anaconda3/lib/python3.7/site-packages
     (from protobuf>=3.6.1->tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (41.0.1)
    Requirement already satisfied: h5py in /home/marco/anaconda3/lib/python3.7/site-packages (from 
     keras-applications>=1.0.6->tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (2.9.0)
    Requirement already satisfied: werkzeug>=0.11.15 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorboard<1.15.0,>=1.14.0->tensorflow-gpu<=1.14.0,>=1.10.0->-r 
    requirements.txt (line 1)) (0.15.4)
    Requirement already satisfied: markdown>=2.6.8 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from tensorboard<1.15.0,>=1.14.0->tensorflow-gpu<=1.14.0,>=1.10.0->-r  
     requirements.txt (line 1)) (3.1.1)
    Requirement already satisfied: idna<2.9,>=2.5 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from requests->visdom->-r requirements.txt (line 3)) (2.8)
    Requirement already satisfied: certifi>=2017.4.17 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from requests->visdom->-r requirements.txt (line 3)) (2019.6.16)
    Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/marco/anaconda3
     /lib/python3.7/site-packages (from requests->visdom->-r requirements.txt (line 3)) (1.24.2)
    Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/marco/anaconda3/lib/python3.7
     /site-packages (from requests->visdom->-r requirements.txt (line 3)) (3.0.4)
    Requirement already satisfied: pycparser in /home/marco/anaconda3/lib/python3.7/site-packages 
     (from CFFI>=1.0->sounddevice->-r requirements.txt (line 10)) (2.19)
    ERROR: spyder 3.3.6 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
    ERROR: spyder 3.3.6 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 
     5.13.0 which is incompatible.
    Installing collected packages: tensorflow-gpu, umap-learn, visdom, tqdm, sounddevice, 
     Unidecode, inflect, PyQt5, multiprocess
    Successfully installed PyQt5-5.13.0 Unidecode-1.1.1 inflect-2.1.0 multiprocess-0.70.8 
     sounddevice-0.3.13 tensorflow-gpu-1.14.0 tqdm-4.35.0 umap-learn-0.3.10 visdom-0.1.8.8
     (base) marco@pc:~/Real-Time-Voice-Cloning$ pip3 install pyqtwebengine
    Collecting pyqtwebengine
      Downloading https://files.pythonhosted.org/packages/a5/e8
     /1ed5d3af4549aaba3d60578cd35d1cb1b3adf74a7164cd7b93036caf41d6/PyQtWebEngine-
    5.13.0-5.13.0-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (64.9MB)
         |████████████████████████████████| 64.9MB 1.2MB/s 
    Requirement already satisfied: PyQt5>=5.13 in /home/marco/anaconda3/lib/python3.7/site-
     packages (from pyqtwebengine) (5.13.0)
    Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /home/marco/anaconda3/lib/python3.7
    /site-packages (from PyQt5>=5.13->pyqtwebengine) (4.19.18)
    ERROR: spyder 3.3.6 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5
     5.13.0 which is incompatible.
    ERROR: spyder 3.3.6 has requirement pyqtwebengine<5.13; python_version >= "3", but you'll 
     have pyqtwebengine 5.13.0 which is incompatible.
    Installing collected packages: pyqtwebengine
    Successfully installed pyqtwebengine-5.13.0

Operating System: Ubuntu 18.04.02 Server Edition
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
pip3 -V
pip 19.2.3 from /home/marco/anaconda3/lib/python3.7/site-packages/pip (python 3.7)

Looking forward to your kind help.
Marco

**Comment by xiaofeiliu200412** [comment]
I met the same issue, you can try:
1. pip3 uninstall pyqt5 
2. pip3 install pyqt5==5.12.0
it works for me

**Comment by marcoippolito** [comment]
Solve. Thank you @xiaofeiliu200412

**Comment by Grabdone** [comment]
spyder 3.3.6 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
ERROR: spyder 3.3.6 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.15.0 which is incompatible

**Comment by Sarrae1406** [comment]
After installing it, SPyder says Zmq ImportError: DLL load failed: The specified module could not be found.

**Comment by theishantha** [comment]
ERROR: spyder 4.1.4 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.                                                                             ERROR: spyder 4.1.4 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.15.1 which is incompatible.

**Comment by washiur17** [comment]
ERROR: Could not find a version that satisfies the requirement pyqt5<5.13; python_version >= "3" (from spyder) (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1)
ERROR: No matching distribution found for pyqt5<5.13; python_version >= "3" (from spyder)

**Comment by shashwatagrawal123** [comment]
even u get this error what do do?
`spyder 3.3.6 requires pyqt5<5.13; python_version >= 3, but you'll have pyqt5 5.15.2 which is incompatible.`

**Comment by moiseyUA** [comment]
ERROR: Could not find a version that satisfies the requirement pyqt5<5.13 (from spyder) (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2)
ERROR: No matching distribution found for pyqt5<5.13 (from spyder)

**Comment by avulagowtham1218** [comment]
Error
spyder 4.2.5 requires pyqt5<5.13, but you have pyqt5 5.15.4 which is incompatible.

Kindly assist me in this 
Gowtham

**Comment by MrKhan8627** [comment]
ERROR: Could not find a version that satisfies the requirement 5.15.4 (from versions: none)
ERROR: No matching distribution found for 5.15.4

**Comment by Budiono55** [comment]
Well, the same problem
the spyder requires pyqt ver 5.12
`spyder 5.2.2 requires pyqt5<5.13, but you have pyqt5 5.15.4 which is incompatible.`

while the pyqt-tools and pyqt-plugin only compatible with pyqt ver 5.15
`pyqt5-tools 5.15.4.3.2 requires pyqt5==5.15.4, but you have pyqt5 5.12.3 which is incompatible.`
`pyqt5-plugins 5.15.4.2.2 requires pyqt5==5.15.4, but you have pyqt5 5.12.3 which is incompatible.`

it's somehow I need to sacrifice one of those tools. Any enlightenment?

regards,
Budi
