### ISSUE TITLE
Numpy is not available

### ISSUE THREAD

**Issue by timmosaurusrex** [CorentinJ/Real-Time-Voice-Cloning#1095]
I have this error if i try to do anything. Does anyone know how I can fix this. Numpy is installed.

![image](https://user-images.githubusercontent.com/79397742/178507329-879b45da-3052-4d45-b628-03bec8a81d95.png)

**Comment by alessandrolamberti** [comment]
You need to be more specific on the various versions of the libraries you're using.
The error is often caused by a mismatch between python's version, pytorch and numpy

**Comment by myfingerhurt** [comment]
This might be working, if it doesn't try removing all the versions then try it again.
`pip install -r requirements.txt -U`
