### ISSUE TITLE
demo toolbox opens briefly then immediately closes

### ISSUE THREAD

**Issue by ThinkGreen1984** [CorentinJ/Real-Time-Voice-Cloning#111]
I am new with python so forgive me if this is an amateur question...When I run the python file for the demo toolbox, the program opens then shuts down..i assume is it because I did not pass a root directory for the dataset? how would I go about accomplishing this? I do not understand on how to extract Libraspeech and connect to datasets root....Any help would be greatly appreciated.
![real time voice](https://user-images.githubusercontent.com/54816497/64234583-7dfd6a00-ceab-11e9-8f97-a2cbf8b88f5a.PNG)

**Comment by SplendidX** [comment]
`python demo_toolbox.py -d <datasets_root>` 
Like mentioned in the README

**Comment by ThinkGreen1984** [comment]
When I copy and paste that code, it says the the syntax of the command is incorrect..I downloaded Linraspeexh but I don’t understand how to assign it as the datasets_root

**Comment by SplendidX** [comment]
Replace <datasat_root> with the path of your librespeech

**Comment by ThinkGreen1984** [comment]
thank you very much for your help, it works! The toolbox was shutting off because I did not add the pretrained models.

**Comment by MILTONNINA** [comment]
LA carpeta  librespeech no esta en el codigo alguien q me ayude xfavor discullpe la molestia
