### ISSUE TITLE
pip install -r requirements.txt,   ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by Atlas5779** [CorentinJ/Real-Time-Voice-Cloning#1117]
This is my first time using this software or coding. Please speak in simple terms. 
  (voice-software) PS C:\windows> cd..
(voice-software) PS C:\> cd Users
(voice-software) PS C:\Users> cd adria
(voice-software) PS C:\Users\adria> cd OneDrive
(voice-software) PS C:\Users\adria\OneDrive> cd Desktop
(voice-software) PS C:\Users\adria\OneDrive\Desktop> cd voice-clone
(voice-software) PS C:\Users\adria\OneDrive\Desktop\voice-clone> pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
(voice-software) PS C:\Users\adria\OneDrive\Desktop\voice-clone> pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
(voice-software) PS C:\Users\adria\OneDrive\Desktop\voice-clone>
  So what have I done wrong here? What is the fix?

**Comment by HexBanana** [comment]
Hmm,i don't speak English so i may make some grammar mistakes.Please forgive me.There is a file called requirements.txt in the root directory of each project, which contains all dependencies of the project.You may not be in the root directory of the project or you may have lost the requirements.txt file.I suggest you download the whole project again and run it again in the root directory of the project.

**Comment by peterpeterpeterpeterpeterpeterpeterpete** [comment]
you need to run 
pip install -r >full path to requirements.txt file in the download<
for me its 
pip install -r F:\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\requirements.txt
it will look a bit different but you have to go exactly to where your requirements.txt is copy the path above the files and add \requirements.txt to it

**Comment by Atlas5779** [comment]
Thanks, I have put voice cloning at the back of my to do list, and started learning to code python instead. I wanted voice cloning for youtube, now I have changed career paths to coding.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
