### ISSUE TITLE
My laptop makes strange scratching nose, while generating WAV file

### ISSUE THREAD

**Issue by oldwizard1010** [CorentinJ/Real-Time-Voice-Cloning#1127]
It happens while using demo_cli
It doesn't have hdd or cd drive, no moving parts, speakers are off

**Comment by Manjil-Karki** [comment]
the pc is cursed, throw away immediately.

**Comment by Blue-EyesWhiteDragon** [comment]
Dedicated GPU or an APU? If it's a dedicated GPU then it's coil whine on the hardware. It is generated from small vibrations from the inductors on your GPU's PCB as voltage is passed through.

There's nothing wrong with it.

EVGA Nvidia RTX cards are known for having higher than normal GPU coil whine.

If you hate it, you can use MSI afterburner [to under-volt your GPU](https://www.youtube.com/watch?v=zUkPAVcb9Xc&t=0s).
