### ISSUE TITLE
Italian training

### ISSUE THREAD

**Issue by ArdeiG** [CorentinJ/Real-Time-Voice-Cloning#1128]
Hi I'm trying to train an italian model for my graduation's thesis.
My dataset contains 14gb of multiskeaker's itaian voice

Abaout the encoder:
I have done 100k steps and this is the plot result
![my_runE_umap_106000](https://user-images.githubusercontent.com/95704232/196067792-6922046d-e108-44bb-878a-212a0dc156ac.png)

about the synthesizer:
i have done 33k steps and these are the results

![step-33000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/95704232/196067856-578dd4e5-2d53-4707-8c28-b1b3ba8e8179.png)

![attention_step_33000_sample_1](https://user-images.githubusercontent.com/95704232/196067882-e79ea54f-a439-4287-986f-79b2a38d1540.png)

about the last picture I'm afraid there are problems because a good output will show a diagonal lines and is not my case, about that I want to know where I may have made mistakes. thanks for the help

**Comment by auri99** [comment]
Hello! 
I've the same problem for the french language ! 
Any idea?

**Comment by ArdeiG** [comment]
i dont know, today I have done more 10k steps, so total is 40k+ steps and this is the result
![attention_step_42000_sample_1](https://user-images.githubusercontent.com/95704232/196166655-801fcef9-9688-496f-85b8-6291273cb972.png)


>

**Comment by ArdeiG** [comment]
> Hello! I've the same problem for the french language ! Any idea?
I dont know, today I have done more 10k steps, so total is 40k+ steps and this is the result
![attention_step_42000_sample_1](https://user-images.githubusercontent.com/95704232/196167465-f5ad363e-d48f-48eb-a4e1-54ed1b68e6a5.png)

**Comment by Alex2610** [comment]
have you solved the issue? do you have some pre- trained models?
