### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by oneduality** [CorentinJ/Real-Time-Voice-Cloning#114]
After many hours trying to get all of the dependencies met.. I got the demo to run, only for it to crash

A s s e r t i o n   f a i l e d !

 P r o g r a m :   X : \  R e a l - T i m e - V o i c e - C l o n i n g \ _ i n t e r n a l \ p y t h o n - 3 . 6 . 8 \ p y t h o n . e x e

 F i l e :   s r c / h o s t a p i / w d m k s / p a _ w i n _ w d m k s . c ,   L i n e   1 0 6 1

 E x p r e s s i o n :   F A L S E

Yes I got this running in windows.. only to get this far unfortunately

**Comment by SplendidX** [comment]
You likely didn't install the requirements.

**Comment by oneduality** [comment]
... And yes, installing requirements was the first thing I did =)

**Comment by josegomez** [comment]
So i have this same problem. Assertion failed with no further explination, did you get any further with this @oneduality ?

**Comment by oneduality** [comment]
@josegomez unfortunately I'm still getting that error :( 

I went with "conda install -c conda-forge python-sounddevice"

It installed without any errors, but running the demo_cli or demo_toolbox script both fail with the same error above.

**Comment by bmills20** [comment]
@oneduality make sure you installed the correct sounddevice version. After trial and error of the wrong version, I a wheel that works on my system. "sounddevice-0.3.15-cp37-cp37m-win_amd64.whl" (cp37 refers to python 3.7, amd64 is 64 bit windows)

I understand this is an old thread but just wanted to help if you hadn't solved it.

**Comment by IanBhatt** [comment]
@bmills20 I also have this error. I ran these commands:
conda install -c conda-forge python-sounddevice
conda install -c conda-forge/label/gcc7 python-sounddevice
conda install -c conda-forge/label/cf201901 python-sounddevice
conda install -c conda-forge/label/cf202003 python-sounddevice
but i still get the error.

**Comment by blue-fish** [comment]
Hi @oneduality ! Just letting you know that we updated the voice cloning toolbox recently with new features such as running without a GPU. I think it installs easier too. If you were not able to get it to work before, you are invited to pull the latest and try again.

I realize you likely invested a lot of time getting to your current point but the codebase has changed and we unfortunately do not have the time to troubleshoot errors that occurred on an old version. I hope you will understand.

**Comment by Ace100ace200** [comment]
> I got past this error by installing https://anaconda.org/conda-forge/python-sounddevice

Can confirm this helped me too. Thanks a lot, you just saved my Bachelor-Thesis!
