### ISSUE TITLE
Caught exception: ModuleNotFoundError("No module named 'sounddevice'") Restarting

### ISSUE THREAD

**Issue by jasonyun** [CorentinJ/Real-Time-Voice-Cloning#1140]
Reference voice: enter an audio filepath of a voice to be cloned (mp3, wav, m4a, flac, ...):
test.wav
Loaded file succesfully
Created the embedding
Write a sentence (+-20 words) to be synthesized:
我的声音是这样的吗？你来听一下，现在是我克隆的声音。

| Generating 1/1

Done.

Created the mel spectrogram
Synthesizing the waveform:
{| ████████████████ 152000/153600 | Batch Size: 16 | Gen Rate: 2.7kHz | }Caught exception: ModuleNotFoundError("No module named 'sounddevice'")
Restarting

Reference voice: enter an audio filepath of a voice to be cloned (mp3, wav, m4a, flac, ...):

what is this error？？

**Comment by d4rk-lucif3r** [comment]
Hi
You need to install sounddevice library. just do pip install sounddevice.
Thanks
