### ISSUE TITLE
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by mefumetsub** [CorentinJ/Real-Time-Voice-Cloning#1145]
When i install the requirements i encounter this error
![Screenshot at 2022-12-11 17-14-21](https://user-images.githubusercontent.com/82994482/206908864-c49e3322-865a-4390-92fc-c456c1ae3d03.png)

`  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
`

**Comment by RobinBrackez** [comment]
I used:

torch==1.11.0
numpy==1.22.4

on Python 3.10

**Comment by anjana-04** [comment]
I also got the error:
 **note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects**
while trying to install xautodl. Python version is 3.11.
