### ISSUE TITLE
it,s give the error

### ISSUE THREAD

**Issue by vivek1432ps** [CorentinJ/Real-Time-Voice-Cloning#1147]
![Screenshot (654)](https://user-images.githubusercontent.com/78531438/207540122-6b4dbfc1-3c23-4a16-95a2-26a77512fe35.png)
![Screenshot (655)](https://user-images.githubusercontent.com/78531438/207540137-06d55ecc-4572-4928-82ae-f2cb3025d907.png)
![Screenshot (656)](https://user-images.githubusercontent.com/78531438/207540150-eae39bf7-1b50-4bd6-b9b4-26de6042a8bf.png)
![Screenshot (657)](https://user-images.githubusercontent.com/78531438/207540165-8e4b7527-0a07-41ab-aa78-c460bf1aee08.png)

**Comment by Scn64** [comment]
I'm getting this error too.
