### ISSUE TITLE
ModuleNotFoundError: No module named 'synthesizer.tacotron2'

### ISSUE THREAD

**Issue by XxPro1445GamerxX** [CorentinJ/Real-Time-Voice-Cloning#115]
Trace back (most recent call last):
  File "C:\Users\14753\OneDrive\Desktop\Real-Time-Voice-Cloning-master\synthesizer\synthesize.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
ModuleNotFoundError: No module named 'synthesizer.tacotron2'

I'm trying to use the synthesizer.
Python = 3.7.3
Windows = 10
CUDA = 10.1
cuDNN = Installed for right CUDA version

**Comment by CorentinJ** [comment]
You're probably not running scripts from the root directory

**Comment by luger19** [comment]
Maybe try `pip install syntheziser.tacotron2`
I had to install several modules myself too.

**Comment by blue-fish** [comment]
Hi @XxPro1445GamerxX . As @CorentinJ said, you need to write a synthesizer script that runs at the top level of the repo. Take the synthesizer code you need from demo_cli.py . If what you need is not found in that file, you can: 1) write some kind of interface to allow you to interact with it from the root level, or 2) rewrite the synthesizer to be standalone.

Unfortunately we do not have the time to provide support for doing this, but best of luck getting the synthesizer to do what you need.
