### ISSUE TITLE
Dear Friends, I am facing segmentation fault

### ISSUE THREAD

**Issue by ImanuillKant1** [CorentinJ/Real-Time-Voice-Cloning#1150]
Dear Friends, I am facing segmentation fault 
`
Segmentation fault (core dumped)` 
 while using 
`$ python demo_toolbox.py`
There is nothing which happens other than this fault, no window popup or any other error. I tried several python versions and also torch versions. Same result. 
I am using Centos 7. Earlier everything was fine. If anyone can help or hint me what could be the reason. 

__Originally posted by @Tortoise17 in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/1143__

__Originally posted by @ImanuillKant1 in https://github.com/HTTPS-PhoenixEnterprise-com/HTTPS-PhoenixEnterprise-com/issues/3__

**Comment by scifisatan** [comment]
can i know why's this closed? if there's a fix for this i'd love to know about it
