### ISSUE TITLE
how I can train the model for Arabic language

### ISSUE THREAD

**Issue by baraalmasri** [CorentinJ/Real-Time-Voice-Cloning#1153]
please I've tried to make the decoder and synthesizer to detect Arabic characters and I still not able to make it spelling well or read the arabic text well ! , what I have to do for adding Arabic language to Real-Time-Voice-Cloning , what I have to change also . 
thank your from now for help

**Comment by MhmadSal** [comment]
@baraalmasri Hello, I'm trying to create one, check the link of the issue I opened here:

https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/1189#issue-1664407508

We can work together on it via social media platforms or even by email (My email is: saleh200220032004@gmail.com).

Also feel free to follow the steps I provided in the new issue to see if you can work out something, I'm planning on releasing it to the public once I finish working on it. It can have both our names of we can work together on this. 👍
