### ISSUE TITLE
'WindowsPath' is not iterable" for demo_cli.py when inputting mp3 on Windows 10

### ISSUE THREAD

**Issue by matthewfisherSU** [CorentinJ/Real-Time-Voice-Cloning#116]
I get the following error when giving a path to an mp3 in Windows 10

```Caught exception: TypeError("argument of type 'WindowsPath' is not iterable")```

![Capture](https://user-images.githubusercontent.com/49797748/64309550-d47dad80-cf6a-11e9-8205-20ee1fd0ee8b.PNG)

**Comment by matthewfisherSU** [comment]
This problem resolved when I converted the file from mp3 to wav format, not sure if figuring out how to support mp3 is worth it or not, but if it isn't feel free to close this!

**Comment by CorentinJ** [comment]
Yeah I don't know, other people have the same issue but I can't reproduce it with mp3 files.
