### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib.seq2seq'

### ISSUE THREAD

**Issue by eazolan** [CorentinJ/Real-Time-Voice-Cloning#117]
When running demo_cli.py

Python = 3.7.4
TensorFlow = 2.0 RC
CUDA = 10.1
cuDNN = Installed for right CUDA version
Windows = 10

**Comment by CorentinJ** [comment]
That's the wrong tensorflow version: https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/requirements.txt#L1
