### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by giorgionanfa** [CorentinJ/Real-Time-Voice-Cloning#12]
Hi! This work is very interesting, and also your thesis! I tried to use the toolbox, but i obtained the following error, when i tried to load a file from the LibriSpeech dataset.

![Screenshot from 2019-06-19 13-21-13](https://user-images.githubusercontent.com/44408221/59761456-31839480-9295-11e9-915f-0090bef5c4c9.png)

I followed all the steps and installed pytorch, torchvision, ecc...
Can you help me?
Thank you in advance,
Giorgio

**Comment by CorentinJ** [comment]
Thank you. In what way did you install PyTorch? Did you compile it or did you use pip/conda?

**Comment by giorgionanfa** [comment]
Thanks for your answer. Sorry for my late reply, i was trying to solve the problem by installing cuda again, but it persists. Now the error changed in:
**Exception: CUDA error: no kernel image is available for execution on the device**
I installed pytorch in this way: 
`conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`

**Comment by CorentinJ** [comment]
Could you try running the script I put here:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/3#issuecomment-502227424

If it fails before using the speaker encoder, then there's definitely something wrong with your PyTorch/Cuda installation.

**Comment by giorgionanfa** [comment]
I obtain:

Forwarding resnet on CPU
Forwarding resnet on GPU
/home/giorgio/anaconda3/envs/newenv/lib/python3.7/site-packages/torch/cuda/__init__.py:118: UserWarning: 
    Found GPU0 GeForce GT 750M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Traceback (most recent call last):
  File "script.py", line 18, in <module>
    model.forward(torch.from_numpy(inputs).cuda())
  File "/home/giorgio/anaconda3/envs/newenv/lib/python3.7/site-packages/torchvision/models/resnet.py", line 192, in forward
    x = self.conv1(x)
  File "/home/giorgio/anaconda3/envs/newenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/giorgio/anaconda3/envs/newenv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

**Comment by CorentinJ** [comment]
Yep, `CUDNN_STATUS_MAPPING_ERROR` either means your PyTorch version does not match your CUDA version or that your GPU is unsupported because it's too old. Given that the exact message `PyTorch no longer supports this GPU because it is too old.` appears up there I think you have no choice but to get a newer GPU. I'm planning for CPU inference maybe some day, but even then that would be very slow. I'm sorry but there's no simple solution here.
