### ISSUE TITLE
PyTorch installation is not configured to use CUDA

### ISSUE THREAD

**Issue by yevgetman** [CorentinJ/Real-Time-Voice-Cloning#124]
Upon cloning of the repo and installation of all dependencies, I am running `python demo_cli.py` and get the following output:

> WARNING: Logging before flag parsing goes to stderr.
W0907 20:44:16.745634 4394239424 deprecation_wrapper.py:119] From /Users/yev/Sites/voice/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

> Arguments:
> 
>     enc_model_fpath:   encoder/saved_models/pretrained.pt
>     syn_model_dir:     synthesizer/saved_models/logs-pretrained
>     voc_model_fpath:   vocoder/saved_models/pretrained/pretrained.pt
>     low_mem:           False
>     no_sound:          False
> 
> Running a test of your configuration...
> 
> Your PyTorch installation is not configured to use CUDA. If you have a GPU ready for deep learning, ensure that the drivers are properly installed, and that your CUDA version matches your PyTorch installation. CPU-only inference is currently not supported.

I believe the main takeaway is `Your PyTorch installation is not configured to use CUDA`

I have both PyTorch and CUDA installed but not sure how to configure PyTorch to use CUDA. 

I am trying to run this repo on a Macbook Pro running macOS Mojave 10.14.5

This machine does NOT comes with an Nvidia Graphics card. The graphics card installed is the following:  Radeon Pro 560 4GB
I dont think you can run CUDA without an Nvidia graphics card.

Is it only possible to run this application on a machine with an Nvidia graphics card?

**Comment by sberryman** [comment]
@yevgetman I'm not associated with this project at all but you are correct in that the Macbook does NOT have an nvidia GPU which means no CUDA. You wouldn't want to train any of the models without a GPU but I would assume you could run inference (at reduced performance) on a CPU.

That assumption of running inference on the CPU vs GPU would require you to make quite a few changes to the code base and dependencies. This is coming from my very high-level scan of this project and dependencies. It would be much easier to rent an instance from Google/Microsoft/Amazon which has an Nvidia GPU.

**Comment by yevgetman** [comment]
Thank you for your reply! I understand the problem now. Will make issue resolved.

**Comment by shawwn** [comment]
I have made the necessary changes to support CPU-only inference here: https://github.com/shawwn/Real-Time-Voice-Cloning/commit/02db1d3c2b21b65daa9aec1fe70c341f49ae9720

You can use it by cloning https://github.com/shawwn/Real-Time-Voice-Cloning

**Comment by yevgetman** [comment]
thank you, sir!

**Comment by TOBACCOCN** [comment]
I met the same question, could you show your detail or solution?

**Comment by Donovantxy** [comment]
@shawwn 
I get this error
"CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBA_CUDA_DRIVER
with the file path of the CUDA driver shared library."
And I cannot see the generated one, any clue?
