### ISSUE TITLE
Python 3.10.12 is not supported 

### ISSUE THREAD

**Issue by KPCOFGS** [CorentinJ/Real-Time-Voice-Cloning#1263]
When I ran python3.10 -m pip install numpy==1.20.3 on linux mint, I got an error while I was trying to install it. But it was totally fine when I used python3.8
![12](https://github.com/CorentinJ/Real-Time-Voice-Cloning/assets/100217654/99071c68-bf38-4ffe-b789-9d292ed539a5)

**Comment by MassEast** [comment]
Meaning what? Why are you planning to use it on python3.10 if it does on 3.8? What about using a different numpy version running on python3.10 and then trying again?

**Comment by KPCOFGS** [comment]
I tried the numpy version mentioned in the requirement.txt and realized that version of numpy could not be installed on python 3.10.12 and so I used older version of python which is 3.8 and it worked with that version of numpy.

**Comment by kajism** [comment]
It works with Python 3.10.12 when numpy version is changed to numpy==1.22.0 in requirements.txt .

**Comment by MassEast** [comment]
Nice, so I think you can happily close this issue :)
