### ISSUE TITLE
Are CMUDict / ARPAbet phonemes supported?

### ISSUE THREAD

**Issue by shawwn** [CorentinJ/Real-Time-Voice-Cloning#127]
Hello,

Other projects that use tacotron such as [mimic2](https://github.com/MycroftAI/mimic2) support ARPAbet phonemes enclosed in curly braces, like `"Turn left on {HH AW1 S S T AH0 N} Street"`:

![image](https://user-images.githubusercontent.com/59632/64665181-3f216400-d417-11e9-9784-f5fc3ff89221.png)

I noticed `synthesizer.utils.symbols` had support for `arpabet`, but it's commented out. When I tried to uncomment it, I get an error when encoding text containing arpabet symbols like `Turn left on {HH AW1 S S T AH0 N} Street.`

![image](https://user-images.githubusercontent.com/59632/64665090-e225ae00-d416-11e9-931e-43d15fa25d8d.png)

Was the model trained with arpabet encodings enabled? If so, what's the proper way to turn on support for it?

If not, how many training iterations do you think it would take to replicate your current model with arpabet encodings enabled? Is there a documented procedure somewhere for replicating your results from scratch?

Thanks for your time!

**Comment by CorentinJ** [comment]
You'd be better off going to rayhane's repo for help. I didn't bother looking into arpabet at all. You might be able to finetune the model in a few thousands of steps (I'm speculating), you'll know it's working when alignment will look good.

**Comment by csu-xiao-an** [comment]
do test

**Comment by blue-fish** [comment]
@shawwn Did you get ARPAbet support working with the toolbox?

**Comment by blue-fish** [comment]
If I were going to do this, I'd preprocess train.txt and convert the texts to ARPAbet using one of the methods suggested here: https://stackoverflow.com/questions/11911028/python-arpabet-phonetic-transcription

Then concat the new file with the original train.txt and finetune the model on the combined file. However, it might take a very large number of iterations before it learns ARPAbet and generalizes it to new situations. Probably just as fast to train the synthesizer from scratch on ARPAbet only and add a text preprocessor that runs at inference time.

@shawwn Do you still want this feature? We are just starting to train a new synthesizer in #449, no guarantees we will have the GPU time to accommodate the request but it is something that jumps out as being feasible.

**Comment by blue-fish** [comment]
I'm closing this issue due to lack of interest. My commits so far in #472 are to the effect of removing the vestiges of support for ARPAbet. Someone sufficiently motivated will have no trouble figuring it out.
