### ISSUE TITLE
Is this open source or paid?

### ISSUE THREAD

**Issue by mustakimweb** [CorentinJ/Real-Time-Voice-Cloning#1277]
Hi just confirming. I am trying to build a project for school and the dev i hired to do so said this is a paid tool and asking for a key. Is that a case or this is open source?

Pleasd guide

Thankyou XOXO

**Comment by RChembalipuram** [comment]
Yes, it is open source as it says in the licence
"Permission is hereby granted, free of charge, to any person obtaining a copy of this software"
