### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by StepHaze** [CorentinJ/Real-Time-Voice-Cloning#1286]
Hi, it's been long time from last update on source code. Is this project abandoned?

Does it still work good? Does it work with the latest version of Pytorch?
Or do you recommend another python project?

**Comment by intrinsicvardhan** [comment]
Need an update on this as well

**Comment by CorentinJ** [comment]
I will not maintain it anymore except to fix critical bugs, as for other recommendations I give a few in the readme:
https://github.com/CorentinJ/Real-Time-Voice-Cloning?tab=readme-ov-file#heads-up
