### ISSUE TITLE
Confusion regarding Dataset and use embedding from. 

### ISSUE THREAD

**Issue by nonlin** [CorentinJ/Real-Time-Voice-Cloning#130]
Is the idea that the more speakers I load or I record the more data this has to train with? 
Or is the LibriSpeech dataset just there to pull speaker voices to clone? 

And is there a way to improve the voice to sound more accurate with more samples from the same voice? I tried recording my voice several times but it didn't sound any better.

**Comment by CorentinJ** [comment]
It's just there to pull voices to clone. You won't improve the quality with more samples.
