### ISSUE TITLE
dependencies pack for non-programmers

### ISSUE THREAD

**Issue by testownik21** [CorentinJ/Real-Time-Voice-Cloning#134]
Hello,

For non-programmers, it would be useful to create some installer pack, with all dependencies required by project like this (or are there any available somewhere?), so that the project is easy to use and to migrate between computers.

For example, right now - since yeasterday I'm searchoing for answers and installing things one after another, and I still don't know how this will end, and whether it will work. So from SQA perspective, this is a major weak spot.

Next step would be to create exact (repeatable) step-by-step framework, how to expand such project for other languages (I'm interested in PL).

Also, I would suggest some compiled version of the project, with all dependencies needed (.exe for Windows users, like me).

**Comment by CorentinJ** [comment]
That's not going to happen. It's a substantial amount of work for which I don't have the time nor the will. This project was never meant to be used as a standalone application. It is purely a work of research upon which I decided to add a UI for newcomers. 

I agree that if you're not familiar with all the environment, it might be difficult to get anything to work for the first time; but that's going to be true for about every deep learning repository out there. @vanpelt recently pushed a lot of changes to make it runnable in google collab, maybe you could try that instead: https://colab.research.google.com/drive/1ts-KRxOuuAHmb-AtjU1XTM_lIFOepAN2.
