### ISSUE TITLE
cli_test.py unable to complete on windows

### ISSUE THREAD

**Issue by oonqt** [CorentinJ/Real-Time-Voice-Cloning#139]
Windows 10 1903
Py 3.7.4

I run `python cli_test.py --low_mem`
It runs fine up until where it asks me for a path to sample audio, which I provide and it throws `Caught exception: TypeError("argument of type 'WindowsPath' is not iterable")`

Help please

**Comment by UNPARALLELE** [comment]
audio format resulit in this error,   using ffmpeg to convet the audio format to ' .wav ' and try again

**Comment by CorentinJ** [comment]
#45
