### ISSUE TITLE
Bangla[BD IN] Language Support Help.

### ISSUE THREAD

**Issue by MuzahidGithub** [CorentinJ/Real-Time-Voice-Cloning#140]
Hello
I'm very new in this sector. I got some datasets for bangla language. 
Here : http://openslr.org/53
Here : http://openslr.org/37/
Will this be enough for Your Software to work in Bangla ?

**Comment by CorentinJ** [comment]
No, it's too small.

**Comment by llxx-lord-xxll** [comment]
I was thinking to create the dataset by my own. 
Is there any tool like subtitle makers for writing or copying subtitle with the exact timeframe with the audio?
