### ISSUE TITLE
Other Native Accents of English -- Received Pronunciation

### ISSUE THREAD

**Issue by DeeGeeTill** [CorentinJ/Real-Time-Voice-Cloning#142]
First off, I wanted to congratulate you on the amazing results this app can create. 

The results are especially amazing if you speak American English. With British English, however, you can easily hear an odd pattern.

Of course, this varies from accent to accent. I'm speaking about Received Pronunciation (or BBC English) in this ticket specifically. When using a voice with a British accent, the voice itself sounds British, but pronounces words in an especially American way.

So, my question is:

_Is it possible to change these pronunciations to be closer to the original accent without retraining the entire dataset?_

Thanks in advance.

**Comment by CorentinJ** [comment]
I doubt it, I guess the model is limited in that way. You would need retraining, maybe by selecting only British speakers. In the SV2TTS paper they trained on VCTK, which is a British dataset IIRC that has a much better quality.

**Comment by boydydoydy** [comment]
I'd like to echo DeeGeeTill's congratulation - thanks for creating this amazing programme!

I am not a programmer. I am a sound artist and have managed to get the RTVC programme up and running. For the purposes I hope to use it for using British accents would be ideal. As per your response above is retraining the dataset using the VCTK dataset something a programming  noob like me will be able to do? Are there any instructions on how to train using a new dataset that you can point me towards? 

My apologies if all this exists somewhere obvious already. This whole journey into voice cloning has been a slow learner for me. 

Thanks again.

**Comment by blue-fish** [comment]
@boydydoydy
1. Learn to train synthesizer with LibriSpeech dataset: [\[wiki page\]](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training)
2. My guide on finetuning the model for better quality: [\[writeup\]](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437), [\[VCTK example\]](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-663308789)

Reorganize your files into this folder structure: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538
