### ISSUE TITLE
low_mem mode not working.

### ISSUE THREAD

**Issue by kashi211** [CorentinJ/Real-Time-Voice-Cloning#144]
Hey, so i'm working with a 2Gig Gpu and for either the low_mem mode or otherwise. i get this issue.

I've tried reducing the batch size's and dimensions but cant quite put my finger on what Parameters i need to edit.

PLEASE HELP!!!!!!

RuntimeError: CUDA out of memory. Tried to allocate 380.00 MiB (GPU 0; 1.96 GiB total capacity; 955.66 MiB already allocated; 190.81 MiB free; 112.34 MiB cached)

![Screenshot from 2019-09-22 13-43-26](https://user-images.githubusercontent.com/30386840/65384354-fc2c8e00-dd3e-11e9-9e18-0d8d76926750.png)

**Comment by CorentinJ** [comment]
Synthesize less text at once
