### ISSUE TITLE
Import Error:(Failed to import any qt binding)

### ISSUE THREAD

**Issue by rosyrososo** [CorentinJ/Real-Time-Voice-Cloning#147]
File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\qt_compat.py"
raise ImportError("Failed to import any qt binding")
 This error shows up when running python demo_toolbox.py -d <datasets_root>. 

  I have PyQt5 and tried reinstalling matplotlib packages. It didn't work. What could possibly cause this error?

**Comment by RossMelbourne** [comment]
I received the same error and got past it by installing pyqt5 using 'pip install pyqt5'.

**Comment by aoneaoneaone** [comment]
Uninstalling an reinstalling pyqt5 worked for me
