### ISSUE TITLE
Almost getting this to work on Ubuntu...

### ISSUE THREAD

**Issue by JimBarrOfficial** [CorentinJ/Real-Time-Voice-Cloning#150]
Having an issue when launching the demo_toolbox.py script:

Traceback (most recent call last):
  File "demo_toolbox.py", line 32, in <module>
    Toolbox(**vars(args))
  File "/home/jlb/Real-Time-Voice-Cloning/toolbox/__init__.py", line 49, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir)
  File "/home/jlb/Real-Time-Voice-Cloning/toolbox/__init__.py", line 97, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_models_dir)
  File "/home/jlb/Real-Time-Voice-Cloning/toolbox/ui.py", line 275, in populate_models
    raise Exception("No encoder models found in %s" % encoder_models_dir)
Exception: No encoder models found in encoder/saved_models

I managed to get this far, but I'm REALLY interested in getting this demo to work fully. Can anyone guide me as to what is wrong? The GUI windows starts for a second, then fails with the above error.

Thanks.

**Comment by AaravVihan** [comment]
you need to download encoder

**Comment by JimBarrOfficial** [comment]
I figured that part out... now I have to figure out CUDA compatible device error. Not sure how to solve this issue. I am running this with 8 GB RAM on a VirtualBox instance. If anyone has any links/advice on how to fix this final error with NVidia/Cuda, I'd be very appreciative. Thanks.
