### ISSUE TITLE
No such file or directory: 'encoder\\saved_models\\pretrained.pt'

### ISSUE THREAD

**Issue by luger19** [CorentinJ/Real-Time-Voice-Cloning#151]
When runnig `python D:\Real-Time-Voice-Cloning-master\demo_cli.py` it says `FileNotFoundError: [Errno 2] No such file or directory: 'encoder\\saved_models\\pretrained.pt'` even though `pretrained.pt` is clearly there. How to fix that?

**Comment by luger19** [comment]
When running `python D:\Real-Time-Voice-Cloning-master\demo_toolbox.py` it says `Exception: No encoder models found in encoder\saved_models` too.

**Comment by raanubis** [comment]
The pretrained model is in the folder: D:\Real-Time-Voice-Cloning\encoder\saved_models\
?

**Comment by CorentinJ** [comment]
You're not running from the root of the repo.

**Comment by NealWalters** [comment]
Looks to me like the readme.md5 is misleading.  It tells you to download the latest pretrained models, but the next step say to run `python demo_cli.py` "without" downloading any data sets.  But demo_cli.py needs the pretrained model. 

### Pretrained models
Download the latest [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models).

### Preliminary
Before you download any dataset, you can begin by testing your configuration with:

`python demo_cli.py`

If all tests pass, you're good to go.
