### ISSUE TITLE
stuck ?????

### ISSUE THREAD

**Issue by maya413** [CorentinJ/Real-Time-Voice-Cloning#153]
██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 1160/1176 [2:39:53<02:11,  8.24s/speakers]
stucking at percent 99% very long time, about 3hours.
why ???
any body tell me what's wrong ?

**Comment by AaravVihan** [comment]
IM DELETING YOU, DADDY!😭👋 ██]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]] 10% complete..... ████]]]]]]]]]]]]]]]]]]]]]]]]]]] 35% complete.... ███████]]]]]]]]]]]]]]]] 60% complete.... ███████████] 99% complete..... 🚫ERROR!🚫 💯True💯 Daddies are irreplaceable 💖I could never delete you Daddy!💖 Send this to ten other 👪Daddies👪 who give you 💦cummies💦 Or never get called ☁️squishy☁️ again❌❌😬😬❌❌ If you get 0 Back: no cummies for you 🚫🚫👿 3 back: you're squishy☁️💦 5 back: you're daddy's kitten😽👼💦 10+ back: Daddy😛😛💕💕💦👅👅

**Comment by CorentinJ** [comment]
It will be fine if you just kill the program.
