### ISSUE TITLE
error: command 'cl.exe' failed: No such file or directory

### ISSUE THREAD

**Issue by SaylorTwift** [CorentinJ/Real-Time-Voice-Cloning#155]
Before you close this issue because it's a repeat, hear me out.

When I try to install the requirements, when it tries installing `webrtcvab`, I get the above error:
` error: command 'cl.exe' failed: No such file or directory`

I have tried everything anyone recommended. I installed Visual Studio. I installed the C++ Build Tools. I added cl.exe to PATH. I can run cl.exe from the command prompt just fine but if pip tries to use the command, cl.exe cannot be found. I installed older versions of both VS and build tools. I reinstalled everything. I tried previous python versions. I tried installing windows-build-tools using npm. I tried using anaconda. I tried running it from a VS command prompt. I tried literally all solutions that are proposed anywhere on the entire internet.
Nothing works. I keep getting this error.
I've been at this for 5h and I'm about ready to shoot a bazooka into my PC. 
Please help me.
Thanks.

**Comment by AaravVihan** [comment]
it seems you are have runtime error, try upgrade applications
best regards

**Comment by CorentinJ** [comment]
Yeah that package is a pain in the ass to install, which is the reason why I wanted to move to a different denoiser. I know this: https://forum.qt.io/topic/90839/lnk1158-cannot-run-rc-exe/4 solved it for me but I don't know if it will help you. You can definitely remove all the webrtcvad code if you really want to get there.

**Comment by SaylorTwift** [comment]
Thank you, @CorentinJ but that didn't work for me. You mean I can remove the webrtcvad code from your source? Which files would I have to edit for that?

**Comment by CorentinJ** [comment]
Just remove the import and replace the body of [that function](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/encoder/audio.py#L58-L98) with `return wav`

**Comment by raanubis** [comment]
Try:
Go to the installation folder (In my case it is): C:\Program Files (x86)\Microsoft Visual C++ Build Tools
Open Visual C++ 2015 x86 x64 Cross Build Tools Command Prompt
Type: pip install package_name

**Comment by blue-fish** [comment]
@SaylorTwift I have good news for you! We made webrtcvad an optional package in #375, the voice cloning toolbox will now run without it. Please pull the latest version of the repository and try again.
