### ISSUE TITLE
Training new dataset in a different language

### ISSUE THREAD

**Issue by nicholasguimaraes** [CorentinJ/Real-Time-Voice-Cloning#156]
Hello, I have a 200+ hours dataset with audio and the transcript and I wonder how exactly I should organize the directory with the data.

When I run encoder_preprocess.py, should the transcript files be in the same folder as the audio files?

Also, at what step will the transcript be needed? Only when running synthesizer_preprocess_embeds.py?

**Comment by CorentinJ** [comment]
You'll have to modify this code: https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/synthesizer/preprocess.py#L13-L80

The transcripts are for synthesizer_preprocess_audio
