### ISSUE TITLE
Can't create pre-trained data file

### ISSUE THREAD

**Issue by nav1-code** [CorentinJ/Real-Time-Voice-Cloning#16]
I have tried to generate pre-trained data, running next command (following your instructions). 

python encoder_preprocess.py <datasets_root>

python encoder_train.py my_run <datasets_root>

I've got following errors. I also tried to use some audio from dataset, but I got an exception (see picture) , I understand here I don't have drivers for nVidia. 

![image](https://user-images.githubusercontent.com/51883861/59923532-5108f180-943c-11e9-8c04-3e2a554fdeaa.png)

C:\Users\admin\Downloads\Real-Time-Voice-Cloning>python encoder_preprocess.py "C
:\Users\admin\Downloads\Real-Time-Voice-Cloning\dataset_root"
Traceback (most recent call last):
  File "encoder_preprocess.py", line 1, in <module>
    from encoder.preprocess import preprocess_librispeech, preprocess_voxceleb1,
 preprocess_voxceleb2
  File "C:\Users\admin\Downloads\Real-Time-Voice-Cloning\encoder\preprocess.py",
 line 1, in <module>
    from multiprocess.pool import ThreadPool
ModuleNotFoundError: No module named 'multiprocess'

C:\Users\admin\Downloads\Real-Time-Voice-Cloning>python encoder_train.py my_run
"C:\Users\admin\Downloads\Real-Time-Voice-Cloning\dataset_root"
Arguments:
    run_id:            my_run
    clean_data_root:   C:\Users\admin\Downloads\Real-Time-Voice-Cloning\dataset_
root
    models_dir:        encoder\saved_models
    vis_every:         10
    umap_every:        100
    save_every:        500
    backup_every:      7500
    force_restart:     False
    visdom_server:     http://localhost
    no_visdom:         False

No model "my_run" found, starting training from scratch.
Updating the visualizations every 10 steps.
WARNING:root:Setting up a new session...
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the
 target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
urllib3\connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\http\client.py
", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\http\client.py
", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\http\client.py
", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\http\client.py
", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\http\client.py
", line 956, in send
    self.connect()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
urllib3\connection.py", line 183, in connect
    conn = self._new_conn()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object
 at 0x000000000A7232B0>: Failed to establish a new connection: [WinError 10061]
No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097
): Max retries exceeded with url: /env/my_run%20(21-06%2001h12) (Caused by NewCo
nnectionError('<urllib3.connection.HTTPConnection object at 0x000000000A7232B0>:
 Failed to establish a new connection: [WinError 10061] No connection could be m
ade because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
visdom\__init__.py", line 548, in _send
    data=json.dumps(msg),
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8
097): Max retries exceeded with url: /env/my_run%20(21-06%2001h12) (Caused by Ne
wConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000A7232B
0>: Failed to establish a new connection: [WinError 10061] No connection could b
e made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Downloads\Real-Time-Voice-Cloning\encoder\visualizations.
py", line 51, in __init__
    self.vis = visdom.Visdom(server, env=self.env_name, raise_exceptions=True)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
visdom\__init__.py", line 406, in __init__
    }, endpoint='env/' + env)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
visdom\__init__.py", line 562, in _send
    raise ConnectionError("Error connecting to Visdom server")
ConnectionError: Error connecting to Visdom server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "encoder_train.py", line 46, in <module>
    train(**vars(args))
  File "C:\Users\admin\Downloads\Real-Time-Voice-Cloning\encoder\train.py", line
 60, in train
    vis = Visualizations(run_id, vis_every, server=visdom_server, disabled=no_vi
sdom)
  File "C:\Users\admin\Downloads\Real-Time-Voice-Cloning\encoder\visualizations.
py", line 53, in __init__
    raise Exception("No visdom server detected. Run the command \"visdom\" in yo
ur CLI to "
Exception: No visdom server detected. Run the command "visdom" in your CLI to st
art it.

How can I do pre-trained data file for Romanian languages or how I should to structure content of the folders and files to generate  pre-trained data for Romanian language.

**Comment by CorentinJ** [comment]
Seems I forgot to include multiprocess in the requirements, I'll do that. I see that I also did not mention you had to run visdom before training, I've updated that [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training#preprocessing-and-training).

As for Romanian, I did tell you that you need a Romanian dataset. Do you have one, a large one?

You do need to have your nvidia drivers installed. Try to run `demo_cli.py` before you run any other scripts. If it doesn't work, the rest of the project won't.

**Comment by nav1-code** [comment]
Dataset for Romanian I have, You mean I should run `demo_cli.py` before `python encoder_preprocess.py <datasets_root>`?

**Comment by CorentinJ** [comment]
You should run it to debug issues. Your configuration seems broken and you need to fix it before doing anything.

**Comment by nav1-code** [comment]
But I'm not good at Python, be sincerely I don't know it, but I'll try to figure out. Can you help me with this issue?

**Comment by CorentinJ** [comment]
Try googling your errors first. I'm going to be busy for a while so I won't be able to help you much but I'll try later.

**Comment by nav1-code** [comment]
OK, meanwhile, I'll be googling. Thanks

**Comment by CorentinJ** [comment]
What's your status?

**Comment by nav1-code** [comment]
I can't install drivers for NVIDIA, I tried several times but without success. I've tried to run python CLI command, and I've got the following error:

`C:\Users\admin\Downloads\Real-Time-Voice-Cloning_2>python demo_cli.py
WARNING: Logging before flag parsing goes to stderr.
W0625 07:59:13.038100  5128 deprecation_wrapper.py:118] From C:\Users\admin\Down
loads\Real-Time-Voice-Cloning_2\synthesizer\models\modules.py:91: The name tf.nn
.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell ins
tead.

This is a UI-less example of interface to SV2TTS. The purpose of this script is
to show how you can interface this project easily with your own. See the source
code for an explanation of what is happening.

Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_dir:     synthesizer\saved_models\logs-pretrained
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    no_sound:          False

Your PyTorch installation is not configured to use CUDA. If you have a GPU ready
 for deep learning, ensure that the drivers are properly installed, and that you
r CUDA version matches your PyTorch installation. CPU-only inference is currently not supported.
`

And the last one, can you show me the proper way to do pretrained data file (I'm little confused in these tutorials visdom). Please help me!!!! 

**PS:** I don't have graphic card, graphic card is build in MB. Feature of my computer is: CPU Intel® Core™ i7-7700, RAM 32GB, MB Asus Z170. Can be this why I couldn't install NVIDIA drivers?

**Comment by CorentinJ** [comment]
Yes, you won't be able to do anything without a GPU (an nvidia gpu is prefered)

**Comment by nav1-code** [comment]
But what about `ClI` command?

**Comment by CorentinJ** [comment]
You won't be able to run it properly until you have a GPU

**Comment by nav1-code** [comment]
What is the minimum characteristics of this GPU, I should have?

**Comment by CorentinJ** [comment]
I'd say anything starting from the NVIDIA GTX600 series. I'm currently working on low VRAM support (for 2gb GPUs) but you would be better off with 4gb at least.

**Comment by aijianiula0601** [comment]
I got the same problem.I run it in linux instead of windows.

**Comment by saumyaupadhyay21** [comment]
Is it possible to run this project without Nvidia graphics card?

**Comment by saumyaupadhyay21** [comment]
> I got the same problem.I run it in linux instead of windows.

You did it without Nvidia graphics card?
