### ISSUE TITLE
out of memory, gtx1080, 8gb, batch_size=32

### ISSUE THREAD

**Issue by maya413** [CorentinJ/Real-Time-Voice-Cloning#164]
its' perform right, when i use batch_size=16, 
but!, it's down very slowly, 
have anybody know that any h param sets, to reslovtion  is problem?

**Comment by maya413** [comment]
i have 2gpu, one is gtx1080, other is intel uhd 630, dose any set on h param to relieve the memory when not engouh ?

**Comment by Stellarize** [comment]
did u check if u don't get other process running in background?

**Comment by maya413** [comment]
@Stellarize how to check ? 
i have almost 200hours train data, when i get this error .

**Comment by Stellarize** [comment]
which system do you use ?

**Comment by Stellarize** [comment]
try to reboot your computer

**Comment by CorentinJ** [comment]
Lower max_mel_frames

**Comment by freecui** [comment]
@CorentinJ , how many gpus were you using on this project?  How much memory does a GPU have?
How long it takes to train encoder and synthesizer and vocoder models?

**Comment by CorentinJ** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models

**Comment by freecui** [comment]
@CorentinJ , How much memory at least to run this project ? I want to know GPU memeroy  limit.
Is 8G GPU  ok ?

**Comment by CorentinJ** [comment]
Yes
