### ISSUE TITLE
Need to rely on pytorch? Which version should I choose?

### ISSUE THREAD

**Issue by smallcoderofme** [CorentinJ/Real-Time-Voice-Cloning#172]
Traceback (most recent call last):
  File "demo_cli.py", line 4, in <module>
    from encoder import inference as encoder
  File "F:\Real-Time-Voice-Cloning\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "F:\Real-Time-Voice-Cloning\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
ModuleNotFoundError: No module named 'torch'

**Comment by UnknownUserG** [comment]
Yes you would have to install PyTorch for this. You can download the appropriate version of PyTorch according to your CUDA version here: https://pytorch.org/get-started/previous-versions/

Note: CUDA 10.1 doesn't work with Tensorflow, you will have to install CUDA 10.0 for this to work

**Comment by smallcoderofme** [comment]
> Yes you would have to install PyTorch for this. You can download the appropriate version of PyTorch according to your CUDA version here: https://pytorch.org/get-started/previous-versions/
> 
> Note: CUDA 10.1 doesn't work with Tensorflow, you will have to install CUDA 10.0 for this to work

Thanks!

**Comment by HumanG33k** [comment]
Do we really need cuda ?
