### ISSUE TITLE
Your PyTorch installation is not configured to use CUDA.

### ISSUE THREAD

**Issue by ajayb108** [CorentinJ/Real-Time-Voice-Cloning#174]
Hi,

I am trying to build this on a win10 machine with NVIDIA GPU - NVS 310 with 1 Gb ram and driver version 392.56

While running `python demo_cli.py --low_mem`, i get the error 

> Your PyTorch installation is not configured to use CUDA. If you have a GPU ready for deep learning, ensure that the drivers are properly installed, and that your CUDA version matches your PyTorch installation. CPU-only inference is currently not supported.

**Version of the dependencies**
Python 3.7.4
CUDA 10.0
cudnn v7.6.4
torch   1.2.0
torchfile   0.1.0
torchvision  0.4.0

Would appreciate if you can help find and fix the break.

Thanks,
Ajay

**Comment by ajayb108** [comment]
> Whats your pytorch version?

Installed following files from pytorch website

torch-1.3.0+cu92-cp37-cp37m-win_amd64
torchvision-0.4.1+cu92-cp37-cp37m-win_amd64

**Comment by dexbyte** [comment]
> torch-1.3.0+cu92-cp37-cp37m-win_amd64
> torchvision-0.4.1+cu92-cp37-cp37m-win_amd64

I think you install PyTorch for CUDA 9.2

Install PyTorch for CUDA 10
```
pip install https://download.pytorch.org/whl/cu100/torch-1.0.1-cp37-cp37m-win_amd64.whl
pip install torchvision
```
Also, it seems like you have installed an incompatible version of cuDNN. Let me know if you face any issues regarding that.

**Comment by nhobson99** [comment]
I had this same problem, and installing different versions of the python packages didn't help. What eventually ended up working was this:

`sudo apt-get install python3-pycude nvidia-driver-435 nvidia-utils-435`

`sudo reboot`

Before I had been using the nvidia-384 driver, and I'm guessing that's what didn't play nice. Regardless, it does seem to start properly now.

**Comment by JQuezada0** [comment]
Is this project only usable with a nvidia gpu? I'm getting this error as well, but I have an intel gpu so I can't use CUDA

**Comment by blue-fish** [comment]
You can run the main repo without CUDA support now. It is slower on CPU but still quite usable by my experience. Please pull the latest and try again.
