### ISSUE TITLE
I have a tensorflow error.

### ISSUE THREAD

**Issue by thomwim** [CorentinJ/Real-Time-Voice-Cloning#178]
I'm trying to run python demo_cli.py, but I'm getting a few errors.

ERROR: tensorflow 2.0.0 has requirement tensorflow-estimator<2.1.0,>=2.0.0, but you'll have tensorflow-estimator 1.14.0 which is incompatible.

KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow_core\python\framework\registry.py:66)"

**Comment by dexbyte** [comment]
As it says, you have an incompatible version of tensorflow-estimator. Remove tensorflow-estimator 1.14.0 and install tensorflow-estimator<2.1.0,>=2.0.0

Simply run `pip install "tensorflow-estimator<2.1.0,>=2.0.0"`

**Comment by blue-fish** [comment]
Root cause appears to be using tensorflow 2.0 when the repo requires 1.x. The suggestion is to pull the latest version of the code, reinstall the requirements and try again. The current toolbox uses tensorflow 1.15.
