### ISSUE TITLE
Cannot install webrtcvad 

### ISSUE THREAD

**Issue by rdrlima** [CorentinJ/Real-Time-Voice-Cloning#179]
Cannot install webrtcvad on windows 10. 

ERROR: Command errored out with exit status 1:
     command: 'd:\tacotron-master\_internal\python-3.6.8\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Rodrigo\\AppData\\Local\\Temp\\pip-install-ndmparqn\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\Rodrigo\\AppData\\Local\\Temp\\pip-install-ndmparqn\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Rodrigo\AppData\Local\Temp\pip-record-0z010yy7\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Rodrigo\AppData\Local\Temp\pip-install-ndmparqn\webrtcvad\
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    copying webrtcvad.py -> build\lib.win-amd64-3.6
    running build_ext
    building '_webrtcvad' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\cbits
    creating build\temp.win-amd64-3.6\Release\cbits\webrtc
    creating build\temp.win-amd64-3.6\Release\cbits\webrtc\common_audio
    creating build\temp.win-amd64-3.6\Release\cbits\webrtc\common_audio\signal_processing
    creating build\temp.win-amd64-3.6\Release\cbits\webrtc\common_audio\vad
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -D_WIN32 -Icbits -Id:\tacotron-master\_internal\python-3.6.8\include -Id:\tacotron-master\_internal\python-3.6.8\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tccbits\pywebrtcvad.c /Fobuild\temp.win-amd64-3.6\Release\cbits\pywebrtcvad.obj
    pywebrtcvad.c
    cbits\pywebrtcvad.c(1): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\tacotron-master\_internal\python-3.6.8\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Rodrigo\\AppData\\Local\\Temp\\pip-install-ndmparqn\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\Rodrigo\\AppData\\Local\\Temp\\pip-install-ndmparqn\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Rodrigo\AppData\Local\Temp\pip-record-0z010yy7\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by Addy771** [comment]
I had a similar issue (on Windows 7), except for me the error was
`    C:\Python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory`
 `error: command 'C:\\Program Files (x86)\\Microsoft VisualStudio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2`

To solve this, I had to install the Windows 10 SDK option from the Visual Studios build tools. 
I then ran the "Developer Command Prompt" under Visual Studios in 'All Programs' in the Start menu. In this command prompt I was able to pip install webrtcvad successfully.

**Comment by hulingpakakak** [comment]
Has someone have managed to solve this? :(

**Comment by ZenithBerserker** [comment]
> 
> 
> I had a similar issue (on Windows 7), except for me the error was
> ` C:\Python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory`
> `error: command 'C:\\Program Files (x86)\\Microsoft VisualStudio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2`
> 
> To solve this, I had to install the Windows 10 SDK option from the Visual Studios build tools.
> I then ran the "Developer Command Prompt" under Visual Studios in 'All Programs' in the Start menu. In this command prompt I was able to pip install webrtcvad successfully.

How did you install it in developer cmd?

**Comment by Sadam1195** [comment]
[https://drive.google.com/file/d/1ze3PHQtfpzCietKjyRT9Nd1t5jXKqtfS/view?usp=sharing](url)

- The provided link is for windows 10, python 3. 
- Unzip this folder and place all the files in it to your directory where main.py file is.

@ZenithBerserker @rdrlima

**Comment by Sadam1195** [comment]
> The same issue here on linux ubuntu 18.4:
> 
> ### Collecting webrtcvad
> ## Using cached https://files.pythonhosted.org/packages/89/34/e2de2d97f3288512b9ea56f92e7452f8207eb5a0096500badf9dfd48f5e6/webrtcvad-2.0.10.tar.gz
> Building wheels for collected packages: webrtcvad
> Building wheel for webrtcvad (setup.py) ... error
> ERROR: Command errored out with exit status 1:
> command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j_8ezvc3/webrtcvad/setup.py'"'"'; **file**='"'"'/tmp/pip-install-j_8ezvc3/webrtcvad/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ydzv_bvg --python-tag cp37
> cwd: /tmp/pip-install-j_8ezvc3/webrtcvad/
> Complete output (20 lines):
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.7
> copying webrtcvad.py -> build/lib.linux-x86_64-3.7
> running build_ext
> building '_webrtcvad' extension
> creating build/temp.linux-x86_64-3.7
> creating build/temp.linux-x86_64-3.7/cbits
> creating build/temp.linux-x86_64-3.7/cbits/webrtc
> creating build/temp.linux-x86_64-3.7/cbits/webrtc/common_audio
> creating build/temp.linux-x86_64-3.7/cbits/webrtc/common_audio/signal_processing
> creating build/temp.linux-x86_64-3.7/cbits/webrtc/common_audio/vad
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-9u8fmL/python3.7-3.7.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWEBRTC_POSIX -Icbits -I/usr/include/python3.7m -c cbits/pywebrtcvad.c -o build/temp.linux-x86_64-3.7/cbits/pywebrtcvad.o
> cbits/pywebrtcvad.c:1:10: fatal error: Python.h: No such file or directory
> #include <Python.h>
> ^~~~~~~~~~
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> ERROR: Failed building wheel for webrtcvad
> Running setup.py clean for webrtcvad
> Failed to build webrtcvad
> Installing collected packages: webrtcvad
> Running setup.py install for webrtcvad ... error
> ERROR: Command errored out with exit status 1:
> command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j_8ezvc3/webrtcvad/setup.py'"'"'; **file**='"'"'/tmp/pip-install-j_8ezvc3/webrtcvad/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-p6nl70v7/install-record.txt --single-version-externally-managed --compile
> cwd: /tmp/pip-install-j_8ezvc3/webrtcvad/
> Complete output (20 lines):
> running install
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.7
> copying webrtcvad.py -> build/lib.linux-x86_64-3.7
> running build_ext
> building '_webrtcvad' extension
> creating build/temp.linux-x86_64-3.7
> creating build/temp.linux-x86_64-3.7/cbits
> creating build/temp.linux-x86_64-3.7/cbits/webrtc
> creating build/temp.linux-x86_64-3.7/cbits/webrtc/common_audio
> creating build/temp.linux-x86_64-3.7/cbits/webrtc/common_audio/signal_processing
> creating build/temp.linux-x86_64-3.7/cbits/webrtc/common_audio/vad
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-9u8fmL/python3.7-3.7.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWEBRTC_POSIX -Icbits -I/usr/include/python3.7m -c cbits/pywebrtcvad.c -o build/temp.linux-x86_64-3.7/cbits/pywebrtcvad.o
> cbits/pywebrtcvad.c:1:10: fatal error: Python.h: No such file or directory
> #include <Python.h>
> ^~~~~~~~~~
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j_8ezvc3/webrtcvad/setup.py'"'"'; **file**='"'"'/tmp/pip-install-j_8ezvc3/webrtcvad/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-p6nl70v7/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

- For Ubuntu you should check this out.
[https://github.com/wiseman/py-webrtcvad/issues/40#issuecomment-561576279](url)

**Comment by Sadam1195** [comment]
- For **Ubuntu** users
[https://drive.google.com/file/d/1FYICqyEh1d45TUksibduBK30h1AjGUh8/view?usp=sharing](url)
use this link (pre-built/pre-compiled).
Unzip this folder and place all the files in it to your directory where main.py file

- But if you want to compile it for yourself click on link below for .wheel file
[https://drive.google.com/file/d/1Sdg8iRwmjIrju-c7ikOZrkxRyPzAP0oH/view?usp=sharing](url)
and install is with `pip install webrtcvad-2.0.10-cp37-cp37m-linux_x86_64.whl`

@blacksocket 
For users if needed in future

**Comment by berzi** [comment]
@Sadam1195 neither of those links work for me (it just sends me to a github page says no result match the search), and there's no main.py file anywhere on the repo so I don't know where I should put the files even if I could get them.

**Comment by Sadam1195** [comment]
> @Sadam1195 neither of those links work for me (it just sends me to a github page says no result match the search), and there's no main.py file anywhere on the repo so I don't know where I should put the files even if I could get them.

Hey @berzi do not click the link, instead copy the text of link and paste in new tab and you'll be directed rightly. Hope it helps.

**Comment by berzi** [comment]
Thank you, yes, that worked.
I'm trying to run demo_cly.py but I keep getting exceptions, and I've installed all packages I could as they kept being reported as not found, but I'm stuck here:

> Traceback (most recent call last):
>   File "demo_cli.py", line 36, in <module>
>     import sounddevice as sd
>   File "/home/brzrkr/.local/lib/python3.7/site-packages/sounddevice.py", line 71, in <module>
>     raise OSError('PortAudio library not found')
> OSError: PortAudio library not found
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
>     from apport.fileutils import likely_packaged, get_recent_crashes
>   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
>     from apport.report import Report
>   File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
>     import apport.fileutils
>   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
>     from apport.packaging_impl import impl as packaging
>   File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
>     import apt
>   File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
>     import apt_pkg
> **ModuleNotFoundError: No module named 'apt_pkg'**
> 
> Original exception was:
> Traceback (most recent call last):
>   File "demo_cli.py", line 36, in <module>
>     import sounddevice as sd
>   File "/home/brzrkr/.local/lib/python3.7/site-packages/sounddevice.py", line 71, in <module>
>     raise OSError('PortAudio library not found')
> **OSError: PortAudio library not found**

In particular, I tried to find apt_pkg but couldn't find it with apt nor with pip. Are you able to help? @Sadam1195

**Comment by Sadam1195** [comment]
> PortAudio library not found

```
sudo apt-get update
sudo apt-get install libportaudio2
sudo apt-get install libasound-dev
sudo apt-get install python-pyaudio
sudo apt-get install python3-pyaudio
```
Try these, I don't remember which one but one of these worked for me. 
@berzi

**Comment by berzi** [comment]
Thank you, that worked. These dependencies should probably be documented...

**Comment by berzi** [comment]
Now demo_cli.py gives the following message:
> Your PyTorch installation is not configured to use CUDA. If you have a GPU ready for deep learning, ensure that the drivers are properly installed, and that your CUDA version matches your PyTorch installation. CPU-only inference is currently not supported.

My GPU supports CUDA but according to an internet search it seems the drivers should be enough to run pytorch. How do I make the CUDA and pytorch versions "match"?

**Comment by Sadam1195** [comment]
> Now demo_cli.py gives the following message:
> 
> > Your PyTorch installation is not configured to use CUDA. If you have a GPU ready for deep learning, ensure that the drivers are properly installed, and that your CUDA version matches your PyTorch installation. CPU-only inference is currently not supported.
> 
> My GPU supports CUDA but according to an internet search it seems the drivers should be enough to run pytorch. How do I make the CUDA and pytorch versions "match"?

please refer that to the relevant issue.

**Comment by blue-fish** [comment]
webrtvcad is no longer required as of #375 so everyone who got stuck on this step is invited to pull the latest from the repo and try again.

**Comment by floripaoliver** [comment]
> [https://drive.google.com/file/d/1ze3PHQtfpzCietKjyRT9Nd1t5jXKqtfS/view?usp=sharing](url)
> 
> * The provided link is for windows 10, python 3.
> * Unzip this folder and place all the files in it to your directory where main.py file is.
> 
> @ZenithBerserker @rdrlima

I am new to this and got all working but when I try to use the encode_preprocess.py I got stuck because of the missing webrtvcd issue. I downloaded your files but I am not sure where to place the, I don't see anywhere the main.py? Sorry again for this question here but I just got this work yesterday and this is all new to me.

**Comment by Sadam1195** [comment]
> > [https://drive.google.com/file/d/1ze3PHQtfpzCietKjyRT9Nd1t5jXKqtfS/view?usp=sharing](url)
> > 
> > * The provided link is for windows 10, python 3.
> > * Unzip this folder and place all the files in it to your directory where main.py file is.
> > 
> > @ZenithBerserker @rdrlima
> 
> I am new to this and got all working but when I try to use the encode_preprocess.py I got stuck because of the missing webrtvcd issue. I downloaded your files but I am not sure where to place the, I don't see anywhere the main.py? Sorry again for this question here but I just got this work yesterday and this is all new to me.

First download the folder, then unzip it.
After unzipping it, copy the content of that folder into the folder where code is, like where you need to import the webrtcvad
Hope it helps.
@floripaoliver

**Comment by floripaoliver** [comment]
@Sadam1195 Awesome! worked like charm! thank you for your extremely fast reply too. ;)
