### ISSUE TITLE
PortAudio or PyAudio False

### ISSUE THREAD

**Issue by srmmedia** [CorentinJ/Real-Time-Voice-Cloning#18]
So I spent the last 3 days trying to get this installed having one problem after the next and I finally worked out all the kinks and managed to get Python to run the python demo_cli py  command just to test everything out to make sure it all works and is installed correctly and I am getting this response : 

Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer import inference as synthesizer
  File "C:\Users\Jay Tea\Documents\Vclone\synthesizer\inference.py", line 2, in <module>
    from synthesizer.synthesizer import Synthesizer
  File "C:\Users\Jay Tea\Documents\Vclone\synthesizer\synthesizer.py", line 4, in <module>
    from synthesizer.models import create_model
ModuleNotFoundError: No module named 'synthesizer.models'\

I don't know anything about python or any of this stuff and most of the language you guys use is greek to me.  Im suprised I got this far.    I am using the Latest verson of Python and the lastest version of Pytorch if that is any help .. I am on Windows 10 and I have CUDA 10

**Comment by CorentinJ** [comment]
No problem, let's walk this through and see what's happening.

Python is saying it cannot see the directory `synthesizer/models` as a module, meaning that the directory either isn't there, that the file `__init__.py` isn't in the directory anymore or that it's not using the proper path to find the module. Can you check the first two? I.e., can you verify that you have exactly [these files](https://github.com/CorentinJ/Real-Time-Voice-Cloning/tree/master/synthesizer/models)?

**Comment by srmmedia** [comment]
> No problem, let's walk this through and see what's happening.
> 
> Python is saying it cannot see the directory `synthesizer/models` as a module, meaning that the directory either isn't there, that the file `__init__.py` isn't in the directory anymore or that it's not using the proper path to find the module. Can you check the first two? I.e., can you verify that you have exactly [this file structure](https://github.com/CorentinJ/Real-Time-Voice-Cloning/tree/master/synthesizer/models)?

Well I did not have that file structure before but I do now after extracting the files in my directory again. I think I made the mistake of joining the downled samples into the folder and I changed the name from models to sample models because I was getting the error that "sample models" could not be found so I assumed it was a mistake.    I got past that error and then got the one I showed you first.    I have now put those files back and my directory does contain all those files ..   I tried to launch it again and now I am getting a different error:  

C:\Users\Jay Tea\Documents\Vclone>python demo_cli.py
WARNING: Logging before flag parsing goes to stderr.
W0625 06:21:51.033622  4416 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Traceback (most recent call last):
  File "demo_cli.py", line 5, in <module>
    from vocoder import inference as vocoder
  File "C:\Users\Jay Tea\Documents\Vclone\vocoder\inference.py", line 1, in <module>
    from vocoder.models.fatchord_version import WaveRNN
ModuleNotFoundError: No module named 'vocoder.models'

**Comment by CorentinJ** [comment]
It's the same thing again. You should restart from scratch. Clone the repository again and extract the contents of the pretrained models archive at the root (that's all you have to do, really). Don't change anything else. Then run the script.

**Comment by srmmedia** [comment]
Ok I did what you said and now I am getting this: 


C:\Users\Jay Tea\Documents\Vclone>C:\Users\Jay Tea\Documents\Vclone>python demo_cli.py
'C:\Users\Jay' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Jay Tea\Documents\Vclone>WARNING: Logging before flag parsing goes to stderr.
'WARNING:' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Jay Tea\Documents\Vclone>W0625 06:21:51.033622  4416 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.
'W0625' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Jay Tea\Documents\Vclone>
C:\Users\Jay Tea\Documents\Vclone>Traceback (most recent call last):
'Traceback' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Jay Tea\Documents\Vclone>  File "demo_cli.py", line 5, in <module>
The syntax of the command is incorrect.

C:\Users\Jay Tea\Documents\Vclone>    from vocoder import inference as vocoder
'from' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Jay Tea\Documents\Vclone>  File "C:\Users\Jay Tea\Documents\Vclone\vocoder\inference.py", line 1, in <module>
The syntax of the command is incorrect.

C:\Users\Jay Tea\Documents\Vclone>    from vocoder.models.fatchord_version import WaveRNN
'from' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Jay Tea\Documents\Vclone>ModuleNotFoundError: No module named 'vocoder.models'
'ModuleNotFoundError:' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Jay Tea\Documents\Vclone>python demo_cli.py
WARNING: Logging before flag parsing goes to stderr.
W0625 06:28:20.329681  1296 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

This is a UI-less example of interface to SV2TTS. The purpose of this script is to show how you can interface this project easily with your own. See the source code for an explanation of what is happening.

Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_dir:     synthesizer\saved_models\logs-pretrained
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    no_sound:          False

A s s e r t i o n   f a i l e d !

 P r o g r a m :   C : \ U s e r s \ J a y   T e a \ A p p D a t a \ L o c a l \ P r o g r a m s \ P y t h o n \ P y t h o n 3 7 \ p y t h o n . e x e
 F i l e :   s r c / h o s t a p i / w d m k s / p a _ w i n _ w d m k s . c ,   L i n e   1 0 6 1

 E x p r e s s i o n :   F A L S E

**Comment by CorentinJ** [comment]
It seems there is an issue with your audio driver. Could you run the program with `--no_sound` in a first time, to see if it works?

**Comment by srmmedia** [comment]
now this WARNING: Logging before flag parsing goes to stderr.
W0625 06:31:42.789124 13028 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

This is a UI-less example of interface to SV2TTS. The purpose of this script is to show how you can interface this project easily with your own. See the source code for an explanation of what is happening.

Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_dir:     synthesizer\saved_models\logs-pretrained
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    no_sound:          False

A s s e r t i o n   f a i l e d !

 P r o g r a m :   C : \ U s e r s \ J a y   T e a \ A p p D a t a \ L o c a l \ P r o g r a m s \ P y t h o n \ P y t h o n 3 7 \ p y t h o n . e x e
 F i l e :   s r c / h o s t a p i / w d m k s / p a _ w i n _ w d m k s . c ,   L i n e   1 0 6 1

 E x p r e s s i o n :   F A L S E

C:\Users\Jay Tea\Documents\Vclone>

**Comment by srmmedia** [comment]
> It seems there is an issue with your audio driver. Could you run the program with `--no_sound` in a first time, to see if it works?

C:\Users\Jay Tea\Documents\Vclone>--no_sound
'--no_sound' is not recognized as an internal or external command,
operable program or batch file.

**Comment by CorentinJ** [comment]
You did not properly add the argument. You're supposed to run

`python demo_cli.py --no_sound`

**Comment by srmmedia** [comment]
C:\Users\Jay Tea>python --no_sound
unknown option --no_sound
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

**Comment by CorentinJ** [comment]
check the command again, that's not what I gave you

**Comment by srmmedia** [comment]
Ok i did it and it says that it works but when I try to launch the demo_cli py  again     I get the same  crash and FALSE error    here is the log  

C:\Users\Jay Tea\Documents\Vclone>python demo_cli.py --no_sound
WARNING: Logging before flag parsing goes to stderr.
W0625 06:36:24.914371  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

This is a UI-less example of interface to SV2TTS. The purpose of this script is to show how you can interface this project easily with your own. See the source code for an explanation of what is happening.

Arguments:
    enc_model_fpath:   encoder\saved_models\pretrained.pt
    syn_model_dir:     synthesizer\saved_models\logs-pretrained
    voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
    no_sound:          True

Found 1 GPUs available. Using GPU 0 (GeForce GTX 1070) of compute capability 6.1 with 8.6Gb total memory.

Loading the encoder, the synthesizer and the vocoder. This should take a few seconds. The synthesizer will output a lot of stuff. Tensorflow is like that.
Loaded encoder "pretrained.pt" trained to step 1564501
W0625 06:36:28.198806  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\inference.py:18: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

Constructing model: Tacotron
W0625 06:36:28.201795  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\synthesizer.py:16: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0625 06:36:28.204787  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\synthesizer.py:22: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0625 06:36:28.207773  6824 deprecation.py:323] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\tacotron.py:86: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

W0625 06:36:28.211768  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\tacotron.py:123: The name tf.train.replica_device_setter is deprecated. Please use tf.compat.v1.train.replica_device_setter instead.

W0625 06:36:28.212747  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\tacotron.py:135: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

W0625 06:36:28.213744  6824 deprecation.py:506] From C:\Users\Jay Tea\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0625 06:36:28.219744  6824 deprecation.py:323] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:112: LSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
W0625 06:36:28.220747  6824 deprecation.py:323] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:421: conv1d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv1D` instead.
W0625 06:36:28.286573  6824 deprecation.py:323] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:422: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
W0625 06:36:28.333447  6824 deprecation.py:323] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:425: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
W0625 06:36:28.416225  6824 deprecation.py:323] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:236: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
W0625 06:36:28.416225  6824 deprecation.py:323] From C:\Users\Jay Tea\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\rnn.py:464: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W0625 06:36:28.470080  6824 deprecation.py:506] From C:\Users\Jay Tea\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py:961: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0625 06:36:28.847071  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:156: The name tf.nn.rnn_cell.LSTMStateTuple is deprecated. Please use tf.compat.v1.nn.rnn_cell.LSTMStateTuple instead.

W0625 06:36:28.848072  6824 deprecation.py:323] From C:\Users\Jay Tea\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\rnn.py:244: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0625 06:36:29.126325  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\attention.py:158: The name tf.layers.Conv1D is deprecated. Please use tf.compat.v1.layers.Conv1D instead.

W0625 06:36:29.127300  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\attention.py:161: The name tf.layers.Dense is deprecated. Please use tf.compat.v1.layers.Dense instead.

W0625 06:36:29.128319  6824 deprecation.py:323] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:305: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
W0625 06:36:29.210095  6824 deprecation.py:323] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\modules.py:269: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
W0625 06:36:29.436499  6824 ag_logging.py:145] Entity <bound method ZoneoutLSTMCell.__call__ of <synthesizer.models.modules.ZoneoutLSTMCell object at 0x0000024CA46900B8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ZoneoutLSTMCell.__call__ of <synthesizer.models.modules.ZoneoutLSTMCell object at 0x0000024CA46900B8>>: ValueError: Failed to parse source code of <bound method ZoneoutLSTMCell.__call__ of <synthesizer.models.modules.ZoneoutLSTMCell object at 0x0000024CA46900B8>>, which Python reported as:
    def __call__(self, inputs, state, scope=None):
        """Runs vanilla LSTM Cell and applies zoneout.
        """
        # Apply vanilla LSTM
        output, new_state = self._cell(inputs, state, scope)

        if self.state_is_tuple:
            (prev_c, prev_h) = state
            (new_c, new_h) = new_state
        else:
            num_proj = self._cell._num_units if self._cell._num_proj is None else \
                                self._cell._num_proj
            prev_c = tf.slice(state, [0, 0], [-1, self._cell._num_units])
            prev_h = tf.slice(state, [0, self._cell._num_units], [-1, num_proj])
            new_c = tf.slice(new_state, [0, 0], [-1, self._cell._num_units])
            new_h = tf.slice(new_state, [0, self._cell._num_units], [-1, num_proj])

        # Apply zoneout
        if self.is_training:
            # nn.dropout takes keep_prob (probability to keep activations) not drop_prob (
                        # probability to mask activations)!
            c = (1 - self._zoneout_cell) * tf.nn.dropout(new_c - prev_c,
                                                         (1 - self._zoneout_cell)) + prev_c
            h = (1 - self._zoneout_outputs) * tf.nn.dropout(new_h - prev_h,
                                                            (1 - self._zoneout_outputs)) + prev_h

        else:
            c = (1 - self._zoneout_cell) * new_c + self._zoneout_cell * prev_c
            h = (1 - self._zoneout_outputs) * new_h + self._zoneout_outputs * prev_h

        new_state = tf.nn.rnn_cell.LSTMStateTuple(c, h) if self.state_is_tuple else tf.concat(1, [c,
                                                                                                  h])

        return output, new_state

This may be caused by multiline strings or comments not indented at the same level as the code.
W0625 06:36:29.464419  6824 ag_logging.py:145] Entity <bound method ZoneoutLSTMCell.__call__ of <synthesizer.models.modules.ZoneoutLSTMCell object at 0x0000024CB49C2358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ZoneoutLSTMCell.__call__ of <synthesizer.models.modules.ZoneoutLSTMCell object at 0x0000024CB49C2358>>: ValueError: Failed to parse source code of <bound method ZoneoutLSTMCell.__call__ of <synthesizer.models.modules.ZoneoutLSTMCell object at 0x0000024CB49C2358>>, which Python reported as:
    def __call__(self, inputs, state, scope=None):
        """Runs vanilla LSTM Cell and applies zoneout.
        """
        # Apply vanilla LSTM
        output, new_state = self._cell(inputs, state, scope)

        if self.state_is_tuple:
            (prev_c, prev_h) = state
            (new_c, new_h) = new_state
        else:
            num_proj = self._cell._num_units if self._cell._num_proj is None else \
                                self._cell._num_proj
            prev_c = tf.slice(state, [0, 0], [-1, self._cell._num_units])
            prev_h = tf.slice(state, [0, self._cell._num_units], [-1, num_proj])
            new_c = tf.slice(new_state, [0, 0], [-1, self._cell._num_units])
            new_h = tf.slice(new_state, [0, self._cell._num_units], [-1, num_proj])

        # Apply zoneout
        if self.is_training:
            # nn.dropout takes keep_prob (probability to keep activations) not drop_prob (
                        # probability to mask activations)!
            c = (1 - self._zoneout_cell) * tf.nn.dropout(new_c - prev_c,
                                                         (1 - self._zoneout_cell)) + prev_c
            h = (1 - self._zoneout_outputs) * tf.nn.dropout(new_h - prev_h,
                                                            (1 - self._zoneout_outputs)) + prev_h

        else:
            c = (1 - self._zoneout_cell) * new_c + self._zoneout_cell * prev_c
            h = (1 - self._zoneout_outputs) * new_h + self._zoneout_outputs * prev_h

        new_state = tf.nn.rnn_cell.LSTMStateTuple(c, h) if self.state_is_tuple else tf.concat(1, [c,
                                                                                                  h])

        return output, new_state

This may be caused by multiline strings or comments not indented at the same level as the code.
initialisation done /gpu:0
W0625 06:36:29.762600  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\models\tacotron.py:286: The name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_variables instead.

Initialized Tacotron model. Dimensions (? = dynamic shape):
  Train mode:               False
  Eval mode:                False
  GTA mode:                 False
  Synthesis mode:           True
  Input:                    (?, ?)
  device:                   0
  embedding:                (?, ?, 512)
  enc conv out:             (?, ?, 512)
  encoder out (cond):       (?, ?, 768)
  decoder out:              (?, ?, 80)
  residual out:             (?, ?, 512)
  projected residual out:   (?, ?, 80)
  mel out:                  (?, ?, 80)
  <stop_token> out:         (?, ?)
  Tacotron Parameters       28.439 Million.
Loading checkpoint: synthesizer\saved_models\logs-pretrained\taco_pretrained\tacotron_model.ckpt-278000
2019-06-25 06:36:29.770423: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-06-25 06:36:29.779078: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-06-25 06:36:29.783882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
2019-06-25 06:36:29.788817: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-06-25 06:36:29.794253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-06-25 06:36:29.797665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-25 06:36:29.801139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-06-25 06:36:29.804398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-06-25 06:36:29.807644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6045 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
W0625 06:36:29.988013  6824 deprecation_wrapper.py:119] From C:\Users\Jay Tea\Documents\Vclone\synthesizer\synthesizer.py:63: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0625 06:36:30.027906  6824 deprecation.py:323] From C:\Users\Jay Tea\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Loaded synthesizer "pretrained" trained to step 278000
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt

All models succesfully loaded!

Testing your configuration with small inputs.
        Testing the encoder...
        Testing the synthesizer...
        Testing the vocoder...
All test passed! You can now synthesize speech.

**Comment by CorentinJ** [comment]
There are plenty of warnings because tensorflow likes to output them routinely, but it's working: check the end of the output.

Fix your sound drivers and run the program without `--no_sounds` and see how that goes.

**Comment by srmmedia** [comment]
Thanks for all your help.   I reinstalled my sound drivers from the MSI website and I downloaded the exact ones for my MotherBoard and I still get the same NO SOUND error and python crash.    I don't know what else to do really at this point.

**Comment by srmmedia** [comment]
I think it has something to do with tensor flow  

 The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead
