### ISSUE TITLE
Where is generated wave file?

### ISSUE THREAD

**Issue by manfonly** [CorentinJ/Real-Time-Voice-Cloning#181]
I am running this code from remote server by VNC, I can not hear voice, how can I download generated wave file?
From demo_toolbox I can see the log is OK, Waveform is generated, but there is nothing in the data directory.

**Comment by vezzick** [comment]
I saved the file by adding something like this to the end of "def vocode(self):" in __init__.py in toolbox:

```
        fpath = "demo_output_toolbox.wav"
        librosa.output.write_wav(fpath, wav.astype(np.float32), 
                                    Synthesizer.sample_rate)
        print("\nSaved output as %s\n\n" % fpath)
```

(and import librosa)
