### ISSUE TITLE
CUDA, cudNN, tensorflow versions

### ISSUE THREAD

**Issue by vezzick** [CorentinJ/Real-Time-Voice-Cloning#186]
Anybody who got this working, what versions of CUDA, CUDNN and tensorflow does this work for?

I am having some issues around this, demo_cli works but not demo_toolbox, I think it may be an issue unrelated to this repository but wanted to know what the best setup for this people have used is.

**Comment by vezzick** [comment]
Although still might be useful for others to see what versions to use, I found the problem was that pytorch installed a version of cudnn separately from installed on my computer, so had to replace that cudnn dll with the proper version.

I got it working with:
tensorflow-gpu 1.14.0
cuda: 10.0
cudnn: 7.4.2

**Comment by Arumathos** [comment]
Working with:

tensorflow 1.14
tensorflow-gpu 1.14
cuda: 10.0
cudnn: 7.6.5
