### ISSUE TITLE
Error in helpers.py with contrib.seq2seq

### ISSUE THREAD

**Issue by johncormack** [CorentinJ/Real-Time-Voice-Cloning#187]
Hello, i am getting a ModuleNotFoundError: No module named 'tensorflow.contrib', it's the import line from helpers.py 
from tensorflow.contrib.seq2seq import Helper
Where is seq2seq located now?

**Comment by blue-fish** [comment]
It is due to using a version of tensorflow that is too old, or too new (>=2.0).

You need to be using tensorflow 1.15 with the very latest version of the repo. Please pull the latest and repeat the installation steps. I am confident that you won't be getting the same error.
