### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.argutils'

### ISSUE THREAD

**Issue by smmiSlam** [CorentinJ/Real-Time-Voice-Cloning#188]
The title says it. I don't understand what is going wrong or where. I tried running it from Kaggle notebook. I have tried to clone the repo into the notebook and also downloading this repo as zip and putting it into the working directory. Both times, it is showing the same error. However, I checked both times, that the file "utils/argutils.py" exists within the path.

![image](https://user-images.githubusercontent.com/19931778/68189965-d0641f80-ffef-11e9-81a7-6041408402fc.png)

I have installed all the dependencies except "sounddevice". Please help me understand where is the problem. Thank you.

**Comment by blue-fish** [comment]
Hello @smmiSlam , thank you for reporting this issue. Unfortunately we cannot support Kaggle Notebook as a platform (we already get more questions than we can handle for Windows, macOS, Linux, and Google colab).

I would like to mention that we have recently enabled CPU support for the toolbox so you should be able to run on most computers now. The GPU is no longer required. Please pull the latest on your computer and try it out!

**Comment by blue-fish** [comment]
I don't mean to discourage anyone from using Kaggle Notebook with this repo. It should work. We just cannot provide setup support and troubleshooting for issues that may be Kaggle-specific.

**Comment by smmiSlam** [comment]
Thank you @blue-fish, for getting back to me.
