### ISSUE TITLE
Tensorflow-gpu Version problem

### ISSUE THREAD

**Issue by entropylaw** [CorentinJ/Real-Time-Voice-Cloning#194]
>pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu<=1.14.0,>=1.10.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu<=1.14.0,>=1.10.0 (from -r requirements.txt (line 1))

**Comment by Felizolinha** [comment]
Were you able to fix this?

**Comment by entropylaw** [comment]
> Were you able to fix this?

Yea, I accidentally installed 3.8.

**Comment by Danika207** [comment]
What do you mean? So now its working for you? (If yes, then what version of python are you using that makes it work for you?)

**Comment by Nelsi0** [comment]
conda install tensorflow-gpu 1.14.0
