### ISSUE TITLE
No audio playback

### ISSUE THREAD

**Issue by ghost** [CorentinJ/Real-Time-Voice-Cloning#196]
I'm not getting any audio playback and pulseaudio volume control is not indicating any audio playback as well.
There are no error messages as well.
(Ubuntu 19.04)

**Comment by blue-fish** [comment]
@ghost Try pulling the latest version of the code and see if the issue persists. I believe that it is likely related to #390 which we merged in the last day. So hopefully fixed now.

**Comment by blue-fish** [comment]
Feel free to reopen the issue if you continue to not get any audio. The toolbox should be a little more helpful and provide a warning (in the terminal) if your output device does not support the sample rate (16 kHz).
