### ISSUE TITLE
No encoder models found in encoder/saved_models BUT the files are in the directory!

### ISSUE THREAD

**Issue by applejack1063** [CorentinJ/Real-Time-Voice-Cloning#199]
I have a really weird problem here.  I have the pretrained.pt file located under:

D:\a\encoder\saved_models

but it says that it can't find the model.  What am I doing wrong here?

EDIT:  And yes, I have downloaded the pretrained models from here:

https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models

**Comment by blue-fish** [comment]
Hi there @applejack1063 . You should also ensure that the pretrained model is located at encoder/saved_models with respect to the location that demo_cli.py, or demo_toolbox.py is located.

There is not enough info to troubleshoot further, please provide the error message and full traceback, and reopen the issue.
