### ISSUE TITLE
PyQt4 and torch are not installable through pip

### ISSUE THREAD

**Issue by kool601** [CorentinJ/Real-Time-Voice-Cloning#2]
I had to manually install them. Pip doesn't seem to want to install those two.

**Comment by CorentinJ** [comment]
Fixed in a538d6cb87425ce7e196737d46286031e60d4f86

**Comment by kool601** [comment]
Also, I have a question. How do you use audio clips from your PC to create the embeddings? If I'm saying that correctly. Like without the microphone.

**Comment by CorentinJ** [comment]
See ec9658aad21178c90c5f673778c2c0051e33ad35

**Comment by kool601** [comment]
I think it would be easier to have a way to just import arbitrary audio files from anywhere on the PC through a file dialog.

**Comment by CorentinJ** [comment]
I can do that, but it will be one file at a time for now

**Comment by kool601** [comment]
That's perfectly fine.

**Comment by CorentinJ** [comment]
Done in 41c37b273fc1c150ceeab0906a6c1282163d9d5b
