### ISSUE TITLE
AMD / CPU-only support?

### ISSUE THREAD

**Issue by zankai2** [CorentinJ/Real-Time-Voice-Cloning#202]
Can't run it...

**Comment by daslicht** [comment]
you managed to get it wiorking with amd / cpu ?

**Comment by Traincraft101** [comment]
I have it working on amd ryzen 5 2600x

**Comment by Titaniumtown** [comment]
I had to manually edit the code to get it working

**Comment by genewitch** [comment]
> 
> 
> I had to manually edit the code to get it working

Can you do a PR / fork?

**Comment by deepseek** [comment]
@Traincraft101 push the edited code

**Comment by ByPort** [comment]
I got rid of all CUDA references in code and was able to run it on CPU
Try [my repo](https://github.com/ByPort/Real-Time-Voice-Cloning) or take a look at [this commit](https://github.com/ByPort/Real-Time-Voice-Cloning/commit/31bbd88b0b1823a562f1bd419a2881b672bb639a)
@genewitch @deepseek

**Comment by GtOkAi** [comment]
> I got rid of all CUDA references in code and was able to run it on CPU
> Try [my repo](https://github.com/ByPort/Real-Time-Voice-Cloning) or take a look at [this commit](https://github.com/ByPort/Real-Time-Voice-Cloning/commit/31bbd88b0b1823a562f1bd419a2881b672bb639a)
> @genewitch @deepseek

I tried your repo, but returned same error. Need some special action?

**Comment by Traincraft101** [comment]
@deepsek I didn't edit the code, it just worked for me.

**Comment by seriiix** [comment]
@ByPort @GtOkAi Same.

**Comment by ByPort** [comment]
@GtOkAi @seriiix I used demo_toolbox.py. Just altered demo_cli.py so pull and try again

**Comment by GtOkAi** [comment]
@ByPort @seriiix Worked with `pip3 install tensorflow==1.13.1`

**Comment by gabrielmontagne** [comment]
@ByPort , awesome. thanks so much.

**Comment by Sba-Stuff** [comment]
> I got rid of all CUDA references in code and was able to run it on CPU
> Try [my repo](https://github.com/ByPort/Real-Time-Voice-Cloning) or take a look at [this commit](https://github.com/ByPort/Real-Time-Voice-Cloning/commit/31bbd88b0b1823a562f1bd419a2881b672bb639a)
> @genewitch @deepseek

Tried Running This Code, Got An Issue Now , nvcuda.dll not found.

Traceback (most recent call last):
  File "RTVC/demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Python\36\RTVC\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Python\36\RTVC\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Python\36\RTVC\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Python\36\RTVC\synthesizer\models\tacotron.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Python\36\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Python\36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python\36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Python\36\lib\site-packages\tensorflow\python\platform\self_check.py", line 70, in preload_check
    % build_info.nvcuda_dll_name)

ImportError: "Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed."

**Comment by DonaldTsang** [comment]
https://mc.ai/clone-your-voice-in-5-minutes/

**Comment by Sba-Stuff** [comment]
Thank You. I Did It.
https://www.youtube.com/watch?v=Ob44qT1c4TY

**Comment by blue-fish** [comment]
Thank you for pioneering CPU support on this project @ByPort .

@pusalieth has implemented an elegant solution in #366 which provides GPU support if it is available and falls back to CPU if necessary. Training works too! It is implemented in the main repo so I would like to suggest that everyone use that instead so we can continue developing it together.
