### ISSUE TITLE
 The memory used raise

### ISSUE THREAD

**Issue by freecui** [CorentinJ/Real-Time-Voice-Cloning#207]
The memory used raise when I run the synthesizer_preprocess_embeds.py; I also doubt whether there is the memory leak or not;

**Comment by blue-fish** [comment]
### Data
Before launching synthesizer_preprocess_embeds.py (on LibriSpeech train-clean-100 and 360):
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            62G        874M         60G         19M        827M         61G
Swap:          979M          0B        979M
```

Immediately after launching synthesizer_preprocess_embeds.py:
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            62G        8.6G         52G         67M        1.6G         53G
Swap:          979M          0B        979M
```

At 35% completion (about 40 min on my computer):
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            62G        8.8G         23G         67M         30G         52G
Swap:          979M          0B        979M
```

### Conclusion
It looks like the data is being cached as it is loaded/being processed, causing free memory to decrease. If there is a memory leak it doesn't seem very serious. Anyone with data is welcome to reopen this issue.
