### ISSUE TITLE
EXACT working environment

### ISSUE THREAD

**Issue by msebi** [CorentinJ/Real-Time-Voice-Cloning#215]
I've been trying to get voice cloning to work for several hours with not success. Can someone be so kind as to share an **EXACT** functional working environment. Packages have changed quite a bit and a mish mash between conda and pip seems unavoidable:

https://pytorch.org/docs/stable/notes/windows.html#import-error

**Comment by s0py** [comment]
I have the same problem. After about 3 hours of trial and error I get the program to launch but tensorflow can't get the "convolution" algorithm.

**Comment by msebi** [comment]
> I have the same problem. After about 3 hours of trial and error I get the program to launch but tensorflow can't get the "convolution" algorithm.

I managed to get it running. Sanity saving guide:

- install python 3.7.4 (strictly greater than 3.7.0 (otherwise conda will fail to initialize)
- create a venv; install conda through pip (you can't get the latest version directly)
- install dependencies as mentioned in the README using pip (never try with conda (it will remove some that it considers to be either circular or deprecated (it does this by default and can't seem to be changed)
- install strictly pytorch 1.0.1 (DON'T TRY NEWER VERSIONS AS THEY THROW AMBIGUOUS MISSING DLL ERRORS)
- make sure to go through this when all else fails:
https://pytorch.org/docs/stable/notes/windows.html#import-error

and this

https://devtalk.nvidia.com/default/topic/1038737/cuda-setup-and-installation/windows-10-cuda-installation-failure-solved/

- always install pytorch as a wheel package through pip (conda installs DO NOT INSTALL vc and vc redistributables 

It took me longer than three hours; it boils down to educated brute force

**Comment by gotoel** [comment]
> I have the same problem. After about 3 hours of trial and error I get the program to launch but tensorflow can't get the "convolution" algorithm.

Try tensorflow==1.13.1, worked for me to fix this error. https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/31

**Comment by msebi** [comment]
> > I have the same problem. After about 3 hours of trial and error I get the program to launch but tensorflow can't get the "convolution" algorithm.
> 
> Try tensorflow==1.13.1, worked for me to fix this error. #31

Why not tensorflow-gpu? It will default to the latest version in the requirements.txt (1.14.0 (make sure you have cuda 10.0))

**Comment by gotoel** [comment]
> > > I have the same problem. After about 3 hours of trial and error I get the program to launch but tensorflow can't get the "convolution" algorithm.
> > 
> > 
> > Try tensorflow==1.13.1, worked for me to fix this error. #31
> 
> Why not tensorflow-gpu? It will default to the latest version in requirements.txt (1.14.0 (make sure you have cuda 10.0))

I had tensorflow-gpu as well, but needed tensorflow for some reason. Maybe incorrect configuration, tensorflow-gpu==1.13.1 may have also fixed it.

**Comment by Arumathos** [comment]
> On a side note, make sure you have 25 GBs of RAM to spare otherwise you'll have wasted time.

I'm not sure why you said that, I've been voice cloning just fine with 8 GBs of RAM.
Plus I also used Conda to install the packages to a functional state, including version 1.2 of Pytorch.
The main issue I dealt with was finding which version of tensorflow would work with my CPU, which turned out to be 1.14.

**Comment by AllenSilver** [comment]
Could anyone please write down all the terminal commands needed to get this started?

**Comment by s0py** [comment]
> 
> 
> > I have the same problem. After about 3 hours of trial and error I get the program to launch but tensorflow can't get the "convolution" algorithm.
> 
> I managed to get it running. Sanity saving guide:
> 
>     * install python 3.7.4 (strictly greater than 3.7.0 (otherwise conda will fail to initialize)
> 
>     * create a venv; install conda through pip (you can't get the latest version directly)
> 
>     * install dependencies as mentioned in the README using pip (never try with conda (it will remove some that it considers to be either circular or deprecated (it does this by default and can't seem to be changed)
> 
>     * install strictly pytorch 1.0.1 (DON'T TRY NEWER VERSIONS AS THEY THROW AMBIGUOUS MISSING DLL ERRORS)
> 
>     * make sure to go through this when all else fails:
>       https://pytorch.org/docs/stable/notes/windows.html#import-error
> 
> 
> and this
> 
> https://devtalk.nvidia.com/default/topic/1038737/cuda-setup-and-installation/windows-10-cuda-installation-failure-solved/
> 
>     * always install pytorch as a wheel package through pip (conda installs DO NOT INSTALL vc and vc redistributables from
> 
> 
> https://pytorch.org/get-started/previous-versions/
> 
> It took me longer than three hours; it boils down to educated brute force.
> 
> On a side note, make sure you have 25 GBs of RAM to spare otherwise you'll have wasted time.

Could you go a bit more in depth on the conda installation and venv creation?
I've never dealt with either before.

**Comment by AllenSilver** [comment]
Same as above. I don't use Linux a lot and half the commands don't work, and it's not clear from the readme what to actually type in to use this software.

**Comment by Jakorbie** [comment]
> > I have the same problem. After about 3 hours of trial and error I get the program to launch but tensorflow can't get the "convolution" algorithm.
> 
> I managed to get it running. Sanity saving guide:
> 
> * install python 3.7.4 (strictly greater than 3.7.0 (otherwise conda will fail to initialize)
> * create a venv; install conda through pip (you can't get the latest version directly)
> * install dependencies as mentioned in the README using pip (never try with conda (it will remove some that it considers to be either circular or deprecated (it does this by default and can't seem to be changed)
> * install strictly pytorch 1.0.1 (DON'T TRY NEWER VERSIONS AS THEY THROW AMBIGUOUS MISSING DLL ERRORS)
> * make sure to go through this when all else fails:
>   https://pytorch.org/docs/stable/notes/windows.html#import-error
> 
> and this
> 
> https://devtalk.nvidia.com/default/topic/1038737/cuda-setup-and-installation/windows-10-cuda-installation-failure-solved/
> 
> * always install pytorch as a wheel package through pip (conda installs DO NOT INSTALL vc and vc redistributables from
> 
> https://pytorch.org/get-started/previous-versions/
> 
> It took me longer than three hours; it boils down to educated brute force.
> 
> On a side note, make sure you have 25 GBs of RAM to spare otherwise you'll have wasted time.

Thank you so much for your help. I finally got it working even tough there are still other minor issues.
The settings that works for me is: PyTorch 1.0.1 with cuda 10.0 , and python 3.75.
I previously tried cuda 9.0, and the newer version of PyTorch, they didn't work at all !
For me, I have to use PyTorch 1.01. That's the only version that works.

**Comment by s0py** [comment]
What pip command are people using to get pytorch 1.0.1?

**Comment by Port0r** [comment]
Here is what worked for me so far:

**CUDA Toolkit 10.0 (Sept 2018)**
https://developer.nvidia.com/cuda-10.0-download-archive

**cuDNN v7.6.5 (November 5th, 2019), for CUDA 10.0** (you must create an account there to get it)
https://developer.nvidia.com/cudnn

**PyTorch, old enough for CUDA 10.0**
`pip install torch==1.2.0 torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`

But with the demo_toolbox.py I also get this convolution error, when I start the synthesizer + vocoder.
The demo_cli.py works fine and generates correct output, though.
I'm not really interested in the GUI as I will just build some web-interface around the CLI program. So it's fine for me...

**Comment by Port0r** [comment]
> What pip command are people using to get pytorch 1.0.1?

I haven't tested it, yet, but give this a try:
`pip install torch==1.0.1 torchvision==0.2.2 -f https://download.pytorch.org/whl/cu100/torch_stable.html`

**Comment by jsmith613** [comment]
Downgrading tensorflow to 1.13.1 worked for me. 
I also followed the instructions here: https://www.tensorflow.org/install/gpu#windows_setup
Make sure you add the right environment variables to the PATH.
With 1.14 versions and lower of tf, you need to install the CPU and GPU packages seperately.

**Comment by Traincraft101** [comment]
Here's what I have.
Anaconda installed in C:\
A Python 3.7.0 environment
Cuda 10.0
Cudnn for Cuda 10.0
Tensorflow gpu 1.14.0

Here's the full list of my installations when I run `pip list`
`absl-py              0.8.1
astor                0.8.0
audioread            2.1.8
certifi              2019.9.11
cffi                 1.13.1
chardet              3.0.4
cycler               0.10.0
decorator            4.4.1
dill                 0.3.1.1
gast                 0.3.2
google-pasta         0.1.8
grpcio               1.25.0
h5py                 2.10.0
idna                 2.8
importlib-metadata   0.23
inflect              3.0.2
joblib               0.14.0
jsonpatch            1.24
jsonpointer          2.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
librosa              0.7.1
llvmlite             0.30.0
Markdown             3.1.1
matplotlib           3.1.1
mkl-fft              1.0.15
mkl-random           1.1.0
mkl-service          2.3.0
more-itertools       7.2.0
multiprocess         0.70.9
numba                0.46.0
numpy                1.17.4
olefile              0.46
Pillow               6.2.1
pip                  19.3.1
protobuf             3.10.0
pycparser            2.19
pyparsing            2.4.5
PyQt5                5.13.2
PyQt5-sip            12.7.0
python-dateutil      2.8.1
pyzmq                18.1.0
requests             2.22.0
resampy              0.2.2
scikit-learn         0.21.3
scipy                1.3.2
setuptools           41.6.0.post20191030
six                  1.13.0
sounddevice          0.3.14
SoundFile            0.10.2
tensorboard          1.14.0
tensorflow-estimator 1.14.0
tensorflow-gpu       1.14.0
termcolor            1.1.0
torch                1.3.1
torchfile            0.1.0
torchvision          0.4.2
tornado              6.0.3
tqdm                 4.38.0
umap-learn           0.3.10
Unidecode            1.1.1
urllib3              1.25.7
visdom               0.1.8.9
webrtcvad            2.0.10
websocket-client     0.56.0
Werkzeug             0.16.0
wheel                0.33.6
wincertstore         0.2
wrapt                1.11.2
zipp                 0.6.0`

**Comment by blue-fish** [comment]
To everyone in the thread, sincere thanks for taking the time to share what has worked for you and to help others get the toolbox working.

However, the advice in this issue is now outdated due to code changes made in the last few weeks so I will be closing it. I am hopeful that the changes will make it easier to install since we've dropped GPU as a hard requirement, and made the webrtcvad package optional (it is difficult to install on Windows).

If you want my suggestion please go here. It is not the quickest way but I believe it is more robust. https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/225#issuecomment-653850695
