### ISSUE TITLE
Using the Project for WrittenAudio

### ISSUE THREAD

**Issue by rupin** [CorentinJ/Real-Time-Voice-Cloning#216]
This is specifically not an issue related to the code. I would be keen to try the project in a web environment.

I recently started a project called WrittenAudio (WrittenAudio.com, you can see a demo video here https://www.youtube.com/watch?v=eznPrInQ0rs&feature=share)

The project solves two problems 1) Eliminate the need to have recording equipment and sound proof rooms 2) Reduce the time it takes to sync and edit a video

It does this by providing the user with an audio track created with Text to Speech services.

The WrittenAudio project is currently in beta, with a few users only. 

How can I employ your work done in the Voice Cloning, to allow for people to record their voice, then use Text to Speech to generate audio without any noise? 

Current batch of voices on the platform use Google Text to Speech, and sound fairly robotic, even with the Wavenet voices. 

Thanks and keen to hear back from you!

**Comment by blue-fish** [comment]
This is beyond the scope for what we can provide support. You will need to figure out how to integrate the toolbox with your application. The demo_cli.py script is designed to help with that. Good luck with your project!
