### ISSUE TITLE
A couple inquiries about the colab version

### ISSUE THREAD

**Issue by rkjoan** [CorentinJ/Real-Time-Voice-Cloning#221]
So I have a setup using a copy of the colaboratory version, but I want to be able to generate a few sentences at a time without having to generate per sentence.

I understand that commas and periods don't work, but in the demonstration video it was mentioned that line breaks are a way to get around this for now... however that's done in the toolbox application. How would it be done in code?

I've tried \n but I assume that's only for print related arguments... but I'm fairly new to Python so excuse my ignorance.

On top of this, how could I improve the voice in colab? In regards to training, it's mentioned that a decent session requires around 500gb or more... since I don't exactly have that in colab, is there another way to go about doing this?

I've tried the code with the input being longer than 10 seconds, but apparently if the input is more than 10 seconds or so the voice seems more jittery than it would be if it were capped at 10 seconds. I absolutely applaud this repo but I just really need to understand it a bit better... Thanks in advance.

**Comment by blue-fish** [comment]
Hi there @rkjoan . Thanks for your thoughts and feedback. I've responded to your questions below.

> I understand that commas and periods don't work, but in the demonstration video it was mentioned that line breaks are a way to get around this for now... however that's done in the toolbox application. How would it be done in code?
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/49d4759503163a5133c2ac815e4a25eea9570fa2/toolbox/__init__.py#L171-L176

Basically splits up the text input to the synthesizer using `\n` as a delimiter and then concatenates the output into a single spectrogram for the vocoder.

> On top of this, how could I improve the voice in colab? In regards to training, it's mentioned that a decent session requires around 500gb or more... since I don't exactly have that in colab, is there another way to go about doing this?

You need better pretrained models. I'm not aware of any that perform better than Corentin's models. Another way is to use Amazon Sagemaker for training, though it is a paid solution. See #398 .

> I've tried the code with the input being longer than 10 seconds, but apparently if the input is more than 10 seconds or so the voice seems more jittery than it would be if it were capped at 10 seconds. 

This seems to be a similar issue to #347 . I don't see a need to keep this issue open so I will be closing it. If you want to continue the conversation feel free to reopen the issue.
