### ISSUE TITLE
Google Colab output file has no sound

### ISSUE THREAD

**Issue by Tymec** [CorentinJ/Real-Time-Voice-Cloning#223]
Google Colab notebook: https://colab.research.google.com/drive/1jv2B6VmjNq0KAeYFqDyLEnm8nuZ_GxqH

The output.wav is can't be played on the notebook and if downloaded it doent't have any sound.

**Comment by blue-fish** [comment]
Please try again, pulling the latest updates from the repo and using our colab notebook: https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/demo_toolbox_collab.ipynb . We cannot provide support for code outside the repo. You can also try installing the toolbox on your own computer, the GPU is no longer required. I wrote some directions here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/225#issuecomment-653850695

Please open a new issue if you experience any problems with the current version of the toolbox.
