### ISSUE TITLE
The Loss of the Encoder

### ISSUE THREAD

**Issue by Liujingxiu23** [CorentinJ/Real-Time-Voice-Cloning#224]
The loss of the encoder  is computed as CrossEntropyLoss of sim_matrix  and the groudtruth(0~63 ids). 
Why the loss designed like this?
Why not use the loss described in the paper "GENERALIZED END-TO-END LOSS FOR SPEAKER VERIFICATION".

**Comment by CorentinJ** [comment]
They are the same, just formulated differently. Note that there is a mistake in the GE2E paper, they've put an extra minus sign somewhere.

**Comment by Liujingxiu23** [comment]
@CorentinJ Thank you very much for you quick reply, I will see the computation in the scripts carefully.
