### ISSUE TITLE
Not code-savy but want to experiment with code

### ISSUE THREAD

**Issue by TheOfficialDan** [CorentinJ/Real-Time-Voice-Cloning#225]
I have Python Spyder downloaded, but I do not know much about coding, or how to get to the stage where I can add audio and synthesize it. What would you recommend?

**Comment by blue-fish** [comment]
Here is a relatively fool-proof way to get started.
1. Install Ubuntu 18.04 and connect to the internet. Use a virtual machine if you can't devote a computer to it.
2. Open a terminal and install Python 3.7 and the virtualenv package.
```
sudo apt install python3.7 python3-venv python3.7-venv
```
3. Install git and clone this repo:
```
sudo apt install git
git clone https://github.com/CorentinJ/Real-Time-Voice-Cloning
```
4. Set up a virtual environment and activate it:
```
cd Real-Time-Voice-Cloning
python37 -m venv env
source env/bin/activate
```
5. Install requirements
```
pip install torch
pip install -r requirements.txt
```
6. Launch the toolbox
```
python demo_toolbox.py
```
