### ISSUE TITLE
  Failed building wheel for webrtcvad

### ISSUE THREAD

**Issue by daddybird292** [CorentinJ/Real-Time-Voice-Cloning#226]
I'm so new to python, learning a lot but really lost.

I had a host of errors but have worked thru most of them.
Now I'm down to this webctvad wheel thing which I don't understand:

Webctvad (last thing to get thru the requirements install)
----------------------------------------
  Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
Failed to build webrtcvad
Installing collected packages: webrtcvad
  Running setup.py install for webrtcvad ... error
    Complete output from command M:\DeepVoice\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\bev\\AppData\\Local\\Temp\\pip-install-c16f8z_f\\webrtcvad\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '
\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\bev\AppData\Local\Temp\pip-record-1ndjc8y0\install-record.txt --single-version-externally-managed --compile --install-headers M:\DeepVoice\include\site\python3.7\webrtcvad:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying webrtcvad.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_webrtcvad' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\cbits
    creating build\temp.win-amd64-3.7\Release\cbits\webrtc
    creating build\temp.win-amd64-3.7\Release\cbits\webrtc\common_audio
    creating build\temp.win-amd64-3.7\Release\cbits\webrtc\common_audio\signal_processing
    creating build\temp.win-amd64-3.7\Release\cbits\webrtc\common_audio\vad
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -D_WIN32 -Icbits -IM:\DeepVoice\include -IC:\Users\bev\AppData\Local\Programs\Python\Python37\include -IC:\Users\bev\AppData\Local\Programs\Python\Pyt
hon37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tccbits\pywebrtcvad.c /Fobuild\temp.win-a
md64-3.7\Release\cbits\pywebrtcvad.obj
    pywebrtcvad.c
    c:\users\bev\appdata\local\programs\python\python37\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "M:\DeepVoice\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\bev\\AppData\\Local\\Temp\\pip-install-c16f8z_f\\webrtcvad\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(comp
ile(code, __file__, 'exec'))" install --record C:\Users\bev\AppData\Local\Temp\pip-record-1ndjc8y0\install-record.txt --single-version-externally-managed --compile --install-headers M:\DeepVoice\include\site\python3.7\webrtcvad" failed with error code 1 in C:\Users\
bev\AppData\Local\Temp\pip-install-c16f8z_f\webrtcvad\

Anyone know what to do with this? I really appreciate it.

**Comment by daddybird292** [comment]
Fixed this problem by building a new system, now there's other problems.

Boy it's tough making this software run.

**Comment by GiuseppeGiacoppo** [comment]
I'm having the same problem. Any hint? Thank you!

**Comment by blue-fish** [comment]
@daddybird292 Congratulations on installing webrtcvad on Windows, that is quite an accomplishment.
@GiuseppeGiacoppo You will be pleased to know that webrtcvad is no longer strictly required to run the toolbox, please pull the latest code and try again. The GPU is also not required anymore so installation should be much easier.
