### ISSUE TITLE
integer division or modulo by zero 

### ISSUE THREAD

**Issue by philip93dk** [CorentinJ/Real-Time-Voice-Cloning#228]
when i try to load a dataset the program says this anyone know how to fix this?

**Comment by blue-fish** [comment]
@philip93dk Please reopen the issue after doing the following, I would like more information on this error so we can troubleshoot it:
1. Pull the latest code from the repo
2. Provide the full traceback that accompanies the error message and reopen the issue.
    * If the error doesn't occur with the latest code then that would be good to know too!
