### ISSUE TITLE
How to load my own audio files in demo_cli.py?

### ISSUE THREAD

**Issue by sdx0112** [CorentinJ/Real-Time-Voice-Cloning#23]
I have several audio files from the same person. In GUI, I can load them using browser and then synthesize and vocode some text. How can I do the same thing without GUI?

Thanks

**Comment by CorentinJ** [comment]
Read the source code of demo_cli.py, you'll find instructions there. I'm planning to add more really soon

**Comment by ak9250** [comment]
I dont see anything in demo_cli where you can load your own audio?

**Comment by CorentinJ** [comment]
See here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/demo_cli.py#L129-L133
