### ISSUE TITLE
I keep getting TypeError: Invalid file: WindowsPath

### ISSUE THREAD

**Issue by Delo001** [CorentinJ/Real-Time-Voice-Cloning#235]
Hi guys I keep getting this error when running python demo_toolbox.py
Exception: Invalid file: WindowsPath('D:/ai/LibriSpeech/train-clean-360/6157/40556/6157-40556-0111.flac')

Also I get this error using eg. python synthesizer_preprocess_audio.py
TypeError: Invalid file: WindowsPath('D:/ai/LibriSpeech/train-clean-100/103/1240/103-1240-0000.flac')

Any help with this would be fantastic it may be something simple I have only just started with python a few days ago. 

I am running Windows 10 and using Anaconda and have downloaded all the files required. I just cant seem to load any voices in the toolbox through Voxceleb, librispeech or custom audio files in any format but i can record my own voice in toolbox. Thanks guys hopefully someone can help me out.

Cheers
Glenn

**Comment by SpiderKnot** [comment]
Hi! Have you solved this issue? I'm facing the exact the same problem.

**Comment by Kayzh3r** [comment]
any news about this issue?

**Comment by SamuelDietz** [comment]
Bump. This issue is affecting me aswell!

**Comment by Kayzh3r** [comment]
This bug is easy to debug. I was testing the algorithm so I hard-coded the url of the input files with the raw string modifier in python. E.g., r"PATH2MYFILE"

**Comment by SamuelDietz** [comment]
Actually I just fixed it for myself.

I changed line 119 in toolbox/__init__.py  to:
`wav = Synthesizer.load_preprocess_wav(str(fpath))`
now it works without any problems.

**Comment by blue-fish** [comment]
It's nice to see you all found a workaround. We formally resolved this problem in #371 . Closing this issue.
