### ISSUE TITLE
How can I speak with cloned voice in realtime after cloning any voice.

### ISSUE THREAD

**Issue by LiChengGong0602** [CorentinJ/Real-Time-Voice-Cloning#238]
When use this toolbox, only text is spoken with cloned voice.
But if the user wants to speak by using any cloned voice in real-time without text, only with his voice, how can perform that?
I want to know how can do this.

**Comment by LiChengGong0602** [comment]
Should I convert voice to text surely to perform that?
Or are there any method or technology?

**Comment by khu834** [comment]
Sounds like you'll need a real time speech to text system then use the output to drive the real time voice cloning.

**Comment by blue-fish** [comment]
The original question has been addressed. I am going to close this issue since it is not an active area of development for this repo. If anyone manages to set this up please reopen this issue and share some results.
