### ISSUE TITLE
How to inform the dataset?

### ISSUE THREAD

**Issue by diemesleno** [CorentinJ/Real-Time-Voice-Cloning#24]
Hi,

I downloaded the dataset LibriSpeech/train-clean-100 and I have it in the project root folder.
But when I try to execute the demo_toolbox.py it tells me that 'you do not have any of the recognized datasets in LibriSpeech'

Maybe I'm passing the path wrong?

python demo-toolbox.py -d LibriSpeech

Do I need to do something different?

**Comment by CorentinJ** [comment]
Yes you need to pass the parent of that directory

**Comment by diemesleno** [comment]
Hi @CorentinJ,

Thank you for your answer.

I'm sorry, but maybe I'm a little confusing about that.

For example, I have the following project structure:

Real-Time-Voice-Cloning <-- project root
    - demo-toolbox.py
    - LibriSpeech <-- Dataset root
       - train-clean-100 <- Dataset directory

So, when you say that I need to pass the parent of that directory should I run like this?
python demo-tooltox.py -d Real-Time-Voude-Cloning

Since the root dataset is inside the project root folder and in that case 'Real-Time-Voice-Cloning' is the parent of it.

I'm sorry if I misunderstand something, but I'm trying to figure out how to use it since the video just show the demo-toolbox already opened and do now show how to execute it correct. 

Thanks

**Comment by CorentinJ** [comment]
You need to run 

python demo_toolbox.py -d .

The dot indicates the current directory
