### ISSUE TITLE
The way to change speech rate of generated wav file 

### ISSUE THREAD

**Issue by KAYA-a** [CorentinJ/Real-Time-Voice-Cloning#243]
Hello :)

I am qurious about the change speech rate of generated wav file by using this Real-Time-Voice-Cloning. 

I generated the wav file which has super fast speech rate with demo_cli.py and the pre-trained model provided by writer.  I don't know why but it is really fast to speak and kind of hard to understand. Is there any way to change the speech rate of generated wav file?

I have tried to change sample rate of synthesizer, but it was not answer. 

Welcome to any advice and help :D

**Comment by khu834** [comment]
I also observed the fast speech rate behavior.
After experimentation with different audio files to generate embeddings, it appears to be highly relevant to the audio file you choose.

I don't have an good answer on how to tune this in a more controllable way for now, but you can try different audio files and see if one of them produces slower speech.

**Comment by KAYA-a** [comment]
@khu834  Thank you for your advice +1: I would try to concatenate the audio later.

**Comment by ChenMorStory** [comment]
@khu834 that's exactly what I did. Worked beautifully.
