### ISSUE TITLE
Training from scratch in English with my own DataSet

### ISSUE THREAD

**Issue by monilshah98** [CorentinJ/Real-Time-Voice-Cloning#246]
I am trying to train the model from scratch in english using my own dataset, and i have collected plenty of hours of audio and transcripts for the same. But i am having some difficulties in running the script files as mentioned on the training page of this repo. 

My questions are:

1) What will i require to create my own english dataset to train the voice cloning model, other than audio and transcript files?

2) What should be the directory structure of my dataset to use it for training the model from scratch as it is trained on librispeech dataset using script files given in this repo?

If anyone has used the scripts from this repo for training the model from scratch, any help would be really appreciated.

**Comment by blue-fish** [comment]
> 1. What will i require to create my own english dataset to train the voice cloning model, other than audio and transcript files?

You will need to prepare an alignment file, see this for the format: https://github.com/CorentinJ/librispeech-alignments#format-txt-alignments

Personally, I think it would be easiest to make your dataset look like LibriSpeech, that way you should be able to reuse the existing preprocessing and training code as written. But I haven't tried training with a custom dataset.
