### ISSUE TITLE
什么时候支持中文啊

### ISSUE THREAD

**Issue by lyuinc** [CorentinJ/Real-Time-Voice-Cloning#249]

**Comment by DearVa** [comment]
I'm waiting for this too!

**Comment by chengzeeyo** [comment]
我也在等这个！

**Comment by chengzeeyo** [comment]
I'm waiting for this too!

**Comment by blue-fish** [comment]
I'm going to close this issue since there is a fork that provides Chinese support. From here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/30#issuecomment-629979383

**Comment by babysor** [comment]
All links to KuangDD's projects now are no longer accessible. I'm currently working on latest fork of this repo to support mandarin and if anyone want to use as reference, please be free to folk and train: https://github.com/babysor/Realtime-Voice-Clone-Chinese
