### ISSUE TITLE
[Errno 2] No such file or directory: 'encoder/_sources.txt'

### ISSUE THREAD

**Issue by rkdlight** [CorentinJ/Real-Time-Voice-Cloning#250]
I have this problem, but I can't understand what does this file contain? There is not _sources.txt in this repo

**Comment by rkdlight** [comment]
Sorry, I dont describe my problem. I try to train this on Russian. But when I run encoder_train.py I get this error

**Comment by zhudu** [comment]
I have the same problem, when I run encoder_train.py, it shows that the _source.txt file cannot be found.I want to know if this file was written by myself, or should it be in the database?

**Comment by rkdlight** [comment]
You can have this problem because:
1) you don't run encoder_preprocess.py
2) if you use data is not from the librispeech or voxceleb, your data can have different format.
3)last: if preprocessing is finished successfully, but you have this problem, you are writing command wrong. It must look like this: 
encoder_train.py <name of your encoder model(it can be anything)> <directory which was made by preprocessing(find it)>

**Comment by zhudu** [comment]
Thank you very much. I did run encode_preprocess.py, but still reported an error. Maybe there is a problem with my data. I will see the reason from the data. Is your_source.txt in voxceleb1?
