### ISSUE TITLE
What's the differences bewteen " Voice Conversion" and "Voice Clone"?

### ISSUE THREAD

**Issue by niu0717** [CorentinJ/Real-Time-Voice-Cloning#251]
In other word, isn't voice conversion converting one sound to another sound also a voice clone? Moreover, the method of speech conversion does not need to train so many models.

**Comment by blue-fish** [comment]
Yes, there is another approach of using style transfer to impart characteristics of a reference audio to another audio. Here is an example of such a repo: https://github.com/mazzzystar/randomCNN-voice-transfer

It might involve fewer models but I am not convinced that it requires less training overall.

**Comment by niu0717** [comment]
> Yes, there is another approach of using style transfer to impart characteristics of a reference audio to another audio. Here is an example of such a repo: https://github.com/mazzzystar/randomCNN-voice-transfer
> 
> It might involve fewer models but I am not convinced that it requires less training overall.

so what is the benefit of this complex model, or why not use another approach to do it ??

**Comment by blue-fish** [comment]
This model requires only a short speech sample to clone a voice, while the style transfer requires a large dataset for the target voice. In other words, the advantage of our 3-stage SV2TTS process is that it generalizes well to voices unseen during training. Also, it can be used to synthesize new speech from any text, while style transfer requires a speech sample as input.

**Comment by niu0717** [comment]
> This model requires only a short speech sample to clone a voice, while the style transfer requires a large dataset for the target voice. In other words, the advantage of our 3-stage SV2TTS process is that it generalizes well to voices unseen during training. Also, it can be used to synthesize new speech from any text, while style transfer requires a speech sample as input.

First, thx for your reply. Do you know GST(global style token)?
When i read [gst](https://arxiv.org/abs/1803.09017) paper, i found it contains not only the token but also the tone of the speaker. In other word, can we separate prosody from the ref audio as much as possible,   or can we synthesis speaker-A's tone with speaker-B's prosody? If this is possible, it will be more interesting!

**Comment by blue-fish** [comment]
> First, thx for your reply. Do you know GST(global style token)?
> When i read [gst](https://arxiv.org/abs/1803.09017) paper, i found it contains not only the token but also the tone of the speaker. In other word, can we separate prosody from the ref audio as much as possible, or can we synthesis speaker-A's tone with speaker-B's prosody? If this is possible, it will be more interesting!

@niu0717 Let's continue the discussion in #230 . You might find the links interesting if you haven't read them already.

**Comment by blue-fish** [comment]
Check out [AutoVC](https://github.com/auspicious3000/autovc) ([audio samples](https://auspicious3000.github.io/autovc-demo/)) as another example of voice style transfer.
