### ISSUE TITLE
Training with multiple recordings

### ISSUE THREAD

**Issue by sheelpatel** [CorentinJ/Real-Time-Voice-Cloning#252]
If I add more recordings of a person can I get better results? Does this network allow me to do so?

**Comment by TKassis** [comment]
I also have the same question, did you figure it out?

**Comment by blue-fish** [comment]
As mentioned in #404, I believe the embedding only depends on the last file loaded. In other words, the toolbox has no memory and does not learn as it is used. If you have multiple recordings you should experiment to find the one that produces the best results.

For best results on a single voice, you could fine-tune the synthesizer and vocoder model by training on your target voice. However that requires the preparation of a dataset. We are not able to walk you through the process of making a custom dataset, but I would suggest making something that looks like the LibriSpeech set as described here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training

If anyone has done this and wants to contribute a tutorial on making a custom dataset, please reopen this issue. We can push the content to a wiki page for better visibility.
