### ISSUE TITLE
Synthesize wrong text content on cloned audio with only feeding one speaker's audios to train Synthesizer and Vocoder

### ISSUE THREAD

**Issue by Honghe** [CorentinJ/Real-Time-Voice-Cloning#253]
With reading the architechture of the framework, I only feed one speaker's audios to train Synthesizer and Vocoder.
But it synthesize wrong text cloning audio. 
![image](https://user-images.githubusercontent.com/1092722/71499640-5ee07900-289c-11ea-9c4c-cd6e95c5c951.png)
My training:
- Encoder, use the pretrained without retrain.
- Synthesizer, use only one speaker's audios.
- Vocoder, tune based on the pretrained model.

In the Vocoder training, the generated content is ok.
![image](https://user-images.githubusercontent.com/1092722/71499785-22614d00-289d-11ea-9ddb-b0b4c58beb06.png)

But When I Clone a new voice, it synthesize wrong audio (wrong content, e.g. not the text I set `Welcome to the toolbox! To begin, load an utterance from your datasets or record one yourself.`)

So, is this framework can not trained only with one speaker's audios in the steps of Synthesizer and Vocoder?

Any help with be appreciated!

![image](https://user-images.githubusercontent.com/1092722/71499903-969bf080-289d-11ea-88af-106a3130a1be.png)

**Comment by blue-fish** [comment]
> So, is this framework can not trained only with one speaker's audios in the steps of Synthesizer and Vocoder?

@Honghe You are correct. It is necessary to use multiple speakers to train the synthesizer and vocoder. The training process teaches the synthesizer and vocoder how the embeddings from the speaker encoder (left side of diagram) relate to the unique characteristics of each speaker used to train the synthesizer and vocoder.

If a single speaker is used to train the synthesizer and vocoder then it is not able to learn this information. I hope this explanation is satisfactory. If you have follow-up questions please reopen this issue.
