### ISSUE TITLE
Unable to load LibriSpeech=Train-clean-100

### ISSUE THREAD

**Issue by ryan0930** [CorentinJ/Real-Time-Voice-Cloning#255]
How to load LibriSpeech Train-clean-100.  Even after calling that correctly the modules are not getting loaded:

Warning: you do not have any of the recognized datasets in LibriSpeech\LibriSpeech\train-clean-100\1447\130551\1447-130551-0000.flac.
The recognized datasets are:
	LibriSpeech/dev-clean

**Comment by YukihimeX** [comment]
Assuming you had everything downloaded and extracted to a folder in your hard drive (make sure there's no spaces in your path)
So do something simple like creating a folder called "Datasets" in the D drive directory 
(So your path would be = D:\Datasets\LibriSpeech\train-clean-100)

Now when you run the toolbox python script. Type this into the terminal and if everything else is installed correctly, then you're in luck.
`python demo_toolbox.py -d D:\Datasets`

**Comment by blue-fish** [comment]
@ryan0930 If you still have the problem after trying the suggestion from @YukihimeX please reopen the issue. I am confident that it should be resolved.

**Comment by eldhoeliaszachariah** [comment]
How to load LibriSpeech Train-clean-100. Even after calling that correctly the modules are not getting loaded:

Warning: you do not have any of the recognized datasets in  The recognized datasets are: LibriSpeech/dev-clean LibriSpeech/dev-other LibriSpeech/test-clean LibriSpeech/test-other LibriSpeech/train-clean-100 LibriSpeech/train-clean-360 LibriSpeech/train-other-500 LibriTTS/dev-clean LibriTTS/dev-other LibriTTS/test-clean

**Comment by eldhoeliaszachariah** [comment]
![image](https://github.com/CorentinJ/Real-Time-Voice-Cloning/assets/121530370/c661aef0-de0b-4d39-a117-9957ec79bdbc)
