### ISSUE TITLE
how to accelerate the vocoder inference time?

### ISSUE THREAD

**Issue by dazzlerrrr** [CorentinJ/Real-Time-Voice-Cloning#258]
the vocoder inference spends several seconds,  how to accelerate ?

**Comment by blue-fish** [comment]
I think this is specific to the vocoder algorithm being used. In the toolbox, you can select Griffin-Lim as the vocoder and it will be much faster with a serious degradation in quality. I don't know how to make the vocoder faster if you are already getting GPU acceleration. A different algorithm perhaps? This one is already reasonably fast and has good quality for a vocoder.

**Comment by blue-fish** [comment]
#182 is a possible solution for this issue. With GPU acceleration it is already faster than real-time which seems like a reasonable level of performance already.

I am going to close this issue due to inactivity. It can be reopened if someone wants to work on it.
