### ISSUE TITLE
File open dialog filter is wrong

### ISSUE THREAD

**Issue by phiresky** [CorentinJ/Real-Time-Voice-Cloning#26]
the file open dialog does not show any files for me

replacing `filter="*.mp3;*.flac;*.wav;*.m4a"` with `filter="Audio Files (*.mp3 *.flac *.wav *.m4a)"` fixes it.

See doc: https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileName

**Comment by CorentinJ** [comment]
Fixed in 3f55ab1a3a46460f7889432fc2ee8f103e378043
