### ISSUE TITLE
No GPU - can we use Google Colab?

### ISSUE THREAD

**Issue by infiniti350** [CorentinJ/Real-Time-Voice-Cloning#261]
noob here without a GPU. How would someone use this with Google Colab

**Comment by natravedrova** [comment]
> noob here without a GPU. How would someone use this with Google Colab

There is an example in the repo: https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/demo_toolbox_collab.ipynb

**Comment by blue-fish** [comment]
Thank you @natravedrova for answering the question about the collab notebook. You can also use this CPU as we have recently made the GPU optional. Pull the latest code and try it out!
