### ISSUE TITLE
Cannot load _sources.txt during encoder_train.py 

### ISSUE THREAD

**Issue by bmccallister** [CorentinJ/Real-Time-Voice-Cloning#262]
Up front - i have been able to get the demo to work, and have had no problems with the application thus far.  Thank you for making the available to researchers everywhere!!

I have grabbed the voxceleb1, librispeech and voxceleb2 datasets.  (Voxceleb2 is all in mp4 files which my ubuntu cannot load, btw) and completed the python encoder_preprocess.py step. (Only using librispeech and voxceleb1, since I cannot open the mp4s).

When I get to the encoder_train.py step - it fails that it cannot find ./LibriSpeech/_sources.txt

As i understand it this is a file created by the py applications - and i've found _sources.txt in subdirectories, but not in the locations it seems to expect.

I git reset --hard master, and re-unzipped my datasets into a new folder and tried again, and got the same result.  Completely stuck on the training set at the moment.  Any assistance?

Thank you again!

**Comment by LordBaaa** [comment]
Could I see the log leading up to the failure?

**Comment by bmccallister** [comment]
sure! thank you so mich for reponding.  here it has nust comoletrd the prior stro. datasets contains the librisperch and coz celeb folders with merggrd assignments 
lucidz@voice:~/Documents/projects/jasonvoice$ c d ..^C
lucidz@voice:~/Documents/projects/jasonvoice$ cd ..
lucidz@voice:~/Documents/projects$ git clone https://github.com/CorentinJ/Real-Time-Voice-Cloning.git
fatal: destination path 'Real-Time-Voice-Cloning' already exists and is not an empty directory.
lucidz@voice:~/Documents/projects$ ls
Alignments  datasetsorig  jasondata   jasonvoice2       jasonweb  melgan                   usa.txt
datasets    jasonchats    jasonvoice  jasonvoicebackup  jvbackup  Real-Time-Voice-Cloning  zips
lucidz@voice:~/Documents/projects$ cd Real-Time-Voice-Cloning/
lucidz@voice:~/Documents/projects/Real-Time-Voice-Cloning$ git reset^C
lucidz@voice:~/Documents/projects/Real-Time-Voice-Cloning$ git fetch origin
git reset --hard origin/master
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
Unpacking objects: 100% (12/12), done.
remote: Total 12 (delta 8), reused 8 (delta 8), pack-reused 4
From https://github.com/CorentinJ/Real-Time-Voice-Cloning
   3e72a7d..c5c2261  master     -> origin/master
lucidz@voice:~/Documents/projects/Real-Time-Voice-Cloning$ git reset --hard origin/master
HEAD is now at c5c2261 Update README.md
lucidz@voice:~/Documents/projects/Real-Time-Voice-Cloning$ python encoder_preprocess.py ./datasets^C
lucidz@voice:~/Documents/projects/Real-Time-Voice-Cloning$ ln -s ../datasets
lucidz@voice:~/Documents/projects/Real-Time-Voice-Cloning$ python encoder_preprocess.py ./datasets
Arguments:
    datasets_root:   datasets
    out_dir:         datasets/SV2TTS/encoder
    datasets:        ['librispeech_other', 'voxceleb1']
    skip_existing:   False

Preprocessing librispeech_other
LibriSpeech/train-other-500: Preprocessing data for 1166 speakers.
LibriSpeech/train-other-500: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 1166/1166 [2:24:09<00:00,  7.42s/speakers]
Done preprocessing LibriSpeech/train-other-500.

Preprocessing voxceleb1
VoxCeleb1: using samples from 1123 (presumed anglophone) speakers out of 1251.
VoxCeleb1: found 1088 anglophone speakers on the disk, 35 missing (this is normal).
VoxCeleb1: Preprocessing data for 1088 speakers.
VoxCeleb1: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 1088/1088 [1:44:53<00:00,  5.78s/speakers]
Done preprocessing VoxCeleb1.

lucidz@voice:~/Documents/projects/Real-Time-Voice-Cloning$ python encoder_train.py my_run ./datasets
Arguments:
    run_id:            my_run
    clean_data_root:   datasets
    models_dir:        encoder/saved_models
    vis_every:         10
    umap_every:        100
    save_every:        500
    backup_every:      7500
    force_restart:     False
    visdom_server:     http://localhost
    no_visdom:         False

No model "my_run" found, starting training from scratch.
Updating the visualizations every 10 steps.
Setting up a new session...
Traceback (most recent call last):
  File "encoder_train.py", line 46, in <module>
    train(**vars(args))
  File "/home/lucidz/Documents/projects/Real-Time-Voice-Cloning/encoder/train.py", line 68, in train
    for step, speaker_batch in enumerate(loader, init_step):
  File "/home/lucidz/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/lucidz/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/lucidz/.local/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lucidz/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lucidz/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/lucidz/Documents/projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker_verification_dataset.py", line 55, in collate
    return SpeakerBatch(speakers, self.utterances_per_speaker, partials_n_frames)
  File "/home/lucidz/Documents/projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker_batch.py", line 8, in __init__
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "/home/lucidz/Documents/projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker_batch.py", line 8, in <dictcomp>
    self.partials = {s: s.random_partial(utterances_per_speaker, n_frames) for s in speakers}
  File "/home/lucidz/Documents/projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker.py", line 34, in random_partial
    self._load_utterances()
  File "/home/lucidz/Documents/projects/Real-Time-Voice-Cloning/encoder/data_objects/speaker.py", line 14, in _load_utterances
    with self.root.joinpath("_sources.txt").open("r") as sources_file:
  File "/usr/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/LibriSpeech/_sources.txt'

**Comment by LordBaaa** [comment]
Ahh, this is a path problem. Don't feel bad I had the same problem at first. I am also getting each step working for myself to. What you should need to do instead is specify the output of the `encoder_preprocess` results as its input like this. `python encoder_train.py my_run "datasets\SV2TTS\encoder"`. Let me know if that works for ya. Also you'll want to start a visdom server. You can follow the instructions here on how to do that https://github.com/noagarcia/visdom-tutorial

**Comment by bmccallister** [comment]
I will try it thank you!

I do have visdom running in another cli as well :)

I promise I’m generally good at following instructions!

Any suggestions in the fact that my Ubuntu doesn’t support the apple ios mp4 situation in voxceleb2? I did the math and it would take quite a while to convert the mp4 to mp3 using ffmpeg (I did some tests)

Thank you again!

**Comment by LordBaaa** [comment]
@bmccallister Well I haven't tried to uses voxceleb2 yet but I would figure it would be up to the program to understand the data not your OS. Did actually you try running preprocess with Voxceleb2?

**Comment by bmccallister** [comment]
Unfortunately voxceleb2 was unable to complete preprocessing, due to the files formats being in mp4. May i ask what datasets you've used (assuming they're public!)

Also - I apologize for the silly question, but I have gotten the system to begin the encoder training.  Does this process complete? It continuously updates the screen and i'm up to about 40 steps, but I wasn't sure if it's a finite process, or I just stop it when it gets to an err/loss point I want to experiment with?

Final question: If I do --skip-existing, can i restart this process if it dies or I stop it?

Thank you so much again!

**Comment by LordBaaa** [comment]
Well I have still be gathering them I want to have a big data set before I start. I have downloaded all of librispeech as well as some of Common speech (https://voice.mozilla.org/en/about) and VCT

**Comment by blue-fish** [comment]
I updated the wiki documentation to fix the original issue. Now the user is directed to run the following train command:
```
python encoder_train.py <datasets_root>/SV2TTS/encoder
```

This will work if the default path is used during the preprocess stage. Closing this issue.
