### ISSUE TITLE
vocoder training : "operands could not be broadcast together with shapes"

### ISSUE THREAD

**Issue by iroh7** [CorentinJ/Real-Time-Voice-Cloning#264]
I've this issue with vocoder training 
![image](https://user-images.githubusercontent.com/58814678/72643636-711b7780-396f-11ea-8695-c33fc27fcd20.png)

Thanks in advance for any support !

**Comment by LordBaaa** [comment]
I haven’t started vocoder training  yet so I don’t know all the ins and outs but well first off it is having a problem combining shapes. The second one has more elements then the rest. Are you using a pretrained model and continuing to train it I have had problems with that before cause you gotta match the settings exactly. I notice it has 428k steps which incidentally is the same number of steps as the pretrained model. The pertained model runs on batch sizes of 100 and it looks like you are using batch sizes of 1. The default batch size in vocoder/hparams.py is 100, did you change it?

**Comment by LordBaaa** [comment]
@iroh7 I haven’t started vocoder training yet so I don’t know all the ins and outs but well first off it is having a problem combining shapes. The second one has more elements then the rest. Are you using a pretrained model and continuing to train it I have had problems with that before cause you gotta match the settings exactly. I notice it has 428k steps which incidentally is the same number of steps as the pretrained model. The pertained model runs on batch sizes of 100 and it looks like you are using batch sizes of 1. The default batch size in vocoder/hparams.py is 100, did you change it?

**Comment by iroh7** [comment]
@LordBaaa Thank you for your quick reply !
A few clarifications, my post wasn't very detailed...
Yes, I try to do transfer learning from the pretrained english model to french. I've not changed any parameters in the vocoder/hparams.py, voc_batch_size is still at 100.
The audio conversion in preprocessing for the synthesizer training wasn't good. So I've changed it and the training of synthesizer seems to be better  (red vs blue curve) :
![image](https://user-images.githubusercontent.com/58814678/72748454-94d0fe80-3bb7-11ea-85c7-6833193b505d.png)
Then I've run the vocoder training and I've got almost the same thing :
![image](https://user-images.githubusercontent.com/58814678/72748919-dca45580-3bb8-11ea-8759-da3ab0c6c76a.png)

**Comment by LordBaaa** [comment]
Hmm well I’ll have to give it a try and see if I get a similar error. As I said I haven’t tried out that stage yet. I have tried synthesizer and encoder stuff, mainly was focusing on getting everything working the best I could before doing some real training. In the meantime you could start a new model to train just to make sure a fresh model works and you don’t have a problem somewhere else.

**Comment by iroh7** [comment]
Thanks for your reply @LordBaaa !
Ok i solved the issue, utterances were too short (0.2 in my case). The min size of utterance you can use is 0.25 which corespond to 0.25*16000 samples/seconde equal to 4000. The shape of 3200 was our smallest audio samples (0.2*16000).

**Comment by LordBaaa** [comment]
@iroh7 Thanks for posting the conclusion. That will definitely be helpful to know when I start working with vocoder training.
