### ISSUE TITLE
demo_cli.py launch error

### ISSUE THREAD

**Issue by LostKin** [CorentinJ/Real-Time-Voice-Cloning#265]
I just installed all the libs, but for some reason running `python3 demo_cli.py` just says `illegal instruction (core dumped)`. If anyone can help at least find out where is the problem i will be much more happier

**Comment by LostKin** [comment]
I did some research. It fails because there is no file `create_model` in `./synthesizer/models`. Can you explain me, what i am doing wrong?

**Comment by LordBaaa** [comment]
Full trace back please.

**Comment by LostKin** [comment]
> Full trace back please.

How can i get it? (what flags i need to add to `python3 demo_cli.py`?)

**Comment by LostKin** [comment]
What i found for now : 
in `synthesizer/tacotron2.py`
`from synthesizer.utils.text import text_to_sequence
from synthesizer.infolog import log
from synthesizer.models import create_model
from synthesizer.utils import plot
from synthesizer import audio
import tensorflow as tf
import numpy as np
import os` - thats all of the imports
and the problem is this one : `from synthesizer.models import create_model`, because there is no such file

**Comment by LordBaaa** [comment]
I’d say make sure you have tensorflow 1.1.14 or 15 installed not 2.0.0 or higher. I think I am using .15. The newer ones cause problems cause the code is different

**Comment by blue-fish** [comment]
I am going to presume this was resolved with identification of the tensorflow issues, but if not reopen the issue and provide the error message and full traceback as requested.
