### ISSUE TITLE
Install requirement error

### ISSUE THREAD

**Issue by jgraf451** [CorentinJ/Real-Time-Voice-Cloning#266]
I'm stuck on step 2 after cloning the files.  When I enter the install requirements command I get:
 Could not open requirements file (Errno 2).  No such file or directory:

**Comment by LordBaaa** [comment]
@jgraf451 did you make sure that where you are running the command in the same directory as the requirements.txt file? What I mean is like if you are in command prompt and you run python. python is gonna be looking for files where ever you are at that time. So like C:\users\your_username. So if you do the pip install make sure you specify the full path to the file or simply change your directory to be in the same folder as the files location.

**Comment by jgraf451** [comment]
Thanks!  That got me one step closer.  But now I'm getting the following 
error: $ pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement 
tensorflow-gpu<=1.14.0,>=1.10.0 (from -r requirements.txt (line 1)) 
(from versions: none)
ERROR: No matching distribution found for 
tensorflow-gpu<=1.14.0,>=1.10.0 (from -r requirements.txt (line 1))

Any ideas?

**Comment by LordBaaa** [comment]
Yeah I had a bit of a problem with that in the past. the greater then or equal to (<=) stuff messed up for me a bit. Also problem that happened to me is it will install tensorflow 2 with tensorflow-gpu to match, but tensorflow 2 is incompatible. All you should need to do is change `tensorflow-gpu>=1.10.0,<=1.14.0` to `tensorflow-gpu==1.14.0`. Or just use this [requirements.txt](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/4088240/requirements.txt)

**Comment by LordBaaa** [comment]
@jgraf451 Oh also for me I got an error like `Warning: Passing (type, 1) or '1type' as a synonym of type is deprecated;` with just the requirements.txt when I tried to import tensorflow as a test. So what has been working for was doing `pip install tensorflow==1.15.0`. This successfully grabbed my `cudart64_100.dll` and yeah been working for me so far. But I'd say try it without this first.

**Comment by jgraf451** [comment]
Hi,

So I went in and changed the tensorflow info in the requirements.txt 
file.  However, when I do "pip install -r requirements.txt"
I get a invalid syntax error msg.  Is this command incorrect?

Thanks,

Jim.

**Comment by LordBaaa** [comment]
@jgraf451 Well try the command in console. Again should just be `pip install tensorflow-gpu==1.14.0` with no spaces between ==. Literally exactly like I typed it. If you just `pip install tensorflow-gpu==` it should show you a list of available versions.

**Comment by jgraf451** [comment]
Still can't get passed the invalid syntax error msg.  Know I'm typing it 
correctly at python prompt.  Any ideas?

**Comment by LordBaaa** [comment]
Well as with all problems I’d say give me the full traceback/log

**Comment by brianteeman** [comment]
I have/had the same problem
from what I can tell there are two potential issues to check

1. Are you running python 64bit?
2. Do you actually have a gpu in the machine your are triyng to install on

**Comment by jgraf451** [comment]
Thanks for trying to walk me thru this but in the end it was just too 
complicated for my limited skills.  Looking at the issues log and the 
comments section of You Tube for this program guess I am not alone.  Was 
wondering how hard it would be to create a repository with a working 
version of this.  Something that would be downloaded and easily 
launched.  That would certainly make it more available to people with 
fewer computing skills.  Baidu's Deep Voice is also out there.  One 
might be easier to do than the other.  Thanks again for your help.

Jim



n 2020-01-21 10:44, LordBaaa wrote:

**Comment by tapankarnik** [comment]
You sure you are running python3 right? People forget more often than you think.
If thats okay, a simple pip install tensorflow-gpu==1.14 should be enough.

But tbh, I always recommend using anaconda for installing tensorflow because it automatically handles download CuDNN on its own.

**Comment by sahmed130** [comment]
@tapankarnik I tried 1.14 but I think tensorflow-gpu==1.14 is no longer available. Lowest version available is 1.15 which does not comply with requirements.

**Comment by nicok1172** [comment]
A:\Program files (x86)\Real Time Voice Cloning\Real-Time-Voice-Cloning-master>pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14.0 (from -r requirements.txt (line 1)) (from versions: 2.2.0rc1, 2.2.0rc2)
ERROR: No matching distribution found for tensorflow-gpu==1.14.0 (from -r requirements.txt (line 1))

Can't install the required version of tensorflow-gpu

**Comment by tapankarnik** [comment]
@nicok1172 Which python version are you using? I used 3.7 and it worked fine

**Comment by nicok1172** [comment]
@tapankarnik 3.8 I think.

**Comment by zrowny** [comment]
Tensorflow isn't supported on Python 3.8 so you'll have to downgrade to 3.7 (using Anaconda or just uninstall and reinstall 3.7)

**Comment by nicok1172** [comment]
Thanks

**Comment by blue-fish** [comment]
@jgraf451 I'm sorry you were unable to get it set up. We have recently improved the code to add CPU support and make a difficult-to-install dependency optional. You are invited to pull the latest and try again. Having installed both GPU and CPU versions, the latter is significantly easier in my experience since you don't need to get the dependencies to line up with your GPU drivers.

If you continue to experience a problem with setup please reopen the issue or open a new one.
