### ISSUE TITLE
Create a exe?

### ISSUE THREAD

**Issue by starinspace** [CorentinJ/Real-Time-Voice-Cloning#267]
Is it possible for you to publish a release as an "exe-file"?

**Comment by bmccallister** [comment]
Undfoetunately this project requires at least a cursory knowledge of programming languages and if not ml, the ability to set up extensive libraries to run with a gpu.

I’m sorry but perhaps we can help get it running?

**Comment by starinspace** [comment]
When running:

` pip install -r requirements.txt`
I get:

```
Building wheels for collected packages: webrtcvad
  Building wheel for webrtcvad (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Lucas\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-3r98ntqu\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-3r98ntqu\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Lucas\AppData\Local\Temp\pip-wheel-8dg3vf10' --python-tag cp37
       cwd: C:\Users\Lucas\AppData\Local\Temp\pip-install-3r98ntqu\webrtcvad\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying webrtcvad.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_webrtcvad' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
Failed to build webrtcvad
Installing collected packages: webrtcvad, audioread, resampy, soundfile, librosa, sounddevice, Unidecode, inflect, dill, multiprocess
  Running setup.py install for webrtcvad ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Lucas\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-3r98ntqu\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-3r98ntqu\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Lucas\AppData\Local\Temp\pip-record-ezwhs4cx\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Lucas\AppData\Local\Temp\pip-install-3r98ntqu\webrtcvad\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying webrtcvad.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_webrtcvad' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Lucas\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-3r98ntqu\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-3r98ntqu\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Lucas\AppData\Local\Temp\pip-record-ezwhs4cx\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by starinspace** [comment]
I do however got Microsoft Visual C++ Build Tools installed

**Comment by evilexecutable** [comment]
> I do however got Microsoft Visual C++ Build Tools installed

Install the full Visual Studio and enable C/C++ in the install options.

**Comment by blue-fish** [comment]
Now that the toolbox has CPU support, we should consider a release in compiled form. Would someone from the community like to work on this?

**Comment by evilexecutable** [comment]
> 
> 
> Now that the toolbox has CPU support, we should consider a release in compiled form. Would someone from the community like to work on this?

I'll happily give this a go.

**Comment by blue-fish** [comment]
@evilexecutable Thank you for taking this on!

**Comment by blue-fish** [comment]
Any updates @evilexecutable ? There is someone in #428 who would like an exe.

**Comment by blue-fish** [comment]
Checking in to see if you've been able to make any progress on the exe.

**Comment by blue-fish** [comment]
Would like someone to take this on. Preferably using #472 since this project will be pytorch-based going forward, it will ensure compatibility with future synthesizer models.

**Comment by blue-fish** [comment]
Hi @CodingRox82, thank you for expressing willingness to help make a compiled version of the toolbox. [PyInstaller](https://www.pyinstaller.org/) seems to be the way to go, but I have not used it before.

**Comment by CodingRox82** [comment]
I'll give it a shot. My long term goal for this is to use it on a smartphone, but I'll settle on running this server side for now. Can you point me in the right direction on which OS to use to start off? I read through some of the other comments and Windows does not seem like the way to go.

**Comment by blue-fish** [comment]
Sorry, I mistakenly assumed that you were an existing user of the toolbox. Why don't you try the toolbox first and then decide whether you want to compile it for the benefit of the community. You should use Ubuntu 20.04, I recommend the [setup guide in the wiki](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Installation---Ubuntu-20.04). Open an issue if you get stuck.

Windows is not too difficult if GPU support is not required. The toolbox also runs on CPU, though somewhat slower.

**Comment by CodingRox82** [comment]
> Windows is not too difficult if GPU support is not required. The toolbox also runs on CPU, though somewhat slower.

I'd prefer Windows (the OS of my personal computer), otherwise my options are an Ubuntu USB or buy a new laptop and install Ubuntu on it. Do we have an instruction set for Windows 10 installation?

**Comment by blue-fish** [comment]
Nothing as detailed for Windows is available, but the instructions in README.md have worked for me.

**Comment by starinspace** [comment]
I prefer windows as well. As GPU does that need something that supports Cuda? I don't got Nvidia. And how is it going?

**Comment by CodingRox82** [comment]
@blue-fish were you able to get it working on your machine?

**Comment by blue-fish** [comment]
@CodingRox82 I don't have any trouble running the toolbox, but I use Linux where setup is very straightforward. I thought you were going to attempt a Windows install, and then compile it with PyInstaller if things went well.

**Comment by CodingRox82** [comment]
Actually, I was thinking of taking this another route since I'm constrained on time now. Can we move this to a private chat? You can message me on discord. My user is Rescue Duck#3868. I'll delete this comment after you confirm that you saw it.

**Comment by blue-fish** [comment]
@CodingRox82 Sent you a github invitation to discuss further. And deleted your comment as requested.

**Comment by Utomo88** [comment]
This is popular things. but until now not a single release available. I hope somebody handle it. Thank you

**Comment by blue-fish** [comment]
It has been over a year with no real progress on this item. I'm closing it. A binary release is still a good idea, but it is not a goal for this repo at this time.

In the meantime, we've made numerous improvements which improve access and make setup much easier:
1. NVIDIA GPU no longer required (#366)
2. Make webrtcvad optional (#375)
3. Remove Tensorflow as dependency (#472)
4. Detailed Windows install instructions (https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542)

**Comment by blue-fish** [comment]
In #865, user AK391 has shared a web app that does not require installation.
https://huggingface.co/spaces/akhaliq/Real-Time-Voice-Cloning
