### ISSUE TITLE
Collection of pretrained models? Easy way to accommodate shorter or longer sentences?

### ISSUE THREAD

**Issue by bmccallister** [CorentinJ/Real-Time-Voice-Cloning#268]
Hey all, 

From reading through issues - many of us are working on models or have generated models which are shared in multiple threads. Could we get a pinned thread to have us post models that we’ve worked on and get feedback on?

Additionally - this is just a general question about the project, I’ve been able to get sentences of 4-6 seconds to sound good but much longer or much shorter is unusable. 

Too long is easy to handle, simply split the text. Howver, are there any easy hParams you could change to allow it to better generate a shorter output?  

I believe it would be possible to cull the dataset for shorter utterances and generate a custom pretrained model - but I figured I would ask before I started down that path.

Thanks!

**Comment by blue-fish** [comment]
@bmccallister Good idea on the collection of pretrained models, it inspired me to start #400. I have no control whether it will get pinned, but it is a start.

As for the issues you raised about the quality of output if there is too little/much reference text, I will prefer to track that in specific issues. #324 (long gaps in the middle of synthesized mel for a short text) and #347 (too fast when a lot of text). Good ideas and feedback here, but will close this as it duplicates more recent and specific issues.
