### ISSUE TITLE
Speaker verification implementation

### ISSUE THREAD

**Issue by MahmoudAliEng** [CorentinJ/Real-Time-Voice-Cloning#275]
I need just the speaker verification part which is the implementation of [GENERALIZED END-TO-END LOSS FOR SPEAKER VERIFICATION](https://arxiv.org/pdf/1710.10467.pdf) paper, how I can proceed to get it please?

**Comment by blue-fish** [comment]
@MahmoudAliEng That is in the encoder folder of the repository. Both scripts for training and inference are provided.

If you have a more specific question that is not answered by this please reopen the issue.
