### ISSUE TITLE
Requirement PyQt5 is broken

### ISSUE THREAD

**Issue by berzi** [CorentinJ/Real-Time-Voice-Cloning#278]
There seems to be a bug with the latest PyQt5 version and it fails to install when I try to install from requirements.txt.
I did however manage to install PyQt5==5.14 so I think that specific version (or anything better that does work) should be specified in requirements.txt.

I'm not sure if that's the only problem with reqs since at present I can't manage to make this software work (because of issue #179 ).

**Comment by blue-fish** [comment]
Thanks for reporting this issue. I don't have an issue installing from requirements.txt so I will assume that a more recent PyQt5 has fixed the bug that you discovered. If there is a reproducible problem with the current PyQt5 please reopen this with a full description of the error.
