### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Ebrahemots** [CorentinJ/Real-Time-Voice-Cloning#279]
![Capture](https://user-images.githubusercontent.com/61065274/74565889-e54f3800-4f7a-11ea-95d5-a6f47d32362a.PNG)

hello guys
i already install cloning toolbox and everything is okay but when i try to insert any voice to the toolbox it say torch not compiled with cuda enabled and i don't have cuda drive i only use cpu and i instaled pytorch for only pc..
second it say  datasets_root:    None
and i can't use anything from my computer to use it on toolbox 
thanks.

**Comment by blue-fish** [comment]
Hi @Ebrahemots , at the time you installed the toolbox a GPU was required. CPU is now supported so you can try pulling the latest and it should be compatible. Just make sure you also update your requirements as we are now up to tensorflow==1.15. Hope this resolves your issue, if it does not feel free to reopen.
