### ISSUE TITLE
Link for youtube video wont work

### ISSUE THREAD

**Issue by IvanVnucec** [CorentinJ/Real-Time-Voice-Cloning#28]
Link to a Youtube video in the README wont work.
When you click on picture in README file Youtube opens but it says that "Video is not available".

**Comment by CorentinJ** [comment]
Works fine for me. You're taking the link from the current readme, right (https://www.youtube.com/watch?v=-O_hYhToKoA)? The one that was initially put doesn't work anymore.

**Comment by IvanVnucec** [comment]
Yes I am talking about that link you've now posted. 
I will post a picture. Its in my "Croatian language" but you'll get the point
![Screenshot_1](https://user-images.githubusercontent.com/50591550/60399591-ed32a700-9b66-11e9-96d9-4ea5243b84ea.jpg)
.

P.S. And maybe it should be written somewere that to open video example you must click on a picture.
It took me a while to figure it out.

**Comment by CorentinJ** [comment]
I really don't know why youtube is doing that. I assume this is based on your location. When I use online proxys it works fine.

I'll add that you should click on the picture in the readme.
