### ISSUE TITLE
Help needed making CUDA and pytorch versions "match"

### ISSUE THREAD

**Issue by berzi** [CorentinJ/Real-Time-Voice-Cloning#280]
When I try to run demo_cli.py, it returns the following output:
> Your PyTorch installation is not configured to use CUDA. If you have a GPU ready for deep learning, ensure that the drivers are properly installed, and that your CUDA version matches your PyTorch installation. CPU-only inference is currently not supported.

My GPU (GeForce 940MX) supports CUDA but according to an internet search it seems the drivers should be enough to run pytorch. How do I make the CUDA and pytorch versions "match"?

If I try `cat /usr/local/cuda/version.txt` it says no such file or directory, so I guess it's possible I don't have the CUDA runtime installed at all. I managed to get all the way to [this page](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa) to get the drivers, but I don't know which version I should pick to be able to run RTVC correctly.

OS version: Ubuntu 18.04, Windows subsystem for Linux
Current version of pytorch: 1.4.0
Current version of nvcc: 9.1, V9.1.85
Current version through `cat /usr/local/cuda/version.txt`: not found

**Comment by TKassis** [comment]
Easiest would be to use TF 1.14.0 and Pytorch 1.2.0 which both work with cudnn=10.0. I would recommend you use a conda environment.

**Comment by meme-lord** [comment]
I was having the same problem and upgrading PyTorch from 1.1.0 to 1.2.0 worked for me.
The working combination I ended up with was: CUDA 10.0, CudNN 7.6.5, Python 3.7.7 (Other python versions may work), Torch 1.2.0, Tensorflow 1.14.0 .
Information like this should probably be in the README or maybe detailed info in INSTALL.md ?
Took days to work this out and lots of large downloads of different versions.

**Comment by blue-fish** [comment]
@berzi There is a helpful chart in the quick start at https://pytorch.org/ which directs you to download the appropriate version of torch to match your CUDA version.

The repo supports CPU now, so you don't have to go through the trouble to match. Please pull the latest and try again.
