### ISSUE TITLE
How to improve the audio file quality?

### ISSUE THREAD

**Issue by junjimei** [CorentinJ/Real-Time-Voice-Cloning#282]
I'm not talking about improving the voice itself, but the quality of the exported file. I tried changing several audio parameters, didn't make a difference. I guess the "mu_law" codec is limiting the audio quality from the beginning of the process. 

Did anyone investigate about this? 
Any help is welcome, thank you!

**Comment by tzhang001** [comment]
I'm also confused with the parameter mu_law=True in vocoder/hparams.py, since the trained label files(wav) which are generated in step2(synthesizer) are not encoded using mu_law. So I think this parameter may need to set False.  Do you mean this?

**Comment by blue-fish** [comment]
This is most likely an issue with your system configuration and not the toolbox code. An inferior codec is being used to write wav files. You can analyze the header of the wav file to determine which. Please submit a pull request if you identify code changes that will fix this issue on your end.
