### ISSUE TITLE
声音有点抖有点沙哑

### ISSUE THREAD

**Issue by freecui** [CorentinJ/Real-Time-Voice-Cloning#283]
请听一下我的这个结果，听着某些词或者字有点抖有点沙哑，特别是抖，不知道原因是什么？
[1350.zip](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/4219503/1350.zip)

**Comment by gongchenghhu** [comment]
请问您方便分享一下得到这个结果使用的数据数据的大小吗，分别训练三个部分（speaker，synthesier, vocoder）的，大概多少说话人, 时长是多少，谢谢。

**Comment by lNeverl** [comment]
> 请听一下我的这个结果，听着某些词或者字有点抖有点沙哑，特别是抖，不知道原因是什么？
> [1350.zip](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/4219503/1350.zip)

请问您可以分享一下中文的训练模型吗，非常感谢，我最近正在做这方面的学习，找不到中文的训练模型。
