### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by AmitBDA** [CorentinJ/Real-Time-Voice-Cloning#285]
while sythesizer_preprocess_audio.py running it intrupted by an assetion error at this point every time . can anyone tell me what is happening?

AssertionError
LibriSpeech:  21%|███▊              | 251/1172 [48:17<2:57:10, 11.54s/speakers]

**Comment by blue-fish** [comment]
I am closing this issue as it has been stale. If you would like help, please pull the latest code from the repo and try again. Reopen this issue, and provide the traceback and error message if the problem occurs.
