### ISSUE TITLE
DLL load failed: The operating system cannot run %1.

### ISSUE THREAD

**Issue by abramax17** [CorentinJ/Real-Time-Voice-Cloning#286]
when i try running the python demo_toolbox.py in powershell i got an error saying

 File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "F:\Plugins\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "F:\Plugins\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 5, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "F:\Plugins\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "F:\Plugins\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Users\%user%\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.

anyone know how to fix this? I follow the steps to install from here

https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/

**Comment by ulfsv** [comment]
I think it is related to this step:

NVIDIA cuDNN for CUDA 10.0
To set this up, you’ll need to extract the ZIP (e.g., cudnn-10.0-windows10-x64-v7.6.5.32.zip) which has three directories in its cuda\ directory (bin, include, and lib). Copy those three directories directly into your CUDA 10.0 install folder. If you used the default path on your C:\ drive, copy them into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0

Then update system environment paths.

I followed this guide for installing tensorflow correctly: https://www.joe0.com/2019/10/19/how-resolve-tensorflow-2-0-error-could-not-load-dynamic-library-cudart64_100-dll-dlerror-cudart64_100-dll-not-found/

I started with installing CUDA 10.2 but it didn't work so installed CUDA 10 which worked.

**Comment by abramax17** [comment]
> 
> 
> I think it is related to this step:
> 
> NVIDIA cuDNN for CUDA 10.0
> To set this up, you’ll need to extract the ZIP (e.g., cudnn-10.0-windows10-x64-v7.6.5.32.zip) which has three directories in its cuda\ directory (bin, include, and lib). Copy those three directories directly into your CUDA 10.0 install folder. If you used the default path on your C:\ drive, copy them into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
> 
> Then update system environment paths.
> 
> I followed this guide for installing tensorflow correctly: https://www.joe0.com/2019/10/19/how-resolve-tensorflow-2-0-error-could-not-load-dynamic-library-cudart64_100-dll-dlerror-cudart64_100-dll-not-found/
> 
> I started with installing CUDA 10.2 but it didn't work so installed CUDA 10 which worked.

sorry im not a programmer what does update system environment paths mean? I followed the steps, I installed CUDA 10 from the very beginning and I copied the files to from the cudnn-10.0-windows10-x64-v7.6.5.32.zip to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0. 


in the website (instructions that I followed) I was told to rename the cudnn64_7.dll or delete it after installing PyTorch which I missed and I end up renamed it after installing CUDA 10 could that be a problem ?

**Comment by ulfsv** [comment]
Not sure if that is the problem. I did change the PyTorch file at all and got it working. 
For the system environment paths check the guide I was referring to who explains how to do it: https://www.joe0.com/2019/10/19/how-resolve-tensorflow-2-0-error-could-not-load-dynamic-library-cudart64_100-dll-dlerror-cudart64_100-dll-not-found/

**Comment by ulfsv** [comment]
I mean did not change PyTorch file.

**Comment by blue-fish** [comment]
Please pull the latest code from the repo and see if you continue to have this issue. We recently made changes such as adding CPU support.
