### ISSUE TITLE
How do I use my own mp3?

### ISSUE THREAD

**Issue by orenong** [CorentinJ/Real-Time-Voice-Cloning#289]
I'm playing with the demo, and I only have an option to record, how do I import an audio file?
tnx.

**Comment by favarete** [comment]
You can click on `Browse`, next to `Utterrance` on the GUI, and then select your audio file.

**Comment by lNeverl** [comment]
> 您可以单击GUI `Browse`旁边`Utterrance`的，然后选择音频文件。
I do n’t know why, my utterance is gray, I ca n’t click it I did not download the data set.

**Comment by shadept-GitHub** [comment]
@favarete I'm sorry but it always doesn't do anything and prints out "Expection: " under the big button under synthesize only and vocode only buttons.
![image](https://user-images.githubusercontent.com/65095770/81487261-cb647f00-9263-11ea-975e-c9a925fa22a9.png) Please help me.

**Comment by lNeverl** [comment]
> @favarete I'm sorry but it always doesn't do anything and prints out "Expection: " under the big button under synthesize only and vocode only buttons.
> ![image](https://user-images.githubusercontent.com/65095770/81487261-cb647f00-9263-11ea-975e-c9a925fa22a9.png) Please help me.

![image](https://user-images.githubusercontent.com/60817289/81488177-008ac480-9298-11ea-8bbe-56f4f7bf8c48.png)


You check if the framed part of my photo is the same as yours.After selecting the sound file by clicking the browse button, does the sound spectrum appear in the lower right corner.

**Comment by shadept-GitHub** [comment]
> > @favarete I'm sorry but it always doesn't do anything and prints out "Expection: " under the big button under synthesize only and vocode only buttons.
> > ![image](https://user-images.githubusercontent.com/65095770/81487261-cb647f00-9263-11ea-975e-c9a925fa22a9.png) Please help me.
> 
> ![image](https://user-images.githubusercontent.com/60817289/81488177-008ac480-9298-11ea-8bbe-56f4f7bf8c48.png)
> 
> You check if the framed part of my photo is the same as yours.After selecting the sound file by clicking the browse button, does the sound spectrum appear in the lower right corner.

It didn't at first, but I realized I needed 5 seconds of audio or more. For some reason mp3 files refused to get imported but exporting them into .WAV using audacity fixed the issue. I'm so dumb..

**Comment by lNeverl** [comment]
> > > @favarete I'm sorry but it always doesn't do anything and prints out "Expection: " under the big button under synthesize only and vocode only buttons.
> > > ![image](https://user-images.githubusercontent.com/65095770/81487261-cb647f00-9263-11ea-975e-c9a925fa22a9.png) Please help me.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/60817289/81488177-008ac480-9298-11ea-8bbe-56f4f7bf8c48.png)
> > You check if the framed part of my photo is the same as yours.After selecting the sound file by clicking the browse button, does the sound spectrum appear in the lower right corner.
> 
> It didn't at first, but I realized I needed 5 seconds of audio or more. For some reason mp3 files refused to get imported but exporting them into .WAV using audacity fixed the issue. I'm so dumb..

Yes, it only supports wav .  lol

**Comment by shadept-GitHub** [comment]
> > > > @favarete I'm sorry but it always doesn't do anything and prints out "Expection: " under the big button under synthesize only and vocode only buttons.
> > > > ![image](https://user-images.githubusercontent.com/65095770/81487261-cb647f00-9263-11ea-975e-c9a925fa22a9.png) Please help me.
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/60817289/81488177-008ac480-9298-11ea-8bbe-56f4f7bf8c48.png)
> > > You check if the framed part of my photo is the same as yours.After selecting the sound file by clicking the browse button, does the sound spectrum appear in the lower right corner.
> > 
> > 
> > It didn't at first, but I realized I needed 5 seconds of audio or more. For some reason mp3 files refused to get imported but exporting them into .WAV using audacity fixed the issue. I'm so dumb..
> 
> Yes, it only supports wav . lol

then i wonder why it said that i could import any audio file lol

**Comment by Haven-Net** [comment]
Thanks for the info.  How do you save your recording once you are happy with the audio and text?
I thought it was the "Take genearated" button but that doesn't do anything for me.

**Comment by lNeverl** [comment]
> Thanks for the info. How do you save your recording once you are happy with the audio and text?
> I thought it was the "Take genearated" button but that doesn't do anything for me.

I also don't know how to save the generated audio. I use software that can record internally.You can learn about [VOICEMEETER BANANA](https://www.vb-audio.com/Voicemeeter/banana.htm).

**Comment by Haven-Net** [comment]
ok thanks

**Comment by blue-fish** [comment]
You might need to install a backend such as ffmpeg for use with audioread. That performs the conversion to other formats. This comes up rather frequently so we might need to catch the exception and print a more helpful error message.
