### ISSUE TITLE
google colab

### ISSUE THREAD

**Issue by ak9250** [CorentinJ/Real-Time-Voice-Cloning#29]
any plans to set this up in google colab as it provides free Nvidia t4 gpus for 12 hour cycles?

**Comment by CorentinJ** [comment]
Not from me, but I would certainly not mind linking it if someone makes one. I think a notebook-ish demo is doable

**Comment by ak9250** [comment]
@CorentinJ I see I have everything setup in colab but i think the problem is the demo_toolbox does not support non ui /running in cli yet?

I get this output running the demo_toolbox, demo_cli tests pass

WARNING: Logging before flag parsing goes to stderr.
W0701 03:24:00.135030 140347045406592 deprecation_wrapper.py:119] From /content/Real-Time-Voice-Cloning/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Arguments:
    datasets_root:    /content/Real-Time-Voice-Cloning/UserAudio/speaker_01
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    low_mem:          False

**Comment by CorentinJ** [comment]
No, the CLI demo is not finished yet. You will have to wait until then.

**Comment by ak9250** [comment]
@CorentinJ any update on this, once it works I can send a PR if you would like to add the colab notebook to the repo

**Comment by CorentinJ** [comment]
Yeah the CLI demo should be working, try it out.

**Comment by ak9250** [comment]
@CorentinJ just tried it got this error
/content/Real-Time-Voice-Cloning/UserAudio/speaker_01/audio_01.wav
Loaded file succesfully
Created the embedding
"this is a test"
Created the mel spectrogram
Synthesizing the waveform:
{| ████████████████ 57000/57600 | Batch Size: 6 | Gen Rate: 4.6kHz | }Caught exception: PortAudioError('Error querying device -1',)
Restarting

**Comment by JasonWei512** [comment]
@ak9250 This is because in demo_cli.py, when synthesizing completes, the synthesized audio will be played. However the Colab VM doesn't have any audio device. You need to modify the code a bit.

**Comment by ak9250** [comment]
@JasonWei512 yep that was it adding --no_sound as a argument fixes it thanks

**Comment by logfella** [comment]
did somebody managed to get this working in Google Colab? Would really like to try but I don't have a gpu at home

**Comment by PapayasTehSkeletor** [comment]
> did somebody managed to get this working in Google Colab? Would really like to try but I don't have a gpu at home

I found this https://colab.research.google.com/github/ak9250/Real-Time-Voice-Cloning/blob/master/Real_Time_Voice_Cloning.ipynb

**Comment by campeaux** [comment]
@PapayasTehSkeletor Still no. It fails at the last step.

**Comment by Yashwanthd1998** [comment]
the tensor flow versions arent supporting in colab

**Comment by gguynn** [comment]
Add this to line 1
%tensorflow_version 1.x

**Comment by zubairahmed-ai** [comment]
The colab notebook gives following error

```
Synthesizing the waveform:
{| ████████████████ 85500/86400 | Batch Size: 9 | Gen Rate: 11.7kHz | }generated_wav.dtype:  float64
Caught exception: AttributeError("module 'librosa' has no attribute 'output'")
Restarting
```

Fixed by - in the translate.py line 131 replace this

```
# librosa.output.write_wav(fpath, generated_wav.astype(np.float32), synthesizer.sample_rate)
import soundfile as sf
sf.write('output.wav', generated_wav.astype(np.float32), synthesizer.sample_rate, 'PCM_24')
```
