### ISSUE TITLE
which utterence is chosen for embedding

### ISSUE THREAD

**Issue by fantasyHq** [CorentinJ/Real-Time-Voice-Cloning#290]
if we wanna synthesis speech sounds like speaker A,there are so many utterences in datasets and we can get lots of  embedding-speakerA-*.npy.Does that mean we choose anyone of them for synthesis speech?

**Comment by blue-fish** [comment]
You can choose any of them but it is likely the embedding that is calculated will vary slightly. This means your results will depend on which utterance is selected as your reference.

If you have additional questions please reopen this issue.
