### ISSUE TITLE
Add torch to requirements.txt

### ISSUE THREAD

**Issue by julianofischer** [CorentinJ/Real-Time-Voice-Cloning#292]
ModuleNotFoundError: No module named 'torch'

**Comment by favarete** [comment]
Torch installation is a little more tricky (some GPU drivers, for example), I think this is the main reason for following the official docs and not to include this one in the requirements.txt

**Comment by blue-fish** [comment]
Torch installation is done separately for compatibility reasons surrounding GPU support. Depending on the version of NVIDIA drivers a different pytorch version is needed. It is not something that can be automated into requirements.txt.
