### ISSUE TITLE
Have this ModuleNotFoundError: No module named 'unidecode'

### ISSUE THREAD

**Issue by videoprice** [CorentinJ/Real-Time-Voice-Cloning#293]
Hi guys, can help me? Thanks
in anaconda command python demo_cli.py have this:
Traceback (most recent call last):
 <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'

**Comment by videoprice** [comment]
ok. everything working. thanks for nice soft:)

**Comment by G00dieB0y** [comment]
how did you fix it?

**Comment by kingofowls812** [comment]
How did you fix it? I have this error as well

**Comment by mohammadJaliliTorkamani** [comment]
as well as me

**Comment by sjmelsom** [comment]
You just need to install unidecode:
`pip install unidecode`
or if using anaconda
`conda install unidecode`

**Comment by blue-fish** [comment]
Closing this issue as it has been resolved.
