### ISSUE TITLE
encoder_train.py and --low_mem

### ISSUE THREAD

**Issue by unassumingbadger** [CorentinJ/Real-Time-Voice-Cloning#294]
VoxCeleb2 dataset doesn't work with encoder_preprocess.py on Linux. The m4a files throw an error and nothing progresses. I converted all the m4a files to wav. This passes preprocessing, but doesn't output numpy files making the next step of training fail.
If I use only LibriSpeech/train-other-500, VoxCeleb1/wav, and VoxCeleb1/vox1_meta.csv, encoder_train.py works until it runs out of memory. I have a GTX 750 ti with only 2GB of VRAM.
I can't figure out how to get --low_mem flag to work with encoder_train.py.

**Comment by blue-fish** [comment]
Thanks for reporting this issue @unassumingbadger . The training scripts do not support the --low-mem flag. You can try reducing your batch size or training with CPU instead (pull the latest code).
