### ISSUE TITLE
Make please google collab notebook version

### ISSUE THREAD

**Issue by shadowzoom** [CorentinJ/Real-Time-Voice-Cloning#295]
Hi. Make please google collab notebook version

**Comment by tugstugi** [comment]
here is a colab notebook: https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/RealTimeVoiceCloning.ipynb

**Comment by blue-fish** [comment]
Also available in the repo: https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/demo_toolbox_collab.ipynb
