### ISSUE TITLE
too many issues and impossible to install on windows :( 

### ISSUE THREAD

**Issue by daciansolgen3** [CorentinJ/Real-Time-Voice-Cloning#297]
there are too many issues and nothing works :(

**Comment by EnriqueSuavonja** [comment]
The same for me. I have tried everything, but sill unable to make it work.

**Comment by curtwagner1984** [comment]
I just installed it on windows and it works just fine.

**Comment by meme-lord** [comment]
Here are the magic numbers:
CUDA 10, CudNN 7.6.5, Python 3.7.7 (Other python versions may work), Torch 1.2.0, tensorflow 1.14.0.

**Comment by spatton8483** [comment]
I've been working on trying to install this for a day and a half.  I've explicitly followed the instructions but can't get it to work!  When I try to install pip install -r requirements.txt I get a lot of errors but the ones in red are these:  

ERROR: tensorflow 2.1.0 has requirement tensorboard<2.2.0,>=2.1.0, but you'll have tensorboard 1.14.0 which is incompatible.
ERROR: tensorflow 2.1.0 has requirement tensorflow-estimator<2.2.0,>=2.1.0rc0, but you'll have tensorflow-estimator 1.14.0 which is incompatible.

Does anyone know of an instruction sheet that details every step needed to get this to work?

**Comment by alsadoon101** [comment]
once you get such issues, run command

pip install --upgrade tensorflow
pip install --upgrade tensorflow-estimator
pip install --upgrade tensorboard

then 
pip install -r requirements.txt

repeat if needed. That's how I was able to proceed

**Comment by snehasharma0707** [comment]
> Here are the magic numbers:
> CUDA 10.0, CudNN 7.6.5, Python 3.7.7 (Other python versions may work), Torch 1.2.0, tensorflow 1.14.0.

@meme-lord  what should the pip version be for these magic versions cause when i try to install torch they say install the correct pip version

**Comment by meme-lord** [comment]
The pip version shouldn't matter but to upgrade pip run `pip install --upgrade pip```
For some of the stuff I had to use the .whl files for torch which you can get from here: https://download.pytorch.org/whl/cu100/torch_stable.html

**Comment by blue-fish** [comment]
We made many changes recently which make the GPU optional, as well as the webrtcvad package which is a nightmare to install on windows. Please pull the latest and try again.
