### ISSUE TITLE
Is there any way to make this work on macOS?

### ISSUE THREAD

**Issue by mrichman** [CorentinJ/Real-Time-Voice-Cloning#299]
This is as far as I got:

```
python3 ./demo_cli.py
WARNING:tensorflow:From /tmp/Real-Time-Voice-Cloning/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Arguments:
    enc_model_fpath:   encoder/saved_models/pretrained.pt
    syn_model_dir:     synthesizer/saved_models/logs-pretrained
    voc_model_fpath:   vocoder/saved_models/pretrained/pretrained.pt
    low_mem:           False
    no_sound:          False

Running a test of your configuration...

Your PyTorch installation is not configured to use CUDA. If you have a GPU ready for deep learning, ensure that the drivers are properly installed, and that your CUDA version matches your PyTorch installation. CPU-only inference is currently not supported.
```

Given that I'm on macOS, and don't have an Nvidia GPU, how can I get this working?

**Comment by monochromicorn** [comment]
I got this working on mac. 
Use this fork instead https://github.com/shawwn/Real-Time-Voice-Cloning
In requirements.txt change the first line to `tensorflow>=1.1.0,<=1.14.0`
Run
`pip install -r requirements.txt`
`pip install torch torchvision`
You'll need to download and install the pretrained models before running `python3 ./demo_cli.py` or it'll complain that it can't find them but you'll be good to go.

**Comment by GoToBoy** [comment]
CPU-only inference is currently not supported ? i flow this ,then show me  not support

**Comment by blue-fish** [comment]
I've got great news for you, we recently added support for CPU inference (and even training)! It even works on macOS. Please pull the latest from the repo and try again.
