### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by hung96ad** [CorentinJ/Real-Time-Voice-Cloning#3]
I tried on PC with GPU 2080ti, cuda, PyQt5 version 10 with on ubuntu 16.04 but when click button "Load" alway error "Aborted (core dumped)".
Can I fix that error?
![Screenshot from 2019-06-14 17-36-22](https://user-images.githubusercontent.com/8874942/59503716-578eea80-8ecb-11e9-82c7-594c368a5e61.png)
Thanks!

**Comment by CorentinJ** [comment]
It looks like the encoder failed to be loaded. What is your version of PyTorch? Have you managed to run other PyTorch models with your setup before?

Also, if you could try to find which of [these lines](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/encoder/inference.py#L30-L38) is causing the problem, that would help.

**Comment by hung96ad** [comment]
> It looks like the encoder failed to be loaded. What is your version of PyTorch? Have you managed to run other PyTorch models with your setup before?
> 
> Also, if you could try to find which of [these lines](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/encoder/inference.py#L30-L38) is causing the problem, that would help.

Thanks for your answer! 
I tried with Pytorch 0.41 and Pytorch 1.1.0.
I change device with CPU on Line 39.
After  I change  [lines,](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/encoder/model.py#L18-L31) to CPU and can load model encode . 
However, it not work. 
I debug and discovered [line](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/encoder/inference.py#L55) About core dump

**Comment by CorentinJ** [comment]
Can you put this script at the root of the project and run it, try to see at what point it fails? You will need a [torchvision](https://pytorch.org/get-started/locally/) version that matches your pytorch version.

```
from torchvision.models import resnet18
from encoder import inference as encoder
from pathlib import Path
import numpy as np
import torch


if __name__ == '__main__':
    # Test to see if your pytorch install works on CPU
    inputs = np.zeros((4, 3, 224, 224), dtype=np.float32)
    model = resnet18()
    model.forward(torch.from_numpy(inputs))
    
    # Same but on GPU
    model = model.cuda()
    model.forward(torch.from_numpy(inputs).cuda())

    # Test to see if the encoder works at all (on CPU) with a small input
    weights_fpath = Path("encoder/saved_models/pretrained.pt")
    device = torch.device("cpu")
    encoder.load_model(weights_fpath, device)
    inputs = np.zeros((1, 100, 40), dtype=np.float32)
    encoder.embed_frames_batch(inputs)
    
    # Same but on GPU
    device = torch.device("cuda")
    encoder.load_model(weights_fpath, device)
    encoder.embed_frames_batch(inputs)
    
```

**Comment by fazlekarim** [comment]
Do you think its because you have PyQt5 and not 4?

**Comment by CorentinJ** [comment]
Hey @hung96ad, any update?

**Comment by hung96ad** [comment]
> Hey @hung96ad, any update?

I tried new code but it not work.
Can you tell me your pytorch version?

**Comment by hung96ad** [comment]
> Do you think its because you have PyQt5 and not 4?

I don't think so. Because PyQt5 is frontend, it doesn't affect load models

**Comment by CorentinJ** [comment]
The models were trained and executed on pytorch 1.10

**Comment by hung96ad** [comment]
> The models were trained and executed on pytorch 1.10.
> 
> At what point does the code I gave you fail?

Thank you!
I tried install pytorch and torchvision. It's work.
I think you need add requirements torchvision.

**Comment by CorentinJ** [comment]
I don't think torchvision has any role to play in the repo. It's a source for common datasets and models and I've only used it in the script I gave you. I suspect something else that you did fixed your setup. I'll still keep this issue in mind if someone else has the same problem. Glad this is fixed for you.
