### ISSUE TITLE
License should be GPL

### ISSUE THREAD

**Issue by rustygentile** [CorentinJ/Real-Time-Voice-Cloning#302]
First off, this is a really cool project. Thanks for sharing it and leaving it up!

I noticed, however, that PyQt5 uses the GPL. Since this is a copyleft license, your code must also be GPL. Otherwise, we're violating the terms of the license.

See also:
https://www.riverbankcomputing.com/commercial/license-faq
https://www.gnu.org/licenses/gpl-faq.html

**Comment by CorentinJ** [comment]
Out of respect for Rayhane-mamah, fatchord, and myself, this project shall remain under an MIT license.

If you or anyone wishes to enforce the use of a GPL license because PyQt is linked in this repo, I will simply remove all PyQt mentions and related code in a commit. Does this work for you?

**Comment by rustygentile** [comment]
Gosh... It’s not really my place to enforce this. I’m just reporting it.

In my opinion though, removing PyQt now would be taking a shortcut. You’ve already reaped lots of benefit and exposure from this project. And some of that should be shared with the creators of PyQt. I’d suggest reaching out to them: info@riverbankcomputing.com

**Comment by rustygentile** [comment]
My mistake! The GPL would only apply to the distribution. If you compile the project, the resulting package would contain code from this repository and PyQt. So if you wanted to distribute that, you’d need to honor the terms of both PyQt’s GPL and your MIT license.

No changes are needed. Sorry for the confusion.
