### ISSUE TITLE
No attribute 'AUTOTUNE'

### ISSUE THREAD

**Issue by EnriqueSuavonja** [CorentinJ/Real-Time-Voice-Cloning#304]
Hi. I recognize I do not have too much experiencience... I have tried everything.

AttributeError: module 'tensorflow.python.data.experimental.ops.optimization' has no attribute 'AUTOTUNE'

I hope you find the time to help people to install this. It is very dificult.

**Comment by blue-fish** [comment]
Can you please try pulling the latest code from the repo and see it resolves your issue?

If there is still a problem, please reopen the issue and provide the error message and full traceback from the terminal.
