### ISSUE TITLE
Synthesizer got different output with same input

### ISSUE THREAD

**Issue by feidotyu** [CorentinJ/Real-Time-Voice-Cloning#306]
When I played with demo_cli.py and input the same audio and sentence, I got different spec from synthesizer (the one specs = synthesizer.synthesize_spectrograms(texts, embeds) ) and thus the generated wav are quite different. 

Is this normal or there are some bugs in the synthesizer model?

**Comment by blue-fish** [comment]
Yes, I can confirm that the variation in the Tacotron output is a feature. In issue #384 , I am trying to find a way to control the output to facilitate benchmarking. Thanks for submitting the bug report.
