### ISSUE TITLE
Error using Vocoder pretrained

### ISSUE THREAD

**Issue by Samtapes** [CorentinJ/Real-Time-Voice-Cloning#307]
when I click at the "Vocode only" or "Synthesize and vocode" using the pretrained vocode happen this:

cuda runtime error(100) : no CUDA-capable device is detected at ../aten/src/THC/THCGeneral.cpp:50

**Comment by blue-fish** [comment]
We recently added CPU support, please pull the latest changes and try again. Feel free to reopen this issue if that does not solve your problem with using the toolbox.
