### ISSUE TITLE
I'm looking to pay someone to install this on my machine; let me know if interestred

### ISSUE THREAD

**Issue by JoeRac** [CorentinJ/Real-Time-Voice-Cloning#308]
I'm looking to pay someone to install this release on my machine and show me the way this works at a basic level, and run a text-to-speech test. Let me know if interested

**Comment by bmccallister** [comment]
Hi Joe,

I have this running and have for a few months. I even have an API that allows you to specify an input wav and auto generate audio by it.  It has some glitches (only sounds good on sentences 3-6 seconds long). (I've deprioritized polishing this for various reasons)

What are you looking to do with this?  I don't have much interest in installing this on someone's machine - but this is part of a developer friendly AI platform we're developing so maybe there's something i can do that helps?


    On Friday, April 3, 2020, 12:32:43 PM PDT, JoeRac <notifications@github.com> wrote:  
 
 


I'm looking to pay someone to install this release on my machine and show me the way this works at a basic level, and run a text-to-speech test. Let me know if interested

**Comment by JoeRac** [comment]
Hey, thanks for the note. I'm only looking to use this software once, to clone a voice and generate a 3 second sentence from it. That's it. 

I have a lot of audio files available for the input voice to be cloned. 

I have the tool installed on my machine but it's very glitchy and I don't know how to use it and some commands are greyed out.

One other option is that I provide audio input files and someone generates the resulting sentence taht I'm looking for and send it over. 

I'll pay whoever can help me with this! Thanks.

**Comment by zakajd** [comment]
> One other option is that I provide audio input files and someone generates the resulting sentence taht I'm looking for and send it over.

I've been playing with this repo for a while. Can help if you still interested. Text me on twitter @dja_zak

**Comment by funnybone72** [comment]
> > One other option is that I provide audio input files and someone generates the resulting sentence taht I'm looking for and send it over.
> 
> I've been playing with this repo for a while. Can help if you still interested. Text me on twitter @dja_zak



> > One other option is that I provide audio input files and someone generates the resulting sentence taht I'm looking for and send it over.
> 
> I've been playing with this repo for a while. Can help if you still interested. Text me on twitter @dja_zak

Zakajd I have a similar request. Can I DM you?

**Comment by zakajd** [comment]
> Zakajd I have a similar request. How can I contact you I don’t use Twitter?
You can find me in Telegram or FB using GitHub name (@zakajd)

**Comment by funnybone72** [comment]
> Hey, thanks for the note. I'm only looking to use this software once, to clone a voice and generate a 3 second sentence from it. That's it.
> 
> I have a lot of audio files available for the input voice to be cloned.
> 
> I have the tool installed on my machine but it's very glitchy and I don't know how to use it and some commands are greyed out.
> 
> One other option is that I provide audio input files and someone generates the resulting sentence taht I'm looking for and send it over.
> 
> I'll pay whoever can help me with this! Thanks.

Any luck getting your request fulfilled?

**Comment by Vishwanathpd** [comment]
I will help you to install it

contact: Gmail: vishwanathdalawai321@gmail.com
LinkedIn: https://www.linkedin.com/in/vishwanath-dalawai/

Thanks,
Vishwanath D

**Comment by sjmelsom** [comment]
Why not just use the better model found on [https://www.resemble.ai/](https://www.resemble.ai/)?

**Comment by zakajd** [comment]
> Why not just use the better model found on https://www.resemble.ai/?

Because they don't allow you to use someone other's voice. (Actually there is an option, but you need to pay for that)

**Comment by nmcbride** [comment]
There are lots of reasons why you wouldn't want to use the commercial service that made this open source project abandoned. Personally, I don't want to upload any voice data to someone else's servers. I'm hoping that someone who understands this stuff better than me picks this up to maintain and then we as a community can contribute and keep it going.

**Comment by partridge** [comment]
> Why not just use the better model found on https://www.resemble.ai/?

Garbage in, garbage out. Unless you pay $499/mo you must record prompts through your browser. The browser method presents many challenges. Mainly, not having control over input audio quality. The browser interface is buggy and suffers multiple outages a session. 

You have no control over model config or tuning time and if you like a model but later make some refinements with additional audio but don't like the new output, you can't rollback.

If you want ultimate control and are ready to cover the 100% cost of maintaining then you'd use this repo. If you're ok with a cookie cutter solution then go with the SaaS option.

**Comment by ramanova** [comment]
Feel free to contact :)

**Comment by mbdash** [comment]
If you are running an Ubuntu PC, I can paste my conda env file and install instructions in here.
I am not on my PC but will be in 2h.
Let me know if you are interested.
