### ISSUE TITLE
Which versino of CUDA/CuDNN/Tensorflow? CuDNN fails on initializing

### ISSUE THREAD

**Issue by SirRosenfeld** [CorentinJ/Real-Time-Voice-Cloning#309]
Hi,

I am using Tensorflow-gpu 1.14.0, CUDA 10.0 and CuDNN 7.4.1 on Windows 10 (Python 3.7) but I can't manage to make it work.

demo_cli.py works fine but demo_toolbox.py sends an error when I try to synthetize an audio.

I keep getting the error : "Failed to get convolution algorithm. This is probably because cuDNN failed to initialize"
It seems to be a version problem : "Loaded runtime CuDNN library: 7.2.1 but source was compiled with: 7.4.1.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration."

Which versions should I be running?

I've attached my log
[Log.txt](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/4431371/Log.txt)

**Comment by sjmelsom** [comment]
Your traceback states that it's trying to use cudnn 7.2.1. You most likely have two versions installed or cudnn 7.4.1 did not install correctly.

**Comment by aemrea** [comment]
i am having the same issue but couldnt solved yet

**Comment by blue-fish** [comment]
The toolbox supports CPU now, so please try pulling the latest and try again.
