### ISSUE TITLE
Pytorch Can Not Install

### ISSUE THREAD

**Issue by kingofowls812** [CorentinJ/Real-Time-Voice-Cloning#313]
I'm attempting to install Pytorch, but I'm getting this error

Error: Could not find a version that satisfies the the requirement torch==1.4.0+cpu  (from versions: 0.1.2, 0.1.2post1, 0.1.2.post2)
Error:  No matching distribution found for torch 1.4.0+cpu

This what I'm using to try to install Pytorch, I'm currently in the virtualenv
pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

**Comment by sjmelsom** [comment]
Follow the instructions on the [PyTorch homepage](https://pytorch.org/) for proper installation.

**Comment by Haven-Net** [comment]
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch -y

**Comment by UJJWAL-1711** [comment]
similar problem here

**Comment by blue-fish** [comment]
If you get that error message, you may need to upgrade pip with `python -m pip install –upgrade pip`.

I'm going to close this as questions about installing dependencies are out of scope for this repo.
