### ISSUE TITLE
The minimum cuda capability that we support is 3.5

### ISSUE THREAD

**Issue by Snuffy4** [CorentinJ/Real-Time-Voice-Cloning#315]
Help me please. Is there any way to start a project with 2.1 cuda capability?
```
Found GPU0 GeForce GT 630M which is of cuda capability 2.1.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Found 1 GPUs available. Using GPU 0 (GeForce GT 630M) of compute capability 2.1 with 2.1Gb total memory.

Preparing the encoder, the synthesizer and the vocoder...
Traceback (most recent call last):
  File "demo_cli.py", line 61, in <module>
    encoder.load_model(args.enc_model_fpath)
  File "C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\encoder\inference.py", line 32, in load_model
    _model = SpeakerEncoder(_device, torch.device("cpu"))
  File "C:\Users\kisel\Desktop\Real-Time-Voice-Cloning-master\encoder\model.py", line 21, in __init__
    batch_first=True).to(device)
  File "C:\Users\kisel\anaconda3\envs\TestVoice\lib\site-packages\torch\nn\modules\module.py", line 386, in to
    return self._apply(convert)
  File "C:\Users\kisel\anaconda3\envs\TestVoice\lib\site-packages\torch\nn\modules\rnn.py", line 127, in _apply
    self.flatten_parameters()
  File "C:\Users\kisel\anaconda3\envs\TestVoice\lib\site-packages\torch\nn\modules\rnn.py", line 123, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_ARCH_MISMATCH
```

**Comment by sjmelsom** [comment]
Unfortunately, your graphics card is too old for using most deep learning libraries. Based on your error message, you'll need a card that has a cuda capability of at least 3.5. You can look at [this chart](https://developer.nvidia.com/cuda-gpus) to help you find a graphics card that has such a capability. However, you will also need a card with enough memory to host the models and data. Off the top of my head, I'm not sure what the minimum memory requirements are for this model, but I'd venture to say that 12GB is a decent benchmark (Nvidia GTX 1080Ti should probably work).  

If you can't get a card with enough memory, you would need to reduce the memory requirements of the model by converting it to half precision.

**Comment by blue-fish** [comment]
I am going to close this because CPU support can be used as a fallback, even for training. The inability to use older GPUs is a limitation of the dependencies (PyTorch, Tensorflow). If you need GPU acceleration, it will be required to upgrade your GPU.
