### ISSUE TITLE
KeyError: "Registering two gradient with name 'BlockLSTM'!     Getting this error

### ISSUE THREAD

**Issue by pks889** [CorentinJ/Real-Time-Voice-Cloning#317]
KeyError: "Registering two gradient with name 'BlockLSTM'! (Previous registration was in register C:\\Users\\pks89\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorflow_core\\python\\framework\\registry.py:66)"

**Comment by blue-fish** [comment]
Not enough info to troubleshoot. Please provide more details about your problem and reopen the issue.

**Comment by blue-fish** [comment]
Duplicate of #185, suggestion is to pull the latest version of the code, reinstall the requirements and try again. I expect it should resolve your problem. It does look like a tensorflow version issue, the current toolbox uses tensorflow 1.15.
