### ISSUE TITLE
Does it support diffrent accents?

### ISSUE THREAD

**Issue by arongamer69** [CorentinJ/Real-Time-Voice-Cloning#318]
I was wondering if this program supports diffrent accents because I was working on somthing with it today with person that had a diffrent accent, but it sounded american. Very much appreciated

**Comment by arongamer69** [comment]
Accent

**Comment by chameleonTK** [comment]
You could train any accents you want if you have enough data. Maybe you should try this one [https://www.resemble.ai/](https://www.resemble.ai/)

**Comment by blue-fish** [comment]
See here for information on how to fine-tune the model to a particular accent: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/429#issuecomment-660514897

If you do not wish to perform training, periodically check #400 and see if anyone has uploaded a model with the desired accent.
