### ISSUE TITLE
Problem:Run demo_cli.py, Nothing happened!

### ISSUE THREAD

**Issue by herorichard** [CorentinJ/Real-Time-Voice-Cloning#322]
I already run " pip3 install -r requirements.txt" ,it's done. 
When I run "demo_cli.py", nothing happened. I repeated it several times, but just nothing. As follows:
(base) C:\Users\Administrator\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>python demo_cli.py

(base) C:\Users\Administrator\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>

Does anyone know why? Thanks.

**Comment by herorichard** [comment]
I run  demo_toolbox.py in anaconda, nothing happened too. As follows:

(base) C:\Users\Administrator\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>python demo_toolbox.py

(base) C:\Users\Administrator\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>

**Comment by herorichard** [comment]
it's tensorflow problem

**Comment by Nutr1t07** [comment]
So did you solve the problem? How?
