### ISSUE TITLE
What i need to study to make this work?

### ISSUE THREAD

**Issue by Ozamatheus** [CorentinJ/Real-Time-Voice-Cloning#323]
since there's no "setup.exe" and no step by step and look's like everyone know how to use this, what i need to know to make this work like the video demonstration? if someone explain to me, that be great, but if someone tell me what kind of knowlege i need to make this work, that be great too

thanks

**Comment by macriluke** [comment]
Plenty of youtube videos available.
[This was the first that came up for me](https://youtu.be/12rdn9jazwE)

**Comment by Ozamatheus** [comment]
I suppose it's just for linux, thanks anyway, it was very enlightening

**Comment by macriluke** [comment]
It works fine on windows.
Package management and environment setup with python can be very tricky if you are not experienced with it.

The general workflow is thus.

1. Git clone the repositoryset up a [virtual environment](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/)

**Comment by Ozamatheus** [comment]
> 
> 
> It works fine on windows.
> Package management and environment setup with python can be very tricky if you are not experienced with it.
> 
> The generalized workflow for setting up machine learning models with python is thus.
> 
>     1. Git clone the repository
> 
>     2. set up a [virtual environment](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/)
> 
>     3. in your virtual environment, pip install -r requirements.txt
> 
>     4. handle dependencies that were not listed in the requirements.txt there are many reasons for this, I won't go over them now.
> 
>     5. download pretrained models/ datasets
> 
>     6. run the eval function for the model.
> 
> 
> I recommend using an IDE like pycharm to consolidate management of virtual environments, version control, ect.

thanks a lot, now i know what learn exactly :D

**Comment by kogake** [comment]
wow that was amazin @macriluke. Thanks

**Comment by blue-fish** [comment]
Closing as this issue has been resolved.
