### ISSUE TITLE
A number of errors

### ISSUE THREAD

**Issue by eupirate** [CorentinJ/Real-Time-Voice-Cloning#326]
hi, I ran in to a number of issues. 
Mac, all prerequisites follow as instructed. 
Great project, would love to get it to work! Thanks

1.
(base) AIDESORRYALONE:Real-Time-Voice-Cloning-master $ ls
LICENSE.txt				synthesizer
README.md				synthesizer_preprocess_audio.py
demo_cli.py				synthesizer_preprocess_embeds.py
demo_toolbox.py				synthesizer_train.py
demo_toolbox_collab.ipynb		toolbox
encoder					utils
encoder_preprocess.py			vocoder
encoder_train.py			vocoder_preprocess.py
requirements.txt			vocoder_train.py
(base) AIDESORRYALONE:Real-Time-Voice-Cloning-master janet.xiushi$ python3 ./demo_cli.py
Traceback (most recent call last):
  File "./demo_cli.py", line 2, in <module>
    from utils.argutils import print_args
  File "/Users/janet.xiushi/Downloads/Real-Time-Voice-Cloning-master/utils/argutils.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

2. demo_cli.py
Unable to import 'librosa'
Unable to import 'torch'
Unable to import 'sounddevice'

3. synthesizer.py
Unable to import 'tensorflow'
No value for argument 'embed_filenames' in method call
Unused variable 'start'
Possible unbalanced tuple unpacking with sequence defined at line 184 of synthesizer.tacotron2: left side has 2 label(s), right side has 0 value(s)

**Comment by mcfilms** [comment]
Same. I did all the installs, but when I run `python demo_cli.py`
I get:
File "demo_cli.py", line 45
    "not supported.", file=sys.stderr)

**Comment by blue-fish** [comment]
Please try again, mac should work now with --cpu option for demo_cli.py

**Comment by blue-fish** [comment]
It also appears that the package requirements are not installed. Please reopen this issue if you continue to experience problems.
