### ISSUE TITLE
You do not have any of the recognized datasets in D:\Datasets\LibriSpeech\train-clean-100

### ISSUE THREAD

**Issue by Lanev** [CorentinJ/Real-Time-Voice-Cloning#327]
I have tried entering the root directory for the dataset in multiple folder locations and every time I get the same error. I noticed someone else had this problem previously but the supposed solution was to make a folder named Datasets in the D: drive separate from where my voice cloning is installed. Then put the LibriSpeech folder into the Datasets folder with the train-clean-100 inside that.
This does not work for me I get the same error when typing this regardless that the dataset exists.
python demo_toolbox.py -d D:\Datasets\LibriSpeech\train-clean-100
Warning: you do not have any of the recognized datasets in D:\Datasets\LibriSpeech\train-clean-100.
I have tried putting LibriSpeech into the voice cloning folder on my D: drive and using that path and I get the same error. The same thing happens when I try to input python demo_toolbox.py -d D:\Datasets\LibriSpeech\train-other-500.
I am using anaconda with python 3.7, pytorch 1.2, tensorflow-gpu 1.14, CUDA 10, cuDNN for CUDA 10.0

**Comment by wutaiqiang** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/255

**Comment by wutaiqiang** [comment]
you should use **python demo_toolbox.py -d D:\Datasets\**
rather than **python demo_toolbox.py -d D:\Datasets\LibriSpeech\train-clean-100**

**Comment by Lanev** [comment]
I used that and now I get Warning: you do not have any of the recognized datasets in D:\Datasets.

**Comment by Lanev** [comment]
My problem was solved by fully extracting the dataset files. They were .gz extracted to .tar then extracted to a folder which is recognized when I enter python demo_toolbox.py -d D:\Datasets
