### ISSUE TITLE
Failure on "from PyQt5.QtCore import Qt"

### ISSUE THREAD

**Issue by MorganCZY** [CorentinJ/Real-Time-Voice-Cloning#33]
When runing demo_toolbox.py, an importError occurs, which points to the line 3 in ui.py "from PyQt5.QtCore import Qt". However, when I tried this import independently in python environment, it succeeded. Details are shown in the following picture.
![image](https://user-images.githubusercontent.com/33675916/60649092-ed3aeb80-9e73-11e9-93bc-6a6f9c3dc58b.png)

**Comment by CorentinJ** [comment]
I assume there's some conflict with another package. What about these threads:
https://forums.linuxmint.com/viewtopic.php?t=291157  
http://eab.abime.net/showthread.php?t=96856

**Comment by MorganCZY** [comment]
@CorentinJ Thanks. I fixed this issue by replacing PyQt5 5.12.3 version with 5.11.3 verison. It seems the error is caused by PyQt5 implementation itself.
