### ISSUE TITLE
Not detecting Librispeech dataset

### ISSUE THREAD

**Issue by LostKin** [CorentinJ/Real-Time-Voice-Cloning#330]
I tried to preprocess synthesizer_audio. I have both train-clean-100 and 360 datasets loaded.
but i keep getting this result
`LibriSpeech: 100%|██████████████████| 1172/1172 [00:00<00:00, 3402.16speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
`

**Comment by youshuaiHou** [comment]
I have the same problem. Is there any solution?

**Comment by rajendrac3** [comment]
I am facing the same issue. Anyone resolved it?

**Comment by blue-fish** [comment]
It is likely you are missing the LibriSpeech alignments which tell the training script which datasets are available to it. Please read the directions on this page closely: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training

**Comment by blue-fish** [comment]
I've confirmed that this occurs when the alignments are not present.
