### ISSUE TITLE
DLL load failed: The operating system cannot run %1.

### ISSUE THREAD

**Issue by screechy1** [CorentinJ/Real-Time-Voice-Cloning#333]
I've been trying to install this on Windows 10, and on a tutorial I found there is a specific .dll I was supposed to delete in the directory `%userprofile%\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib`, and it spits out this error. The full picture is here: https://gyazo.com/831f5bdd9990d88e24779895b6e45fcb

I don't know what the problem is, as I'm new to deep-learning algorithms. I really want to try this out and would appreciate it if I could get some help!

**Comment by bmills20** [comment]
Had the same error, was solved through removing numpy and installing the correct numpy version, making sure the Torch version you are using is compatible with it (the error is thrown b/c Python doesn't know how to import torch without NumPy). 

For me, it was numpy-1.18.4+mkl-cp37-cp37m-win_amd64.whl (cp37 refers to python 3.7, windows 64bit).

**Comment by screechy1** [comment]
> 
> 
> Had the same error, was solved through removing numpy and installing the correct numpy version, making sure the Torch version you are using is compatible with it (the error is thrown b/c Python doesn't know how to import torch without NumPy).
> 
> For me, it was numpy-1.18.4+mkl-cp37-cp37m-win_amd64.whl (cp37 refers to python 3.7, windows 64bit).

So you're saying that version 1.18.4 is the incompatible version, or vice-a-versa?

**Comment by blue-fish** [comment]
I am not sure which set of instructions you are following, but a similar issue was also reported in #286 . Given the recent update to support CPU, I think you should have a much easier time getting the toolbox to work. Please pull the latest and try again.
