### ISSUE TITLE
ImportError: cannot import name 'dense_features' from 'tensorflow.python.feature_column'

### ISSUE THREAD

**Issue by ddroder** [CorentinJ/Real-Time-Voice-Cloning#334]
New to tensorflow and haven't been able to find much about this error! Anyone got any ideas =)??

**Comment by blue-fish** [comment]
I cannot find any code to this effect in the repo. More info would be needed to troubleshoot. Could you please try pulling the latest code and see if this problem still exists? Tensorflow 1.15 is required. Please reopen the issue if you have more info.
