### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.distribution'

### ISSUE THREAD

**Issue by Lanev** [CorentinJ/Real-Time-Voice-Cloning#336]
I can get SV2TTS working fine with the base pretrained models however when I paste Tacotron 2 files to the Real-Time-Voice-Cloning synthesizer folder and paste WaveRNN Vocoder + TTS files to Real-Time-Voice-Cloning vocoder folder I get the following error when launching python demo_toolbox.py

Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\VoiceClone2\toolbox\__init__.py", line 4, in <module>
    from vocoder import inference as vocoder
  File "D:\VoiceClone2\vocoder\inference.py", line 1, in <module>
    from vocoder.models.fatchord_version import WaveRNN
  File "D:\VoiceClone2\vocoder\models\fatchord_version.py", line 4, in <module>
    from utils.distribution import sample_from_discretized_mix_logistic
ModuleNotFoundError: No module named 'utils.distribution'

Conda Install Utils does not fix the problem and there is no Conda install utils.distribution

**Comment by blue-fish** [comment]
It's not a straight copy of WaveRNN, you will need to make some modifications. For example, the problematic line of code in this repo is:

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/ba1a78d869030f996c771fd2e9f244e57dfd2e8d/vocoder/models/fatchord_version.py#L4

**Comment by blue-fish** [comment]
I should also add that the voice cloning code is not meant to consume pretrained models that have not been trained on this codebase. The Tacotron2 in this repo has a special modification to take the embedding from the speaker encoder, without it cloning a voice is not possible. The WaveRNN also needs to be trained using data from the modified Tacotron2.

Please take a look at [this](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/30#issuecomment-508381648) and hopefully it will make a little more sense.
