### ISSUE TITLE
Problem with demo_cli.py

### ISSUE THREAD

**Issue by NumpyG** [CorentinJ/Real-Time-Voice-Cloning#339]
C:\Users\Test\Desktop\Real-Time-Voice-Cloning-master>python demo_cli.py --low_mem
Traceback (most recent call last):
  File "demo_cli.py", line 2, in <module>
    from utils.argutils import print_args
  File "C:\Users\Test\Desktop\Real-Time-Voice-Cloning-master\utils\argutils.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

What am I doing wrong?

**Comment by AndrejHatzi** [comment]
pip install numpy

**Comment by appstore-redphoenix** [comment]
> pip install numpy

didn't help

**Comment by blue-fish** [comment]
@appstore-redphoenix If you would like to get support, please open a new issue and post the error message and full traceback. Please check and make sure you are running Python 3.6 or 3.7, and have installed the requirements per the readme.
