### ISSUE TITLE
china version google-drive please

### ISSUE THREAD

**Issue by willshion** [CorentinJ/Real-Time-Voice-Cloning#34]
Pretrained models
Download the latest here.

I need " https://pan.baidu.com/ "
cant get the pretrain model 
plz uplode the pan.baidu.com version

**Comment by CorentinJ** [comment]
I don't mind uploading the pretrained models somewhere else, but not on a website in a language I don't understand that requires me to create an account.

**Comment by charlesld** [comment]
hahaha，是时候进 大厂了，这样google 无阻力。
我上传了。
链接：https://pan.baidu.com/s/1dTEiDwJe648W126-gs66LA 
提取码：xpxy 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by CorentinJ** [comment]
Please use English in this repo @charlesld

**Comment by willshion** [comment]
ok

**Comment by willshion** [comment]
plz  give me a mega drive link

**Comment by CorentinJ** [comment]
https://megaupload.nz/F982Z8x6n5/pretrained_12_06_19_zip

**Comment by willshion** [comment]
veryvery thankyou！！！！！！

**Comment by willshion** [comment]
https://mega.nz/ plz    the-megaupload tooooo slow

**Comment by CorentinJ** [comment]
https://mega.nz/#!irxCGKoT!Zf-ICtEFwDuDPmdg5OFcX4SnmHtJ5VMubZHO0_9QVlI

**Comment by primejava** [comment]
Nobody owes you anything.
