### ISSUE TITLE
Re: speed or rate of talking - generated audio speaking way too fast

### ISSUE THREAD

**Issue by andrewarrow** [CorentinJ/Real-Time-Voice-Cloning#347]
I've gotten some very good results with the small file I pass into `encoder.preprocess_wav(file)`. It is amazing how well the generated voice takes on the sample provided. But, is there a simple way to change how fast the text is read? It feels like the speaker is talking just way too fast.

**Comment by rfwatkins** [comment]
There's an optimum point for length of input text - too short and you get hissy noise all over, too long and the speech rate goes way too high.  You just need to experiment with the length of input text strings.

**Comment by btahir** [comment]
Same issue. It seems its optimized to produce 5-6 seconds of output and will adjust accordingly. Maybe this is a setting that can be tweaked?

**Comment by blue-fish** [comment]
I would like to request someone look at this as well. Other tacotron implementations do not have this issue.

There is a chance it will improve if we upgrade to tensorflowTTS/tacotron2 (see #370) ... but I don't know how much of this is embedded in the pretrained models.

**Comment by blue-fish** [comment]
#324 is also related (too few words and large gaps in output appear)

**Comment by gabrielmontagne** [comment]
wanted to add a workflow aside: synthesizing (at least on my rig) is cheaper.  so I tweak the line break and "synthesize only" a few times -- even a few times without changing the line breaks -- until the gaps on the spectrogram look better.  only then do I vocode.

**Comment by blue-fish** [comment]
I'm also noticing this in my tacotron1 model that I'm training in #447 and I mentioned there,

> Rate of speech (#347) may be an issue but it at least seems to be consistent and affects short text inputs too. (Edit: I also think this is from the training data which has similar speech rate.) We might add an option to the toolbox UI to postprocess the output with a speed multiplier that doesn't affect pitch.

**Comment by blue-fish** [comment]
I think this is improved somewhat with the new pretrained model in #538 . Selected training utterances a bit more deliberately and the speaking rate is more consistent in inference. Again, if this is a problem, it is with the training data. If it is too fast you can postprocess to suit your needs.
