### ISSUE TITLE
unable to install webrtcvad

### ISSUE THREAD

**Issue by UJJWAL-1711** [CorentinJ/Real-Time-Voice-Cloning#349]
C:\Users\UJJWAL RASTOGI\Documents\GitHub\Real-Time-Voice-Cloning>pip3 install webrtcvad
Collecting webrtcvad
  Using cached webrtcvad-2.0.10.tar.gz (66 kB)
Using legacy setup.py install for webrtcvad, since package 'wheel' is not installed.
Installing collected packages: webrtcvad
    Running setup.py install for webrtcvad ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ujjwal rastogi\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\UJJWAL RASTOGI\\AppData\\Local\\Temp\\pip-install-3lkfcsuw\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\UJJWAL RASTOGI\\AppData\\Local\\Temp\\pip-install-3lkfcsuw\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\UJJWAL RASTOGI\AppData\Local\Temp\pip-record-ciqa_agr\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ujjwal rastogi\appdata\local\programs\python\python38\Include\webrtcvad'
         cwd: C:\Users\UJJWAL RASTOGI\AppData\Local\Temp\pip-install-3lkfcsuw\webrtcvad\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    copying webrtcvad.py -> build\lib.win-amd64-3.8
    running build_ext
    building '_webrtcvad' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\ujjwal rastogi\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\UJJWAL RASTOGI\\AppData\\Local\\Temp\\pip-install-3lkfcsuw\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\UJJWAL RASTOGI\\AppData\\Local\\Temp\\pip-install-3lkfcsuw\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\UJJWAL RASTOGI\AppData\Local\Temp\pip-record-ciqa_agr\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ujjwal rastogi\appdata\local\programs\python\python38\Include\webrtcvad' Check the logs for full command output.

**Comment by Haven-Net** [comment]
Try using this.   pip install webrtcvad-wheels

**Comment by shock-wave007** [comment]
https://stackoverflow.com/a/50210015/9440595

this will help

**Comment by blue-fish** [comment]
This repo will run without webrtcvad now (#375).
