### ISSUE TITLE
What is required to make voice data for this?

### ISSUE THREAD

**Issue by DrasticGray** [CorentinJ/Real-Time-Voice-Cloning#350]
My friend has given me a challenge to make him swear with this tool using regular data of him reading samples of text. I got it working with recording my voice, but when i try to load his voice from an mp3 file i get "audioread.exceptions.NoBackendError"

What can i do to make the voice files processable?

**Comment by Santiblocks** [comment]
Maybe try converting it to FLAC or WAV? That worked for me

**Comment by blue-fish** [comment]
Take a look at librosa/librosa#219, you need to install a backend. The person who had this same issue in #386 resolved this by installing ffmpeg.
