### ISSUE TITLE
关于训练中文模型

### ISSUE THREAD

**Issue by neil3212080** [CorentinJ/Real-Time-Voice-Cloning#353]
用开源的中文数据训练了，效果勉强过得去，有没有也在做的小伙伴？一起交流一下

**Comment by 0DARKer** [comment]
我也在做，能否留个联系方式我 qq 1746368754

**Comment by Mesalcode** [comment]
Please speak english as this is an english repository.

**Comment by mxins** [comment]
> 用开源的中文数据训练了，效果勉强过得去，有没有也在做的小伙伴？一起交流一下



> 用开源的中文数据训练了，效果勉强过得去，有没有也在做的小伙伴？一起交流一下

开源的中文数据在哪里呢

**Comment by mxins** [comment]
> Please speak english as this is an english repository.

ok

**Comment by michaellin99999** [comment]
I’m working on Chinese version using this please add me

**Comment by neil3212080** [comment]
> > 用开源的中文数据训练了，效果勉强过得去，有没有也在做的小伙伴？一起交流一下
> 
> > 用开源的中文数据训练了，效果勉强过得去，有没有也在做的小伙伴？一起交流一下
> 
> 开源的中文数据在哪里呢

开源的话 你可以用openslr上的啊

**Comment by wangsnial** [comment]
很多地方的普通话带口音，尤其是福建等地，不知道方言语音集怎么搞

**Comment by wangsnial** [comment]
希望能一起讨论学习 训练中文accent 刚创建了qq 群 867722852
