### ISSUE TITLE
How to run the app

### ISSUE THREAD

**Issue by XxBlackBirdxX** [CorentinJ/Real-Time-Voice-Cloning#355]
I cannot run the app. how to do it?

**Comment by XDarkTitan** [comment]
idk how about fixing your name first

**Comment by Santiblocks** [comment]
First install torch, then install the requirements, The more explained installation is actually on this same repo
there will be some problems and you'll need to install visual studio build tools, cuda, & other stuff
As a recommendation, when you get errors, please read the traceback. It says you exactly what to do
Good luck

**Comment by shock-wave007** [comment]
https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/

step by step guide, witout this it took apprx 10 hr for me to make up and running

and other resource 

http://www.xilodyne.com/SBS_RTVC_Demo_Setup

**Comment by blue-fish** [comment]
@XxBlackBirdxX If you are still having an issue please provide a more detailed description of your problem and we will try to help.
