### ISSUE TITLE
lack of documentation, setup failure

### ISSUE THREAD

**Issue by marshonhuckleberry** [CorentinJ/Real-Time-Voice-Cloning#356]
multiple errors, not worth mentioning them. if someone got it to work on windows please share python version, requirments versions and additional installed software. project seems outdated

**Comment by kevind003** [comment]
I have the same problem im on windows 10 - I need this for some theatrical developments im working on - need it in a major way. this is the only implementation out there despite what the readme says.

I believe 2 of the 20 packages that need to be installed would not install
maybe a couple of more

really need help with this I could care less about the new software the pricing does not involve me in any way and never will

**Comment by marshonhuckleberry** [comment]
i hate this guy he left his open source project for becoming commercial what a sad thing, he would have make more money if he added a donation button on his open source project page and improve the project than make his rensemble ai who me personally i would never pay a cent for it, it also has limitation makes it useless, its online so your data privacy is zero, i would gladly donate to good people who make free things

**Comment by kevind003** [comment]
I might try to see if I can make a full list of what is broken in terms of the failing library installs
its pretty **** hairy I remember the last time I tried, it was not fun - but if successful
I could turn this into a lot of profit potential but not with a **** surfer riding me

**Comment by marshonhuckleberry** [comment]
windows 10 64
python 3.6.8
visual studio community 2017
cuda 10.0
cudnn 10.0 (unpack to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0)

1. unzip pretrained.zip to real-time-voice-cloning
2. install torch==1.0.1
3. install requirements.txt 
tensorflow-gpu==1.14.0
umap-learn==0.4.4
visdom==0.1.8.9
webrtcvad==2.0.10
librosa==0.7.2
matplotlib==3.2.2
numpy==1.18.5
scipy==1.4.1
tqdm==4.46.1
sounddevice==0.3.15
Unidecode==1.1.1
inflect==4.1.0
PyQt5==5.15.0
multiprocess==0.70.10
numba==0.48
4. run demo_toolbox.py

opinions: following author instructions will not work because requirements versions are not specified, in this case python installs latest numba==0.50 wich will result in error and in original requirements file pip is allowed to install latest numba version. in time those modules if not specified, newer versions will appear and the errors will show up. even though i specified all the requirements there might be sub-dependencies wich in future may get updated and cause program not to work, i don't fully understand how pip works. my opinion about the program, out of the box is crap maybe improving the idea will get better results.

**Comment by blue-fish** [comment]
Pleased that you were able to get it working @marshonhuckleberry ! I am going to close this issue now as it is resolved.
