### ISSUE TITLE
class ZoneoutLSTMCell(tf.nn.rnn_cell.RNNCell):  AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by wumingzhibei** [CorentinJ/Real-Time-Voice-Cloning#357]
class ZoneoutLSTMCell(tf.nn.rnn_cell.RNNCell):

AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

**Comment by blue-fish** [comment]
Seems like tensorflow version mismatch. Please pull the latest version of this repo and ensure you are running the version of tensorflow in requirements.txt (currently 1.15).

We changed that code in #366:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/f6fabeaf3effdf2f023db98b37bdabd1ec3d81e5/synthesizer/models/modules.py#L92

Please reopen this issue if you continue to have problems after implementing the suggestions above.
