### ISSUE TITLE
 Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by NumpyG** [CorentinJ/Real-Time-Voice-Cloning#358]
I tried to install tensor flow using the command "pip install tensorflow" and came up with this error : 

ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\Test\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\tensorboard_plugin_wit\\_vendor\\tensorflow_serving\\sources\\storage_path\\__pycache__\\file_system_storage_path_source_pb2.cpython-38.pyc'

**Comment by DrewEdgette** [comment]
Are you using a new computer? There is a path length limit and it's low by default. 

see here: https://stackoverflow.com/questions/54778630/could-not-install-packages-due-to-an-environmenterror-errno-2-no-such-file-or

how to change that can be found here: https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing

**Comment by blue-fish** [comment]
Issue is stale and not a bug related to the code in this repo, closing at this time. @NumpyG feel free to reopen if this continues to be a problem.
