### ISSUE TITLE
demo_toolbox_collab.ipynb Dependencies error

### ISSUE THREAD

**Issue by IrvDelgado** [CorentinJ/Real-Time-Voice-Cloning#359]
Hi,

I was trying to use the demo_toolbox_collab.ipynb on Colab, however I get the following error:

![image](https://user-images.githubusercontent.com/28610164/84207859-f49d4880-aa77-11ea-8b7c-b1679b766074.png)

Then I tried 

!pip uninstall -y tensorflow
!pip install tensorflow-gpu==1.14.0

it fixed it but then I get another error:

![image](https://user-images.githubusercontent.com/28610164/84207923-126aad80-aa78-11ea-8b86-72198f526e91.png)

What version should I use?

Thanks.

**Comment by eugenioclrc** [comment]
bump

**Comment by Gustavo886** [comment]
Colab has instaled by default TensorFlow 2.2.0. You have to unistall TensorFlow first:
!pip uninstall tensorflow

**Comment by eugenioclrc** [comment]
also, this has work for me
```
%tensorflow_version 1.x
import tensorflow
print(tensorflow.__version__)

%tensorflow_version 1.x
!pip install umap-learn
!pip install visdom
!pip install webrtcvad
!pip install librosa>=0.5.1
!pip install matplotlib>=2.0.2
!pip install numpy>=1.14.0
!pip install scipy>=1.0.0
!pip install tqdm
!pip install sounddevice
!pip install Unidecode
!pip install inflect
!pip install PyQt5
!pip install multiprocess
!pip install numba
```

**Comment by IrvDelgado** [comment]
It worked, thanks!!

**Comment by maxi07** [comment]
This also solved the issue for me, maybe the Colab Book needs to be updated.
