### ISSUE TITLE
Doesn't work on mac? Or maybe it does... I don't know??!!

### ISSUE THREAD

**Issue by WumpusTheCoder** [CorentinJ/Real-Time-Voice-Cloning#361]
So I have followed every step on mac (anaconda, pytorch etc etc) however because I am using a 2019 iMac (3rd model 4K), I cannot use tensorflow-gpu so the requirements.txt does not install with pip! PLEASE HELP!

**Comment by michaellin99999** [comment]
it wont work with a mac. you need Cuda cores. which requires a Nvidia GPU. macs dont have nvidia GPUS unless you do bootcamp with windows and run a egpu

**Comment by WumpusTheCoder** [comment]
Ok thanks a bunch, will run on my windows PC with a 1050Ti then!

**Comment by blue-fish** [comment]
This will run on mac now that CPU support is enabled with #366 . However, CPU is considerably slower.
