### ISSUE TITLE
Tensorflow v2 compatibility

### ISSUE THREAD

**Issue by blue-fish** [CorentinJ/Real-Time-Voice-Cloning#370]
In #364, @CorentinJ wrote:

> First things first, the biggest issue for me with this project is the hecking tensorflow code. Tensorflow sucks, and it sucks just as much to install it let alone install an older version.

> I believe it would lower the entry barrier for new users if the version of that package were to be upgraded. I've seen a PR for that but that's only for the collab version it seems. A PR for the entire repo would be appreciated.

> Ideally, we'd replace all of the synthesizer code with pytorch code (there are several open source pytorch synthesizers out there), but that's a lot of work.

> If anybody is willing to pick up on either of these things, let me know.

The collab PR (#338) is an update to tensorflow 1.15.2 I believe. With #366 the rest of the repo also advances to 1.15.

One of the best things about this repo is that it works well out of the box. After set up, one can clone a voice with pretrained models, or replicate the original training procedure by following some simple instructions on the wiki. This needs to be the case no matter what solution is pursued here.

So far I have found these options which seem promising:
1. [Mozilla TTS](https://github.com/mozilla/TTS) which has a tacotron-based synthesizer which supports tensorflow v2. Multi-speaker is not yet officially supported but the community has been able to get it work.
2. NVIDIA has a [pytorch-based tacotron2](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2) implementation.

I think the easier approach is to try to support tensorflow v2 by using Mozilla TTS. It also has a larger userbase and better community support. If we switch, will the existing pretrained model continue to work?

**Comment by blue-fish** [comment]
I am attempting to convert the existing synthesizer code to tensorflow v2, making some progress but could use some help with this error message. demo_cli.py gets as far as starting the synthesizer test.

Affected code is in `custom_decoder.py` and `helpers.py` in synthesizer/models. I have a branch here: [https://github.com/blue-fish/Real-Time-Voice-Cloning/commits/370_tf2_compat](https://github.com/blue-fish/Real-Time-Voice-Cloning/commits/370_tf2_compat)

```
$ python demo_cli.py --cpu
Arguments:
    enc_model_fpath:   encoder/saved_models/pretrained.pt
    syn_model_dir:     synthesizer/saved_models/logs-pretrained
    voc_model_fpath:   vocoder/saved_models/pretrained/pretrained.pt
    low_mem:           False
    no_sound:          False
    cpu:               True

Running a test of your configuration...

Using CPU for inference.
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "pretrained.pt" trained to step 1564501
Found synthesizer "pretrained" trained to step 278000
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder/saved_models/pretrained/pretrained.pt
Testing your configuration with small inputs.
	Testing the encoder...
	Testing the synthesizer... (loading the model will output a lot of text)
Constructing model: Tacotron
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/synthesizer/models/modules.py:113: LSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/synthesizer/models/modules.py:420: conv1d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv1D` instead.
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/layers/convolutional.py:218: Layer.apply (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/synthesizer/models/modules.py:421: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/synthesizer/models/modules.py:424: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/synthesizer/models/modules.py:234: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py:464: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py:966: Layer.add_variable (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py:970: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:1666: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From ./Real-Time-Voice-Cloning/synthesizer/models/modules.py:304: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
Traceback (most recent call last):
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1654, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 0 for '{{node Tacotron_model/inference/decoder/concat}} = ConcatV2[N=2, T=DT_INT32, Tidx=DT_INT32](Tacotron_model/inference/decoder/concat/values_0, Tacotron_model/inference/decoder/concat/values_1, Tacotron_model/inference/decoder/concat/axis)' with input shapes: [1], [], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_cli.py", line 98, in <module>
    mels = synthesizer.synthesize_spectrograms(texts, embeds)
  File "./Real-Time-Voice-Cloning/synthesizer/inference.py", line 77, in synthesize_spectrograms
    self.load()
  File "./Real-Time-Voice-Cloning/synthesizer/inference.py", line 58, in load
    self._model = Tacotron2(self.checkpoint_fpath, hparams)
  File "./Real-Time-Voice-Cloning/synthesizer/tacotron2.py", line 28, in __init__
    split_infos=split_infos)
  File "./Real-Time-Voice-Cloning/synthesizer/models/tacotron.py", line 218, in initialize
    swap_memory=hp.tacotron_swap_with_cpu)
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/typeguard/__init__.py", line 840, in wrapper
    retval = func(*args, **kwargs)
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow_addons/seq2seq/decoder.py", line 341, in dynamic_decode
    decoder.output_dtype,
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in map_structure
    structure[0], [func(*x) for x in entries],
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow_addons/seq2seq/decoder.py", line 338, in <lambda>
    _prepend_batch(decoder.batch_size, shape), dtype=dtype
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow_addons/seq2seq/decoder.py", line 529, in _prepend_batch
    return tf.concat(([batch_size], shape), axis=0)
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 1606, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1189, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1817, in __init__
    control_input_ops, op_def)
  File "./Real-Time-Voice-Cloning/venv-tensorflow2/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1657, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 1 but is rank 0 for '{{node Tacotron_model/inference/decoder/concat}} = ConcatV2[N=2, T=DT_INT32, Tidx=DT_INT32](Tacotron_model/inference/decoder/concat/values_0, Tacotron_model/inference/decoder/concat/values_1, Tacotron_model/inference/decoder/concat/axis)' with input shapes: [1], [], [].
```

I have attempted to workaround the error by making the last datatype (sample_id) a sequence to raise its rank, but then get this error. Does anyone have any thoughts?

```
Exception has occurred: ValueError
The two structures don't have the same nested structure.

First structure: type=CustomDecoderOutput str=CustomDecoderOutput(rnn_output=160, token_output=2, sample_id=TensorShape([]))

Second structure: type=CustomDecoderOutput str=CustomDecoderOutput(rnn_output=tf.float32, token_output=tf.float32, sample_id=[<class 'numpy.int32'>])
```

**Comment by blue-fish** [comment]
I figured out a solution to the above issue, to use tf.TensorShape().with_rank() to increase the rank as needed. Now working through a different set of errors.

**Comment by dathudeptrai** [comment]
@blue-fish hi, can i contribute my Tensorflow2 tacotron2, our framework also plan to support tflite for TTS model both real-time vocoder and Text2Mel model. Can you take a look our framework ?

github: https://github.com/TensorSpeech/TensorflowTTS
sample audio: https://tensorspeech.github.io/TensorflowTTS/
colab demo: https://colab.research.google.com/drive/1akxtrLZHKuMiQup00tzO2olCaN-y3KiD?usp=sharing

we also supported FastSpeech2 which quality comparable with tacotron2 and much faster.

**Comment by blue-fish** [comment]
@dathudeptrai Yes! That's much better than me trying to convert the existing code to Tensorflow2.

**Comment by dathudeptrai** [comment]
@blue-fish the most important thing is that we need to re-use the pretrained model here so converting the weight to be able to load on my Tacotron2 implementation is the right way :)). My implementation is 90% the same as the tacotron2 implementation here, just need modify some layer and parameter to replicate the model then we can ez to load the pretrained weight here to inference.

**Comment by blue-fish** [comment]
@dathudeptrai I am new to TTS and don't have the expertise to make the changes you are describing. Would you be willing to point out exactly what needs to be changed? Or submit a pull request (working or not) to get us started?

**Comment by DRob81** [comment]
> I figured out a solution to the above issue, to use tf.TensorShape().with_rank() to increase the rank as needed. Now working through a different set of errors.
> 
> Edit: Although it makes that one error go away, I do not know if it is the correct fix so I have not committed it.

Can you tell how you fixed 'Shape must be rank 1 but is rank 0' error?
I guess it is 'batch_size' in line 98 tacotron.py

**Comment by blue-fish** [comment]
@DRob81 Although I solved it once before, it is eluding me this time. I thought I added with_rank() somewhere in synthesizer/models/helpers.py or custom_decoder.py, but it is not working. Thank you for your guess, I inspected `batch_size` in the debugger for tensorflow v1 and v2 and could not find any difference. I still think it is somewhere in the custom decoder, based on the error message.

**Comment by DRob81** [comment]
@blue-fish i also debugged and ended up with batch_size. Glad i found that 
batch_size = -tf.TensorShape(0).with_rank_at_least(1)[0]
is the solution here. Still more problems to fix

**Comment by blue-fish** [comment]
Thanks for sharing that @DRob81 . If I make that change then the next error message is `TypeError: can only concatenate list (not "int") to list` at line 218 of synthesizer/models/tacotron.py . It's hard to tell if it's getting further than before, since that is the same line where it errored out before. It is very hard to debug errors with the custom decoder.

**Comment by DRob81** [comment]
@blue-fish i fixed that already. Can you tell me which line exactly? I think my line numbers differ from yours now.

**Comment by blue-fish** [comment]
I'm unable to get past this part, before or after the last fix: https://github.com/blue-fish/Real-Time-Voice-Cloning/blob/621f62f150f5d0995ce61930479bec9e9043aebe/synthesizer/models/tacotron.py#L212-L218

It might be easier if you fork my repo using these instructions (https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/401#issuecomment-653929209), that would make it easier to share code updates and discuss issues like these.

**Comment by DRob81** [comment]
@blue-fish i forked your repo and i will commit my changes.

**Comment by HumanG33k** [comment]
hi,
keep in mind,
- I too tired to read all things now but tensorflow 1.15 just not work with python 3.8 (at this day) throught pip. 
- I just don’t have cuda and never will i prefer the [opencl](https://en.wikipedia.org/wiki/OpenCL)

I think it can be good for the record to keep one brach tensorflow 1.X and go for a new master based on tensorflow 2. 
I just check and there is an "automatic code updater" provide by tsf. I just execute it. I provide the report. In short what y do :
- do the standard failing install of the repo.
- check my tensorflow version with 
```python
import tensorflow as tf

print(tf.__version__)
```
2.2.0 in my case (debian testing)
Use the following script in the parent directory of the project directory
```bash
#!/bin/bash
tf_upgrade_v2 \
  --intree Real-Time-Voice-Cloning/ \
  --outtree Real-Time-Voice-Cloning_v2/ \
  --reportfile report.txt
```
and will have a bunch of ouput and a 
[report.txt](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/4928730/report.txt)

I just not look at the output or content in report.txt

But for check go in v2 directory, edit the requirement.txt and set  ```tensorflow==2.2.0 ```

retry the pip install to be sure : 
```bash
pip install -r requirements.txt
```
Everythings look satisfied.
No have the time to check more. Feel free to ping me and try to continue that if i have time this week end.

**Comment by blue-fish** [comment]
@HumanG33k I have already performed automatic conversion using that process on the `370_tf2_compat` branch of my fork. There are still a bunch of errors that need to be worked through. I have published fixes for some of these, and getting stuck on some others where @DRob81 is also helping. The current errors are runtime so we may be getting close.

If you can run `demo_cli.py` without errors, please commit those changes to your fork and we can continue developing from there. If not, let's concentrate the effort on my tensorflow2 fork. I am accepting pull requests.

**Comment by blue-fish** [comment]
@DRob81 I would like to continue the tensorflow2 effort, can you please commit your changes or submit a pull request to my fork?

**Comment by javaintheuk** [comment]
Hello, @blue-fish  please how can I add another voice on your colab (I'd like to upload or link it to a 5 - 10 seconds wav sample)? thanks!

https://colab.research.google.com/drive/1akxtrLZHKuMiQup00tzO2olCaN-y3KiD

**Comment by blue-fish** [comment]
We are not going to pursue tensorflow v2 now that the torch-based synthesizer is working (#472). Thanks to all who contributed their time here.
