### ISSUE TITLE
question about linux compatibility

### ISSUE THREAD

**Issue by azamet90** [CorentinJ/Real-Time-Voice-Cloning#377]
is it okay to install this tool to linux?

**Comment by blue-fish** [comment]
Yes, it will run on Linux.

**Comment by azamet90** [comment]
> Yes, it will run on Linux.

thx for answering but my last question is; is it only in english or can we use another languages too?

**Comment by blue-fish** [comment]
To use another language you will need to do some coding and train your own models. Please see #30 .

**Comment by blue-fish** [comment]
Closing this issue as it appears to be resolved. @azamet90 Please reopen this issue if you continue to have additional questions.
