### ISSUE TITLE
i cant install NVIDIA CUDA

### ISSUE THREAD

**Issue by bllurr** [CorentinJ/Real-Time-Voice-Cloning#378]
I can't install NVIDIA CUDA even though I followed everything that [this guide](https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/l) told me to do. I also have tried searching for this problem on the internet, but none of them solves my problem. I also have provided the image of the error [here](https://imgur.com/a/fYkiBYQ).

**Comment by blue-fish** [comment]
Following a recent change, CUDA is no longer a hard requirement and it is possible to run the voice cloning demo without GPU support. Use the --cpu option in demo_cli.py

Questions about CUDA installation should be submitted to a different support channel. Try asking your question in the CUDA setup and installation section of the NVIDIA developer forums: [https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation](https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation)
