### ISSUE TITLE
Synthesizer training: loss exploded, has anybody seen this?

### ISSUE THREAD

**Issue by goodmangu** [CorentinJ/Real-Time-Voice-Cloning#382]
Here is the error: 

in line 220 of Real-Time-Voice-Cloning-master/synthesizer/train.py", line 220
Loss exploded to nan at step 32
Exiting due to exception: Loss exploded

(believe loss=nan is causing this, but how loss ended up with NAN?)

Complete info:

(voice) goodman@goodman-dl-box:~/development/Real-Time-Voice-Cloning-master$ python synthesizer_train.py goodman_run datasets/SV2TTS/synthesizer
Arguments:
    name:                   goodman_run
    synthesizer_root:       datasets/SV2TTS/synthesizer
    models_dir:             synthesizer/saved_models/
    mode:                   synthesis
    GTA:                    True
    restore:                True
    summary_interval:       2500
    embedding_interval:     10000
    checkpoint_interval:    2000
    eval_interval:          100000
    tacotron_train_steps:   2000000
    tf_log_level:           1
    slack_url:              None
    hparams:                

Checkpoint path: synthesizer/saved_models/logs-goodman_run/taco_pretrained/tacotron_model.ckpt
Loading training data from: datasets/SV2TTS/synthesizer/train.txt
Using model: Tacotron
Hyperparameters:
  allow_clipping_in_normalization: True
  attention_dim: 128
  attention_filters: 32
  attention_kernel: (31,)
  cbhg_conv_channels: 128
  cbhg_highway_units: 128
  cbhg_highwaynet_layers: 4
  cbhg_kernels: 8
  cbhg_pool_size: 2
  cbhg_projection: 256
  cbhg_projection_kernel_size: 3
  cbhg_rnn_units: 128
  cleaners: english_cleaners
  clip_for_wavenet: True
  clip_mels_length: True
  cross_entropy_pos_weight: 20
  cumulative_weights: True
  decoder_layers: 2
  decoder_lstm_units: 1024
  embedding_dim: 512
  enc_conv_channels: 512
  enc_conv_kernel_size: (5,)
  enc_conv_num_layers: 3
  encoder_lstm_units: 256
  fmax: 7600
  fmin: 55
  frame_shift_ms: None
  griffin_lim_iters: 60
  hop_size: 200
  mask_decoder: False
  mask_encoder: True
  max_abs_value: 4.0
  max_iters: 2000
  max_mel_frames: 900
  min_level_db: -100
  n_fft: 800
  natural_eval: False
  normalize_for_wavenet: True
  num_mels: 80
  outputs_per_step: 2
  postnet_channels: 512
  postnet_kernel_size: (5,)
  postnet_num_layers: 5
  power: 1.5
  predict_linear: False
  preemphasis: 0.97
  preemphasize: True
  prenet_layers: [256, 256]
  ref_level_db: 20
  rescale: True
  rescaling_max: 0.9
  sample_rate: 16000
  signal_normalization: True
  silence_min_duration_split: 0.4
  silence_threshold: 2
  smoothing: False
  speaker_embedding_size: 256
  split_on_cpu: True
  stop_at_any: True
  symmetric_mels: True
  tacotron_adam_beta1: 0.9
  tacotron_adam_beta2: 0.999
  tacotron_adam_epsilon: 1e-06
  tacotron_batch_size: 36
  tacotron_clip_gradients: True
  tacotron_data_random_state: 1234
  tacotron_decay_learning_rate: True
  tacotron_decay_rate: 0.5
  tacotron_decay_steps: 50000
  tacotron_dropout_rate: 0.5
  tacotron_final_learning_rate: 1e-05
  tacotron_gpu_start_idx: 0
  tacotron_initial_learning_rate: 0.001
  tacotron_num_gpus: 1
  tacotron_random_seed: 5339
  tacotron_reg_weight: 1e-07
  tacotron_scale_regularization: False
  tacotron_start_decay: 50000
  tacotron_swap_with_cpu: False
  tacotron_synthesis_batch_size: 128
  tacotron_teacher_forcing_decay_alpha: 0.0
  tacotron_teacher_forcing_decay_steps: 280000
  tacotron_teacher_forcing_final_ratio: 0.0
  tacotron_teacher_forcing_init_ratio: 1.0
  tacotron_teacher_forcing_mode: constant
  tacotron_teacher_forcing_ratio: 1.0
  tacotron_teacher_forcing_start_decay: 10000
  tacotron_test_batches: None
  tacotron_test_size: 0.05
  tacotron_zoneout_rate: 0.1
  train_with_GTA: False
  trim_fft_size: 512
  trim_hop_size: 128
  trim_top_db: 23
  use_lws: False
  utterance_min_duration: 1.6
  win_size: 800
Loaded metadata for 290550 examples (366.70 hours)
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:424: conv1d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv1D` instead.
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/layers/convolutional.py:218: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:425: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:428: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:238: bidirectional_dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/rnn.py:464: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/contrib/rnn/python/ops/lstm_ops.py:360: Layer.add_variable (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:152: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/goodman/voice/lib/python3.6/site-packages/tensorflow_core/python/ops/rnn.py:244: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:308: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/models/modules.py:272: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
initialisation done /gpu:0
Initialized Tacotron model. Dimensions (? = dynamic shape): 
  Train mode:               True
  Eval mode:                False
  GTA mode:                 False
  Synthesis mode:           False
  Input:                    (?, ?)
  device:                   0
  embedding:                (?, ?, 512)
  enc conv out:             (?, ?, 512)
  encoder out (cond):       (?, ?, 768)
  decoder out:              (?, ?, 80)
  residual out:             (?, ?, 512)
  projected residual out:   (?, ?, 80)
  mel out:                  (?, ?, 80)
  <stop_token> out:         (?, ?)
  Tacotron Parameters       28.439 Million.
initialisation done /gpu:0
Initialized Tacotron model. Dimensions (? = dynamic shape): 
  Train mode:               False
  Eval mode:                True
  GTA mode:                 False
  Synthesis mode:           False
  Input:                    (?, ?)
  device:                   0
  embedding:                (?, ?, 512)
  enc conv out:             (?, ?, 512)
  encoder out (cond):       (?, ?, 768)
  decoder out:              (?, ?, 80)
  residual out:             (?, ?, 512)
  projected residual out:   (?, ?, 80)
  mel out:                  (?, ?, 80)
  <stop_token> out:         (?, ?)
  Tacotron Parameters       28.439 Million.
Tacotron training set to a maximum of 2000000 steps
No model to load at synthesizer/saved_models/logs-goodman_run/taco_pretrained

Generated 64 train batches of size 36 in 10.608 sec
2020-06-26 19:01:40.807582: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once.
Step       1 [12.904 sec/step, loss=16.35126, avg_loss=16.35126]

Saving Model Character Embeddings visualization..
Tacotron Character embeddings have been updated on tensorboard!
Step       2 [6.847 sec/step, loss=15.53714, avg_loss=15.94420]
Step       3 [4.838 sec/step, loss=15.90006, avg_loss=15.92949]
Step       4 [3.857 sec/step, loss=15.50690, avg_loss=15.82384]
Step       5 [3.281 sec/step, loss=16.05422, avg_loss=15.86992]
Step       6 [2.893 sec/step, loss=15.65896, avg_loss=15.83476]
Step       7 [2.662 sec/step, loss=15.95315, avg_loss=15.85167]
Step       8 [2.435 sec/step, loss=15.56872, avg_loss=15.81630]
Step       9 [2.236 sec/step, loss=14.92921, avg_loss=15.71773]
Step      10 [2.175 sec/step, loss=16.66508, avg_loss=15.81247]
Step      11 [2.067 sec/step, loss=15.62867, avg_loss=15.79576]
Step      12 [2.105 sec/step, loss=16.61783, avg_loss=15.86427]
Step      13 [2.043 sec/step, loss=15.61330, avg_loss=15.84496]
Step      14 [1.990 sec/step, loss=15.65932, avg_loss=15.83170]
Step      15 [1.941 sec/step, loss=15.72975, avg_loss=15.82490]
Step      16 [1.907 sec/step, loss=16.01140, avg_loss=15.83656]
Step      17 [1.864 sec/step, loss=16.74607, avg_loss=15.89006]
Step      18 [1.882 sec/step, loss=16.24770, avg_loss=15.90993]
Step      19 [1.858 sec/step, loss=16.09855, avg_loss=15.91986]
Step      20 [1.811 sec/step, loss=15.36602, avg_loss=15.89217]
Step      21 [1.778 sec/step, loss=15.64704, avg_loss=15.88049]
Step      22 [1.755 sec/step, loss=16.20744, avg_loss=15.89535]
Step      23 [1.811 sec/step, loss=15.50780, avg_loss=15.87850]
Step      24 [1.767 sec/step, loss=14.58111, avg_loss=15.82445]
Step      25 [1.779 sec/step, loss=16.41258, avg_loss=15.84797]
Step      26 [1.736 sec/step, loss=14.44029, avg_loss=15.79383]
Step      27 [1.698 sec/step, loss=15.03655, avg_loss=15.76578]
Step      28 [1.668 sec/step, loss=14.68268, avg_loss=15.72710]
Step      29 [1.635 sec/step, loss=14.78862, avg_loss=15.69474]
Step      30 [1.610 sec/step, loss=15.06529, avg_loss=15.67376]
Step      31 [1.645 sec/step, loss=15.35733, avg_loss=15.66355]
Step      32 [1.612 sec/step, loss=nan, avg_loss=nan]
Loss exploded to nan at step 32
Exiting due to exception: Loss exploded
Traceback (most recent call last):
  File "/home/goodman/development/Real-Time-Voice-Cloning-master/synthesizer/train.py", line 220, in train
    raise Exception("Loss exploded")
Exception: Loss exploded
2020-06-26 19:02:20.803409: W tensorflow/core/kernels/queue_base.cc:277] _0_datafeeder/input_queue: Skipping cancelled enqueue attempt with queue not closed

**Comment by blue-fish** [comment]
> `Checkpoint path: synthesizer/saved_models/logs-goodman_run/taco_pretrained/tacotron_model.ckpt`

Are you trying to continue training of the pretrained synthesizer using a dataset that is processed using embeddings from your custom encoder? I wonder if that has anything to do with it.

You can also read related issues at Rayhane-mamah's Tacotron2 repo: [https://github.com/Rayhane-mamah/Tacotron-2/issues?q=loss+exploded](https://github.com/Rayhane-mamah/Tacotron-2/issues?q=loss+exploded) From what I can tell it might be intermittent and you might just need to keep trying.

**Comment by blue-fish** [comment]
@goodmangu Is "loss exploded" still a problem for your synthesizer training? If it is resolved, would you please go ahead and close this issue?
