### ISSUE TITLE
Saving can be supported by scaling float values to int values

### ISSUE THREAD

**Issue by honestabelink** [CorentinJ/Real-Time-Voice-Cloning#39]
Sorry, this should really be just a pull request but I just don't have the time to make a proper implementation for you.

I've been dragging myself through the papers and your thesis. (I'm just a self taught hobbyist trying to squeeze by). Thanks so much for sharing your implementations and models.

I just needed this quickly and saw it was on your todo list :)
Took a bit of googling to _kinda_ find out a way. So I thought I'd leave this here for you and others. (The errors it throws if you don't do this are a bit obtuse and misleading)

Add these and it'll save... Though there's something up a bit. Every now and then there's a clicking. And in general the audio sounds a tad bit different then the playback.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/2ef15c652c8d255e7d37e20209593a5297677ae3/toolbox/ui.py#L143

    import soundfile as sf #pip3 install soundfile

    def float2pcm(self, sig, dtype='int32'):
        i = np.iinfo(dtype)
        abs_max = 2 ** (i.bits - 1)
        offset = i.min + abs_max
        return (sig * abs_max + offset).clip(i.min, i.max).astype(dtype)

    def save(self, wav, sample_rate) :
        data = self.float2pcm(wav)
        sf.write('temp.wav', data, sample_rate)

Then make sure to call the save after generation
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/2ef15c652c8d255e7d37e20209593a5297677ae3/toolbox/__init__.py#L213

    self.ui.save(wav, Synthesizer.sample_rate)

https://stackoverflow.com/a/45032967

Thanks again for your work and time

**Comment by CorentinJ** [comment]
Thank you. However, I already have code to save audio and it's much simpler than that. E.g.: https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/vocoder/audio.py#L21
The TODO is just there to say that I need to put a button in the toolbox that does that.

**Comment by JaeDukSeo** [comment]
Is this hard to do? Is it going to be updated? thank you!
