### ISSUE TITLE
Is there any way to change the language?

### ISSUE THREAD

**Issue by SebyPlays** [CorentinJ/Real-Time-Voice-Cloning#394]
Hey, i have successfully installed it,
And I just wanted to ask if there was any way to 
Change the pronunciation language to German?

**Comment by blue-fish** [comment]
At the very least you will need to modify the synthesizer code, and train new synthesizer and vocoder models. See #30

**Comment by blue-fish** [comment]
Please post any follow-up questions in #30. Closing as a duplicate.
