### ISSUE TITLE
For anyone still having trouble, you can check out my fork and run this project using SageMaker  

### ISSUE THREAD

**Issue by rustygentile** [CorentinJ/Real-Time-Voice-Cloning#398]
Shameless plug: https://github.com/rustygentile/Real-Time-Voice-Cloning

I'm told most of the installation pain has been resolved now that there's CPU support. Still, you might find this useful in case you want to generate a large number of voice files.

**Comment by blue-fish** [comment]
@rustygentile Do you know if training would work with Sagemaker? That could also be another use case.

**Comment by rustygentile** [comment]
> @rustygentile Do you know if training would work with Sagemaker? That could also be another use case.

Yes, that would absolutely be possible. I might take that up now if there's enough interest.

**Comment by blue-fish** [comment]
I am interested in the training use case. Use the repo locally on CPU or low-end GPU for development, then transfer to Sagemaker when everything is working.

In your README.md you mention using `ml.p2.xlarge` which costs $1.26/hour for (4 vCPU + 61 GB mem) + (K80 GPU + 12 GB). On the pricing page there is also an option of using `ml.g4dn.xlarge` which is $0.74/hour for (4 vCPU + 16 GB mem) + (T4 GPU + 16 GB). Which would be preferred here?

**Comment by blue-fish** [comment]
Now that it runs on CPU, inference could run on the same `ml.t2.medium` instance you recommend for installation ($0.0464/hour for 2 vCPU + 4 GB mem). Though I would still recommend getting a GPU instance if playing with the toolbox for more than a few minutes.

**Comment by blue-fish** [comment]
Also for maintainability it might be best to make the Sagemaker version a distinct repo instead of a direct fork, and incorporate files from this repo as a submodule.

**Comment by rustygentile** [comment]
@blue-fish 

> I am interested in the training use case. Use the repo locally on CPU or low-end GPU for development, then transfer to Sagemaker when everything is working.

Sure. It seems there's a demand for it. And I don't think it wouldn't be too much effort for me to get that up and running.

> In your README.md you mention using ml.p2.xlarge which costs $1.26/hour for (4 vCPU + 61 GB mem) + (K80 GPU with 12 GB). On the pricing page there is also an option of using ml.g4dn.xlarge which is $0.74/hour for (4 vCPU + 16 GB mem) + (T4 GPU with 16 GB). Which would be preferred here?

Unfortunately, ml.g4dn.xlarge's won't work for batch transform jobs. Only certain instance types are supported. ml.p2.xlarge is still the cheapest GPU option.

> Now that it runs on CPU, inference could run on the same ml.t2.medium instance you recommend for installation ($0.0464/hour for 2 vCPU + 4 GB mem). Though I would still recommend getting a GPU instance if playing with the toolbox for more than a few minutes.

It would have to be ml.m5.large at $0.134/hour but yeah, still much cheaper than P2's.

> Also for maintainability it might be best to make the Sagemaker version a distinct repo instead of a direct fork, and incorporate files from this repo as a submodule.

I agree that makes more sense, especially now that you're actively maintaining it. Do you have any plans for versioning or distribution with this project? It would be nice if I could grab the files from PyPI and then import it as a library. If I just use whatever the latest files are from the master branch here, there's no way to guarantee they're compatible with my code. I'm open to other suggestions too.

**Comment by blue-fish** [comment]
>  If I just use whatever the latest files are from the master branch here, there's no way to guarantee they're compatible with my code. I'm open to other suggestions too.

I'd suggest that you fork this repo, and for the Sagemaker project to consume the fork. You would manage the fork to maintain compatibility between the two codebases. It also gives you flexibility to implement changes to the RTVC code that make your life easier with Sagemaker.

**Comment by blue-fish** [comment]
I'm cleaning up the issues list, and there hasn't been much discussion on this topic so I'm closing it due to inactivity. Thank you for the contribution @rustygentile .
