### ISSUE TITLE
can't install requirements

### ISSUE THREAD

**Issue by nav1-code** [CorentinJ/Real-Time-Voice-Cloning#4]
Hi guys, I tried to install this tool, following next steps: 
1) Install Python 3.73 
2) Install pip 
3) Run from command line pip install -r requirements.txt 

but I've got the following error: (see below). Could you help me with some suggestion. I don't know python well, but I will very gratefull if your suggestion help me.
Thank you in advance.

C:\Users\admin\Desktop\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-ma
ster>pip install -r requirements.txt
Requirement already satisfied: tensorflow-gpu<=1.14.0,>=1.10.0 in c:\users\admin
\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.
txt (line 1)) (1.13.1)
Requirement already satisfied: umap-learn in c:\users\admin\appdata\local\progra
ms\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (0.3.9)

Requirement already satisfied: visdom in c:\users\admin\appdata\local\programs\p
ython\python37\lib\site-packages (from -r requirements.txt (line 3)) (0.1.8.8)
Collecting webrtcvad (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/89/34/e2de2d97f3288512b9e
a56f92e7452f8207eb5a0096500badf9dfd48f5e6/webrtcvad-2.0.10.tar.gz
Collecting librosa>=0.5.1 (from -r requirements.txt (line 5))
Collecting matplotlib>=2.0.2 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/3b/52/17dbb82ca36937dd4d0
027fe1945c3c78bdb465b4736903d0904b7f595ad/matplotlib-3.1.0-cp37-cp37m-win_amd64.
whl
Requirement already satisfied: numpy>=1.14.0 in c:\users\admin\appdata\local\pro
grams\python\python37\lib\site-packages (from -r requirements.txt (line 7)) (1.1
6.4)
Requirement already satisfied: scipy>=1.0.0 in c:\users\admin\appdata\local\prog
rams\python\python37\lib\site-packages (from -r requirements.txt (line 8)) (1.3.
0)
Collecting tqdm (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/45/af/685bf3ce889ea191f3b
916557f5677cc95a5e87b2fa120d74b5dd6d049d0/tqdm-4.32.1-py2.py3-none-any.whl
Collecting sounddevice (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/7f/15/fd6d923adccc64d2d93
fcffc245bb2471a2509bb2905a89c4fc772ce4e35/sounddevice-0.3.13-py2.py3.cp26.cp27.c
p32.cp33.cp34.cp35.cp36.cp37.cp38.pp27.pp32.pp33.pp34.pp35.pp36-none-win_amd64.w
hl
Requirement already satisfied: protobuf>=3.6.1 in c:\users\admin\appdata\local\p
rograms\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0-
>-r requirements.txt (line 1)) (3.8.0)
Requirement already satisfied: wheel>=0.26 in c:\users\admin\appdata\local\progr
ams\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r
requirements.txt (line 1)) (0.33.4)
Requirement already satisfied: tensorboard<1.14.0,>=1.13.0 in c:\users\admin\app
data\local\programs\python\python37\lib\site-packages (from tensorflow-gpu<=1.14
.0,>=1.10.0->-r requirements.txt (line 1)) (1.13.1)
Requirement already satisfied: six>=1.10.0 in c:\users\admin\appdata\local\progr
ams\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r
requirements.txt (line 1)) (1.12.0)
Requirement already satisfied: astor>=0.6.0 in c:\users\admin\appdata\local\prog
rams\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r
 requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\admin\appdata\local\
programs\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0
->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\admin\appd
ata\local\programs\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.
0,>=1.10.0->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\admin\appdata\local\pro
grams\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-
r requirements.txt (line 1)) (1.21.1)
Requirement already satisfied: keras-applications>=1.0.6 in c:\users\admin\appda
ta\local\programs\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.0
,>=1.10.0->-r requirements.txt (line 1)) (1.0.8)
Requirement already satisfied: tensorflow-estimator<1.14.0rc0,>=1.13.0 in c:\use
rs\admin\appdata\local\programs\python\python37\lib\site-packages (from tensorfl
ow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (1.13.0)
Requirement already satisfied: absl-py>=0.1.6 in c:\users\admin\appdata\local\pr
ograms\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->
-r requirements.txt (line 1)) (0.7.1)
Requirement already satisfied: gast>=0.2.0 in c:\users\admin\appdata\local\progr
ams\python\python37\lib\site-packages (from tensorflow-gpu<=1.14.0,>=1.10.0->-r
requirements.txt (line 1)) (0.2.2)
Requirement already satisfied: scikit-learn>=0.16 in c:\users\admin\appdata\loca
l\programs\python\python37\lib\site-packages (from umap-learn->-r requirements.t
xt (line 2)) (0.21.2)
Requirement already satisfied: numba>=0.37 in c:\users\admin\appdata\local\progr
ams\python\python37\lib\site-packages (from umap-learn->-r requirements.txt (lin
e 2)) (0.44.0)
Requirement already satisfied: tornado in c:\users\admin\appdata\local\programs\
python\python37\lib\site-packages (from visdom->-r requirements.txt (line 3)) (6
.0.2)
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs
\python\python37\lib\site-packages (from visdom->-r requirements.txt (line 3)) (
2.22.0)
Requirement already satisfied: websocket-client in c:\users\admin\appdata\local\
programs\python\python37\lib\site-packages (from visdom->-r requirements.txt (li
ne 3)) (0.56.0)
Requirement already satisfied: torchfile in c:\users\admin\appdata\local\program
s\python\python37\lib\site-packages (from visdom->-r requirements.txt (line 3))
(0.1.0)
Requirement already satisfied: pillow in c:\users\admin\appdata\local\programs\p
ython\python37\lib\site-packages (from visdom->-r requirements.txt (line 3)) (6.
0.0)
Requirement already satisfied: pyzmq in c:\users\admin\appdata\local\programs\py
thon\python37\lib\site-packages (from visdom->-r requirements.txt (line 3)) (18.
0.1)
Collecting decorator>=3.0.0 (from librosa>=0.5.1->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0
dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting resampy>=0.2.0 (from librosa>=0.5.1->-r requirements.txt (line 5))
Requirement already satisfied: joblib>=0.12 in c:\users\admin\appdata\local\prog
rams\python\python37\lib\site-packages (from librosa>=0.5.1->-r requirements.txt
 (line 5)) (0.13.2)
Collecting audioread>=2.0.0 (from librosa>=0.5.1->-r requirements.txt (line 5))
Collecting python-dateutil>=2.1 (from matplotlib>=2.0.2->-r requirements.txt (li
ne 6))
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57
f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any
.whl
Collecting cycler>=0.10 (from matplotlib>=2.0.2->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af69644
0ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=2.0.2->-r
requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e2576
9976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=2.0.2->-r requirements.txt (line
6))
  Using cached https://files.pythonhosted.org/packages/c6/ea/e5474014a13ab2dcb50
56608e0716c600c3d8a8bcffb10ed55ccd6a42eb0/kiwisolver-1.1.0-cp37-none-win_amd64.w
hl
Collecting CFFI>=1.0 (from sounddevice->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/2f/ad/9722b7752fdd88c858b
e57b47f41d1049b5fb0ab79caf0ab11407945c1a7/cffi-1.12.3-cp37-cp37m-win_amd64.whl
Requirement already satisfied: setuptools in c:\users\admin\appdata\local\progra
ms\python\python37\lib\site-packages (from protobuf>=3.6.1->tensorflow-gpu<=1.14
.0,>=1.10.0->-r requirements.txt (line 1)) (40.8.0)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\admin\appdata\local
\programs\python\python37\lib\site-packages (from tensorboard<1.14.0,>=1.13.0->t
ensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (0.15.4)
Requirement already satisfied: markdown>=2.6.8 in c:\users\admin\appdata\local\p
rograms\python\python37\lib\site-packages (from tensorboard<1.14.0,>=1.13.0->ten
sorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: h5py in c:\users\admin\appdata\local\programs\pyt
hon\python37\lib\site-packages (from keras-applications>=1.0.6->tensorflow-gpu<=
1.14.0,>=1.10.0->-r requirements.txt (line 1)) (2.9.0)
Requirement already satisfied: mock>=2.0.0 in c:\users\admin\appdata\local\progr
ams\python\python37\lib\site-packages (from tensorflow-estimator<1.14.0rc0,>=1.1
3.0->tensorflow-gpu<=1.14.0,>=1.10.0->-r requirements.txt (line 1)) (3.0.5)
Requirement already satisfied: llvmlite>=0.29.0 in c:\users\admin\appdata\local\
programs\python\python37\lib\site-packages (from numba>=0.37->umap-learn->-r req
uirements.txt (line 2)) (0.29.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\use
rs\admin\appdata\local\programs\python\python37\lib\site-packages (from requests
->visdom->-r requirements.txt (line 3)) (1.25.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\loca
l\programs\python\python37\lib\site-packages (from requests->visdom->-r requirem
ents.txt (line 3)) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\admin\appdata\local\pr
ograms\python\python37\lib\site-packages (from requests->visdom->-r requirements
.txt (line 3)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\admin\appdata\l
ocal\programs\python\python37\lib\site-packages (from requests->visdom->-r requi
rements.txt (line 3)) (3.0.4)
Collecting pycparser (from CFFI>=1.0->sounddevice->-r requirements.txt (line 10)
)
Building wheels for collected packages: webrtcvad
  Building wheel for webrtcvad (setup.py) ... error
  ERROR: Complete output from command 'c:\users\admin\appdata\local\programs\pyt
hon\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Us
ers\\admin\\AppData\\Local\\Temp\\pip-install-iqkryxja\\webrtcvad\\setup.py'"'"'
;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'
\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))
' bdist_wheel -d 'C:\Users\admin\AppData\Local\Temp\pip-wheel-7ewjy9xx' --python
-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying webrtcvad.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_webrtcvad' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
Failed to build webrtcvad
Installing collected packages: webrtcvad, decorator, resampy, audioread, librosa
, python-dateutil, cycler, pyparsing, kiwisolver, matplotlib, tqdm, pycparser, C
FFI, sounddevice
  Running setup.py install for webrtcvad ... error
    ERROR: Complete output from command 'c:\users\admin\appdata\local\programs\p
ython\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\
Users\\admin\\AppData\\Local\\Temp\\pip-install-iqkryxja\\webrtcvad\\setup.py'"'
"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'
"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'
))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-t598pe1f\inst
all-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying webrtcvad.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_webrtcvad' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command "'c:\users\admin\appdata\local\programs\python\python37\python.ex
e' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\admin\\AppData\\L
ocal\\Temp\\pip-install-iqkryxja\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '
"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"
');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:
\Users\admin\AppData\Local\Temp\pip-record-t598pe1f\install-record.txt' --single
-version-externally-managed --compile" failed with error code 1 in C:\Users\admi
n\AppData\Local\Temp\pip-install-iqkryxja\webrtcvad\

**Comment by CorentinJ** [comment]
This is a shitty error you will meet on windows with python packages that require compilation. Usually you can find precompiled binaries for these but in this case it's the `webrtcvad` package and I haven't found any myself. You have to fix that yourself.

You need to keep trying to install webrtcvad until you manage to do it, then you can reinstall all the requirements to make sure you have them all. So the command is `pip install webrtcvad`. It will give you the same error that appears at the end of the error message you pasted here:

```
ERROR: running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.7
copying webrtcvad.py -> build\lib.win-amd64-3.7
running build_ext
building '_webrtcvad' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```

See [this thread](https://github.com/benfred/implicit/issues/76) to find the build tools. It's a bit of a pain to install. Check the other answers until that solves it. Then try to install webrtcvad again. 

If after that you get "LINK : fatal error LNK1158: cannot run 'rc.exe'", check [this](https://forum.qt.io/topic/90839/lnk1158-cannot-run-rc-exe/2).

**Comment by nav1-code** [comment]
Thank you @CorentinJ, it works fine. Firstly I installed [BuldTools](https://github.com/felixrieseberg/windows-build-tools#examples-of-modules-supported) , and then webrtcvad and after that I ran pip install -r requirements.txt

**Comment by blacksocket** [comment]
Hi I am having similar issue but during the installation in Linux Ubuntu:

![image](https://user-images.githubusercontent.com/13651344/69082285-15507300-0a40-11ea-851a-f78f04ef94cb.png)
and
![image](https://user-images.githubusercontent.com/13651344/69082316-25685280-0a40-11ea-81b7-63a33f0ca985.png)

**Comment by sandika-biswas** [comment]
> Hi, I am having similar issue but during the installation in Linux Ubuntu:
> 
> ![image](https://user-images.githubusercontent.com/13651344/69082285-15507300-0a40-11ea-851a-f78f04ef94cb.png)
> and
> ![image](https://user-images.githubusercontent.com/13651344/69082316-25685280-0a40-11ea-81b7-63a33f0ca985.png)

I am facing same issue..please suggest how to resolve it.

**Comment by sarah-q17** [comment]
> Thank you @CorentinJ, it works fine. Firstly I installed BuldTools , and then webrtcvad and after that I ran pip install -r requirements.txt

Hi, I done with the BuildTools and also webrtcvad and it works. But still I can't run pip install -r requirements.txt

can help?

**Comment by himanshisyadav** [comment]
Have the same issue. Any solutions?

**Comment by mbdash** [comment]
Please visit the new Wiki.
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki

I highly recommend Ubuntu 18 or 20 and miniconda3.
cheers.
