### ISSUE TITLE
List of pretrained models available for download

### ISSUE THREAD

**Issue by blue-fish** [CorentinJ/Real-Time-Voice-Cloning#400]
This issue will be used to provide a listing of pretrained models that are freely available to use (resolves #268).

**Comment by blue-fish** [comment]
Will turn this into a table at a later time. If I missed a model please let me know and I will add it!

### English
* @CorentinJ default pretrained models: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models
    * @blue-fish vocoder model (compatible with default model, extends the above vocoder to 1159k steps): https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-650531957
        * Better at reducing sound arti@facts than the default vocoder (https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-650549809)
* @sberryman models: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-536097366 (hparams: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-573523609)
    * Sound quality is good but cloned voices do not resemble reference audio (https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-604999848)

### Multi-language
* @sberryman mixed encoder: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-535936275

### Chinese
* @KuangDD (Uses zhrtvc fork at https://github.com/KuangDD/zhrtvc) (https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/30#issuecomment-629979383)

### Swedish
* @ViktorAlm (Uses https://github.com/codemandosch/taco2swe synthesizer), see #257 for model

**Comment by blue-fish** [comment]
The list is still being maintained at this time. It is closed to avoid cluttering the issues list.

**Comment by mennatallah644** [comment]
is there arabic model?

**Comment by mennatallah644** [comment]
@blue-fish 
are these the most updated pretrained models?

**Comment by blue-fish** [comment]
@mennatallah644 The list is up-to-date. There are no Arabic pretrained models at this time.

**Comment by mennatallah644** [comment]
i tried to use @sberryman pretrained models but it give me this error
![error](https://user-images.githubusercontent.com/32370077/98085653-4eb70400-1e86-11eb-920c-4a4ed2447f95.PNG)

**Comment by babysor** [comment]
> @mennatallah644 The list is up-to-date. There are no Arabic pretrained models at this time.

It seems the link to the Chinese model is now broken.
