### ISSUE TITLE
Would you like to add support for tensorflow2

### ISSUE THREAD

**Issue by Arryboom** [CorentinJ/Real-Time-Voice-Cloning#408]
Thanks for your great work at first!  but now tensorflow2 has a bunch upgrade,would you like to add support for it?

**Comment by blue-fish** [comment]
We have an issue for this in #370. Would like to either upgrade the synthesizer to tensorflow2, or switch to a pytorch-based synthesizer. (The synthesizer is the only part that uses TF.) It would be appreciated if you would contribute your help to add tensorflow2 support.

I am going to close this issue, if you have anything further to say on the issue please do so in #370.
