### ISSUE TITLE
poor performance in compare to the main paper?

### ISSUE THREAD

**Issue by amintavakol** [CorentinJ/Real-Time-Voice-Cloning#411]
Hi,
For those of you who are working with this repo to synthesize different voices;
Have you noticed a huge difference between the voices generated by this repo and the samples released by the main paper [here](https://google.github.io/tacotron/publications/speaker_adaptation/)?
If yes, let's discuss and find out the reason(s).

**Comment by blue-fish** [comment]
I would recommend reading #41 and the first few posts of #126 for some context. The main points as I understand them:

* SV2TTS authors trained speaker encoder to 50M steps, this one is just over 1M.
* SV2TTS authors used embedding size of 768, this one uses 256.
* SV2TTS authors used a larger, proprietary dataset for encoder training which gets better results.

> The speaker encoder was trained on a proprietary voice search corpus containing 36M utterances with median duration of 3.9 seconds from 18K English speakers in the United States. This dataset is not transcribed, but contains anonymized speaker identities. It is never used to train synthesis networks.

![image](https://user-images.githubusercontent.com/67130644/87026713-f77f7c00-c190-11ea-80c3-7ad481fef3ad.png)

**Comment by CorentinJ** [comment]
Don't forget this too:

> This issue of large gaps is something that also occurred at Resemble.AI, and that I have worked on and fixed. It's a serious amount of work, I'll give you the big lines:
> 
> * Use LibriTTS instead of LibriSpeech in order to have punctuation.
> * LibriTTS needs to be curated of speakers with bad prosody.
> * You can lower the upper bound I put on utterance duration, which I suspect has for effect of removing long utterances that are more likely to have more pauses (I formally evaluated models trained this way to generate less frequent long pauses). It also trains faster and does not have drawbacks (with a good attention paradigm, the model can generate longer sentences than seen in training).
> * The attention paradigm needs to be replaced, forward attention is poor.
> * If the attention paradigm holds prosody-specific parameters, it may be complemented with a speaker embedding mechanism

https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/364#issuecomment-653996443

**Comment by CorentinJ** [comment]
At Resemble.AI we also have better results by using a new vocoder that my colleague @fatchord developed. I believe he's about to publish the paper he wrote about it.

**Comment by blue-fish** [comment]
We can reduce artifacts in the vocoder with additional training (https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-650549809) . However, it does not make a perceptible difference in the cloned voice. This result also suggests that to the extent the vocoder has an impact on the output quality, we are reaching the limits of what is possible with WaveRNN.

**Comment by winterfate** [comment]
> At Resemble.AI we also have better results by using a new vocoder that my colleague @fatchord developed. I believe he's about to publish the paper he wrote about it.

Absolutely astounding what you're all doing at Resemble, as well. Saw the LTT videos done in cooperation with you lot as well; was very happy to see some publicity in front of the average tech nerd.

**Comment by CorentinJ** [comment]
Yeah and the LTT video is using models dating from january, our sound quality has way improved since
