### ISSUE TITLE
New Audio Issue: Assertion Failed

### ISSUE THREAD

**Issue by kyukenmyo** [CorentinJ/Real-Time-Voice-Cloning#420]
This was working yesterday fine, and no big changes were made. 
However, today starting up the demo toolbox loaded:
Assertion failed!

Program: C:\Users\paul1\AppData\Local\Programs\Python\Python37\python.exe
File: src/hostapi/wdmks/pa_win_wdmks.c, Line 1061

Expression: FALSE

I have tried reinstalling visual studio as well, but to no avail. Any thoughts on this would be deeply appreciated.

**Comment by blue-fish** [comment]
1. How far do you get starting up the toolbox?
2. Can you post the error message and full traceback?

**Comment by blue-fish** [comment]
Doing a quick search on the error message, it looks like a problem with sounddevice (or portaudio)... if you start python and type `import sounddevice`, does that command give the same error message?

One possible resolution (found [here](https://stackoverflow.com/questions/62412684)):
1. Download a sounddevice .whl file here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#sounddevice
    * Likely `sounddevice‑0.3.15‑cp37‑cp37m‑win_amd64.whl` based on your python and OS.
2. `pip uninstall sounddevice`
3. `pip install sounddevice-0.3.15-cp37-cp37m-win_amd64.whl`

If that does not solve your issue, check this out: https://github.com/spatialaudio/python-sounddevice/issues/7 ... I didn't read all of it but it seems like uninstalling and reinstalling sounddevice is the resolution. You could ask there if you continue to have issues with sounddevice.

**Comment by kyukenmyo** [comment]
This worked~ not sure why sounddevice has moments of weird dastardliness at times. My friend was also experiencing this issue, and an update to his nvidia hd driver actually fixed it for him. My guess is it reset sounddevice somehow as well. All in all, thanks for the help and let's keep on going!!
