### ISSUE TITLE
Tensorflow.contrib file missing  what to do

### ISSUE THREAD

**Issue by ash1407** [CorentinJ/Real-Time-Voice-Cloning#425]

**Comment by ash1407** [comment]
i tried to in istall TF14.0 and 15.0 but i as not able to install.

**Comment by blue-fish** [comment]
The current version of the code requires Tensorflow 1.15. If you are having trouble installing it, try setting up a Python virtual environment.

**Comment by ash1407** [comment]
i tried virtual env and in there i tried to install Tensorflow 1.15 but i failed

**Comment by ash1407** [comment]
> 
> 
> The current version of the code requires Tensorflow 1.15. If you are having trouble installing it, try setting up a Python virtual environment.

i tried virtual env and in there i tried to install Tensorflow 1.15 but i failed

**Comment by blue-fish** [comment]
Please make sure you are using a supported version of Python (README.md specifies this as 3.6 or 3.7) and try the Tensorflow 1.15 installation again. As noted in #401 , Python 3.8+ only supports Tensorflow 2.x which is not compatible with the toolbox.

**Comment by ash1407** [comment]
> 
> 
> Please make sure you are using a supported version of Python (README.md specifies this as 3.6 or 3.7) and try the Tensorflow 1.15 installation again. As noted in #401 , Python 3.8+ only supports Tensorflow 2.x which is not compatible with the toolbox.

Thanks friend problem got solved .from your advice.

**Comment by blue-fish** [comment]
@ash1407 Thanks for confirming that the root cause is a Python version issue.
