### ISSUE TITLE
pytorch is failing to install

### ISSUE THREAD

**Issue by ash1407** [CorentinJ/Real-Time-Voice-Cloning#426]
![11](https://user-images.githubusercontent.com/68329823/87601170-2d34df80-c712-11ea-8fe1-aa7c58c2a1a3.JPG)

using 3.7 python,

**Comment by blue-fish** [comment]
You need to update your pip. After that it will be able to find the latest torch.

```
pip install pip --upgrade
```

**Comment by ash1407** [comment]
> 
> 
> You need to update your pip. After that it will be able to find the latest torch.
> 
> ```
> pip install pip --upgrade
> ```

Thanks friend it also helped me .1)upgraded it  2)than i used this  pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl  . than it worked

**Comment by blue-fish** [comment]
@ash1407 Good to know that this is resolved. Thanks for posting the solution that worked for you.
