### ISSUE TITLE
Windows 10 - DLL Error

### ISSUE THREAD

**Issue by gfhsrtras** [CorentinJ/Real-Time-Voice-Cloning#428]
I've been stuck on this step for 2 days and I know people have posted this problem before, but the answers have not been too helpful to me considering I am retarded, technologically speaking. Anyway, when I type:

> python demo_cli.py

I am returned with:

> Traceback (most recent call last):
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "demo_cli.py", line 4, in <module>
>     from synthesizer.inference import Synthesizer
>   File "C:\Users\hugow\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
>     from synthesizer.tacotron2 import Tacotron2
>   File "C:\Users\hugow\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
>     from synthesizer.models import create_model
>   File "C:\Users\hugow\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
>     from .tacotron import Tacotron
>   File "C:\Users\hugow\Downloads\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 1, in <module>
>     import tensorflow as tf
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
>     from tensorflow_core import *
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
>     module = self._load()
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
>     module = _importlib.import_module(self.__name__)
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Users\hugow\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
> 

Please, If you have anything to help, can you literally spell it out for me because I cannot stress enough that I have no idea what I'm doing. Thanks.

**Comment by blue-fish** [comment]
There is not enough info to determine a root cause of the DLL error. For some possibilities see https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156 . This is a tensorflow installation issue and you should request assistance at [https://github.com/tensorflow/tensorflow/issues](https://github.com/tensorflow/tensorflow/issues) . Mention that you require version 1.15 specifically.

> I cannot stress enough that I have no idea what I'm doing.

You are not the target audience for this project, it is a research code and not a finished product. It happens to be very user-friendly as far as research codes go, but may cause frustration if you do not have any relevant computer experience. I commend you for trying, but you may want to wait for the compiled version (#267) which is in work.

**Comment by gfhsrtras** [comment]
Ok thanks. I guess I will just wait for the .exe

**Comment by blue-fish** [comment]
@gfhsrtras I'm not sure on the status on the exe, if you don't want to wait for it another option is to run it in an Amazon Sagemaker notebook, see #398 .
