### ISSUE TITLE
A question about Celeb datasets and process.

### ISSUE THREAD

**Issue by pnwseeker** [CorentinJ/Real-Time-Voice-Cloning#43]
I was able to get this repo working pretty well and even tested out my own voice with a few utterances and using the libra 100 data set.  However I would like to get better results and wish to attempt to use the other data sets.  I noticed that the librispeech data sets all extracted as you say in the Librispeech folde as expected ; however when i downloaded the VoxCeleb datasets the files in the zip files consist of folders in each zip file and then it has files named ***_dev_wav_partaa  etc.

My question is in VoxCeleb1  do I extract and dump everything under the VoxCeleb1 folder? Where do I put the txt files?  

You have done a spectacular job with this and you deserve a medal.  I am just a bit confused as to how to extract these VoxCeleb datasets. 

One more question.  Once I get all the data sets installed.   What is the step by step process to creating a model of my own voice?  Do i create a bunch of utterances in toolbox and insert a bunch of utterances from datasets and then click the sythesise and vocode?   What is the best method and approach.   I am sorry for asking so many questions that perhaps you think are obvious but I really am just now learning about how to use this type of stuff and I am eager to know more.  This is more of hobby for me

**Comment by CorentinJ** [comment]
Thanks. You're supposed to gather all the parts of each VoxCeleb dataset, than you can extract them as if it was one big zip file. It's a feature of zip for large archives to allow you to split them in multiple sub archives.

As for how the training works, no, you're supposed to run the scripts. The toolbox is just for demonstration purposes. Refer to the [wiki](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training).
