### ISSUE TITLE
demo_clie.py error

### ISSUE THREAD

**Issue by Mazlak** [CorentinJ/Real-Time-Voice-Cloning#430]
ım open directory and use python demo_cli.py and it result like this 

![Untitled](https://user-images.githubusercontent.com/68504604/87875913-1ece1880-c9dd-11ea-8fcc-99b35dfa8be6.png)
how can ı fix it

**Comment by blue-fish** [comment]
Here is the solution for NoBackendError: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-660647785

If you followed the instructions in README.md, ffmpeg should already be installed and all you need to do is edit the environment variables to add them to path.
