### ISSUE TITLE
I would like to sing in polish language instead of text

### ISSUE THREAD

**Issue by annaskarzynska** [CorentinJ/Real-Time-Voice-Cloning#434]
Is this tool able to "render" singing voice based on my voice? (not by typing text)
I would like to sound like some other person. so, basically train model with some other speech -> I am recording my song with my voice -> generate singing voice like some other else. It doesn't need to be "perfect", I want it just to sound like someone else.

Is that possible? How?

**Comment by blue-fish** [comment]
@annaskarzynska You seem to be describing voice style transfer, here are some examples of repositories that do this. It will take a lot of work to train a model to do what you are proposing.

* https://github.com/auspicious3000/autovc ([audio samples](https://auspicious3000.github.io/autovc-demo/))
* https://github.com/mazzzystar/randomCNN-voice-transfer ([sample1](https://soundcloud.com/mazzzystar/sets/stairway2nightcall), [sample2](https://soundcloud.com/mazzzystar/sets/speech-conversion-sample))
* https://github.com/andabi/deep-voice-conversion ([audio samples](https://soundcloud.com/andabi/sets/voice-style-transfer-to-kate-winslet-with-deep-neural-networks))

**Comment by annaskarzynska** [comment]
Thanks you so much! That's exactly what I am looking for :)

**Comment by blue-fish** [comment]
Also see https://github.com/NVIDIA/mellotron ([samples](https://nv-adlr.github.io/Mellotron)), it can make "singing text".

It works like this: first, you train mellotron on someone else's voice to develop a text-to-speech model. When you synthesize new speech from that model, condition the output using your singing voice to make it sing.
