### ISSUE TITLE
umap no attribute

### ISSUE THREAD

**Issue by Mazlak** [CorentinJ/Real-Time-Voice-Cloning#435]
ı add couple of flac file but its stuck it 1 more points and its every time sad to me umap has no attribute umap and second questionhow can ı use synthesize , vocoder and encoder trainer 
![Capture](https://user-images.githubusercontent.com/68504604/88093538-d0ff0f00-cb9a-11ea-949f-af40d2318bc1.PNG)

**Comment by blue-fish** [comment]
Hi @Mazlak . Can you copy and paste the full traceback from your terminal?

**Comment by blue-fish** [comment]
Here are the instructions for training: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training

**Comment by blue-fish** [comment]
This might help resolve the umap issue: https://github.com/lmcinnes/umap/issues/24#issuecomment-346438635
