### ISSUE TITLE
InvalidArgumentError: 2 root error(s) found.   (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,4,512] vs. shape[1] = [2,4,256]

### ISSUE THREAD

**Issue by GauriDhande** [CorentinJ/Real-Time-Voice-Cloning#440]
I get the following error while running demo_toolbox_collab.ipynb. This error occurs when tacotron model is loaded

```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,4,512] vs. shape[1] = [2,4,256]
	 [[node Tacotron_model/inference/concat (defined at /home/Work/Real-Time-Voice-Cloning/synthesizer/models/tacotron.py:158) ]]
	 [[Tacotron_model/inference/Reshape_3/_267]]
  (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [1,4,512] vs. shape[1] = [2,4,256]
	 [[node Tacotron_model/inference/concat (defined at /home/Work/Real-Time-Voice-Cloning/synthesizer/models/tacotron.py:158) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node Tacotron_model/inference/concat:
 Tacotron_model/inference/Tile (defined at /home/Work/Real-Time-Voice-Cloning/synthesizer/models/tacotron.py:157)	
 Tacotron_model/inference/encoder_LSTM/concat (defined at /home/Work/Real-Time-Voice-Cloning/synthesizer/models/modules.py:238)

Input Source operations connected to node Tacotron_model/inference/concat:
 Tacotron_model/inference/Tile (defined at /home/Work/Real-Time-Voice-Cloning/synthesizer/models/tacotron.py:157)	
 Tacotron_model/inference/encoder_LSTM/concat (defined at /home/Work/Real-Time-Voice-Cloning/synthesizer/models/modules.py:238)
```

Can anyone please help? 
Thanks in advance.

**Comment by blue-fish** [comment]
Hi, I am sorry to hear that you are having difficulties with the toolbox. Unfortunately the best I can offer is this form response from https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-663577257

> ### All questions about Colab Notebook
> 
> The Colab Notebook is a community-developed resource to enable users to run the toolbox without having a GPU or going through a complicated setup. Recently, these issues have been resolved with CPU support being added (#366) and the installation process streamlined (#375). **We recommend that you use a normal Python environment.**
> 
> Users who still prefer using Colab Notebook should understand that no official support will be provided, though you are welcome to ask questions to get help from the community. If you believe you've found a bug with the underlying toolbox code, please try to replicate the issue in a normal Python environment. We are not Colab Notebook users and are unable to troubleshoot Colab Notebook errors.
