### ISSUE TITLE
How can i pass a root directory for datasets ? 

### ISSUE THREAD

**Issue by FulvioZozix** [CorentinJ/Real-Time-Voice-Cloning#443]
datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    low_mem:          False

Warning: you did not pass a root directory for datasets as argument.

When i open the toolbox,i can't add any projections,pls help

**Comment by mbdash** [comment]
use arguments 
-d 
or 
--datasets_root

ie:
_windows:_
python demo_toolboc.py --datasets_root d:/RTVC/datasets/train-clean-360

_ubuntu:_
python demo_toolboc.py --datasets_root /home/myuser/RTVC/datasets/train-clean-360

**Comment by blue-fish** [comment]
You need to load an audio file and/or synthesize at least 4 times until the projections will be shown.

Click the "browse" button to load a file. An embedding will be calculated. Once you have this you can synthesize your own speech.

**Comment by blue-fish** [comment]
@FulvioZozix If this did not solve your issue, please reopen it. Thanks @mbdash for answering the part about datasets.
