### ISSUE TITLE
Catch NoBackendError exception and tell user to install ffmpeg

### ISSUE THREAD

**Issue by blue-fish** [CorentinJ/Real-Time-Voice-Cloning#446]
Despite instructions to install ffmpeg in README.md (#414), people still skip it and get audioread's NoBackendError whenever trying to load mp3s. The exception is confusing to the end user and we get a lot of questions about it.

* The error message looks like this: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/386#issue-646643932
* What people need to do to resolve it is this: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-660647785

Here are some options for dealing with it, sorted in ascending order of preference.

### Option 1: Catch it when it occurs
This would make a nice starter issue for someone who is just getting started with python:

In demo_cli.py and demo_toolbox.py,
1. Use try/except around librosa.load()
    * [Lines 132-138 of demo_cli.py](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/054f16ecc186d8d4fa280a890a67418e6b9667a8/demo_cli.py#L132-L138)
    * [Lines 153-156 of toolbox/\_\_init\_\_.py](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/054f16ecc186d8d4fa280a890a67418e6b9667a8/toolbox/__init__.py#L153-L156)
2. Catch the NoBackendError exception (this will require you to import NoBackendError from audioread.exceptions)
3. Print a helpful error message instructing the user to install ffmpeg for mp3 support.

### Option 2: Test for mp3 support as toolbox is loaded
This is a little more advanced, but I think this is preferred.
1. As the toolbox is opened, or when demo_cli.py is started, we either use librosa.load() or audioread.audio_open() on a sample mp3 file to test the capability.
2. If we catch NoBackendError we nag the user and tell them to either install ffmpeg, or rerun the toolbox with `--no_mp3_support`
3. The `--no_mp3_support` flag disallows loading of mp3s when one is selected, preventing NoBackendError from being encountered.

### Option 3: Check for ffmpeg backend as toolbox is loaded
Although other backends are able to open mp3, we can force a check for Windows users to see if they followed the instructions and installed ffmpeg. Then do the same nag as option 2 if not detected.

audioread.ffdec.available() can test for ffmpeg availability: [audioread/ffdec.py](https://github.com/beetbox/audioread/blob/master/audioread/ffdec.py)

Take a look at [audioread/\_\_init\_\_.py](https://github.com/beetbox/audioread/blob/master/audioread/__init__.py) and see how it raises NoBackendError. The code is extremely simple.

### Option 4: Contribute to audioread to make the error message more descriptive
https://github.com/beetbox/audioread/issues/104

**Comment by blue-fish** [comment]
This is resolved by #517. Thank you for the contribution @ramalamadingdong .

**Comment by ramalamadingdong** [comment]
Thanks for the support!
