### ISSUE TITLE
Projections points stuck in 4

### ISSUE THREAD

**Issue by FulvioZozix** [CorentinJ/Real-Time-Voice-Cloning#448]
help,my projections points never changes,i add vocoder and Synthesizer,but still in 4...i need download something ?

**Comment by blue-fish** [comment]
What happens when you load a file? Does the embedding and mel spectrogram display?

Can you post a screenshot?

**Comment by FulvioZozix** [comment]
![print toolbox 2](https://user-images.githubusercontent.com/68534383/88445709-d8245800-cdfa-11ea-9049-0b3a4abb133d.png) 

and the projections are stuck in 4...

**Comment by blue-fish** [comment]
This is the code that prints "4 more points":
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/054f16ecc186d8d4fa280a890a67418e6b9667a8/toolbox/ui.py#L99-L111

Try commenting these lines out and see if it makes a difference:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/054f16ecc186d8d4fa280a890a67418e6b9667a8/toolbox/__init__.py#L118-L119

I do not know what else could be clearing `self.utterances` in the toolbox.

Can you do a `pip freeze` and share the output? You might have some incompatible package versions.

**Comment by blue-fish** [comment]
Any updates @FulvioZozix ? If I had to guess you might need to upgrade your matplotlib version.

**Comment by blue-fish** [comment]
I hope this is now resolved, but if not, feel free to reopen the issue when you have more information that will allow us to continue troubleshooting.

**Comment by blue-fish** [comment]
This bug is confirmed, we will be tracking and fixing it in #455. Thank you for submitting the report @FulvioZozix .
