### ISSUE TITLE
demo_cly.py : TypeError("argument of type 'WindowsPath' is not iterable")

### ISSUE THREAD

**Issue by git-davi** [CorentinJ/Real-Time-Voice-Cloning#45]
Every time I try a filepath in demo_cli.py I get the same error:
Caught exception: TypeError("argument of type 'WindowsPath' is not iterable")

I don't know what am I doing wrong.
How should be the filepath formatted?

PS -> demo_toolbox.py is 100% working.

**Comment by CorentinJ** [comment]
What do you give as input?

**Comment by git-davi** [comment]
I tried every type of path.
From windows like to unix like.

Absolut filepath
c:\path\to\file
/path/to/file
also a mixture:
c:/path/to/file

also local file path
path/to/file
file
to/file

**Comment by git-davi** [comment]
(btw great job, congrats!!!!!!)

**Comment by CorentinJ** [comment]
Thanks. What's your python version? Do your packages meet the minimum requirements in the requirements.txt?

**Comment by git-davi** [comment]
Yes, also installed ffmpeg. Python 3.7

**Comment by DoubleAW** [comment]
I am having the same issue. Did you ever figure out the problem?

**Comment by CorentinJ** [comment]
I'd be great if one of you guys could hop into a debugger and see where it happens.

**Comment by mhessler97** [comment]
I had the same problem and the error for me was fixed by only using .wav files.

**Comment by git-davi** [comment]
> I had the same problem and the error for me was fixed by only using .wav files.

Closing the Issue.
