### ISSUE TITLE
cant detect cudart64.dll even change the configure to right version of it.

### ISSUE THREAD

**Issue by ACG-MM** [CorentinJ/Real-Time-Voice-Cloning#452]
![3](https://user-images.githubusercontent.com/63167197/88533332-b6b0af80-d038-11ea-8bd2-24e6f330aeb4.PNG)
my graphic driver cudart64.dll is under "C:\ProgramData\NVIDIA Corporation" and "C:\Program Files\NVIDIA Corporation\NvStreamSrv" also pip has installed tensorflow-gpu

**Comment by blue-fish** [comment]
Download the `423_add_cpu_mode` branch on my fork. Then you can run `python demo_toolbox.py --cpu` and it will override the `CUDA_VISIBLE_DEVICES` environment variable to force the toolbox to run in CPU-only mode.

If this resolves your problem I will go ahead and submit a pull request for it.

**Comment by blue-fish** [comment]
If you must have GPU support then try asking your question in the CUDA setup and installation section of the NVIDIA developer forums: [https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation](https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-setup-and-installation)

**Comment by blue-fish** [comment]
@ACG-MM Would you please provide an update? Is this resolved?
