### ISSUE TITLE
Error - AttributeError: 'Colorbar' object has no attribute 'set_clim'

### ISSUE THREAD

**Issue by barubbabba123** [CorentinJ/Real-Time-Voice-Cloning#455]
Hello everyone! Every time I run I got this following error:

```
inference.py", line 174, in plot_embedding_as_heatmap
    cbar.set_clim(*color_range)
AttributeError: 'Colorbar' object has no attribute 'set_clim'
```

I can comment the line and working fine, but I'd be glad to fix this.
The specific line is this last one:

```
cbar = plt.colorbar(mappable, ax=ax, fraction=0.046, pad=0.04)
cbar.set_clim(*color_range)
```

Could you help me? Thanks a lot!

**Comment by blue-fish** [comment]
@FulvioZozix is also experiencing this in #448 but I could not get enough data to confirm.

Can you run `pip freeze` in your terminal? I wonder if matplotlib was recently updated to remove `set_clim`

**Comment by blue-fish** [comment]
That is exactly what happened, the API changed in matplotlib 3.3.0:
https://github.com/matplotlib/matplotlib/blob/a8831d57207db5e9bf681e30810ce0ea146f4a31/doc/api/prev_api_changes/api_changes_3.3.0/removals.rst

> `colorbar.ColorbarBase.get_clim` (use `ScalarMappable.get_clim` instead)
> `colorbar.ColorbarBase.set_clim` (use `ScalarMappable.set_clim` instead)

@barubbabba123 Would you be so kind as to make an update and submit a pull request?

**Comment by blue-fish** [comment]
Workaround is to install a matplotlib version that is lower than 3.3.

```
pip install matplotlib==3.2
```

**Comment by blue-fish** [comment]
Please also change the order of imports in toolbox/ui.py so `import matplotlib.pyplot as plt` comes first. See: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/504#issuecomment-678733034

It will not matter when using matplotlib>=3.3.2 but this is a preventative measure to preempt incompatibility issues when using an older version.
