### ISSUE TITLE
pip install -r requirements.txt gives an error

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [CorentinJ/Real-Time-Voice-Cloning#456]
It gives me an error message, when I run the given command `pip install -r requirements.txt`:
![image](https://user-images.githubusercontent.com/19879399/88696181-373be280-d103-11ea-9ab5-4e47b710eab5.png)
![image](https://user-images.githubusercontent.com/19879399/88696262-52a6ed80-d103-11ea-8f42-cd6ff32c1b62.png)

**Comment by blue-fish** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-665165023
> ### Pip error: `Could not find a version that satisfies the requirement tensorflow==1.15`
> 
> You are likely using Python 3.8+ which is incompatible with Tensorflow 1.15. To resolve this, you will need to switch to Python 3.6 or 3.7.

**Comment by blue-fish** [comment]
Presumed to be resolved. Reopen this issue if you are still experiencing this specific problem, or open a new issue if you have a different problem.
