### ISSUE TITLE
"OSError: [WinError 193] %1 is not a valid Win32 application" on attempt to run python scripts

### ISSUE THREAD

**Issue by EnergeticSpaceCore** [CorentinJ/Real-Time-Voice-Cloning#457]
I'm set up with an Anaconda environment for Python 3.7.7
Running on a 64-bit Windows 10 system with an AMD processor.
Installed PYTorch and ffmpeg through `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch` and `conda install ffmpeg` (unsure if that may introduce some difference), and the rest through the Pip requirements file.

Merged the pretrained models into the file structure, went to to test the configuration with `python demo_cli.py`, from the conda environment, with active directory appropriately at the root of the project.

![Error 1](https://user-images.githubusercontent.com/5068499/88719104-bf64bc80-d0f0-11ea-87ab-ac901ba28b61.PNG)

Similar error with `python demo_toolbox.py`:

![Error 2](https://user-images.githubusercontent.com/5068499/88719350-25514400-d0f1-11ea-90c7-dc1770ce5d58.PNG)

This error seems supremely uninformative, does anyone have any insight?

**Comment by blue-fish** [comment]
I hope that you don't mind that I try to build the FAQ while solving your problem (which also occurred in #163). Provide any info that is useful to the resolution and I will add it.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-665277071

> ### OSError: [WinError 193] %1 is not a valid Win32 application
> #### Summary
> 
> This error message occurs when you have multiple python environments and they are conflicting with each other.
> #### Solution
> 
> See [pytorch/pytorch#27693 (comment)](https://github.com/pytorch/pytorch/issues/27693#issuecomment-540513657) for more information.

**Comment by blue-fish** [comment]
It may be caused by mixing `conda install` and `pip install` , you should do one or the other.

If you want to use conda, try:
```
conda install --file requirements.txt
```

**Comment by blue-fish** [comment]
@EnergeticSpaceCore Did you resolve this?

**Comment by EnergeticSpaceCore** [comment]
@blue-fish Unfortunately, the full set of required packages are not available on the standard conda channels. By adding the channels `conda-forge` and `dsdale24` the missing packages can be found, but they do not all have the same name (having "python" or "py" prepended).

Missing packages:
`visdom`
`soundfile`
`umap-learn`
`multiprocess`
`librosa[version='>=0.5.1']`
`pyqt5`
`sounddevice`

Modifying the `requirements.txt` file to contain the updated names appears to break the whole thing by introducing package conflicts, which was expected, but I figured was worth a shot.

I'm also investigating the possibility that forcing conda to only download 32-bit packages (but still using pip as originally) could resolve the issue, but no progress on that yet.

**Comment by blue-fish** [comment]
You don't need `visdom` to use the toolbox. It is only ever used for encoder training which few users will ever perform.

The toolbox is a breeze to set up on a Linux system (with the exception of GPU support which is optional). You might find it easier to run it on a virtual machine with Ubuntu 18.04 if you have that option.

**Comment by EnergeticSpaceCore** [comment]
Using `pip` to install each package succeeded, but the resultant setup threw the same error as before, with the `%1`. Pursuing the Ubuntu angle now.

Also, I'm curious what you mean by saying that I don't "need" `visdom`. It is contained in `requirements.txt` and will throw an error if not acquired properly, so I assume you mean that the setup would mostly function if I removed that line from the text file?

**Comment by blue-fish** [comment]
Visdom is not hard to install but if you are installing packages manually it can be skipped to save time. It's your call as to whether to remove that line from requirements.txt.

The only toolbox program that uses it is`encoder_train.py` and 99% of users will never touch it.

**Comment by blue-fish** [comment]
@EnergeticSpaceCore Can you provide an update? I hope this is resolved, but if you're still trying to set up, it would be helpful to know the current problem point.

**Comment by blue-fish** [comment]
Closed issue due to inactivity.
