### ISSUE TITLE
Real time voice conversion

### ISSUE THREAD

**Issue by kool601** [CorentinJ/Real-Time-Voice-Cloning#46]
Just a question, but will there ever be a way to clone a voice, except instead of typing it out, you can just have a real time (or almost real time) voice conversion? As in I could say something after "training" it to a different voice into the mic, and it would output audio in near real time. I don't know how else to explain it, I hope you know what I mean. XP

**Comment by CorentinJ** [comment]
This is called voice conversion and it's essentially a form of style transfer, usually applied at the spectrogram level. 

There are proofs of concept here and there:
https://github.com/leimao/Voice_Converter_CycleGAN
https://github.com/hujinsen/StarGAN-Voice-Conversion

It is however beyond the scope of this repo.

**Comment by kool601** [comment]
Thanks for the quick response! And that's a bit disappointing (but understandable), because this tool is very easy to set up and use, unlike the other "voice conversion" tools I've seen. If you know of a repo like this one (as in easy to setup and has pretrained models and stuff), please let me know. I've always wanted to try out something like that.

**Comment by arzutahtasiz2** [comment]
Chat now

**Comment by arzutahtasiz2** [comment]
434
