### ISSUE TITLE
Output file not as clear as audio played within toolbox

### ISSUE THREAD

**Issue by halswift** [CorentinJ/Real-Time-Voice-Cloning#462]
Hello, so after a week I finally got the toolbox to work (I have never worked with Python). The project I am working on is replicating my deceased father's voice to have his cloned voice read his memoir. The issue I am running into is that the output .wav file that is rendered is of lesser quality than the audible voice that the toolbox plays. I also noticed I am unable to export as a .flac file. It states "File contains data in an unimplemented format" which makes me think I don't have something installed right. Any help someone can give me would be greatly appreciated. 

Thank you!
Hal

**Comment by blue-fish** [comment]
@halswift Would you please export a wav file (preferably using one of the included [samples](https://github.com/CorentinJ/Real-Time-Voice-Cloning/tree/master/samples) to make the embedding), zip it up and attach it here?

I'd like to compare the encoding of the wav file with what is generated on my system. I think it's a system configuration or dependency issue.

**Comment by blue-fish** [comment]
Please see https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/282#issuecomment-706946711 . Try running on a different computer or platform (e.g. Linux) and see if you still have the issue.
