### ISSUE TITLE
Issue about training and cloning

### ISSUE THREAD

**Issue by DereWah** [CorentinJ/Real-Time-Voice-Cloning#464]
Hi,
I haven't really understood the point in this repo. I wanted to ask a few things:
1- If I wanted to get a voice and clone it, do I have to pretrain datasets with different sentences from that voice or I can use pretrained datasets?
2- For emebedding, can I use more than 5 seconds of audio or that's a limit?
Thamk

**Comment by blue-fish** [comment]
1. The pretrained models can generalize to voices and speech (text) unseen during training. This is known as zero-shot voice cloning.
    * The finetuning in #437 is completely optional and will get better results by training on voice samples of the target speaker.
2. Any length of audio can be used (I've done 20 minutes before) but the characteristics of the speaker will be averaged over the entire timeframe, so it may not produce better results than a 5-10 second sample.
