### ISSUE TITLE
The box with clusters isn't working.

### ISSUE THREAD

**Issue by DereWah** [CorentinJ/Real-Time-Voice-Cloning#465]
Hi,
When I load different or same pretrained datasets the box where points appear and form clusters are not working. Just nothing happens there. How can I solve this?
Also the audio often seems "doubled" or with a lot of noise. How can I improve that?
Thank you

**Comment by DereWah** [comment]
Solved 👍 
pip uninstall matplotlib
pip install matplotlib==3.2.2

**Comment by blue-fish** [comment]
The issue with matplotlib is a known issue: #455 

Does the audio issue occur when you click the "replay" button? I notice if the computer has high CPU usage trying to plot the umap projection it will affect the playback. But I don't get that issue when using "replay".
