### ISSUE TITLE
No matching distribution found for tensorflow==1.15

### ISSUE THREAD

**Issue by biplab1** [CorentinJ/Real-Time-Voice-Cloning#469]
From the installation instructions: Run pip install -r requirements.txt to install the remaining necessary packages.

```
$: pip3 install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from -r requirements.txt (line 1)) (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.15 (from -r requirements.txt (line 1))
```

**Comment by blue-fish** [comment]
Let me know if this doesn't solve your issue: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-665165023

And if it does resolve it, please close this one.

**Comment by bhrt-sharma** [comment]
@biplab1  please create a virtual environment using "virtualenv venv_name -p python3" and not using "python3 -m venv venv_name" 
then you will note get this error.

**Comment by biplab1** [comment]
Downgrading Python to 3.7 helped.

**Comment by biplab1** [comment]
> @biplab1 please create a virtual environment using "virtualenv venv_name -p python3" and not using "python3 -m venv venv_name"
> then you will note get this error.

couldn't make it work using this method. Still getting the error mentioned above.
