### ISSUE TITLE
Issue - python: can't open file 'demo_toolbox.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hmmhellohi** [CorentinJ/Real-Time-Voice-Cloning#470]
Hello, I'm new to programming and I know basically nothing. I have been trying to install the software by following the steps in the site. Everything went well until that part:
![issue](https://user-images.githubusercontent.com/69292518/89494197-09ead680-d78c-11ea-8b2c-e67e666dec11.png)

When I open the command prompt and type        python demo_toolbox.py            I get the following message:
![issue2](https://user-images.githubusercontent.com/69292518/89494348-60581500-d78c-11ea-9127-e7464b9ccfe6.png)

Am I opening the wrong command prompt? The instructions say to open a 'command prompt in the master branch directory' but what would the master branch directory be and how can I open a command prompt in the master branch directory?

I suppose I did the previous step wrong (image below) too because it said the same about opening a command prompt in the master branch directory. And can you show me how to open the master branch for this step too?
![issue3](https://user-images.githubusercontent.com/69292518/89494649-fe4bdf80-d78c-11ea-8caa-62e04e270a19.png)

Sorry if those are really obvious questions and thank you for reading everything :)

**Comment by blue-fish** [comment]
@hmmhellohi You need to navigate to the directory that contains the Real-Time-Voice-Cloning code, then run the `python demo_toolbox.py` command. However, I think it is very unlikely that it was set up correctly based on the information you have provided.

I wrote this in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/428#issuecomment-660242818 and it is also applicable here.

> You are not the target audience for this project, it is a research code and not a finished product. It happens to be very user-friendly as far as research codes go, but may cause frustration if you do not have any relevant computer experience. I commend you for trying, but you may want to wait for the compiled version (#267) which is in work.

You can also consider the colab notebook (in this repository) and Sagemaker fork #398 as alternatives if you are experiencing difficulties setting up the toolbox.

Although I am closing this issue, you are welcome to open a new one if you have a specific question or problem concerning this toolbox.
