### ISSUE TITLE
Error Occured while installing on ubuntu desktop

### ISSUE THREAD

**Issue by sssharmass97** [CorentinJ/Real-Time-Voice-Cloning#473]
I got error while trying **pip3 install requirements.txt** 

_Here is the error_: 

ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from -r requirements.txt (line 1)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.15 (from -r requirements.txt (line 1))

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/785e5513b45daf6a83b86b0b459f1717033859cb/requirements.txt#L1

**Comment by blue-fish** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-665165023
