### ISSUE TITLE
Should we create a Slack Channel to communicate?

### ISSUE THREAD

**Issue by mbdash** [CorentinJ/Real-Time-Voice-Cloning#474]
@blue-fish should we create a Slack Channel to communicate?

**Comment by blue-fish** [comment]
@mbdash We can try it out. Invited you to a repo that has the invite link. If anyone else wants it, reply here.

I would still like to make an effort to have all communication here that may be of interest in the future. The slack channel is intended as a temporary thing for the next few weeks while we get new models trained up, and will not be archived.

**Comment by mbdash** [comment]
@blue-fish I agree:
`I would still like to make an effort to have all communication here that may be of interest in the future. The slack channel is intended as a temporary thing for the next few weeks while we get new models trained up, and will not be archived.`

**Comment by CodingRox82** [comment]
I'm interested in a voice to voice system.

**Comment by blue-fish** [comment]
@CodingRox82 Sent you an invite so we can discuss further.

**Comment by michaellin99999** [comment]
Hello I am interested in the voice to voice system

**Comment by pleonard212** [comment]
@blue-fish I have some GPU resources that could be put to work on this; happy to join the Slack for further details.

**Comment by zubairahmed-ai** [comment]
@blue-fish Any progress on this? I need a project like this

**Comment by turian** [comment]
@blue-fish I am interested. username at gmail dot com

**Comment by minime283** [comment]
I am interested in this system, if it's still happening

**Comment by 1995YogeshSharma** [comment]
@blue-fish 
Hey, is there still anything going towards voice-to-voice? I would be super interested to know more!

**Comment by SanCrystal** [comment]
hello there, please I would like to be part of the project(voice-to-voice). please add me up.
