### ISSUE TITLE
Multi language cloning

### ISSUE THREAD

**Issue by sid0791** [CorentinJ/Real-Time-Voice-Cloning#478]
Hi, 
is it possible to train the model for multilingual voice cloning?
Is there any trained model available. 
Or can you help with the parameters to train the model in multilingual using language database.
Thanks

**Comment by blue-fish** [comment]
@sid0791 Please see #30 regarding support for other languages, or #400 for a list of pretrained models (including languages other than English). You might also want to check out https://github.com/Tomiinek/Multilingual_Text_to_Speech , but I cannot help with it as I have never used it.

I am going to close this issue, you are welcome to open a new one if you have a more specific question.
