### ISSUE TITLE
Error installing tensorflow1.15.0 

### ISSUE THREAD

**Issue by justinjohn0306** [CorentinJ/Real-Time-Voice-Cloning#479]
Error installing tensorflow1.15.0 

ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.0 (from -r requirements.txt (line 1)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.15.0 (from -r requirements.txt (line 1))

**Comment by gabrielmontagne** [comment]
I've had a really good experience with anaconda.  I've installed this project a few times and it's been quite simple if I create and activate a new environment, then, on it, `conda install tensorflow=1.15`,  then `conda install pytorch torchvision -c pytorch` then on the repo `pip install -r requirements.txt`.  Conda makes sure versions are compatible, etc.

**Comment by blue-fish** [comment]
We have a FAQ for this, please see: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-665165023

**Comment by blue-fish** [comment]
Since this is a known issue I am going to close this now. Please feel free to open a new issue if you experience any other problems during setup or use.
