### ISSUE TITLE
Documentation isn't particularly helpful. Is there an exe coming or am I permanently stuck

### ISSUE THREAD

**Issue by NerdIt** [CorentinJ/Real-Time-Voice-Cloning#481]
I found this project the start of last year and have been trying to get it to work ever since. I've followed the official documentation and a bunch of articles that try to repair the official documentation, as well as youtube videos that where supposed to show you how to do it. None of the approaches work and it's kinda getting tiring. 

I've looked through all the requirements and made sure I include each of them for each tutorial. I always just get a 'torch module' doesn't  exist even though I've clearly installed it several times. 

I have looked through the other issues and know that an exe compiled version may or may not be coming, but I really hope it does because I am seriously struggling to get it to work. If their is one on the way, what's the status?

**Comment by blue-fish** [comment]
@NerdIt I feel your frustration. How do you self-rate your computer skills? I will offer to walk you through the setup if you want to give it one last try. We will quickly diagnose what is going on in Windows, and if that doesn't work then you can set up a virtual machine with Ubuntu and run it there.

**Comment by blue-fish** [comment]
> I always just get a 'torch module' doesn't exist even though I've clearly installed it several times.

It sounds like you may have a really old version of pip. Upgrade your pip as follows:
```
python -m pip install pip --upgrade
```

Then you can `pip install torch` and get the real thing.

**Comment by blue-fish** [comment]
> I always just get a 'torch module' doesn't exist even though I've clearly installed it several times.

@NerdIt I think the problem is that when you run `python` it launches python 2.x which doesn't work with torch or the toolbox. Retry the commands with `python3` in place of "python".

This is what it looks like when you try to import torch in python 2.x:
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named torch
>>> 
```

**Comment by NerdIt** [comment]
@blue-fish oh. thx for the suggestions. I'll try both the fixes and see if it works. My computer skills are not particularly developed for the console, but i understand software pretty well.

**Comment by blue-fish** [comment]
@NerdIt I apologize for the installation difficulties, we're continuing to work on it. I've always thought of it as a research code, and it is quite user-friendly from that perspective. Thanks for giving the toolbox another chance.

Make sure you're using Python 3.6 or 3.7 (check it with `python --version`). Don't hesitate to reach out when you encounter the inevitable error message.

**Comment by blue-fish** [comment]
@NerdIt Any updates? Did you make any progress on the toolbox setup?

**Comment by RocketSauce28** [comment]
> @NerdIt Any updates? Did you make any progress on the toolbox setup?

I'm having an issue when installing requirements, I get the following error message:
`ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from -r requirements.txt (line 1)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.15 (from -r requirements.txt (line 1))`

**Comment by blue-fish** [comment]
Tensorflow 1.15 is not available for Python 3.8. Make sure you're using Python 3.6 or 3.7 (check it with `python --version`).

**Comment by NerdIt** [comment]
@blue-fish in the process of re-installing everything so I am not left with any incorrect versions

**Comment by NerdIt** [comment]
@blue-fish ok so I seem to no longer be having the errors I had last time, but now I am getting configuration messages. I don't understand what I am meant to do with them or what is causing them.

`Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.6, library is 1.10.5
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================

General Information:
-------------------
                   HDF5 Version: 1.10.5
                  Configured on: 2019-03-04
                  Configured by: Visual Studio 15 2017 Win64
                    Host system: Windows-10.0.17763
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: C:/Program Files/HDF5

Compiling Options:
------------------
                     Build Mode:
              Debugging Symbols:
                        Asserts:
                      Profiling:
             Optimization Level:

Linking Options:
----------------
                      Libraries:
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:x64
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries:
                       Archiver:
                         Ranlib:

Languages:
----------
                              C: yes
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe 19.16.27027.1
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
                         CFLAGS:  /DWIN32 /D_WINDOWS /W3
                      H5_CFLAGS:
                      AM_CFLAGS:
               Shared C Library: YES
               Static C Library: YES

                        Fortran: OFF
               Fortran Compiler:
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe 19.16.27027.1
                      C++ Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

                            JAVA: OFF
                   JAVA Compiler:

Features:
---------
                   Parallel HDF5: OFF
Parallel Filtered Dataset Writes:
              Large Parallel I/O:
              High-level library: ON
                    Threadsafety: OFF
             Default API mapping: v110
  With deprecated public symbols: ON
          I/O filters (external):  DEFLATE DECODE ENCODE
                             MPE:
                      Direct VFD:
                         dmalloc:
  Packages w/ extra debug output:
                     API Tracing: OFF
            Using memory checker: OFF
 Memory allocation sanity checks: OFF
          Function Stack Tracing: OFF
       Strict File Format Checks: OFF
    Optimization Instrumentation:
Bye...`

**Comment by NerdIt** [comment]
Oh and the tool box still doesn't open lol

**Comment by blue-fish** [comment]
@NerdIt We've had this reported in another issue. Please see the suggestion here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/421#issuecomment-657180528

Let me know if it doesn't work

**Comment by NerdIt** [comment]
@blue-fish ok. I most likely will have to restart the installation process through because I made the error of tampering with one of the system variables and have lost the original value. At this point, I am doing a quick backup and restoring my Windows files to this morning.

**Comment by blue-fish** [comment]
@NerdIt If you're following an installation guide, please be aware that they were written when this toolbox required GPU and it was a real pain to set up. Likely they will lead you down a path of installing NVIDIA drivers which is really not needed since we've added CPU support. We've also removed webrtcvad as a dependency which means you can start with Python 3.7 and for the most part be up and running with the toolbox after running the commands below. Our readme documentation is a little better now.
```
pip install pip --upgrade
pip install torch
pip install -r requirements.txt
```

Vocoding is slow with CPU but for the purposes of testing out the toolbox, it's much better than spending hours trying to get it working with the GPU. Only if you like the toolbox that much should you go down that route.

**Comment by NerdIt** [comment]
@blue-fish well the window opened for the first time, but only for a second before crashing.

I'm getting this error.
`Traceback (most recent call last):
  File "demo_toolbox.py", line 32, in <module>
    Toolbox(**vars(args))
  File "E:\USER\Anaconda\deepvoice\RealTimeVoiceCloningmMaster\toolbox\__init__.py", line 49, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir)
  File "E:\USER\Anaconda\deepvoice\RealTimeVoiceCloningmMaster\toolbox\__init__.py", line 97, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_models_dir)
  File "E:\USER\Anaconda\deepvoice\RealTimeVoiceCloningmMaster\toolbox\ui.py", line 275, in populate_models
    raise Exception("No encoder models found in %s" % encoder_models_dir)
Exception: No encoder models found in encoder\saved_models
`

**Comment by NerdIt** [comment]
Unless I just need a data set

**Comment by NerdIt** [comment]
Never mind. I found the thread where you already solved this error. I'm downloading the pre-trained model now

**Comment by blue-fish** [comment]
Great! I think you're getting close. If you are going to clone a voice by loading mp3 files please make sure to install FFmpeg (a link is provided in README.md).

**Comment by NerdIt** [comment]
In downloaded and unzipped the pre-trained model but it gave me the same error. I am using 
`python demo_toolbox.py -d E:\USERNAME\Downloads\pretrained`
is this correct?

**Comment by NerdIt** [comment]
@blue-fish or is there a directory I am meant to add the model to?

**Comment by blue-fish** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models
> The archive comes with the same directory structure as the repo, and you're expected to merge its contents with the root of the repository.

@NerdIt The documentation is not particularly clear but you are supposed to unzip everything to the top level of the repo, so it will make a `saved_models` folder in each of encoder, synthesizer, and vocoder. I explain this in a little more detail here:

https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/494#issuecomment-674123036

**Comment by NerdIt** [comment]
Nevermind. Figured it out. It's working now. I'll close the issue. Thanks for the help o/

**Comment by blue-fish** [comment]
If you have any suggestions for the documentation after you get the toolbox working I would really appreciate them.

**Comment by NerdIt** [comment]
Not really. I think the documentation is easy enough for people to follow if they understand what they are doing. In my case I had no idea what I was doing until the end of the process when i finally figured out how larger python programs worked.

**Comment by NerdIt** [comment]
I should have done some more research on machine learning and python before attempting. But it's working now, so yay
