### ISSUE TITLE
Model files not found.

### ISSUE THREAD

**Issue by tjonas331** [CorentinJ/Real-Time-Voice-Cloning#482]
While trying to install the Real-Time-Voice-Cloning repo,
I am unable to run the toolbox, because I always get the following error:
_Error: Model files not found. If needed, download them here:_
I tried this command python `demo_toolbox.py`
and this one with the path to the modules `python demo_toolbox.py -d C:\Users\Raphael\Documents\GitHub\Real-Time-Voice-Cloning\models`

But nothing works.
Is there someone that can help me with this issue? :)

P.S.
I downloaded the ffmpeg libary but I don't know where I should paste it in.

**Comment by blue-fish** [comment]
1. Did you download the pretrained models? The URL should be on the second line of the error message, but in case you can't see it, it is: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models

2. Do the following files exist after extracting the archive in step 1?
(The file/folder paths are relative to the top-level folder of the repo)
```
encoder\saved_models\pretrained.pt
synthesizer\saved_models\logs-pretrained
vocoder\saved_models\pretrained\pretrained.pt
```

3. Are you running the `python demo_toolbox.py` command from this location?
`C:\Users\Raphael\Documents\GitHub\Real-Time-Voice-Cloning\`

**Comment by tjonas331** [comment]
I downloaded the pretrained models from this link [](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models)
Yes, I am running the `python demo_toolbox.py `command from this location `C:\Users\Raphael\Documents\GitHub\Real-Time-Voice-Cloning\`
The path to the extracted model is `C:\Users\Raphael\Documents\GitHub\Real-Time-Voice-Cloning\models` in that I can find all of the model files: 
```
encoder\saved_models\pretrained.pt
synthesizer\saved_models\logs-pretrained
vocoder\saved_models\pretrained\pretrained.pt
```

**Comment by justinjohn0306** [comment]
> I downloaded the pretrained models from this link https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models
> Yes, I am running the `python demo_toolbox.py `command from this location `C:\Users\Raphael\Documents\GitHub\Real-Time-Voice-Cloning\`
> The path to the extracted model is `C:\Users\Raphael\Documents\GitHub\Real-Time-Voice-Cloning\models` in that I can find all of the model files:
> 
> ```
> encoder\saved_models\pretrained.pt
> synthesizer\saved_models\logs-pretrained
> vocoder\saved_models\pretrained\pretrained.pt
> ```

Just extract them into C:\Users\Raphael\Documents\GitHub\Real-Time-Voice-Cloning....not in models folder

**Comment by tjonas331** [comment]
> Just extract them into C:\Users\Raphael\Documents\GitHub\Real-Time-Voice-Cloning....not in models folder
Thanks, that was my mistake.
Can you say me where I have to put the ffmpeg libary into?

**Comment by tjonas331** [comment]
hhhhhhhhhh

**Comment by tjonas331** [comment]
Sorry never used github before ;/

**Comment by blue-fish** [comment]
Here are instructions for installing ffmpeg on windows: https://video.stackexchange.com/a/20496

It's really only needed if you want to use mp3 files as input (to create the speaker embedding).

**Comment by tjonas331** [comment]
> 
> 
> Here are instructions for installing ffmpeg on windows: https://video.stackexchange.com/a/20496
> 
> It's really only needed if you want to use mp3 files as input (to create the speaker embedding).

Oh ok,
Thanks a lot for the help
