### ISSUE TITLE
Using speaker embeddings instead of utterance embeddings

### ISSUE THREAD

**Issue by blue-fish** [CorentinJ/Real-Time-Voice-Cloning#483]
In #437 I found that single-speaker finetuning converged faster with better results when using the same embedding for all samples, instead of the individual utterance embeddings that are created during preprocessing. We can probably extend this idea to synthesizer training as well. @rfwatkins had this observation in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/162#issuecomment-543167918 and it matches my experience with the toolbox: 

> Some subsamples of a voice clone better than others. The key to getting a good voice synthesis seems to me to be testing a range of different samples from the same speaker and discovering the one which clones the best.

Let's define the speaker embedding as the L2-norm of all utterance embeddings collected from the same speaker. If we train the synthesizer on the speaker embedding, it should perform better (in general) for unseen inputs rather than the current situation where the output voice and prosody are influenced by the utterance embedding used.

To implement this, we'd need an extra preprocessing step to take the L2-norm of each speaker's embeds prior to synth training, and redefine the embed.npy file references accordingly in train.txt. The toolbox UI also needs to be updated to L2-norm all embeds in its cache, and provide a means to clear the cache to try out new speakers. Maybe a "load/save speaker embedding file" button too.

This is not a proposal to make a formal change to the toolbox, but something that I'd like to try when my GPU is freed up after training a model for #472 . I'd be interested if anyone has any ideas or experience with it.

**Comment by Ananas120** [comment]
For ideas to test this thing you have many things to do ! but it can take lot of computational time and find datasets appropriated... 
For instance : 
- Add emotion using an embedded of the speaker with this particular emotion
- Try to improve the encoder to create « identity card » of a speaker (with the L2-norm of all his embeddings)
- ...

**Comment by blue-fish** [comment]
#### https://gist.github.com/blue-fish/7eccac290cdd8b9205b8c5f488e39bb2
This will replace your utterance embeddings with speaker embeddings.
```
python make_speaker_embeds.py path/to/datasets_root/SV2TTS/synthesizer/embeds
```

**Comment by Ananas120** [comment]
Nice, well done !

**Comment by blue-fish** [comment]
With a good encoder, the utterance embeddings will have very high cosine similarity which means the speaker embedding will not be far off. Therefore it should make little difference whether an utterance or speaker embedding is used.

In practice the encoder does transfer prosody, as noted in Corentin's thesis:

> The speech generated by the synthesizer matches correctly the text, even in the presence of complex or fictitious words.  The prosody is however sometimes unnatural, with pauses at unexpected locations in the sentence, or the lack of pauses where they are expected.  This is particularly noticeable with the embedding of some speakers who talk slowly, showing that the speaker encoder does capture some form of prosody.  The lack of punctuation in LibriSpeech is partially responsible for this, forcing the model to infer punctuation from the text alone.  This issue was highlighted by the authors as well,  and can be heard on some of their samples of LibriSpeech speakers.

I'm going to close this as I don't expect to perform any experiments in the near future.
