### ISSUE TITLE
Warning: You do not have any of the recognized datasets in LibriSpeech/train-clean-100

### ISSUE THREAD

**Issue by justinjohn0306** [CorentinJ/Real-Time-Voice-Cloning#485]
This message shows "Warning: You do not have any of the recognized datasets in LibriSpeech/train-clean-100"

**Comment by blue-fish** [comment]
Which file are you trying to run, and how are you running it?

Also full traceback and error message would be very helpful for troubleshooting the problem.

**Comment by justinjohn0306** [comment]
> Which file are you trying to run, and how are you running it?
> 
> Also full traceback and error message would be very helpful for troubleshooting the problem.

![Capture](https://user-images.githubusercontent.com/34035011/90019350-e663e680-dccb-11ea-8d0f-14fec8fc21be.PNG)

**Comment by justinjohn0306** [comment]
check the warning message
 
i typed in python demo_toolbox.py -d LibriSpeech\train-clean-100

**Comment by blue-fish** [comment]
Did you download the dataset from https://openslr.org/12 and extract it to your Real-Time-Voice-Cloning folder?

**Comment by justinjohn0306** [comment]
> Did you download the dataset from https://openslr.org/12 and extract it to your Real-Time-Voice-Cloning folder?
> 
> In the python command, try specifying full path to the folder just 1 level above LibriSpeech. It automatically looks for LibriSpeech/train-clean-100, etc. relative to the specified path.
yes I did

**Comment by blue-fish** [comment]
What does the warning message say when you specify full path to the folder just 1 level above LibriSpeech?
Can you show me where you are placing your dataset and the python command used to launch the toolbox?

**Comment by justinjohn0306** [comment]
> What does the warning message say when you specify full path to the folder just 1 level above LibriSpeech?
> Can you show me where you are placing your dataset and the python command used to launch the toolbox?

![Capture](https://user-images.githubusercontent.com/34035011/90084583-53f72d80-dd33-11ea-88c0-8aea44591d93.PNG)

**Comment by justinjohn0306** [comment]
![Capture](https://user-images.githubusercontent.com/34035011/90084652-915bbb00-dd33-11ea-8a3f-d7d1fd0fc544.PNG)
And this is the warning

**Comment by blue-fish** [comment]
Try putting the `LibriSpeech` folder inside a folder named `datasets` and run:

`python demo_toolbox.py -d datasets`

**Comment by justinjohn0306** [comment]
> python demo_toolbox.py -d datasets

hoo...finally it's working...thanks a bunch

**Comment by blue-fish** [comment]
You're welcome @justinjohn0306 !

**Comment by bhoffmann93** [comment]
> > python demo_toolbox.py -d datasets
> 
> hoo...finally it's working...thanks a bunch

i did exaclty that and still get the error

**Comment by richmind1** [comment]
> You're welcome @justinjohn0306 !

please i need your help on my set up, am unable to get librispeech on my file, what should i do have downloaded it so manytime

**Comment by richmind1** [comment]
please i need your help on my set up, am unable to get librispeech on my file, what should i do have downloaded it so manytime
