### ISSUE TITLE
NameError: name 'self' is not defined message appears when running in --low mem option

### ISSUE THREAD

**Issue by justinjohn0306** [CorentinJ/Real-Time-Voice-Cloning#491]
![Capture](https://user-images.githubusercontent.com/34035011/90137968-f47d3a00-dd93-11ea-8248-0d5881b0279a.PNG)

It says NameError: name 'self' is not defined when running in low memory option

**Comment by blue-fish** [comment]
Thank you for reporting this bug, we should make `seed` an argument to `_one_shot_synthesize_spectrograms`. I have pushed a fix for this in the [`491_lowmem_synthesize_error`](https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/491_lowmem_synthesize_error) branch of my fork, but I am unable to test it as I do not have a GPU available.

I do not plan to submit a PR because we will migrate to a torch-based synthesizer shortly.

**Comment by blue-fish** [comment]
> I have tried the main repository, and i get the error that "self" is not defined. There was an issue about this, so i used the branch from that fix. Now i am getting:
> **raceback (most recent call last): File "demo_cli.py", line 93, in mels = synthesizer.synthesize_spectrograms(texts, embeds) File "D:\RealTimeDeepFake\voice\Real-Time-Voice-Cloning\Real-Time-Voice-Cloning\synthesizer\inference.py", line 101, in synthesize_spectrograms [(self.checkpoint_fpath, embeddings, texts, self._seed)])[0] File "C:\Users\fnafm\AppData\Local\Programs\Python\Python37\lib\site-packages\multiprocess\pool.py", line 276, in starmap return self._map_async(func, iterable, starmapstar, chunksize).get() File "C:\Users\fnafm\AppData\Local\Programs\Python\Python37\lib\site-packages\multiprocess\pool.py", line 657, in get raise self._value multiprocess.pool.MaybeEncodingError: Error sending result: '<multiprocess.pool.ExceptionWithTraceback object at 0x00000250FDB07DC8>'. Reason: 'TypeError("can't pickle tensorflow_core.python._tf_stack.Stack objects")'**
> 
> I have tried using conda environment with python 3.7, and also, plain python, following this procedure : https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/
> 
> My hardware really sucks and i can't run linux. I am stuck with live sessions and windows.
> How can i fix the issue?

_Originally posted by @AntINFINAit in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/529#issue-703594168_
