### ISSUE TITLE
Error - AttributeError: 'Colorbar' object has no attribute 'set_clim'

### ISSUE THREAD

**Issue by FulvioZozix** [CorentinJ/Real-Time-Voice-Cloning#495]
i'm getting this error,how to fix ? i'm a little noob in Deep Learning,can anyone explain how to fix step-by-step ? thanks

**Comment by blue-fish** [comment]
We are tracking the matplotlib incompatibility in another issue, here is the workaround for this problem: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/455#issuecomment-674410447

**Comment by blue-fish** [comment]
@FulvioZozix Please ask any follow-up questions in #455.
