### ISSUE TITLE
Voice Cloning to Brazilian language...how ?

### ISSUE THREAD

**Issue by FulvioZozix** [CorentinJ/Real-Time-Voice-Cloning#496]
How i can train voices to Brazilian language ? my imput model (Bolsonaro) result sounds horrible,what i'm doing wrong ? thanks

**Comment by fifthdice** [comment]
1. You mean portuguese.
2. You have to train it to speak in that language, since it only speaks english.
3. It will take a long, long time.
4. I am still learning so i cant tell you how to train it, since i dont know myself :/

**Comment by blue-fish** [comment]
See https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-673555684 for some information on how to get started with training. Please note:

> First thing, we do not provide any official support for training a model with your own data, it is expected that anyone who trains a model is capable of coding in Python and solving the inevitable error messages on their own. You are welcome to open an issue if you get stuck but no one will walk you through the entire process.

You need to find a suitable dataset. Mozilla CommonVoice currently has a total of 48 hours of Portuguese speech from 744 speakers, which is a start but probably not enough.

Mozilla TTS has a model in Brazilian Portuguese. See: https://github.com/mozilla/TTS/issues/160 It doesn't support voice cloning but you could finetune a voice given enough data. However, you would need to learn how to use their repo. They do have a discussion board where questions can be asked.

This is going to be a lot of work. Plan on 20 hours if you know what you're doing and 100 hours if you don't.

**Comment by blue-fish** [comment]
Is anyone training a model in Brazilian Portuguese at this time? If not I will go ahead and close this issue.

**Comment by gcsfred2** [comment]
Are there simpler instructions to train and synthesize Brazilian Portuguese? I followed instructions to train with the GUI of demo_toolbox.py and the end result sounds like someone from Mississipi.
