### ISSUE TITLE
Error while running pip install requirements.txt

### ISSUE THREAD

**Issue by explodersname** [CorentinJ/Real-Time-Voice-Cloning#505]
Collecting PyQt5 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/8c/90/82c62bbbadcca98e8c6fa84f1a638de1ed1c89e85368241e9cc43fcbc320/PyQt5-5.15.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-ulwxy262/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ulwxy262/PyQt5/
What should I do?

**Comment by explodersname** [comment]
I solved it via adding the sip line right before pyqt5

**Comment by blue-fish** [comment]
Closing as this is resolved, thank you for sharing your solution @explodersname .
