### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow==1.15

### ISSUE THREAD

**Issue by MarcoDotIO** [CorentinJ/Real-Time-Voice-Cloning#509]
I'm having a bit of trouble installing the required libraries, as I'm running into the following error when using "pip3 install -r requirements.txt"

`ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from -r requirements.txt (line 1)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.15 (from -r requirements.txt (line 1))`

I am running Ubuntu 20.04.1 with Python 3.8.2. I can provide other versions of programs if needed.

Update: I looked through the Issues with the repo, and have found this comment- 
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-665165023 

If it does only run with 3.7 or 3.6, is there any reliable way of downgrading to those? I've tried pyenv, but it seems like it doesn't change the python3 to point to the downgraded version. (e.g., if I run "python -V", the output will be "Python 3.6.0", but if I run "python3 -V" the output will be "Python 3.8.2")

Update 2: I managed to complete the initial requirements installation by simply installing Python 3.7.0 for pyenv. However, I am stuck running on demo_cli.py since it freezes at "Running a test of your configuration...", which shouldn't take forever with the setup I have (1080 TI, 16 GB of RAM). However, looking into the demo code more, it looks like the program is freezing at this line:
`device_id = torch.cuda.current_device()`

**Comment by blue-fish** [comment]
@MarcoDotIO If you want to be a beta tester look at my pull request that eliminates the tensorflow requirement, see #472.

That will work on 20.04.1 (bug #504 applies, but has a solution). Unfortunately our pretrained models on the torch-based synthesizer are not that good and we are still developing them. See https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/449#issuecomment-674420484 for a model that works with the torch-based synth. You will still need the encoder and vocoder model from the [pretrained models](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models) wiki page.

**Comment by MarcoDotIO** [comment]
@blue-fish Thank you for the suggestion. I downgraded the machine to be running Ubuntu 18.04 now with Python 3.7.5. I had completed installing PyTorch and FFMPEG, but I'm stuck on `pip3 install -r requirements_gpu.txt` Where webrtcvad is causing issues:
`    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gzlnmnxc/webrtcvad/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gzlnmnxc/webrtcvad/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qzppu8_s/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/rachnera/.local/include/python3.7m/webrtcvad
         cwd: /tmp/pip-install-gzlnmnxc/webrtcvad/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    copying webrtcvad.py -> build/lib.linux-x86_64-3.7
    running build_ext
    building '_webrtcvad' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/cbits
    creating build/temp.linux-x86_64-3.7/cbits/webrtc
    creating build/temp.linux-x86_64-3.7/cbits/webrtc/common_audio
    creating build/temp.linux-x86_64-3.7/cbits/webrtc/common_audio/signal_processing
    creating build/temp.linux-x86_64-3.7/cbits/webrtc/common_audio/vad
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWEBRTC_POSIX -Icbits -I/usr/include/python3.7m -c cbits/pywebrtcvad.c -o build/temp.linux-x86_64-3.7/cbits/pywebrtcvad.o
    cbits/pywebrtcvad.c:1:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gzlnmnxc/webrtcvad/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gzlnmnxc/webrtcvad/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qzppu8_s/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/rachnera/.local/include/python3.7m/webrtcvad Check the logs for full command output.
`

**Comment by blue-fish** [comment]
Congratulations on completing the setup! It is far from a smooth process as you experienced. You can [`pip install webrtcvad-wheels`](https://pypi.org/project/webrtcvad-wheels/) to avoid having to build webrtcvad from source.

I am going to close this issue as I believe it is resolved, if you have any further issues you are welcome to reopen it, or start a new issue. Thanks for sharing the solutions to each of the problems that you encountered, they will help others.

**Comment by MarcoDotIO** [comment]
I wanted to leave one last thing before closing, here's the link to the .whl file required for webrtcvad:
https://drive.google.com/file/d/1Sdg8iRwmjIrju-c7ikOZrkxRyPzAP0oH/view
