### ISSUE TITLE
about “the three networks training order”

### ISSUE THREAD

**Issue by sunnnnnnnny** [CorentinJ/Real-Time-Voice-Cloning#51]
The encoder and synthesiser network training has a sequential relationship, and the vocoder network is not dependent on these two networks, can be trained at any time?

**Comment by CorentinJ** [comment]
The vocoder is dependent on the synthesizer if you are training with GTA synthesized mel spectrograms (the default). This dependency is only lost if you train on ground truth spectrograms.
