### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by saran-gangster** [CorentinJ/Real-Time-Voice-Cloning#510]
File "F:\projects\real time voice cloning app\Real-Time-Voice-Cloning-master\encoder\inference.py", line 174, in plot_embedding_as_heatmap
    cbar.set_clim(*color_range)
AttributeError: 'Colorbar' object has no attribute 'set_clim'
i have tried both 3.6 and 3.7
tensorflow = 1.15
pytorch = 1.5.0
Any help? is appreciated

**Comment by blue-fish** [comment]
This is a known issue. From https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/455#issuecomment-674410447

> Workaround is to install a matplotlib version that is lower than 3.3.
> 
> ```
> pip install matplotlib==3.2.2
> ```

**Comment by blue-fish** [comment]
Closing this support request due to inactivity (it is presumed resolved). Please comment in #455 for anything related to this particular problem, or open a new issue if experiencing other difficulties.
