### ISSUE TITLE
Not able to train Synthesizer with tensorflow-gpu==1.15

### ISSUE THREAD

**Issue by satan17** [CorentinJ/Real-Time-Voice-Cloning#512]
Hi,

I've been trying to train synthesizer model but I'm getting this error "Could not load dynamic library 'libcudart.so.10.0'".   
 Cuda driver_version : 440
Cuda Version : 10.2

![Capture](https://user-images.githubusercontent.com/24227200/91488354-d0aa1000-e8cc-11ea-858f-a97d510ce28b.png)

Could you please suggest me the right version of Cuda and tensorflow which is compatible with whole project. 

Many Thanks !

**Comment by blue-fish** [comment]
Tensorflow 1.15 only supports CUDA 10.0, and you have 10.2. That setup is not trivial and I am unable to provide support for it. 

If you are training from scratch, try my pytorch fork [`472_pytorch_synthesizer`](https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/447_pytorch_synthesizer). I am trying to get it merged but the main thing holding it up is lack of a pretrained model that is on par with the tensorflow one.

**Comment by blue-fish** [comment]
@satan17 Closing as the original question has been answered, reopen this issue if you have further questions.
