### ISSUE TITLE
i am confuse with the places of folders?

### ISSUE THREAD

**Issue by afantasialiberal** [CorentinJ/Real-Time-Voice-Cloning#513]
Hello i did downloaded the LibriSpeech/train-clean-100 (tar.gz 5gb)  and extract it to the root of the app as LibriSpeech/
but i am getting this.

 python3.7 demo_toolbox.py --low_mem  -d LibriSpeech/
Arguments:
    datasets_root:    LibriSpeech
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    low_mem:          True
    seed:             None

Warning: you do not have any of the recognized datasets in LibriSpeech.
The recognized datasets are:
	LibriSpeech/dev-clean
	LibriSpeech/dev-other
	LibriSpeech/test-clean
	LibriSpeech/test-other
	LibriSpeech/train-clean-100 
	LibriSpeech/train-clean-360
	LibriSpeech/train-other-500
	LibriTTS/dev-clean
	LibriTTS/dev-other
	LibriTTS/test-clean
	LibriTTS/test-other
	LibriTTS/train-clean-100
	LibriTTS/train-clean-360
	LibriTTS/train-other-500
	LJSpeech-1.1
	VoxCeleb1/wav
	VoxCeleb1/test_wav
	VoxCeleb2/dev/aac
	VoxCeleb2/test/aac
	VCTK-Corpus/wav48
Feel free to add your own. You can still use the toolbox by recording samples yourself.
[AVAudioResampleContext @ 0x5639cd9da6c0] Invalid input channel layout: 0
[AVAudioResampleContext @ 0x5639cd9cf340] Invalid input channel layout: 0
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768

**Comment by afantasialiberal** [comment]
this is a one diierent try   

python3.7 demo_toolbox.py --low_mem  -d LibriSpeech/train-clean-100/
Arguments:
    datasets_root:    LibriSpeech/train-clean-100
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    low_mem:          True
    seed:             None

libEGL warning: DRI2: failed to authenticate
Warning: you do not have any of the recognized datasets in LibriSpeech/train-clean-100.
The recognized datasets are:
	LibriSpeech/dev-clean
	LibriSpeech/dev-other
	LibriSpeech/test-clean
	LibriSpeech/test-other
	LibriSpeech/train-clean-100
	LibriSpeech/train-clean-360
	LibriSpeech/train-other-500
	LibriTTS/dev-clean
	LibriTTS/dev-other
	LibriTTS/test-clean
	LibriTTS/test-other
	LibriTTS/train-clean-100
	LibriTTS/train-clean-360
	LibriTTS/train-other-500
	LJSpeech-1.1
	VoxCeleb1/wav
	VoxCeleb1/test_wav
	VoxCeleb2/dev/aac
	VoxCeleb2/test/aac
	VCTK-Corpus/wav48
Feel free to add your own. You can still use the toolbox by recording samples yourself.
[AVAudioResampleContext @ 0x5655461e9100] Invalid input channel layout: 0
[AVAudioResampleContext @ 0x565545d2b4c0] Invalid input channel layout: 0
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
ALSA lib pcm_dmix.c:1090:(snd_pcm_dmix_open) unable to open slave

**Comment by blue-fish** [comment]
Try `python3.7 demo_toolbox.py --low_mem -d ./`

It is looking for a folder called `LibriSpeech` within the directory that is passed to the toolbox. We need to make that warning more helpful. Let me know if you have any suggestions.

**Comment by afantasialiberal** [comment]
Oh this time it seems to work(thanks!), mmm maybe you should put that on the readme. 


now i am trying to Synthetize and vocode the default text on the box with that dataset 5561 utterance 41615  

python3.7 demo_toolbox.py --low_mem  -d ./
Arguments:
    datasets_root:    .
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    low_mem:          True
    seed:             None

libEGL warning: DRI2: failed to authenticate
[AVAudioResampleContext @ 0x5586f987ab00] Invalid input channel layout: 0
[AVAudioResampleContext @ 0x5586f993ca80] Invalid input channel layout: 0
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768


ALSA lib pcm_dmix.c:1090:(snd_pcm_dmix_open) unable to open slave
Loaded encoder "pretrained.pt" trained to step 1564501
Traceback (most recent call last):
  File "/home/cmkat/src/voiceclone/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 74, in <lambda>
    self.ui.browser_load_button.clicked.connect(lambda: self.load_from_browser())
  File "/home/cmkat/src/voiceclone/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 158, in load_from_browser
    self.add_real_utterance(wav, name, speaker_name)
  File "/home/cmkat/src/voiceclone/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 187, in add_real_utterance
    self.ui.draw_embed(embed, name, "current")
  File "/home/cmkat/src/voiceclone/Real-Time-Voice-Cloning-master/toolbox/ui.py", line 74, in draw_embed
    plot_embedding_as_heatmap(embed, embed_ax)
  File "/home/cmkat/src/voiceclone/Real-Time-Voice-Cloning-master/encoder/inference.py", line 174, in plot_embedding_as_heatmap
    cbar.set_clim(*color_range)
AttributeError: 'Colorbar' object has no attribute 'set_clim'
Found synthesizer "pretrained" trained to step 278000
multiprocess.pool.RemoteTraceback:


and at the end do nothing.

**Comment by blue-fish** [comment]
Another known issue, see #455. Workaround is to install matplotlib 3.2.2. I have been focused on the pytorch synthesizer so have not been keeping up with dependencies.

**Comment by afantasialiberal** [comment]
Oh thanks, but i did install it and did nt work but seems as it is this bug here https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/491 because the --low_mem argument, i try without it and work, now i am playing with it, seems like my 4gb ram are enough by now, but now i note the ascent on the synthetized are from english, BTW it start to be amazing congratulation to you there and thanks for your work, i have this doubt about the ascents on the results, i want bring some audio books to the internet jeje maybe can this be posible?

**Comment by blue-fish** [comment]
Closing as this issue is resolved. Thank you for sharing what worked for you @afantasialiberal .
