### ISSUE TITLE
Cannot load dataset, they're greyed out.

### ISSUE THREAD

**Issue by theheartbenvn** [CorentinJ/Real-Time-Voice-Cloning#514]
I'm a bit noob at this, please excuse me if i made any mistakes.
I believe that upon launch, i should be able to load and pick datasets, but on my side, when i launched the app, the whole section of datasets are greyed out. Is this supposed to happen?
![image](https://user-images.githubusercontent.com/16258774/91665753-275c5780-eb22-11ea-9cdd-f0a5f631a658.png)

**Comment by blue-fish** [comment]
In the GUI you can see this text: `Warning: you did not pass a root directory for datasets as argument`

You need to launch the toolbox with the following command, where datasets_root is the parent folder containing your LibriSpeech or other supported dataset.
```
python demo_toolbox.py -d path/to/datasets_root
```

**Comment by theheartbenvn** [comment]
Ah okay, i got it. Thanks.

**Comment by Franchize27** [comment]
I have specified the directory for the data roots and still no luck
