### ISSUE TITLE
ERROR: No matching distribution found for tensorflow==1.15

### ISSUE THREAD

**Issue by therealjr** [CorentinJ/Real-Time-Voice-Cloning#516]
I'm trying to install the prerequisites but am unable to install tensorflow version 1.15. Does anyone have a workaround? Using python3-pip.

**Comment by xbogdan** [comment]
https://stackoverflow.com/questions/61491893/i-cannot-install-tensorflow-version-1-15-through-pip

**Comment by blue-fish** [comment]
This is a known issue, please see https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-665165023

**Comment by blue-fish** [comment]
Presumed resolved. @therealjr reopen this issue, or start a new issue if you are still having trouble setting up the toolbox.
