### ISSUE TITLE
Requesting Wiki Write access

### ISSUE THREAD

**Issue by mbdash** [CorentinJ/Real-Time-Voice-Cloning#518]
@CorentinJ @blue-fish 

Hi, I would like to create some wiki pages with detailed install instructions. 
I already created documentation for myself in my personal Confluence, I'd like to share with the community.

**Comment by mbdash** [comment]
Here is a documentation sample:

[Ubuntu20.04-Setup-NvidiaDrivers-020920-1812.pdf](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/5164052/Ubuntu20.04-Setup-NvidiaDrivers-020920-1812.pdf)

My aim would be to document how to get setup with this library step by step for Ubuntu20.04 and MiniConda.

I plan on installing the lib on other VMs so I would tweak the documentation I already created for myself in the process and share is with the community.

**Comment by blue-fish** [comment]
I support this request since we need better documentation. Would you also agree to help maintain the installation guides that you create?

Setup will become a lot easier when we merge #472, and when that happens the documentation should also reflect that.

**Comment by CorentinJ** [comment]
I've sent an invite

**Comment by mbdash** [comment]
Accepted, thank you.

@blue-fish I will try my best.
