### ISSUE TITLE
AttributeError: module 'umap' has no attribute 'UMAP' on Windows 10

### ISSUE THREAD

**Issue by lawrence124** [CorentinJ/Real-Time-Voice-Cloning#519]
not sure if it is a platform specific problem, all umap import would need to be changed to this format:
import umap.umap_ as umap

to resolve this problem from multiple files:
AttributeError: module 'umap' has no attribute 'UMAP'

**Comment by blue-fish** [comment]
Thank you for sharing @lawrence124 , I do not know exactly what conditions are needed for this to be a problem.
This is also reported in #435 and more information is available here: https://github.com/lmcinnes/umap/issues/24

**Comment by lawrence124** [comment]
a bit more info, it was a clean install that i followed closely with this guide:
https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/

**Comment by blue-fish** [comment]
Now I am getting this issue after #517. Something in this commit is responsible: https://github.com/blue-fish/Real-Time-Voice-Cloning/commit/14c3646e1737d0a71b7f12077fba38dcd1eee4ef

**Comment by blue-fish** [comment]
Actually this is not the case. I was using a different venv which had `umap` installed (in addition to the correct package `umap-learn`) , clearing pycache fixed it.
