### ISSUE TITLE
No matching distribution found for tensorflow==1.15

### ISSUE THREAD

**Issue by franciscojuan1974** [CorentinJ/Real-Time-Voice-Cloning#523]
I can't install this.

pip install tensorflow==1.15

Result:
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.15

the latest version lauch a error like:

File "C:\Users\...\Python\Real-Time-Voice-Cloning-master\synthesizer\models\helpers.py", line 3, in <module>
    from tensorflow.contrib.seq2seq import Helper
ModuleNotFoundError: No module named 'tensorflow.contrib'

ANY IDEA to solve this?

**Comment by rlutsyshyn** [comment]
mb you use python 3.8+ but TF v.1.X.X have to be installed on python<= 3.7

**Comment by franciscojuan1974** [comment]
I have Pyton 3.8.5
I think tensorflow version 1.15 was removed.

"pip install tensorflow==1.15"
I can install tensorflow > 2.2 but not 1.15

If there are any alternatives to build project with version >2, that would be fantastic or others ways to install tensorflow 1.15.

**Comment by rlutsyshyn** [comment]
You can just install Python <= 3.7 and don't have any problems or can refactored code to get transfer from tf.v.1.X to v.2.X. In my opinion is more efficient to create a new virtual env with python 3.7...

**Comment by franciscojuan1974** [comment]
Tomorrow I'll test that. Thanks rlutsyshyn. :)

**Comment by franciscojuan1974** [comment]
With Python 3.7.1 works. Great !!
