### ISSUE TITLE
 No such file or directory: 'synthesizer\\saved_models\\pretrained\\pretrained.pt'

### ISSUE THREAD

**Issue by EthanZoneCoding** [CorentinJ/Real-Time-Voice-Cloning#524]
No such file or directory: 'synthesizer\\saved_models\\pretrained\\pretrained.pt'. The encoder and vocoder have one, but where is it for the synthisiser?

That was run frum demo_cli.py.
demo_toolkit.py throws:
Exception: No synthesizer models found in synthesizer\saved_models

**Comment by EthanZoneCoding** [comment]
The only thing in there is a "logs-pretrained" folder

**Comment by blue-fish** [comment]
Hi @EthanZoneCoding , I take it you are running the PyTorch synthesizer from #472? The pretrained model in `logs-pretrained` is Tensorflow-based and will not work.

Take the file linked in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/449#issuecomment-674420484 and save it as `synthesizer/saved_models/pretrained/pretrained.pt` It is not a very good model. I've made some progress towards better models but still trying to improve the similarity and quality of the output voices.

You will get a better result with the toolbox if you use Corentin's repo and set up tensorflow, but it can be hard on some systems.

**Comment by EthanZoneCoding** [comment]
Thank you, that worked!

**Comment by SmartPoly1** [comment]
file link is broken

**Comment by Anirban600** [comment]
Again all the links are broken. Can anyone upload the "synthesizer\\saved_models\\pretrained\\pretrained.pt" file in google drive or onedrive please...

**Comment by MdAamirShuaib** [comment]
yes the link is broken. can anyone please upload the "synthesizer\saved_models\pretrained\pretrained.pt" file

**Comment by Anirban600** [comment]
You will find all the original pretrained files here, https://drive.google.com/drive/folders/1lb-LlS8Sx9RqcGzuV6GxvKHk-PC9TqQx?usp=sharing

**Comment by MdAamirShuaib** [comment]
Thank you!
this link works.
