### ISSUE TITLE
can't pickle tensorflow

### ISSUE THREAD

**Issue by AntINFINAit** [CorentinJ/Real-Time-Voice-Cloning#529]
I have tried the main repository, and i get the error that "self" is not defined. There was an issue about this, so i used the branch from that fix. Now i am getting:
**raceback (most recent call last):
  File "demo_cli.py", line 93, in <module>
    mels = synthesizer.synthesize_spectrograms(texts, embeds)
  File "D:\RealTimeDeepFake\voice\Real-Time-Voice-Cloning\Real-Time-Voice-Cloning\synthesizer\inference.py", line 101, in synthesize_spectrograms
    [(self.checkpoint_fpath, embeddings, texts, self._seed)])[0]
  File "C:\Users\fnafm\AppData\Local\Programs\Python\Python37\lib\site-packages\multiprocess\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\fnafm\AppData\Local\Programs\Python\Python37\lib\site-packages\multiprocess\pool.py", line 657, in get
    raise self._value
multiprocess.pool.MaybeEncodingError: Error sending result: '<multiprocess.pool.ExceptionWithTraceback object at 0x00000250FDB07DC8>'. Reason: 'TypeError("can't pickle tensorflow_core.python._tf_stack.Stack objects")'**

I have tried using conda environment with python 3.7, and also, plain python, following this procedure : https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/

My hardware really sucks and i can't run linux. I am stuck with live sessions and windows. 
How can i fix the issue?

**Comment by blue-fish** [comment]
Hi @AntINFINAit , thank you for reporting this issue. As a workaround, remove the `seed` argument from this line:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/8f71d678d2457dffc4d07b52e75be11433313e15/synthesizer/inference.py#L109

That is, change it to:
```
model = Tacotron2(checkpoint_fpath, hparams) 
```

You will be not have the ability to force deterministic synthesis, but at least it should run. If you need that feature, try the [`423_add_cpu_mode`](https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/423_add_cpu_mode) branch of my fork, and change the `--low_mem` argument to `--cpu`.

**Comment by AntINFINAit** [comment]
The issue is that "self" does not appear to be referenced in this python. That is why i used your other branch. How can i fix that error?

**Comment by blue-fish** [comment]
I should have been a little more clear, you should be able to make the above change on Corentin's master and it should also resolve the "self" issue by not referencing it.

Since you're using my fork as the starting point, try replacing `seed=self._seed` with `seed=None` in this line:
https://github.com/blue-fish/Real-Time-Voice-Cloning/blob/8e4a0565544d0ae6ee3d22518961a28ed88eba5e/synthesizer/inference.py#L100-L101

If that doesn't work then try the CPU mode since that bypasses the low_mem code that is giving you issues.

**Comment by blue-fish** [comment]
@AntINFINAit Are you still experiencing this problem?

**Comment by AntINFINAit** [comment]
I am giving up on this. Windows just isn't good. If it weren't for my shit hardware, i could run linux like any normal person.
I'd much rather have windows in a box with visual studio than the other way around. 
Thank you for the help.
