### ISSUE TITLE
fixing pyqt5 and matplotlib issues - ImportError: Failed to import any qt binding

### ISSUE THREAD

**Issue by quarterturn** [CorentinJ/Real-Time-Voice-Cloning#532]
I had this all working fine for a while and somewhere along the way an 'apt upgrade' or 'apt autoremove' broke pyqt5 and/or matplotlib. Trying to run the 'demo_toolbox.py" results in:

`
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "/home/alex/Downloads/Real-Time-Voice-Cloning/toolbox/__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "/home/alex/Downloads/Real-Time-Voice-Cloning/toolbox/ui.py", line 1, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_qt5.py", line 16, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/qt_editor/figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/qt_compat.py", line 175, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
`

I've tried reinstalling libqt5gui4, python3-pyqt5, pyqt5, and matplotlib to no avail. This is Ubuntu 18.04.

matplotlib with Agg is fine:
`
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('Agg')
>>> import matplotlib.pyplot as plt
>>> exit()
`

without segfaults:
`
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> import matplotlib.pyplot as plt
Segmentation fault (core dumped)
`

CUDA 10.1 and Tensorflow 1.15 is OK as I can still run stylegan2 (it has no GUI).

**Comment by quarterturn** [comment]
Fixed the segfault issue with matplotlib by uninstalling the 3.x version and installing 2.2.5.

**Comment by quarterturn** [comment]
`
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('Qt5Agg')
>>> from PyQt5 import QtCore, QtWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/local/lib/python3.6/dist-packages/PyQt5/QtCore.abi3.so)

`

**Comment by quarterturn** [comment]
final fix:

`sudo apt install --reinstall libqt5gui5`

**Comment by hvaddi9** [comment]
When I run demo_cli.py, I get this error 16262 segmentation fault (core dumped)  python demo_cli.py

Reinstalling libqt5gui5 is working only once, and the issue comes back again. 
So, I'm reinstalling libqt5gui5 every time I run the demo.
