### ISSUE TITLE
Testing Demo_cli.py

### ISSUE THREAD

**Issue by Kurokawa-san** [CorentinJ/Real-Time-Voice-Cloning#533]
I installed everything and double checked, but when I ran "python demo_cli.py --low_mem" it says:
Librosa will be unable to open mp3 files if additional software is not installed.
Please install ffmpeg or add the '--no_mp3_support' option to proceed without support for mp3 files.
Librosa and ffmpeg were already installed how do i fix this?

**Comment by blue-fish** [comment]
You can either disable mp3 support with:
```
python demo_cli.py --low_mem --no_mp3_support
```

Or if you want mp3 support, you likely need to add ffmpeg to your path (see the "edit environment variables" section of: https://video.stackexchange.com/a/20496 ).

**Comment by blue-fish** [comment]
@Kurokawa-san Is this resolved?

**Comment by Kurokawa-san** [comment]
> @Kurokawa-san Is this resolved?

Yes, it works perfectly now, thanks

**Comment by blue-fish** [comment]
Glad to hear it, please feel free to open another issue if you experience another problem or have questions about the repo.

**Comment by athifongoqa** [comment]
I've installed ffmpeg and added its path to my environment variables but I still see this error. Any suggestions?
