### ISSUE TITLE
Error installing tensorflow

### ISSUE THREAD

**Issue by TwashMan** [CorentinJ/Real-Time-Voice-Cloning#534]
Using python version 3.7.1. Attempting to install tensorflow and only tensorflow (everything else within the text file seems to install fine) gives error: 
```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Comment by blue-fish** [comment]
@TwashMan It's highly likely you are using a 32-bit python, and tensorflow only supports 64-bit. Please install a 64-bit python and try again.

**Comment by TwashMan** [comment]
> @TwashMan It's highly likely you are using a 32-bit python, and tensorflow only supports 64-bit. Please install a 64-bit python and try again.

You were right i was using a 32-bit version of python so i installed the 64 bit version and deleted the 32 bit version.
It didn't seem to change anything though.
![image](https://user-images.githubusercontent.com/72085916/94588802-b45f1180-0284-11eb-8e38-85f51f370eca.png)

**Comment by TwashMan** [comment]
I feel so dumb... i spelt it wrong.. But i definetly did have a 32-bit version so thank you very much for informing me of that!
