### ISSUE TITLE
Where can I learn all of this?

### ISSUE THREAD

**Issue by ak57u** [CorentinJ/Real-Time-Voice-Cloning#542]
Very interested in how AI voice cloning works but the subject is shrouded in so much ambiguity that I don't even know where to start.
My goal is not speech synthesis from text but speech synthesis from other speech (like a voice changer that makes you sound like Morgan Freeman) but I don't even know where to begin.

You think you can point me to where you picked up on YOUR journey?

**Comment by blue-fish** [comment]
I've had a great experience following Corentin's instructions for reproducing the synthesizer and vocoder training: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training Once you get the hang of it, try modifying the parameters and using different datasets with it. Do some experimentation and use the papers in the README for reference.

Next, pick some kind of a project, like training a synthesizer model in a different language, and you will learn from solving the problems as they come up.

If you want to skip straight to voice style transfer, check out [AutoVC](https://github.com/auspicious3000/autovc) or [SpeechSplit](https://github.com/auspicious3000/SpeechSplit). That community is not as developed as TTS so you may have a harder time getting help.

**Comment by ak57u** [comment]
> I've had a great experience following Corentin's instructions for reproducing the synthesizer and vocoder training: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training Once you get the hang of it, try modifying the parameters and using different datasets with it. Do some experimentation and use the papers in the README for reference.
> 
> Next, pick some kind of a project, like training a synthesizer model in a different language, and you will learn from solving the problems as they come up.
> 
> If you want to skip straight to voice style transfer, check out [AutoVC](https://github.com/auspicious3000/autovc) or [SpeechSplit](https://github.com/auspicious3000/SpeechSplit). That community is not as developed as TTS so you may have a harder time getting help.

**Comment by ak57u** [comment]
> I've had a great experience following Corentin's instructions for reproducing the synthesizer and vocoder training: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training Once you get the hang of it, try modifying the parameters and using different datasets with it. Do some experimentation and use the papers in the README for reference.
> 
> Next, pick some kind of a project, like training a synthesizer model in a different language, and you will learn from solving the problems as they come up.
> 
> If you want to skip straight to voice style transfer, check out [AutoVC](https://github.com/auspicious3000/autovc) or [SpeechSplit](https://github.com/auspicious3000/SpeechSplit). That community is not as developed as TTS so you may have a harder time getting help.

Thank you very much!
