### ISSUE TITLE
Lack of pre-compiled results in lost interest

### ISSUE THREAD

**Issue by drats666** [CorentinJ/Real-Time-Voice-Cloning#543]
so I know the first thing people are going to say is, this isn't an issue. However, it is. by not having a precompiled version to download over half the people that find their way to this GitHub are going to lose interest.  Honestly, I'm one of them. I attempted to compile it but then I saw that I had to track down each module for this, yeah quickly drove me away from it.  all I wanted to do was mess around and see what it can do. even if the results arent mind-blowing the concept interests me.  but due to not having a ready to use executable I like many others I'm sure of, have decided it isn't even worth messing with.

**Comment by blue-fish** [comment]
Hi there @drats666 , thank you for taking the time to share your perspective. I can relate to this because there are a great deal of interesting repos but there's usually some obstacle and I decide that it's not worth hours of my time to set up.

We actually have an issue for this: #267 and it's the only one marked "help wanted" to draw special attention to it. I don't have Windows, but someone who does can run [PyInstaller](https://www.pyinstaller.org/) on demo_toolbox.py and upload the result.

**Comment by drats666** [comment]
Well, I  tried to compile it using pyinstaller. however the dist it creates opens then instantly closes.

**Comment by blue-fish** [comment]
@drats666 You might be close! #546 was merged yesterday and fixes a bug where the toolbox opens and instantly closes. Please make sure you have the latest code and try again.

**Comment by drats666** [comment]
eh, seems like that isnt the issue. pyinstall seems to have missed a bunch of modules. 
`
This file lists modules PyInstaller was not able to find. This does not
necessarily mean this module is required for running you program. Python and
Python 3rd-party packages include a lot of conditional or optional modules. For
example the module 'ntpath' only exists on Windows, whereas the module
'posixpath' only exists on Posix systems.

Types if import:
* top-level: imported at the top-level - look at these first
* conditional: imported within an if-statement
* delayed: imported from within a function
* optional: imported within a try-except-statement

IMPORTANT: Do NOT post this list to the issue-tracker. Use it as a basis for
           yourself tracking down the missing module. Thanks!

missing module named _scproxy - imported by urllib.request (conditional)
missing module named termios - imported by tty (top-level), getpass (optional)
missing module named pwd - imported by posixpath (delayed, conditional), shutil (optional), tarfile (optional), pathlib (delayed, conditional, optional), http.server (delayed, optional), webbrowser (delayed), netrc (delayed, conditional), getpass (delayed), distutils.util (delayed, conditional, optional)
missing module named org - imported by copy (optional)
missing module named _posixshmem - imported by multiprocessing.resource_tracker (conditional), multiprocessing.shared_memory (conditional)
missing module named asyncio.DefaultEventLoopPolicy - imported by asyncio (delayed, conditional), asyncio.events (delayed, conditional)
missing module named posix - imported by os (conditional, optional), shutil (conditional)
missing module named resource - imported by posix (top-level), test.support (optional)
missing module named grp - imported by shutil (optional), tarfile (optional), pathlib (delayed)
missing module named vms_lib - imported by platform (delayed, conditional, optional)
missing module named 'java.lang' - imported by platform (delayed, optional), xml.sax._exceptions (conditional)
missing module named java - imported by platform (delayed)
missing module named _winreg - imported by platform (delayed, optional)
excluded module named _frozen_importlib - imported by importlib (optional), importlib.abc (optional), zipimport (top-level)
missing module named _frozen_importlib_external - imported by importlib._bootstrap (delayed), importlib (optional), importlib.abc (optional), zipimport (top-level)
missing module named readline - imported by cmd (delayed, conditional, optional), code (delayed, conditional, optional), pdb (delayed, optional)
missing module named 'org.python' - imported by pickle (optional), xml.sax (delayed, conditional)
missing module named multiprocessing.get_context - imported by multiprocessing (top-level), multiprocessing.pool (top-level), multiprocessing.managers (top-level), multiprocessing.sharedctypes (top-level)
missing module named multiprocessing.TimeoutError - imported by multiprocessing (top-level), multiprocessing.pool (top-level)
missing module named multiprocessing.BufferTooShort - imported by multiprocessing (top-level), multiprocessing.connection (top-level)
missing module named multiprocessing.AuthenticationError - imported by multiprocessing (top-level), multiprocessing.connection (top-level)
missing module named win32evtlog - imported by logging.handlers (delayed, optional)
missing module named win32evtlogutil - imported by logging.handlers (delayed, optional)
missing module named _posixsubprocess - imported by subprocess (optional), multiprocessing.util (delayed)
missing module named multiprocessing.set_start_method - imported by multiprocessing (top-level), multiprocessing.spawn (top-level)
missing module named multiprocessing.get_start_method - imported by multiprocessing (top-level), multiprocessing.spawn (top-level)
missing module named numpy - imported by encoder.model (top-level), encoder.audio (top-level), encoder.inference (top-level), toolbox.ui (top-level), synthesizer.models.helpers (top-level), synthesizer.models.tacotron (top-level), synthesizer.utils.plot (top-level), synthesizer.audio (top-level), synthesizer.tacotron2 (top-level), synthesizer.inference (top-level), vocoder.distribution (top-level), vocoder.display (top-level), vocoder.audio (top-level), toolbox (top-level), utils.argutils (top-level)
missing module named webrtcvad - imported by encoder.audio (optional), toolbox (delayed, optional)
missing module named audioread - imported by toolbox (top-level)
missing module named librosa - imported by encoder.audio (top-level), synthesizer.audio (top-level), synthesizer.inference (top-level), vocoder.audio (top-level), toolbox (top-level)
missing module named torch - imported by encoder.model (top-level), encoder.inference (top-level), synthesizer.models.modules (top-level), vocoder.models.fatchord_version (top-level), vocoder.distribution (top-level), vocoder.inference (top-level), toolbox (top-level)
missing module named lws - imported by synthesizer.audio (delayed)
missing module named 'scipy.io' - imported by synthesizer.audio (top-level)
missing module named scipy - imported by encoder.model (top-level), synthesizer.audio (top-level)
missing module named tensorflow - imported by synthesizer.models.tacotron (top-level), synthesizer.models.helpers (top-level), synthesizer.models.modules (top-level), synthesizer.models.architecture_wrappers (top-level), synthesizer.models.attention (top-level), synthesizer.models.custom_decoder (top-level), synthesizer.audio (top-level), synthesizer.tacotron2 (top-level), synthesizer.inference (top-level)
missing module named 'librosa.filters' - imported by synthesizer.audio (top-level)
missing module named 'tensorflow.contrib' - imported by synthesizer.models.helpers (top-level), synthesizer.models.tacotron (top-level), synthesizer.models.attention (top-level), synthesizer.models.architecture_wrappers (top-level), synthesizer.models.custom_decoder (top-level), synthesizer.hparams (top-level)
missing module named 'scipy.signal' - imported by vocoder.audio (top-level)
missing module named 'matplotlib.pyplot' - imported by encoder.inference (top-level), synthesizer.utils.plot (top-level), vocoder.display (top-level)
missing module named 'torch.nn' - imported by vocoder.models.fatchord_version (top-level), vocoder.distribution (top-level)
missing module named numba - imported by synthesizer.inference (top-level)
missing module named 'multiprocess.context' - imported by synthesizer.inference (top-level)
missing module named multiprocess - imported by synthesizer.inference (top-level)
missing module named matplotlib - imported by toolbox.ui (top-level), encoder.inference (top-level), synthesizer.utils.plot (top-level)
missing module named inflect - imported by synthesizer.utils.numbers (top-level)
missing module named unidecode - imported by synthesizer.utils.cleaners (top-level)
missing module named 'tensorflow.python' - imported by synthesizer.models.attention (top-level), synthesizer.models.architecture_wrappers (top-level), synthesizer.models.custom_decoder (top-level)
missing module named 'scipy.ndimage' - imported by encoder.audio (top-level)
missing module named 'scipy.optimize' - imported by encoder.model (top-level)
missing module named sklearn - imported by encoder.model (top-level)
missing module named umap - imported by toolbox.ui (top-level)
missing module named soundfile - imported by toolbox.ui (top-level)
missing module named sounddevice - imported by toolbox.ui (top-level)
missing module named 'PyQt5.QtWidgets' - imported by toolbox.ui (top-level)
missing module named PyQt5 - imported by toolbox.ui (top-level)
missing module named 'matplotlib.figure' - imported by toolbox.ui (top-level)
missing module named 'matplotlib.backends' - imported by toolbox.ui (top-level)
`

which may or may not bring me back to my original post.

**Comment by blue-fish** [comment]
You'll need to install the requirements to get the modules.
```
python3 -m pip install pip --upgrade
python3 -m pip install torch
python3 -m pip install -r requirements.txt
```

**Comment by blue-fish** [comment]
Also, since python is interpreted, there's no need to compile the code in order to use it. You do have to track down the dependencies, but it should not be too hard with pip and requirements.txt.

If you succeed in compiling the toolbox, then it would save others the trouble of installing and configuring python. Thanks for giving it a shot.

**Comment by drats666** [comment]
eh as I feared. that brings me back to my original post. not worth the trouble sorry.

**Comment by CorentinJ** [comment]
> but due to not having a ready to use executable I like many others I'm sure of, have decided it isn't even worth messing with.

And you wouldn't entirely be wrong. You would have had an easier experience with a team of dedicated developers maintaining the repo at least 20 hours a week, but that is just not the case. The generation quality is poor and hasn't improved one bit since I made the project public, and there is little motivation to make the project easier of access before that is worked on. Hence the disclaimer in the readme.
