### ISSUE TITLE
Please install ffmpeg or add the '--no_mp3_support' option to proceed without support for mp3 files.

### ISSUE THREAD

**Issue by varungolusupudi** [CorentinJ/Real-Time-Voice-Cloning#544]
I typed python .\demo_toolbox.py in the cmd. 
After that, I getting this error message:
"Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    low_mem:          False
    seed:             None
    no_mp3_support:   False

Librosa will be unable to open mp3 files if additional software is not installed.
Please install ffmpeg or add the '--no_mp3_support' option to proceed without support for mp3 files."
Please guide me!

**Comment by varungolusupudi** [comment]
I got it! Just referred to this issue #533

**Comment by blue-fish** [comment]
I'm glad it's working for you now @varungolusupudi. Did you resolve it with `--no_mp3_support` or by adding ffmpeg to your path?
