### ISSUE TITLE
Encoder training does not use GPU

### ISSUE THREAD

**Issue by padmalcom** [CorentinJ/Real-Time-Voice-Cloning#548]
Hi, I have a TITAN RTX and Cuda 10.2 installed correctly on my system. Nevertheless, the encoder training happens on CPU. Is there a way to make it use the GPU? I could not find any option.

**Comment by blue-fish** [comment]
It's autodetected. Encoder training uses GPU if `torch.cuda.is_available()` is True.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/e32cf8f4ddb63d9a7603eeb31f1855b54926aee6/encoder/train.py#L30

**Comment by padmalcom** [comment]
Thanks, so I guess it should be used then....

**Comment by blue-fish** [comment]
Open up python and type the following. Does it return True? If not you'll have to troubleshoot your installation.
```
import torch
torch.cuda.is_available()
```
