### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by jay-1104** [CorentinJ/Real-Time-Voice-Cloning#549]
Hey, i am trying to run this code and everytime i run demo_toolbox.py there comes an error "failed to load qt binding" i tried reinstalling matplotlib and also tried installing PYQt5 . 

Need Help !!!

**Comment by blue-fish** [comment]
Which operating system are you using? Can you provide the output of `pip freeze` so we know the version of packages you are using?

**Comment by jay-1104** [comment]
hey @blue-fish , i am using windows 10 OS.

Output of pip freeze : 
C:\Users\jayas>pip freeze
absl-py==0.10.0
astor==0.8.1
astroid==2.4.2
certifi==2020.6.20
colorama==0.4.3
cycler==0.10.0
gast==0.2.2
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
importlib-metadata==2.0.0
isort==5.5.4
joblib==0.17.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
llvmlite==0.31.0
Markdown==3.3
matplotlib==3.3.2
mccabe==0.6.1
numba==0.48.0
numpy==1.19.2
opt-einsum==3.3.0
Pillow==7.2.0
protobuf==3.13.0
pylint==2.6.0
pyparsing==2.4.7
PyQt5==5.15.1
PyQt5-sip==12.8.1
python-dateutil==2.8.1
scipy==1.5.2
six==1.15.0
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
threadpoolctl==2.1.0
toml==0.10.1
typed-ast==1.4.1
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.3.0

Please do needfull, i require it urgently

**Comment by blue-fish** [comment]
I didn't notice anything unusual in the pip freeze output, except you'll also need torch. However, installing torch is not going to solve your PyQt5 problem, which I don't know how to troubleshoot.

If you're looking for something to try, you could download [Anaconda 64-bit](https://www.anaconda.com/products/individual#Downloads) and follow the [wiki instructions](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Installation-Ubuntu-20.04---Installing-RTVC#setup-a-conda-workspace) for setup. If you still experience PyQt issues with Anaconda see this: https://stackoverflow.com/questions/42497689

**Comment by jay-1104** [comment]
Hello @blue-fish , i have checked everything and i found that there is line in the demo_toolbox stating "import toolbox from TOOLBOX" . 
But there is no TOOLBOX folder in the code , resulting in the import error !!

Please check it

**Comment by blue-fish** [comment]
@jay-1104 Toolbox is a class, it's defined here in `__init.py__` in the toolbox folder: https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/e32cf8f4ddb63d9a7603eeb31f1855b54926aee6/toolbox/__init__.py#L42

If you're missing the toolbox folder then your copy of the repository is damaged and you should download it again.
