### ISSUE TITLE
No torch version in requirements.txt

### ISSUE THREAD

**Issue by mrgloom** [CorentinJ/Real-Time-Voice-Cloning#55]
No torch version in requirements.txt

**Comment by mrgloom** [comment]
Seems to work with:

```
pip freeze | grep torch
torch==1.1.0
torchfile==0.1.0
torchvision==0.3.0
```

**Comment by CorentinJ** [comment]
I won't add torch to requirements.txt because the authors prefer you install it from the website. It will fail through pip, for example. I've added the version in the readme: 81ee160d46b11770d11b950895810c7793988873
