### ISSUE TITLE
using embedding from a specific wav file sounds nothing like it in output

### ISSUE THREAD

**Issue by arceuss** [CorentinJ/Real-Time-Voice-Cloning#550]
im trying to recreate the scout from tf2s voice but the output sounds absolutely nothing like him

**Comment by blue-fish** [comment]
Can you post the file you are using to create the embedding, and the output you get from the toolbox? You can attach zip files here.

**Comment by arceuss** [comment]
[Real-Time-Voice-Cloning.zip](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/5351560/Real-Time-Voice-Cloning.zip)
here you go

**Comment by arceuss** [comment]
im using a fresh install with the pretrained models

**Comment by blue-fish** [comment]
The models are not that great, especially when the input file is nothing like an audiobook (which is where the training data came from). Try a few different voice samples and see if you get better results. Also certain voices are too far away from the training voices so it's unable to generalize.

**Comment by arceuss** [comment]
i tried with alot of samples and its still not accurate

**Comment by blue-fish** [comment]
I'm not surprised. Open-source voice cloning is bad quality at present.

**Comment by blue-fish** [comment]
If you have a lot of samples, and can make transcripts, it is possible to finetune a single-speaker model with about 20 minutes of data. That works a lot better. See #437 if interested.

**Comment by arceuss** [comment]
there is already transcripts on the tf2 wiki

**Comment by blue-fish** [comment]
Great, then you'll have everything you need if you decide to pursue this. Ask questions if you get stuck

**Comment by arceuss** [comment]
im in school right now but ill make sure to try it when im home

**Comment by arceuss** [comment]
i dont really know how to train since im new at this lol

**Comment by blue-fish** [comment]
Start here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training

Here I break it down into some bite-sized steps to help you get started. You have to really want it because it's not a simple task. But if you are sufficiently motivated it is doable.

1. Download the datasets for the synthesizer
2. Preprocess the data
3. Start training a model
    * Either from scratch or continuing the training of the pretrained model.
    * Confirm you can run the scripts. Get the training to run for a small number of steps.
    * Look at the outputs it produces.
4. Gather and preprocess your own dataset
    * Assemble your wavs and texts in this format: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538
5. Train your own model (usually more productive to finetune the pretrained model)

**Comment by arceuss** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'synthesizer/saved_models/logs-singlespeaker/datasets_root/SV2TTS/synthesizer\\SV2TTS\\synthesizer\\train.txt'
using windows 10 btw

**Comment by blue-fish** [comment]
If you get an error message, please also share the command you were attempting to use. Try removing SV2TTS/synthesizer from the command you were using.

**Comment by arceuss** [comment]
thank you that fixed it

**Comment by arceuss** [comment]
ok i did all the processing stuff what now
it still doesnt sound like scout

**Comment by arceuss** [comment]
oh i didnt do a custom dataset yet im smart lol

**Comment by arceuss** [comment]
`python synthesizer_preprocess_audio.py  synthesizer/saved_models/logs-singlespeaker/datasets_root
2020-10-09 15:35:30.305837: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Arguments:
    datasets_root:   synthesizer\saved_models\logs-singlespeaker\datasets_root
    out_dir:         synthesizer\saved_models\logs-singlespeaker\datasets_root\SV2TTS\synthesizer
    n_processes:     None
    skip_existing:   False
    hparams:
    no_alignments:   False
    datasets_name:   LibriSpeech
    subfolders:      train-clean-100, train-clean-360

Using data from:
    synthesizer\saved_models\logs-singlespeaker\datasets_root\LibriSpeech\train-clean-100
    synthesizer\saved_models\logs-singlespeaker\datasets_root\LibriSpeech\train-clean-360
LibriSpeech:   0%|                                                                                                                                                                                              | 0/1 [00:00<?, ?speakers/s]2020-10-09 15:35:36.352287: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-09 15:35:36.354889: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-09 15:35:36.387177: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-09 15:35:36.408799: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-09 15:35:36.413293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-09 15:35:36.444144: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
LibriSpeech: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.86s/speakers]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "C:\Users\arceus\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 49, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence`
huh

**Comment by blue-fish** [comment]
You get that error message when it didn't find anything to process. Make sure that when you add wavs, they are at the right level in that folder structure (see https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538 for guidance) and there is a corresponding text file for each wav.

**Comment by blue-fish** [comment]
Also, in synthesizer/hparams.py, there are 2 settings of interest:
```
max_mel_frames = 900            # frames, or 11.25 seconds. The preprocess script discards anything longer than this.
utterance_min_duration = 1.6    # seconds. Anything less than this is discarded by preprocess.
```

**Comment by blue-fish** [comment]
@arceuss I hope that worked for you. With the repo in its current state, the result you get through the finetuning process is as good as it will get. To further improve the quality is a huge task, one I've been working on for months now. Reopen the issue if you're still stuck.

**Comment by arceuss** [comment]
ok so i finally made my own dataset
