### ISSUE TITLE
Cannot find tensorflow==1.15 or tensorflow-gpu==1.15

### ISSUE THREAD

**Issue by TBNRregs** [CorentinJ/Real-Time-Voice-Cloning#552]
I tried to run with the new version of tensorflow and didn't worked "ModuleNotFoundError: No module named 'tensorflow.contrib'" and I couldn't find it so I tried to install the other version so yeah I am struck https://i.imgur.com/E3nxPC4.png
Any good help is appreciated

**Comment by blue-fish** [comment]
You either need to:
1. Downgrade your Python to 3.7 to get tensorflow==1.15, or 
2. Use the experimental [pytorch-only repo](https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/447_pytorch_synthesizer) + [pretrained model](https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/472#issuecomment-695206377)

**Comment by TBNRregs** [comment]
well another problem https://i.imgur.com/lpG547R.png
