### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1,401) (0,)

### ISSUE THREAD

**Issue by Jesper117** [CorentinJ/Real-Time-Voice-Cloning#553]

**Comment by blue-fish** [comment]
Please post the command you were trying to run, and the full traceback

**Comment by Jesper117** [comment]
I was trying to import an mp3, recording will return this error as well.

**Comment by blue-fish** [comment]
If you would like support with this, please copy and paste the full error message (the "traceback") from the terminal. From what you've provided there's not enough information to determine which file is erroring out and why.

**Comment by blue-fish** [comment]
Please reopen the issue when able to provide the requested information.
