### ISSUE TITLE
Generate a speech which still keep the speaker's speaking rate

### ISSUE THREAD

**Issue by CYT823** [CorentinJ/Real-Time-Voice-Cloning#559]
I've gotten some good results with this project. It is really amazing!

However, as title, is keeping speaker's speaking rate achievable during generating?
I knew that there's an optimum length of input text(too short: the voice will be stretched out with pauses; too long: the voice will be rushed).

e.g., there are 5 people A, B, C, D, and E. Their speaking rates are different.
#### My input sentences are: 
>Please call Stella. Ask her to bring these things with her from the store:
>Six spoons of fresh snow peas, five thick slabs of blue cheese, and maybe a snack for her brother Bob.
>We also need a small plastic snake and a big toy frog for the kids.
>She can scoop these things into three red bags, and we will go meet her Wednesday at the train station.

I expected to get 5 different length of output voice.
However, all of the output utterances are 17-19 seconds.

That's the reason why I'm curious. Is it possible to keep speaker's speaking rate?
If it is, could anyone tell me how to make it or give me a hint?
Should I change the encoder for capturing more speaker's features, or I need to modify on synthesizer?

Thanks in advance for anyone's reply.

**Comment by blue-fish** [comment]
I'd expect the speech rate is a hard-to-untangle function of the speaker embedding + the specific input sequence + which elements get affected by the random dropout during inference. This is because the prosody is inconsistent between speakers (and even between utterances for a given speaker) in the LibriSpeech dataset that is used for training.

The easiest way is to postprocess and resample the wav to a different length, in such a way that the pitch is preserved. It is a common operation but if you find a way of doing it automatically in Python, please share the code. It would enable a feature where we add a slider to the toolbox UI that can adjust the output rate.

**Comment by blue-fish** [comment]
I read your question again, and I think you are wanting the speech rate of the output to match the sample used for cloning. The toolbox doesn't work this way as the speaker encoder is not designed to capture any information about prosody.

Please take a look at [mellotron](https://github.com/NVIDIA/mellotron) or [SpeechSplit](https://github.com/auspicious3000/SpeechSplit) for ideas on how to transfer speech rate from a reference sample.

**Comment by blue-fish** [comment]
Closing this since prosody transfer is outside the scope of SV2TTS.

**Comment by CYT823** [comment]
> I'd expect the speech rate is a hard-to-untangle function of the speaker embedding + the specific input sequence + which elements get affected by the random dropout during inference. This is because the prosody is inconsistent between speakers (and even between utterances for a given speaker) in the LibriSpeech dataset that is used for training.
> 
> The easiest way is to postprocess and resample the wav to a different length, in such a way that the pitch is preserved. It is a common operation but if you find a way of doing it automatically in Python, please share the code. It would enable a feature where we add a slider to the toolbox UI that can adjust the output rate.

@blue-fish Thanks for your advice. I will try the idea you provided. If it's successful, I will share with you.
