### ISSUE TITLE
Error message keeps saying I need to download the pretrained models even though i already have?

### ISSUE THREAD

**Issue by icandancelikecool** [CorentinJ/Real-Time-Voice-Cloning#560]
![Screenshot 2020-10-15 175631](https://user-images.githubusercontent.com/65001148/96200935-2041ab00-0f10-11eb-99de-d4983d8a7279.png)

**Comment by blue-fish** [comment]
Updated documentation: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models
Also submitted a pull request to improve the error message: #562
You should be able to figure it out now.
