### ISSUE TITLE
Where can I find datasets for VCTK p240 and VCTK p260?

### ISSUE THREAD

**Issue by vasinl124** [CorentinJ/Real-Time-Voice-Cloning#565]
I listen to the ones here - https://google.github.io/tacotron/publications/speaker_adaptation/
and these 2 datasets look really promising. I would like to try. Anyone, please guide me on how to get these datasets.

Thank you very much.

**Comment by blue-fish** [comment]
https://datashare.is.ed.ac.uk/handle/10283/3443
You must download the whole collection to get p240 and p260.
