### ISSUE TITLE
MegaUpload  model link not working

### ISSUE THREAD

**Issue by ranshaa05** [CorentinJ/Real-Time-Voice-Cloning#566]
The MegaUpload link to the models is no longer working. maybe replace it with a new [mega.nz](url) link?

**Comment by blue-fish** [comment]
Thank you for reporting this @ranshaa05 , I have removed the old link from the pretrained models wiki page since it is down. (For reference, it was: `https://megaupload.nz/F982Z8x6n5/pretrained_12_06_19_zip` ) Google drive is currently the only option for pretrained models.

**Comment by ranshaa05** [comment]
alright, but why not just upload the models to mega.nz (their new domain) and put it there instead? i personally prefer it to google drive.

**Comment by blue-fish** [comment]
I added a dropbox link to the [pretrained models](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models) wiki page to provide a second option.
