### ISSUE TITLE
C++ version

### ISSUE THREAD

**Issue by Siberian-Software** [CorentinJ/Real-Time-Voice-Cloning#567]
Could you please make a pure C++ code version without interpreting languages and CUDA?
So that it could be easily embedded into Win32 and Win64 applications.

**Comment by blue-fish** [comment]
Sorry, but a port to C++ is not planned. There are not enough developers working on the project to make that happen. Also, the voice cloning quality is bad and improving that is our top priority.

However you are welcome to contribute a C++ version. Steps are as follows:
1. Start with [tacotron-tts-cpp](https://github.com/syoyo/tacotron-tts-cpp) (the only C++ tacotron on github?). Implement the SV2TTS changes, preferably after upgrading it to tacotron2.
    * Matching Rayhane's tacotron2 would allow you to transfer weights from our pretrained model, otherwise you'll also need to find a way to train (either implement training in C++ or make an equivalent python implementation to train)
2. Reimplement the speaker encoder in C++
3. You'll need some kind of vocoder. I didn't find any C++ implementations but didn't look very hard. As a last resort you can use Griffin-Lim.
4. Connect everything together once you have all the pieces.

**Comment by blue-fish** [comment]
WaveRNN vocoder in C++: https://github.com/geneing/WaveRNN-Pytorch
