### ISSUE TITLE
is there a Turkish model ?

### ISSUE THREAD

**Issue by toolgaege** [CorentinJ/Real-Time-Voice-Cloning#569]
is there a Turkish model ?
I was try with a turkish model but program was give to me a error.

**Comment by blue-fish** [comment]
All community-developed models are listed here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/400
At the time of this writing, models are only available in English, Chinese and Swedish.

If you are extremely motivated and want to train your own model, you can look at https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-673555684 for an idea of the process but we cannot help with it. 

You would also need to find datasets, based on a quick search I found:
* https://lionbridge.ai/datasets/12-best-turkish-language-datasets-for-machine-learning/
* https://github.com/JRMeyer/open-speech-corpora
