### ISSUE TITLE
Recommended length of input audio?

### ISSUE THREAD

**Issue by mrgloom** [CorentinJ/Real-Time-Voice-Cloning#57]
What should be the length of input audio? What are other requirements(can there be silence, etc.)?

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/2e8ef14bf7865c7e3828219236bac3b098d07584/demo_cli.py#L133

Is it feasible to use several audio files and averaged embedding for better quality?

**Comment by CorentinJ** [comment]
[My thesis, page 24](https://matheo.uliege.be/bitstream/2268.2/6801/5/s123578Jemine2019.pdf#page=25):
>While the “optimal” duration of reference speech was found to be 5 seconds, the embedding is
>shown to be already meaningful with only 2 seconds of reference speech (see table 4).
>We believe that with utterances no shorter than the duration of partial utterances
>(1.6s), the utterance embedding should be sufficient for a meaningful capture of the
>voice, hence we used utterance embeddings for training the synthesizer.

![image](https://user-images.githubusercontent.com/12038136/61625423-fd780680-ac7a-11e9-8c2b-401d0f0e5efe.png)

As for other requirements: the silences are removed automatically. There can be background noise, the encoder is robust. Unfortunately the synthesizer/vocoder aren't, so a voice that deviates a little too much from the training data will be cloned poorly.

See here for your last question: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/41#issuecomment-510323973
