### ISSUE TITLE
How to speed up voice clone creation?

### ISSUE THREAD

**Issue by TechGenius28** [CorentinJ/Real-Time-Voice-Cloning#570]
Hello, may I first congratulate the authors on this fantastic project. However, I was wondering if there is anyway of increasing the speed of the voice clone creation. I am using this code to synthesise around 300 words and due to the issue of crackling, I have modified the demo_cli.py file to process around 8 words at a time and then stitch together them into one sound file at the end. Currently it is taking around 60 minutes to read out the 300 words. If there a way of speeding this up?

**Comment by blue-fish** [comment]
Yes, you should be able to speed this up considerably. What is happening is you have your vocode inside your loop:
```
for texts in paragraph:
    spec = synthesizer.synthesize_spectrograms(texts, embeds)   # This is fast
    wav = vocoder.infer_waveform(spec)                          # This is slow
# **concat the wavs**
```

Because WaveRNN works more efficiently for longer inputs, you should only vocode once, when all your specs have been generated:
```
for texts in paragraph:
    spec = synthesizer.synthesize_spectrograms(texts, embeds)   # This is fast

# **concat the specs**
wav = vocoder.infer_waveform(concat_spec)                       # This is slow
```

To speed it up further, you should make use of batch generation for spectograms (put multiple texts into a list when calling `synthesize_spectrograms`).

**Comment by TechGenius28** [comment]
Hello, thank you very much for replying to my question.

How exactly would I concatenate the specs?

Do I just put them into a list?

`    for textGenerate in cloningText:
        counter += 1
        print(str(counter)+"/"+str(len(textGenerate)))
        print(textGenerate)
        try:
            message = "Reference voice: enter an audio filepath of a voice to be cloned (mp3, " \
                      "wav, m4a, flac, ...):\n"
            soundFilePath = "voiceClone/rawaudio.mp3"
            in_fpath = Path(soundFilePath.replace("\"", "").replace("\'", ""))
            if in_fpath.suffix.lower() == ".mp3" and args.no_mp3_support:
                print("Can't Use mp3 files please try again:")
                continue
            preprocessed_wav = encoder.preprocess_wav(in_fpath)
            original_wav, sampling_rate = librosa.load(str(in_fpath))
            preprocessed_wav = encoder.preprocess_wav(original_wav, sampling_rate)
            print("Loaded file succesfully")
            embed = encoder.embed_utterance(preprocessed_wav)
            print("Created the embedding") 
            text = textGenerate
            texts = [text]
            embeds = [embed]
            specs = synthesizer.synthesize_spectrograms(texts, embeds)
            spec = specs[0]
            print("Created the mel spectrogram")
            print("Synthesizing the waveform:")
            if args.seed is not None:
                torch.manual_seed(args.seed)
                vocoder.load_model(args.voc_model_fpath)
            generated_wav = vocoder.infer_waveform(spec)
            generated_wav = np.pad(generated_wav, (0, synthesizer.sample_rate), mode="constant")
            generated_wav = encoder.preprocess_wav(generated_wav)
            if not args.no_sound:
                try:
                    sd.stop()
                    sd.play(generated_wav, synthesizer.sample_rate)
                except sd.PortAudioError as e:
                    print("\nCaught exception: %s" % repr(e))
                    print("Continuing without audio playback. Suppress this message with the \"--no_sound\" flag.\n")
                except:
                    raise
            filename = "voiceClone/demo_output_%02d.wav" % num_generated
            wavFiles.append(filename)
            print(generated_wav.dtype)
            sf.write(filename, generated_wav.astype(np.float32), synthesizer.sample_rate)
            num_generated += 1
            print("\nSaved output as %s\n\n" % filename)
            `
Thank you very much in advance.

**Comment by blue-fish** [comment]
> How exactly would I concatenate the specs?

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/bfb6002a94c1142b3ca431aefc7ef1489818d2af/demo_cli.py#L106-L108

Recall my other suggestion of batching the text inputs to the synthesizer for extra speed. That trick only works on a GPU. From the generation times mentioned in your original post, it sounds like you are using a CPU, so batching will not make synthesis any faster.

However, synthesis is still much faster than WaveRNN vocode, so total time should be 5 min or less once you concatenate the specs and reduce it to a single vocode.
