### ISSUE TITLE
able to do Speech-To-Speech Synthesis

### ISSUE THREAD

**Issue by ruah1984** [CorentinJ/Real-Time-Voice-Cloning#576]
Can it perform Speech to speech synthesis, instead of text to speech

**Comment by blue-fish** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/46#issuecomment-511217717
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/434#issuecomment-661294839
