### ISSUE TITLE
PaErrorCode -9997

### ISSUE THREAD

**Issue by Laurauwu74372** [CorentinJ/Real-Time-Voice-Cloning#580]
demo_cli.py works fine and crates a .wav file, but when trying to play something with the toolbox I get an error (Exception: Error opening OutputStream: Invalid sample rate [PaErrorCode -9997]) and I don't know how to access the results. I followed the steps as closely as possible.

**Comment by blue-fish** [comment]
Have you tried changing the "audio output" device?

If you don't have any usable devices then we may need to do something similar to #417 which adds code to ignore that exception so it is not fatal.

**Comment by Laurauwu74372** [comment]
> Have you tried changing the "audio output" device?
> 
> If you don't have any usable devices then we may need to do something similar to #417 which adds code to ignore that exception so it is not fatal.

Thank you a lot for the quick reply, I can't select any audio output devices, it says that it didn't detect and input or output devices, but I don't really care about that, I just want the output file. I'll look into #417 and try to figure out what to do.

**Comment by blue-fish** [comment]
Can you confirm that the exception is not fatal? I think it should just get logged, but the toolbox should not close as a result.

After vocoding, you can click "export" to save the generated waveform to an audio file. Try that.

**Comment by Laurauwu74372** [comment]
> Can you confirm that the exception is not fatal? I think it should just get logged, but the toolbox should not close as a result.
> 
> After vocoding, you can click "export" to save the generated waveform to an audio file. Try that.

I can't export it afaik.
I made a video, maybe that can help.
https://drive.google.com/file/d/11Rplua8mOzfjgGXQl6Hnv0f0tmKYn7D9/view?usp=drivesdk

**Comment by blue-fish** [comment]
You'll need something like #417 because the exception is preventing execution of the other code which adds it to history and allows export. I'll make a branch for this, it should be available for testing shortly.

**Comment by blue-fish** [comment]
This should fix it: https://github.com/blue-fish/Real-Time-Voice-Cloning/commit/69a074cb732190cb34e2d4f4d944be69e4cd09ff

Would you please let me know if you're able to export audio files after making that change? You can modify the file directly, or download it from my branch: [`blue-fish:580_export_after_portaudio_error`](https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/580_export_after_portaudio_error)

**Comment by Laurauwu74372** [comment]
> This should fix it: https://github.com/blue-fish/Real-Time-Voice-Cloning/commit/69a074cb732190cb34e2d4f4d944be69e4cd09ff
> 
> Would you please let me know if you're able to export audio files after making that change? You can modify the file directly, or download it from my branch: [`blue-fish:580_export_after_portaudio_error`](https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/580_export_after_portaudio_error)

Thank you a *lot* for the quick replies and helping me, it works, I can export it now.
