### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by JakubReha** [CorentinJ/Real-Time-Voice-Cloning#583]
@blue-fish Hey I have some question regarding the repo, would it be possible to get in touch with you through email?

**Comment by blue-fish** [comment]
I apologize, I am not available to provide consultation outside of the issues board here. For now, my priorities are 1) code development and 2) bug fixes. I answer support questions as time permits but that is not my purpose here.

_Originally posted by @blue-fish in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/486#issuecomment-673397231_
