### ISSUE TITLE
I tried to use pretrained models provided by @sberryman but i go this error

### ISSUE THREAD

**Issue by mennatallah644** [CorentinJ/Real-Time-Voice-Cloning#589]
![error](https://user-images.githubusercontent.com/32370077/98088980-d272ef80-1e8a-11eb-9f48-23bb24a63570.PNG)
#### Encoder
https://www.dropbox.com/s/xl2wr13nza10850/encoder.zip?dl=0

#### Synthesizer (Tacotron)
https://www.dropbox.com/s/t7qk0aecpps7842/tacotron.zip?dl=0

#### Vocoder
https://www.dropbox.com/s/bgzeaid0nuh7val/vocoder.zip?dl=0

_Originally posted by @sberryman in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-536097366_

**Comment by mennatallah644** [comment]
![rrr](https://user-images.githubusercontent.com/32370077/98112775-58069780-1eab-11eb-835a-dcccf6ee75ce.PNG)

**Comment by blue-fish** [comment]
Try a relative path:
```
synthesizer = Synthesizer(Path("synthesizer/saved_models/logs-pretrained/taco_pretrained"))
```

Or this command which may be closer to what you intended:
```
synthesizer = Synthesizer(Path(project_name + "/synthesizer/saved_models/logs-pretrained/taco_pretrained"))
```

Most users starting out with the toolbox use either of these commands. You can study the code in `demo_cli.py` and adapt it for your specific purposes.
```
python demo_cli.py
python demo_toolbox.py
```

Also, I apologize but the github issues board is not for technical support. It is for coordinating development of the software and reporting bugs. This is a research code, not a finished product. For these types of problems you'll need to seek help somewhere else.
