### ISSUE TITLE
Encoder's embeds _loss becomes NaN

### ISSUE THREAD

**Issue by tranctan** [CorentinJ/Real-Time-Voice-Cloning#593]
Hi, I gave a try training the Encoder on my dataset (which is much smaller - around 500 speakers) to see how the model behaves. However, at nearly step 25,000, I encountered an error: 

``
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
``

Does anyone know what is the error here ? My 2cent is it may encouter the vanishing gradient problem (possibly because the dataset is too small). If this is the case, should I decrease the learning rate ? Any help or comments are appreciated :D.

**Comment by JakubPilny** [comment]
You can try changing the learning rate in params_model

**Comment by tranctan** [comment]
Thank you for your recommendation, definitely changing learning rate is one of the first option that comes in my mind, the other option could be gradient clipping. 

I also try reducing the learning rate from (default) 1e-4 to 1e-5, this helps my model survives longer than 25k steps, but then the same issue occurred. 

IMO, the reason could be the size of the data is not large enough. When I used the pre-trained model and fine-tune on my little data, everything works just fine! 

I will leave this issue open for a while in case any other people have a more proper answer to this :)

**Comment by blue-fish** [comment]
I tried making an encoder based on LibriSpeech `train-clean-100` (251 speakers). It trained to 60k steps without problems using default settings. Only thing I modified is batch size 64 --> 32 to fit in limited vram. So I think it has something to do with your dataset.

**Comment by Jackson-Kang** [comment]
Hello, guys.

I solved this issue.
Please check this pull request.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/678


Hope that my solution be helpful.
