### ISSUE TITLE
Where can I find the 1.15 version of tensorflow-gpu?

### ISSUE THREAD

**Issue by zydlaks** [CorentinJ/Real-Time-Voice-Cloning#594]
Where can I find the 1.15 version of tensorflow-gpu?

**Comment by 0lm** [comment]
get yourself python 3.7x and type `pip install tensorflow==1.15.0`
it should download and install that version then.

**Comment by AlessioScarlet** [comment]
`ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1)
ERROR: No matching distribution found for tensorflow==1.15.0`

**Comment by JakubPilny** [comment]
You have to use Python 3.7.x for Tensforflow 1.x

**Comment by rekkerz** [comment]
https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux
I found this quite useful. If you download Python 3.8.x from
https://www.python.org/downloads/ you should be able to set up
`update-alternatives` which would enable you to easily choose the version
of Python that you require.
