### ISSUE TITLE
Someone is selling this software!?

### ISSUE THREAD

**Issue by bostjan39** [CorentinJ/Real-Time-Voice-Cloning#598]
Hi,

Just found this: https://realtimevoicecloning.com

Is he selling your work as his own?

**Comment by JakubPilny** [comment]
Issued report on the seller, you can do too (https://www.shopify.com/legal/report-aup-violation)

**Comment by blue-fish** [comment]
The [license](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/LICENSE.txt) gives permission to sell copies of the software. It would be nice if those who take from this project also give back, but it is not a requirement.

**Comment by blue-fish** [comment]
There might be some copyright violations involved in reuploading Corentin's youtube video and using images from [this video](https://www.youtube.com/watch?v=pKoOw5a74XU) on the webpage.

**Comment by GreatestFool** [comment]
Considering they have an embedded vimeo reupload of the YouTube demo video, I'm pretty sure they are breaking YouTube's terms.

From a quick nslookup, I'm pretty sure they're using Shopify. I can see shopify in the DOM as well, so pretty sure. And if they are. they are most likely breaking their terms of service. Specifically point 3 about general conditions. As an end user, you are not allowed to use shopify for any illegal or sketchy purposes. Could be worth giving shopify a heads up on their abuse portal.

**Comment by CorentinJ** [comment]
Thanks for reporting. @blue-fish is correct, I they're within their rights given that I put an MIT license. I'll report the vimeo video but the rest is technically fair game.
