### ISSUE TITLE
Failed running demo_cli.py

### ISSUE THREAD

**Issue by rekkerz** [CorentinJ/Real-Time-Voice-Cloning#599]
Hi,
Context: I'm running on Python 3.6.12 on Ubuntu 20.04.01 LTS.

I'm getting an error while running `demo_cli.py`. Below is the Traceback:
```File "demo_cli.py", line 75, in <module>
    encoder.load_model(args.enc_model_fpath)
  File "/home/defin/code/Real-Time-Voice-Cloning/encoder/inference.py", line 34, in load_model
    _model.load_state_dict(checkpoint["model_state"])
  File "/home/defin/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SpeakerEncoder:
        Missing key(s) in state_dict: "similarity_weight",
```
(I'm not including all missing keys in the `state_dict` - there's many more.)

Not really sure what's going wrong since it's my first time using PyTorch.

Thanks in advance.

**Comment by blue-fish** [comment]
Make sure you placed the correct pretrained.pt file in `encoder/saved_models/pretrained.pt` , filesize should be 17090379. See instructions here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models

**Comment by rekkerz** [comment]
Thanks, seems my download/upload was corrupt :')
