### ISSUE TITLE
WaveRNN modifications?

### ISSUE THREAD

**Issue by mrgloom** [CorentinJ/Real-Time-Voice-Cloning#60]
Is this repo uses vanilla version of WaveRNN (https://github.com/fatchord/WaveRNN)? or architecture was modified and model was retrained?

It's quite fast relative to my benchmark of tacotron2  + wavernn from here https://github.com/erogol/WaveRNN  but (maybe) have less natural voice.

BTW I don't tried new `universal vocoder` version.

**Comment by m-toman** [comment]
What I've seen the most significant differences are 16kHz sampling rate and a slightly smaller window size for the batched synthesis.

**Comment by mrgloom** [comment]
https://github.com/fatchord/WaveRNN/blob/master/hparams.py#L20

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/vocoder/hparams.py#L6
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/synthesizer/hparams.py#L117

https://github.com/erogol/WaveRNN
mold model:
"sample_rate": 22050
https://drive.google.com/drive/folders/1wpPn3a0KQc6EYtKL0qOi4NqEmhML71Ve

10bit model:
"sample_rate": 22050
https://drive.google.com/drive/folders/1VnTJfg2zmvochFNyX7oyUv9TFq6JsnVp

universal vocoder:
"sample_rate": 16000
https://drive.google.com/drive/u/0/folders/15JhAbc91dT-RRZwakh_v4tBVOEuoOikg

**Comment by CorentinJ** [comment]
> What I've seen the most significant differences are 16kHz sampling rate and a slightly smaller window size for the batched synthesis.

This is correct. I haven't changed anything else.
