### ISSUE TITLE
My voices always come out weird which doesnt happen to others, and it says I'm missing a noise removal component.

### ISSUE THREAD

**Issue by BlockyBoyRoll** [CorentinJ/Real-Time-Voice-Cloning#601]
If you need me to send any logs or screenshare myself running tests let me know,

**Comment by blue-fish** [comment]
I uninstalled webrtcvad (your missing noise removal component) and performed the following test in demo_toolbox.py with Corentin's pretrained models:
1. Use `samples/p240_00000.mp3` to generate a speaker embedding.
2. Text: `Welcome to the toolbox! To begin, load an utterance from your datasets or record one yourself.`
3. Random seed box checked, value = 0
4. Expected output (wav file inside zip): [p240_sample.zip](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/5576210/p240_sample.zip)

If your result sounds similar then your toolbox installation is working.

Please set your expectations very low, especially for voice samples that don't sound like a normal person reading an audiobook.
