### ISSUE TITLE
Is it possible to input our mic voice instead of text?

### ISSUE THREAD

**Issue by trafalgarxlaw** [CorentinJ/Real-Time-Voice-Cloning#603]
I think it would be cool to have my voice as input processed in real time to make it sound like another voice.

**Comment by blue-fish** [comment]
That's something completely different from the SV2TTS paradigm this repo implements. Check out [autovc](https://github.com/auspicious3000/autovc) for an example of a repo that would do it. It's not as user-friendly though.
