### ISSUE TITLE
speech is distorted when the text entered is long

### ISSUE THREAD

**Issue by savinay** [CorentinJ/Real-Time-Voice-Cloning#604]
When I enter a short text, the speech looks good but when it is longer, it is distorted and incomprehensible. Are there any changes we need to do?

**Comment by blue-fish** [comment]
Known issue, discussed somewhat in #347. What I think occurs is the attention drops off for very long inputs and the model struggles. You can try my alternative pretrained model in #538, but the usual workaround is to break up your inputs into smaller chunks (add line breaks in the toolbox).

**Comment by savinay** [comment]
Thanks for your reply. I tried with the pretrained model but the speech is still not good for longer texts.  What changes need to be done to break the inputs into smaller chunks? Is this possible to do when running demo_cli.py?

**Comment by savinay** [comment]
Got it to work.. Thanks a lot for your suggestions. It is much better now. Broke the longer text into smaller segments and that worked!
