### ISSUE TITLE
Guidance in selecting GPU

### ISSUE THREAD

**Issue by sandarshnaroju** [CorentinJ/Real-Time-Voice-Cloning#607]
Thanks for creating this repo. Sorry for asking this dumb question here,   I am trying to train a model for encoder in my local language. I am very new to AI. I need assistance in choosing a GPU for training encoder.   I understand a normal MacBook Pro(8GB ram, 256SSD) cannot be used for training for days. I am thinking of renting a server in AWS SageMaker to train. But there are several instances [here](https://aws.amazon.com/sagemaker/pricing/). How would one go about selecting a server for this kind of heavy load training? I request you to guide me.

**Comment by sriharsha0806** [comment]
go for A100 for Training if available or else use P100. I believe the cost is worth it. you can check this link https://towardsdatascience.com/choosing-the-right-gpu-for-deep-learning-on-aws-d69c157d8c86 for further information

**Comment by blue-fish** [comment]
Training on your own hardware is generally more cost-effective.
