### ISSUE TITLE
Reuse a cloned voice

### ISSUE THREAD

**Issue by savinay** [CorentinJ/Real-Time-Voice-Cloning#609]
Hi,

Is it possible to reuse a cloned voice for inference later on (I would like to clone just a single voice and build different audio for the same voice)? If yes, how can we go about it?

This would help me speed up the process.

**Comment by blue-fish** [comment]
Yes. The synthesizer takes 2 inputs: text and embedding. The embedding is a numerical representation of the target voice. Once you have the embedding output from the encoder (a 256-element array), it can be saved and reused.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/5425557efe30863267f805851f918124191e0be0/demo_cli.py#L156
