### ISSUE TITLE
Quality of the voice

### ISSUE THREAD

**Issue by sriharsha0806** [CorentinJ/Real-Time-Voice-Cloning#611]
Hi, I am trying to clone the voice of famous people like Abdul Kalam, Modi. I collected their speeches from youtube videos. But the quality of the voice is very low. There is no similarity between the voice generated by the model and the target's voice. 
I am attaching the generated audio file(.wav) and the audio file which i used for training(.mp3)

https://drive.google.com/file/d/1ESAdcecXgAkIjZMKWsE236pkcVv7YDco/view?usp=sharing, https://drive.google.com/file/d/1c99n-iD36q6cHoir4S9qviCGe-D9wZvL/view?usp=sharing, https://drive.google.com/file/d/1y_RtrygSIBqI-ODYy80AkYE8kSdlSaHB/view?usp=sharing

**Comment by JakubPilny** [comment]
This is mainly because your speakers have different accent, than the pretrained model.

**Comment by blue-fish** [comment]
See #411 and #590 for additional explanation of low quality.
