### ISSUE TITLE
How can I do on this repositor with Anaconda for python??

### ISSUE THREAD

**Issue by Xnessax** [CorentinJ/Real-Time-Voice-Cloning#614]
I am still not getting it into execute deep voice. I need some codes for language in portuguese. I want to try some tests.

**Comment by blue-fish** [comment]
* If you need GPU support, here are instructions for [setup using Ubuntu 20.04 + Miniconda](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Installation---Ubuntu-20.04)
* If you don't need GPU support, this is easier: [setup using Ubuntu 20.04 (no Anaconda)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/615#issuecomment-740270185)

**Comment by Xnessax** [comment]
It's in windows 10.

**Comment by justinjohn0306** [comment]
@Xnessax check out my video : https://www.youtube.com/watch?v=_4ySXTe5iyQ&feature=youtu.be

**Comment by Xnessax** [comment]
the last step would be like ...: c://users/documents/Freixas_voices.mp3 ("I gave up on discussing on politics.") 
Is that right? 
Hope to know about it.
