### ISSUE TITLE
GUIDE: Setting it up on Linux

### ISSUE THREAD

**Issue by FreddyFeuerstein** [CorentinJ/Real-Time-Voice-Cloning#615]
# Setting up RTVC on Linux:
***This is still very WIP but it will work on any version of debian/ubuntu/mint.***
First, add the dead snake ppa:
```
sudo add-apt-repository ppa:deadsnakes/ppa
```
After that, you need to install git, python 3.6 and python virtual enviorment:
```
sudo apt install python3.6 python3 python3-pip git
pip3 install virtualenv
virtualenv --python python36 rtvc
cd ./rtvc/bin/
source ./activate
```
Then, you have to cd to the directory you want to install RTVC in. If you have done that, run the following to clone and set up RTVC:
```
git clone https://github.com/CorentinJ/Real-Time-Voice-Cloning.git
cd Real-Time-Voice-Cloning
pip3 install -r requirements.txt
# If you have a GPU, run the following, too.
pip3 install -r requirements_gpu.txt
```
Now, the only thing left to do, is creating a launch script:
```
nano ./rtvc.sh
```
In the editor, you will need to type in the following:
```
#!/bin/bash
source <path-to-the-rtvc-folder-we-made-with-virtualenv>/bin/activate
cd "<path-to-the-cloned-repo>"
python3 ./demo_toolbox.py
```
Thats all.
I hope it is useful for you guys!

**Comment by blue-fish** [comment]
Nice guide! We have a [guide for Ubuntu 20.04](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Installation---Ubuntu-20.04) in the wiki, but it uses miniconda, which I prefer to avoid.

I tried out the instructions on Ubuntu 20.04 and here is some feedback:
1. `sudo apt install python3-pip` returns an error: "Package 'python3-pip' has no installation candidate" (even after `apt update`)
2. Missing a step to download pytorch: `pip install torch -f https://download.pytorch.org/whl/torch_stable.html`
3. Also need `snap install ffmpeg` to pass the mp3 loading check.
4. Missing a step to download the [pretrained models](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models)
5. Need to install libportaudio2. Due to a bug, you may need to build it yourself with these instructions: https://stackoverflow.com/a/60824906
6. Should install `python3-dev` which enables `pip install webrtcvad` (in requirements_gpu.txt). This unlocks the "enhance vocoder output" option to trim gaps from output.

Overall I do not recommend 20.04 because python 3.8 as default causes too many problems.

**Comment by blue-fish** [comment]
### Ubuntu 20.04 install instructions (tested)

#### 1. Add repositories
```
sudo add-apt-repository universe
sudo add-apt-repository ppa:deadsnakes/ppa
```
#### 2. Install software
```
snap install ffmpeg
sudo apt install python3.6 python3.6-dev python3 python3-pip git
pip3 install virtualenv
```
Additional steps are needed to overcome bugs with portaudio and QT:
* Portaudio bugfix: https://stackoverflow.com/a/60824906
```
sudo apt install libasound2-dev
git clone -b alsapatch https://github.com/gglockner/portaudio
cd portaudio
./configure && make
sudo make install
sudo ldconfig
cd ..
```
* QT bugfix: https://askubuntu.com/a/1069502
```
sudo apt install --reinstall libxcb-xinerama0
```
#### 3. Make a virtual environment and activate it
```
~/.local/bin/virtualenv --python python36 rtvc
source rtvc/bin/activate
```
#### 4. Download RTVC
```
git clone --depth 1 https://github.com/CorentinJ/Real-Time-Voice-Cloning.git
```
#### 5. Install requirements
```
cd Real-Time-Voice-Cloning
pip install torch
pip install -r requirements.txt
pip install webrtcvad
```
#### 6. Get pretrained models
```
wget https://www.dropbox.com/s/5udq50bkpw2hipy/pretrained.zip?dl=1 -O pretrained.zip
unzip pretrained.zip
```
#### 7. Launch toolbox
```
python demo_toolbox.py
```

**Comment by FreddyFeuerstein** [comment]
> Additional steps are needed to overcome bugs with portaudio and QT:
> 
>     * Portaudio bugfix: https://stackoverflow.com/a/60824906

Thx for adding that.

**Comment by omertalmi5** [comment]
@blue-fish 
Thanks, It is very helpful.
 I recommend addin it to the README.
It might help another people

**Comment by Langstra** [comment]
Any suggestions for Ubuntu 20.10, there is no version 3.6 or 3.7 of python for this version. Only option is to download Ubuntu?

**Comment by blue-fish** [comment]
@Langstra The deadsnakes ppa only supports Ubuntu LTS releases (20.04). Try the [Ubuntu setup wiki page](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Installation---Ubuntu-20.04), it uses miniconda to install python 3.7. The CUDA/cuDNN steps are unnecessary in my experience: without them, synthesizer training (tensorflow) still has GPU acceleration.

**Comment by Sorry-Im-Stupid** [comment]
So I've been trying to get this to run, and this tutorial got me pretty close, but now I'm getting this:

**It does this for any version of python I try.**

python3.9 demo_toolbox.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maker/RTVC/Real-Time-Voice-Cloning/Real-Time-Voice-Cloning/demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "/home/maker/RTVC/Real-Time-Voice-Cloning/Real-Time-Voice-Cloning/toolbox/__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "/home/maker/RTVC/Real-Time-Voice-Cloning/Real-Time-Voice-Cloning/toolbox/ui.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 138, in <module>
    from . import cbook, rcsetup
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 31, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.9 from "/usr/bin/python3.9",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'



Now, I _DO_ have the right numpy installed... So how do I get this program in particular to use that version?

**Comment by FreddyFeuerstein** [comment]
This has to be run explicitly on python 3.6 in virtualenv.

**Comment by Sorry-Im-Stupid** [comment]
Oooohhh, kay. I'll see about making it use 3.6 and get back to you.

**Comment by Sorry-Im-Stupid** [comment]
Two steps forward, one step back. 
I had it working, was playing around, I closed the terminal window I was starting it from so I could test the shell script, and now I'm back to having it run the same numpy error.
I have the shell script structured as instructed above, and it doesn't even start the virtualenv.
If I run the steps myself in terminal they work, until it gets to the numpy error.

#!/bin/bash
source /home/maker/RTVC/Real-Time-Voice-Cloning/rtvc/bin/activate
cd /home/maker/RTVC/Real-Time-Voice-Cloning/Real-Time-Voice-Cloning
python3.6 demo_toolbox.py

**Comment by Sorry-Im-Stupid** [comment]
Now I'm trying to train it, can't even DL the big one https://www.openslr.org/resources/12/train-other-500.tar.gz
But I have the Celebvox files, and I've managed to get the encoder preprocess to see it, but it's running into a problem at line 57.
```
assert args.datasets_root.exists()
    args.out_dir.mkdir(exist_ok=True, parents=True)
```

```
python3 encoder_preprocess.py -d /media/maker/Storage 2/Audio_Dev_Bulk/VoxCeleb2/dev
Traceback (most recent call last):
  File "encoder_preprocess.py", line 57, in <module>
    assert args.datasets_root.exists()
AssertionError

```

**Comment by Sorry-Im-Stupid** [comment]
I got the big one, LibriSpeech 500. And I ran the encoder preprocess, it worked, the files exist!
Now I have to figure out where to put it and how to tell the program to use them.

**Comment by Sorry-Im-Stupid** [comment]
So it's seeing them, and I've re-pre-processed them with the aligners, but it's still giving me this:

![integer error](https://user-images.githubusercontent.com/84992987/134786512-fc404625-0ef1-40b0-a308-7a6b60c764b9.png)
```

Arguments:
    datasets_root:    /media/maker/D330-3157/Audio_Dev_Bulk/Output
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Traceback (most recent call last):
  File "/home/maker/RTVC/Real-Time-Voice-Cloning/Real-Time-Voice-Cloning/toolbox/__init__.py", line 82, in <lambda>
    self.ui.browser_load_button.clicked.connect(lambda: self.load_from_browser())
  File "/home/maker/RTVC/Real-Time-Voice-Cloning/Real-Time-Voice-Cloning/toolbox/__init__.py", line 154, in load_from_browser
    self.ui.browser_select_next()
  File "/home/maker/RTVC/Real-Time-Voice-Cloning/Real-Time-Voice-Cloning/toolbox/ui.py", line 322, in browser_select_next
    index = (self.utterance_box.currentIndex() + 1) % len(self.utterance_box)
ZeroDivisionError: integer division or modulo by zero

```
And while we're on this, why is it saying cpu: false, but it's not using my GPU? 
And how do I use an AMD GPU for this? I have the right version of torch installed, and it is using that version.

**Comment by westindiantech** [comment]
Hi is there anyway to install this on apple osx catalina?

**Comment by blue-fish** [comment]
This guide was written before #472 was merged and removed the requirement for Tensorflow 1.15. Installation should be a lot easier now.

I am closing this issue because these steps are obsolete. The repo can be set up without using a PPA to install an old version of Python. A new set of instructions is requested.

**Comment by FreddyFeuerstein** [comment]
does that mean that we dont need cuda anymore and can use opencl and amd cards instead?

**Comment by blue-fish** [comment]
No, those issues are unrelated. However, Pytorch recently added support for ROCm, so it may work with AMD cards now.
