### ISSUE TITLE
What do the X and Y axes of the mel spectrogram mean？

### ISSUE THREAD

**Issue by niu0717** [CorentinJ/Real-Time-Voice-Cloning#616]
X axes means Hz and Y axes means Time in demo.toolbox, right?
![(X9B1`83`I9L6}@T~M2E TL](https://user-images.githubusercontent.com/45747807/102575254-c175f900-412d-11eb-8ee6-954a0e68bd18.png)

**Comment by blue-fish** [comment]
X (horizontal) axis is time.
Y (vertical) axis is Hz, with lower freq on top and higher on bottom.

**Comment by niu0717** [comment]
How can I make a picture like this， X  is frame and Y is mel channel? 
THX :) !

**Comment by blue-fish** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/5425557efe30863267f805851f918124191e0be0/vocoder/display.py#L115-L119
