### ISSUE TITLE
AttributeError: module 'tensorflow.python.util.compat' has no attribute 'v1'

### ISSUE THREAD

**Issue by visant76** [CorentinJ/Real-Time-Voice-Cloning#619]
AttributeError: module 'tensorflow.python.util.compat' has no attribute 'v1'

after running demo_cli.py   What is that?

**Comment by blue-fish** [comment]
Which version of tensorflow is installed? This repo needs 1.15.x

**Comment by blue-fish** [comment]
Closed due to inactivity.
