### ISSUE TITLE
Synthesizer alignment.txt

### ISSUE THREAD

**Issue by Eug83** [CorentinJ/Real-Time-Voice-Cloning#62]
Thank you very much for your the work! Recently, I want to run through the steps of training synthesizer and vocoder. I use LibriSpeech as the dataset. When I run `synthesizer_preprocess_audio.py`, the output metadata is an empty list (and therefore `train.txt` is an empty file). It seems that `.alignment.txt` files are required but I cannot find them in the LibriSpeech dataset I downloaded. I did not run `encoder_preprocess.py` and `encoder_train.py` (and I guess they are not required). Did I miss any steps? Thanks.

**Comment by wotulong** [comment]
I suggest you to look at the detail of 'preprocess.py' which in 'synthesizer' directory. The purpos of '.alignment.txt' is to split the wav file into pieces.I think you need to rewrite 'preprocess.py' for LibriSpeech, because it doesn't need to split wav file and it couldn't.It's what the way I process vctk dataset, hope it help, thanks.

**Comment by CorentinJ** [comment]
> I suggest you to look at the detail of 'preprocess.py' which in 'synthesizer' directory. The purpos of '.alignment.txt' is to split the wav file into pieces.I think you need to rewrite 'preprocess.py' for LibriSpeech, because it doesn't need to split wav file and it couldn't.It's what the way I process vctk dataset, hope it help, thanks.

This is wrong. You simply need to download the [alignments](https://github.com/CorentinJ/librispeech-alignments#download-links) as is explained [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training).

**Comment by wotulong** [comment]
> > I suggest you to look at the detail of 'preprocess.py' which in 'synthesizer' directory. The purpos of '.alignment.txt' is to split the wav file into pieces.I think you need to rewrite 'preprocess.py' for LibriSpeech, because it doesn't need to split wav file and it couldn't.It's what the way I process vctk dataset, hope it help, thanks.
> 
> This is wrong. You simply need to download the [alignments](https://github.com/CorentinJ/librispeech-alignments#download-links) as is explained [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training).

You are right, LibriSpeech has alignment.txt and I have download it before，I'm sorry I forget it.

**Comment by GauriDhande** [comment]
I have a custom dataset which contain a bunch of wav files with there text transcriptions. I require alignment.txt for those respective wav files. Is there a way where we can create those .alignment.txt for a custom dataset?

**Comment by CorentinJ** [comment]
You don't need alignments, it's only something I did for LibriSpeech but it's overengineering for little results. Remove the code that splits sentences based on alignments and you'll be fine.

As a matter of fact we should be removing alignments repo-wide.

**Comment by GauriDhande** [comment]
Would you please let me know which code to be removed? And should I add TextGrids in the code?

**Comment by CorentinJ** [comment]
This function and its usages:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/5e400d474043044ba0e3e907a74b4baccb16ee7c/synthesizer/preprocess.py#L83-L152
