### ISSUE TITLE
Error: Model files not found. Follow these instructions to get and install the models:

### ISSUE THREAD

**Issue by aylitat** [CorentinJ/Real-Time-Voice-Cloning#621]
I have downloaded the files about encoder and so on.
But when I run toolbox,it still show this:
Error: Model files not found. Follow these instructions to get and install the models:

**Comment by blue-fish** [comment]
Please ensure the files are extracted to these locations within your local copy of the repository:
```
encoder\saved_models\pretrained.pt
synthesizer\saved_models\logs-pretrained\taco_pretrained\checkpoint
synthesizer\saved_models\logs-pretrained\taco_pretrained\tacotron_model.ckpt-278000.data-00000-of-00001
synthesizer\saved_models\logs-pretrained\taco_pretrained\tacotron_model.ckpt-278000.index
synthesizer\saved_models\logs-pretrained\taco_pretrained\tacotron_model.ckpt-278000.meta
vocoder\saved_models\pretrained\pretrained.pt
```

**Comment by aylitat** [comment]
> Please ensure the files are extracted to these locations within your local copy of the repository:
> 
> ```
> encoder\saved_models\pretrained.pt
> synthesizer\saved_models\logs-pretrained\taco_pretrained\checkpoint
> synthesizer\saved_models\logs-pretrained\taco_pretrained\tacotron_model.ckpt-278000.data-00000-of-00001
> synthesizer\saved_models\logs-pretrained\taco_pretrained\tacotron_model.ckpt-278000.index
> synthesizer\saved_models\logs-pretrained\taco_pretrained\tacotron_model.ckpt-278000.meta
> vocoder\saved_models\pretrained\pretrained.pt
> ```

thx for all.I have solved .
