### ISSUE TITLE
Is this complete app ?

### ISSUE THREAD

**Issue by Ud4ba** [CorentinJ/Real-Time-Voice-Cloning#626]
Can i use this on windows 10 ?

**Comment by blue-fish** [comment]
It will run on Windows 10, but you need to install python and required python packages. Expect it to be difficult if you're not already a python user. Someone put together a video explaining how to set it up: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/614#issuecomment-748032599

**Comment by Ud4ba** [comment]
thanks for this .
