### ISSUE TITLE
Trouble with starting toolbox.

### ISSUE THREAD

**Issue by Diovosh** [CorentinJ/Real-Time-Voice-Cloning#627]
In the past, back in September, I could manage to run this program, but now I am running into the same error.
A s s e r t i o n   f a i l e d !

 P r o g r a m :   C : \ U s e r s \ d a n i e \ a n a c o n d a 3 \ e n v s \ T e s t \ p y t h o n . e x e
 F i l e :   s r c / h o s t a p i / w d m k s / p a _ w i n _ w d m k s . c ,   L i n e   1 0 8 1

 E x p r e s s i o n :   F A L S E
I cannot bypass it and I have found no solutions online either.

**Comment by blue-fish** [comment]
Try downloading the precompiled sounddevice linked from: https://github.com/spatialaudio/python-sounddevice/issues/7#issuecomment-751341488
You'll need to match your python version and CPU architecture.
```
pip uninstall sounddevice
pip install sounddevice‑0.4.1‑cp37‑cp37m‑win_amd64.whl
```
