### ISSUE TITLE
Can I convert a speech to someone else's voice with this software? Speech to Speech voice conversation 

### ISSUE THREAD

**Issue by FurkanGozukara** [CorentinJ/Real-Time-Voice-Cloning#628]
Ok here what I want to achieve.

I have a speech recording and I want to convert this speech to another voice.

Is this possible?

I am not interested in text to speech. I want to convert the voice. 

This will be used for experimental purposes.

Also do application have any pre-trained voices that I can convert my speech into?

**Comment by blue-fish** [comment]
You need a different repo for voice conversion. I have a list in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/434#issuecomment-661294839

If you don't want to take the time to set it up, upload or point me to an audio file and I'll convert it with one of my pretrained voices.
