### ISSUE TITLE
Error in macOS when trying to launch the toolbox

### ISSUE THREAD

**Issue by notluke27** [CorentinJ/Real-Time-Voice-Cloning#629]
Traceback (most recent call last):
  File "/Users/luke/Documents/Real-Time-Voice-Cloning-master/demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "/Users/luke/Documents/Real-Time-Voice-Cloning-master/toolbox/__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "/Users/luke/Documents/Real-Time-Voice-Cloning-master/toolbox/ui.py", line 6, in <module>
    from encoder.inference import plot_embedding_as_heatmap
ModuleNotFoundError: No module named 'encoder.inference'

**Comment by blue-fish** [comment]
I'm unable to reproduce this problem in macOS. Which version of python are you using, and how did you install it?

**Comment by blue-fish** [comment]
To eliminate obvious issues, please check the following:
1. Does the file `inference.py` exist in the folder: `/Users/luke/Documents/Real-Time-Voice-Cloning-master/encoder` ?
2. Are you running the `python demo_toolbox.py` command from the terminal, in this folder? `/Users/luke/Documents/Real-Time-Voice-Cloning-master`

**Comment by notluke27** [comment]
> To eliminate obvious issues, please check the following:
> 
> 1. Does the file `inference.py` exist in the folder: `/Users/luke/Documents/Real-Time-Voice-Cloning-master/encoder` ?
> 2. Are you running the `python demo_toolbox.py` command from the terminal, in this folder? `/Users/luke/Documents/Real-Time-Voice-Cloning-master`

There's no file with that name and yes i am running it from the terminal with that command in that folder

**Comment by blue-fish** [comment]
> There's no file with that name

That explains it. Try extracting the .zip file again. You can also try using git to clone the repository:
```
git clone --depth 1 https://github.com/CorentinJ/Real-Time-Voice-Cloning
```
