### ISSUE TITLE
Sorry, you can't view or download this file at this time.

### ISSUE THREAD

**Issue by mrgloom** [CorentinJ/Real-Time-Voice-Cloning#63]
Seems google drive  have some limitations
`Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.`

**Comment by kool601** [comment]
https://lmgtfy.com/?q=how+to+bypass+google+drive+download+limit

**Comment by CorentinJ** [comment]
I'll gladly upload if you give a mirror you want it uploaded to
