### ISSUE TITLE
Can't load dataset

### ISSUE THREAD

**Issue by notluke27** [CorentinJ/Real-Time-Voice-Cloning#630]
![Captura de Tela 2021-01-18 às 10 39 44](https://user-images.githubusercontent.com/77593871/104922448-827bd300-5979-11eb-8de7-3bc8118f6497.png)
  datasets_root:    None
Warning: you did not pass a root directory for datasets as argument.
The recognized datasets are:
	LibriSpeech/dev-clean
	LibriSpeech/dev-other
	LibriSpeech/test-clean
	LibriSpeech/test-other
	LibriSpeech/train-clean-100
	LibriSpeech/train-clean-360
	LibriSpeech/train-other-500
	LibriTTS/dev-clean
	LibriTTS/dev-other
	LibriTTS/test-clean
	LibriTTS/test-other
	LibriTTS/train-clean-100
	LibriTTS/train-clean-360
	LibriTTS/train-other-500
	LJSpeech-1.1
	VoxCeleb1/wav
	VoxCeleb1/test_wav
	VoxCeleb2/dev/aac
	VoxCeleb2/test/aac
	VCTK-Corpus/wav48

**Comment by blue-fish** [comment]
The use of a dataset is optional. You can ignore that message and load your own audio files (.wav, .mp3, .flac).

If you want to do some exploration with a dataset, get one from here: https://openslr.org/12

The readme recommends `train-clean-100`, but any of the smaller "dev" or "test" datasets will work too. Make a folder called `datasets_root` in your Real-Time-Voice-Cloning folder. Extract the .tar.gz file and move the `LibriSpeech` folder inside datasets_root. Then launch the toolbox with this command:

```
python demo_toolbox.py -d datasets_root
```

Also, if you see `.DS_Store` in the dropdown menus (as in your screenshot), you will have to switch them to `pretrained` for proper operation.

**Comment by notluke27** [comment]
Thanks!
