### ISSUE TITLE
Errno 2 when attempting to install Pytorch and every other necessary material

### ISSUE THREAD

**Issue by Woolton** [CorentinJ/Real-Time-Voice-Cloning#632]
No clue what exactly im missing, but when installing pytorch or tensorflow (or literally anything from requirements.txt i guess) I get a no such file or directory error. I have python installed from the windows store if this matters. 
![image](https://user-images.githubusercontent.com/36093760/105107435-20f55a80-5a86-11eb-9698-144cbad9219d.png)

**Comment by Woolton** [comment]
When attempting to install tensorflow with the "pip install -r requirements.txt" file i get this:
![image](https://user-images.githubusercontent.com/36093760/105107711-a711a100-5a86-11eb-848f-a45f1a23096f.png)

**Comment by blue-fish** [comment]
Python 3.8 is not supported: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-665165023

We can't help with the EnvironmentError message in the 1st screenshot, that's not our code.
