### ISSUE TITLE
Installation solutions for people with multiple python versions?

### ISSUE THREAD

**Issue by Woolton** [CorentinJ/Real-Time-Voice-Cloning#633]
I've been doing a lot of troubleshooting trying to get this to work. though I _believe_ im on python 3.8 right now, ive been installing everything using **pip** instead of **pip3**. thus installing tensorflow version 1.15 didnt work, instead i installed the newest tensorflow. installing everything else worked fine.

I attempted to test "demo_cli.py" normally, I got "no module named 'numpy'" so I used python3 when running the command instead and got "ModuleNotFoundError: no module named 'tensorflow.contrib'

I dont know what to do now, is there a way i can choose to use an older python in the command line, because i do in fact have both 2.7 and 3.7 installed

**Comment by blue-fish** [comment]
Set up a python 3.7 virtual environment. If the command doesn't work, you need to add it to your system path.
```
cd Real-Time-Voice-Cloning
python3.7 -m venv venv
venv\Scripts\activate.bat
```

Then `pip install torch` and `pip install -r requirements.txt` should work.

**Comment by blue-fish** [comment]
When installing dependencies to a virtual environment, you'll need to ensure it is activated before launching the toolbox. You'll know it's active because `(venv)` shows up in your command prompt. If not, run `activate.bat` using the command above.
