### ISSUE TITLE
Synthesizer doesn't work in Python 3.8+

### ISSUE THREAD

**Issue by blue-fish** [CorentinJ/Real-Time-Voice-Cloning#634]
The synthesizer uses Tensorflow 1.x, which is not supported in Python 3.8 or higher. We need help to upgrade the synthesizer model.

* In #370, we tried upgrading the code to Tensorflow 2.x. However, the differences between TF 1.x and 2.x are significant. Even switching to an existing TF 2.x Tacotron model would require an overhaul of the training and inference scripts.
* The preferred approach is to replace it with a Pytorch-based synthesizer. This is something we discussed in #447. I submitted a PR #472, which was not accepted due to bad voice quality. The heavy lifting is done but more work is needed to improve the model.

Please respond to this issue or submit a pull request to help out.

**Comment by vinamramunot-tech** [comment]
I am also facing the same issue. I tried to see if there was packages in tensorflow_addon however couldn't find it. Is there an update to this? @blue-fish

**Comment by blue-fish** [comment]
The information above is still current. [My fork](https://github.com/blue-fish/Real-Time-Voice-Cloning) works with Python 3.8, but it's not the long-term solution to this problem. Someone else needs to step up and contribute a better model.

**Comment by vinamramunot-tech** [comment]
@blue-fish Although I am not knowledgeable but I can give it a try. Is there something that we can start on?

**Comment by blue-fish** [comment]
@vinamramunot-tech Actually I just found something that should improve my pytorch model. I'll report back in a few days if it worked. https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/472#issuecomment-765875497

**Comment by vinamramunot-tech** [comment]
@blue-fish thank you!! Let me know if I can be of any help.

**Comment by blue-fish** [comment]
@vinamramunot-tech It worked, and I expect to have a model for release within a week.

If you are available to help, it would be nice to add mixed precision training support. That will allow us to train better models on consumer GPUs with limited memory. If you have any interest in helping, leave a message in #487 and I'll let you know how you can get started.

**Comment by blue-fish** [comment]
Tentatively closing this since this issue doesn't require attention at this time.
