### ISSUE TITLE
demo_toolbox now inoperable

### ISSUE THREAD

**Issue by Woolton** [CorentinJ/Real-Time-Voice-Cloning#639]
After successfully opening this program just last week I can now no longer use it because i get some numba related issue. numba 0.48 gives me "numba.core not found" 0.51 gives me "numba.decorations not found" numba 0 .49 "ImportError: cannot import name 'structref' from 'numba.experimental'"

what version of numba am i supposed to use?

**Comment by Tomodachi94** [comment]
#638 might be related to this.

**Comment by blue-fish** [comment]
If you do any other work with Python you should use a virtual environment as suggested in #640. The setup instructions for Linux on the wiki and in #615 do this.

Look for a tutorial on the internet ("python virtualenv") or watch #640 for updates, in case instructions are added.
