### ISSUE TITLE
Fail to run demo_cli

### ISSUE THREAD

**Issue by vankhoa21991** [CorentinJ/Real-Time-Voice-Cloning#64]
Hello, I run into this when run the test. Could you help me? Thanks
python demo_cli.py --low_mem
WARNING: Logging before flag parsing goes to stderr.
W0723 23:25:54.357200 139851400320832 deprecation_wrapper.py:119] From /home/vankhoa/code/Sound/Real-Time-Voice-Cloning/synthesizer/models/modules.py:91: The name tf.nn.rnn_cell.RNNCell is deprecated. Please use tf.compat.v1.nn.rnn_cell.RNNCell instead.

Arguments:
    enc_model_fpath:   encoder/saved_models/pretrained.pt
    syn_model_dir:     synthesizer/saved_models/logs-pretrained
    voc_model_fpath:   vocoder/saved_models/pretrained/pretrained.pt
    low_mem:           True
    no_sound:          False

Running a test of your configuration...

Found 1 GPUs available. Using GPU 0 (GeForce GTX 1050 Ti) of compute capability 6.1 with 2.1Gb total memory.

Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "pretrained.pt" trained to step 1564501
Found synthesizer "pretrained" trained to step 278000
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder/saved_models/pretrained/pretrained.pt
Traceback (most recent call last):
  File "demo_cli.py", line 63, in <module>
    vocoder.load_model(args.voc_model_fpath)
  File "/home/vankhoa/code/Sound/Real-Time-Voice-Cloning/vocoder/inference.py", line 31, in load_model
    _model.load_state_dict(checkpoint['model_state'])
  File "/home/vankhoa/contrib/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for WaveRNN:
	Unexpected key(s) in state_dict: "upsample.resnet.batch_norm.num_batches_tracked", "upsample.resnet.layers.0.batch_norm1.num_batches_tracked", "upsample.resnet.layers.0.batch_norm2.num_batches_tracked", "upsample.resnet.layers.1.batch_norm1.num_batches_tracked", "upsample.resnet.layers.1.batch_norm2.num_batches_tracked", "upsample.resnet.layers.2.batch_norm1.num_batches_tracked", "upsample.resnet.layers.2.batch_norm2.num_batches_tracked", "upsample.resnet.layers.3.batch_norm1.num_batches_tracked", "upsample.resnet.layers.3.batch_norm2.num_batches_tracked", "upsample.resnet.layers.4.batch_norm1.num_batches_tracked", "upsample.resnet.layers.4.batch_norm2.num_batches_tracked", "upsample.resnet.layers.5.batch_norm1.num_batches_tracked", "upsample.resnet.layers.5.batch_norm2.num_batches_tracked", "upsample.resnet.layers.6.batch_norm1.num_batches_tracked", "upsample.resnet.layers.6.batch_norm2.num_batches_tracked", "upsample.resnet.layers.7.batch_norm1.num_batches_tracked", "upsample.resnet.layers.7.batch_norm2.num_batches_tracked", "upsample.resnet.layers.8.batch_norm1.num_batches_tracked", "upsample.resnet.layers.8.batch_norm2.num_batches_tracked", "upsample.resnet.layers.9.batch_norm1.num_batches_tracked", "upsample.resnet.layers.9.batch_norm2.num_batches_tracked".

**Comment by mrgloom** [comment]
Most likely your pytorch version is not compatible with the model:
Try `torch==1.1.0`

**Comment by vPunk** [comment]
I have the same problem

**Comment by blue-fish** [comment]
Hello @vankhoa21991 . We recently made a change to the codebase and we are unable to troubleshoot problems that occurred with the old code. May I ask that you please pull the latest code and try again? I expect it should just work, but feel free to open a new issue if it doesn't.
