### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by Dezlite** [CorentinJ/Real-Time-Voice-Cloning#641]
I have been trying to set this Voice Cloning up for a while and I get this error: `Failed to load the native TensorFlow runtime.` I am using Windows, and I set up a virtual environment on Anaconda. This error comes with `ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.` I have installed the requirements.txt, PyTorch, and ffmpeg in the virtual environment. I do not understand what the error means, because when I type `pip show tensorflow` it results in: `Name: tensorflow
Version: 1.15.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\programdata\anaconda3\envs\voicecloning\lib\site-packages
Requires: google-pasta, termcolor, keras-preprocessing, tensorflow-estimator, absl-py, grpcio, gast, opt-einsum, protobuf, six, tensorboard, keras-applications, wheel, astor, numpy, wrapt
Required-by:` so I do not understand what I am missing to get this working up.
The entire error is very long, but if you want me to copy and paste it here, I will.

**Comment by blue-fish** [comment]
Try running this command:
```
python -c "import sys; print(sys.maxsize > 2**32)"
```

The result should be True, but if it returns False then you are on a 32-bit version of Python, and need to install a 64-bit version.

Some other troubleshooting scenarios are mentioned here: https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156
* This might be helpful if your CPU does not support AVX instructions: https://stackoverflow.com/questions/49932993

If none of this helps, you'll need to seek support elsewhere for this issue. You can also try [my fork](https://github.com/blue-fish/Real-Time-Voice-Cloning) for a tensorflow-free version of this repo.

**Comment by Dezlite** [comment]
It outputs true, so what do I do now?

**Comment by blue-fish** [comment]
I don't know enough about your computer's configuration to provide next steps for resolving the tensorflow issue. If you're unable to solve it yourself, these are your remaining options:

1. Install Ubuntu 20.04 (to a virtual machine, or "Try Ubuntu" from a live USB if you have >= 16 GB RAM) and follow these [step-by-step instructions](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/615#issuecomment-740270185) which I've tested, or
2. Install my version of the toolbox which does not use tensorflow: https://github.com/blue-fish/Real-Time-Voice-Cloning
    * However, this is an unofficial version and I cannot provide any help for it.

**Comment by Dezlite** [comment]
Thanks, my computer has 8 GB ram ill try both of those options out.

**Comment by Dezlite** [comment]
Thank you for the help, your version works for me. Since it does not use TensorFlow, are there any differences in the performance of the engine compared to the other one? I figured this because it tells me
`UserWarning: Tensorflow not installed; ParametricUMAP will be unavailable`.

**Comment by blue-fish** [comment]
If you want to hear the difference, we've made some comparisons: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/472#issuecomment-687651582 , and https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/472#issuecomment-704377514

The current pytorch model will perform worse mainly because the network is smaller (15M parameters vs 28M for tensorflow). The next iteration of pytorch synthesizer will have comparable voice quality.
