### ISSUE TITLE
warn("Tensorflow not installed; ParametricUMAP will be unavailable")

### ISSUE THREAD

**Issue by tailname** [CorentinJ/Real-Time-Voice-Cloning#643]
Hello. Help me please. I want to teach Real-Time-Voice-Cloning in Russian.
I run
`python encoder_train.py my_run E:\Tacotron\datasets\LibriSpeech`

### error code

2021-01-28 23:01:47.570003: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
e:\ProgramData\Miniconda3\envs\Now\lib\site-packages\umap\__init__.py:9: UserWarning: Tensorflow not installed; ParametricUMAP will be unavailable
  ### warn("Tensorflow not installed; ParametricUMAP will be unavailable")
Arguments:
    run_id:            my_run
    clean_data_root:   E:\Tacotron\datasets\LibriSpeech\SV2TTS\encoder
    models_dir:        encoder\saved_models
    vis_every:         10
    umap_every:        100
    save_every:        500
    backup_every:      7500
    force_restart:     False
    visdom_server:     http://localhost
    no_visdom:         False

No model "my_run" found, starting training from scratch.
Updating the visualizations every 10 steps.
Setting up a new session...
2021-01-28 23:02:01.214143: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
e:\ProgramData\Miniconda3\envs\Now\lib\site-packages\umap\__init__.py:9: UserWarning: Tensorflow not installed; ParametricUMAP will be unavailable
  warn("Tensorflow not installed; ParametricUMAP will be unavailable")
2021-01-28 23:02:11.390284: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll

CONDA  LIST

# Name                    Version                   Build  Channel
absl-py                   0.11.0                   pypi_0    pypi
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astor                     0.8.1                    pypi_0    pypi
audioread                 2.1.9            py37h03978a9_0    conda-forge
blas                      1.0                         mkl
brotlipy                  0.7.0           py37hcc03f2d_1001    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
certifi                   2020.12.5        py37h03978a9_1    conda-forge
cffi                      1.14.4           py37hd8e9650_1    conda-forge
chardet                   4.0.0            py37h03978a9_1    conda-forge
cryptography              3.3.1            py37hd8e9650_1    conda-forge
cudatoolkit               10.2.89              h74a9793_1
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
dill                      0.3.3              pyhd8ed1ab_0    conda-forge
enum34                    1.1.10                   pypi_0    pypi
freetype                  2.10.4               hd328e21_0
gast                      0.2.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.35.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.4.0            py37h03978a9_0    conda-forge
inflect                   5.0.2            py37h03978a9_1    conda-forge
intel-openmp              2020.2                      254
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9b                   hb83a4c4_2
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1            py37h8c56517_1    conda-forge
libflac                   1.3.3                h0e60522_1    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.37               h2a8f88b_0
librosa                   0.8.0              pyh9f0ad1d_0    conda-forge
libsndfile                1.0.31               h0e60522_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libtiff                   4.1.0                h56a325e_1
libvorbis                 1.3.7                h0e60522_0    conda-forge
llvmlite                  0.34.0                   pypi_0    pypi
lz4-c                     1.9.3                h2bbff1b_0
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.3                    pypi_0    pypi
matplotlib                3.3.3            py37h03978a9_0    conda-forge
matplotlib-base           3.3.3            py37h3379fd5_0    conda-forge
menuinst                  1.4.16                   pypi_0    pypi
mkl                       2020.2                      256
mkl-service               2.3.0            py37h196d8e1_0
mkl_fft                   1.2.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.11.1        py37hcc03f2d_1    conda-forge
ninja                     1.10.2           py37h6d14046_0
numba                     0.52.0           py37h08fd248_0    conda-forge
numpy                     1.19.3                   pypi_0    pypi
numpy-base                1.19.2           py37ha3acd2a_0
olefile                   0.46                     py37_0
openssl                   1.1.1i               h8ffe710_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.8               pyhd3deb0d_0    conda-forge
pillow                    8.1.0            py37h4fa10fc_0
pip                       20.3.3           py37haa95532_0
pooch                     1.3.0              pyhd8ed1ab_0    conda-forge
portaudio                 19.6.0               hca4a3dc_3    conda-forge
protobuf                  3.14.0                   pypi_0    pypi
pycosat                   0.6.3                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pynndescent               0.5.1              pyhd3deb0d_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py37h6538335_4    conda-forge
pyqt5                     5.15.2                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pysocks                   1.7.1            py37h03978a9_3    conda-forge
pysoundfile               0.10.3.post1       pyhd3deb0d_0    conda-forge
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                      py_0    conda-forge
python-sounddevice        0.4.1              pyh9f0ad1d_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.5.1           py3.7_cuda102_cudnn7_0    pytorch
pyzmq                     21.0.1           py37h0d95fc2_0    conda-forge
qt                        5.9.7            vc14h73c81de_0
requests                  2.25.1             pyhd3deb0d_0    conda-forge
resampy                   0.2.2                      py_0    conda-forge
ruamel-yaml               0.15.87                  pypi_0    pypi
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.6.0                    pypi_0    pypi
setuptools                52.0.0           py37haa95532_0
sip                       4.19.8           py37h6538335_0
six                       1.15.0           py37haa95532_0
sqlite                    3.33.0               h2a8f88b_0
synthesizer               0.2.0                    pypi_0    pypi
tbb                       2020.2               h2d74725_3    conda-forge
tensorboard               1.15.0                   pypi_0    pypi
tensorflow                1.15.0                   pypi_0    pypi
tensorflow-estimator      1.15.1                   pypi_0    pypi
tensorflow-gpu            1.15.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               he774522_0
torchfile                 0.1.0                      py_0    conda-forge
torchvision               0.6.1                py37_cu102    pytorch
tornado                   6.1              py37hcc03f2d_1    conda-forge
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
umap-learn                0.5.0            py37h03978a9_0    conda-forge
unicode                   2.8                      pypi_0    pypi
unidecode                 1.1.1                      py_0    anaconda
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1
visdom                    0.1.8.9                       0    conda-forge
vs2015_runtime            14.27.29016          h5e58377_2
webrtcvad                 2.0.10                   pypi_0    pypi
websocket-client          0.57.0           py37h03978a9_4    conda-forge
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
win_inet_pton             1.1.0            py37h03978a9_2    conda-forge
wincertstore              0.2                      py37_0
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h62dcd97_0
zeromq                    4.3.3                h0e60522_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                h04227a9_0

### Sorry if this question is stupid

**Comment by blue-fish** [comment]
Does `encoder_train.py` run? This repo does not use ParametricUMAP, so the warning can be ignored. If the program is stopping, it is for a different reason.

**Comment by tailname** [comment]
> 
> 
> Does `encoder_train.py` run? This repo does not use ParametricUMAP, so the warning can be ignored. If the program is stopping, it is for a different reason.

thanks. 
The program works, I just don't understand why "Tensorflow not installed" .
 I installed Tensorflow this is visible in conda list

**Comment by blue-fish** [comment]
ParametricUMAP needs Tensorflow 2.0 or higher, but when the ImportError occurs it just tells the user to install Tensorflow.

This is fixed in https://github.com/lmcinnes/umap/commit/d599e59fe6a6fd5939a3fd7e868658edca1afff0 . With the latest code, I do not get a warning with Tensorflow 1.15 installed. For more information: https://github.com/lmcinnes/umap/issues/551 

However, users will continue to see the warning until a new release of umap-learn is pushed to PyPI.

**Comment by tailname** [comment]
> 
> 
> ParametricUMAP needs Tensorflow 2.0 or higher, but when the ImportError occurs it just tells the user to install Tensorflow.
> 
> This is fixed in [lmcinnes/umap@d599e59](https://github.com/lmcinnes/umap/commit/d599e59fe6a6fd5939a3fd7e868658edca1afff0) . With the latest code, I do not get a warning with Tensorflow 1.15 installed. For more information: [lmcinnes/umap#551](https://github.com/lmcinnes/umap/issues/551)
> 
> However, users will continue to see the warning until a new release of umap-learn is pushed to PyPI.

Hello. 
Sorry to bother you, I was wondering. 
How to run python encoder_train.py my_ru <datasets_root>/SV2TTS/encoder on the GPU ?

**Comment by blue-fish** [comment]
To check if you have GPU support, start Python and type:
```
import torch
torch.cuda.is_available()
```

If it returns True, you have GPU support and it should work automatically. We check `torch.cuda.is_available()` at runtime and use the GPU if Pytorch says it is available.

If it returns False, then you do not have GPU support. If that is the case you'll have to go elsewhere for help setting up Pytorch for CUDA support.

**Comment by blue-fish** [comment]
Change this line: https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/5425557efe30863267f805851f918124191e0be0/encoder/train.py#L30

To: `device = torch.device("cuda")`

And let me know which error message you get.

**Comment by tailname** [comment]
I have not received an error message. 
I double-checked what I saved
`device = torch.device ("cuda")`
after launch
`python encoder_train.py my_ru <datasets_root> / SV2TTS / encoder`
 only CPU works.

**Comment by blue-fish** [comment]
What indication are you getting that it's using the CPU?

**Comment by tailname** [comment]
Sorry. 
Maybe I made a mistake and the GPU does everything much faster than the CPU .
And the load on the CPU is due to reading and writing .
[this is a snapshot of my system](https://drive.google.com/file/d/1jj_nRANPfeNE5Ytsg5lVEwwiVJ3D5ax7/view?usp=sharing)
