### ISSUE TITLE
Fails to export file

### ISSUE THREAD

**Issue by MatthewAlner** [CorentinJ/Real-Time-Voice-Cloning#646]
Ok so i'm on Mac 11.1 Big sur and have ffmpeg installed via brew, when trying to export I get the error "File contains data in an unimplemented format."

After some googling it seems to be an issue with a conflict of version of `libsndfile`, `soundfile` picks up the `libsndfile.dylib` file that homebrew distributes (I think as a dep of ffmpeg)

my "Fix" was to monkeypatch `soundfile.py` on line 140

```
try:
    _libname = _find_library('sndfile')
    if _libname is None:
        raise OSError('sndfile library not found')
    _snd = _ffi.dlopen(_libname)
except OSError:
```

it's looking for the library first, make sure it can't find it by changing it too,

```
_libname = None
```

🤷🏻‍♂️ I don't know what the real fix is, but I thought i'd document this incase it helps someone else

p.s this thread was the key to figuring out the issue for me

https://github.com/bastibe/python-soundfile/issues/237

**Comment by blue-fish** [comment]
Thanks for reporting this. Are you using conda?

**Comment by blue-fish** [comment]
I'm going to blame this on conda. Solution is to not use conda.
Please reopen this issue if the problem occurs in a normal Python environment.
