### ISSUE TITLE
Can't Install requirements_gpu.txt

### ISSUE THREAD

**Issue by LiamCat** [CorentinJ/Real-Time-Voice-Cloning#652]
my graphics card is GTX 1650, I installed CUDA 10, downloaded Tensorflow 1.14.0 and I used this video to set up the program: https://www.youtube.com/watch?v=nvBF0Rf2m2Y&t=548s

I looked at this forum and so I typed in the anaconda3 console ` pip install -r requirements_gpu.txt`

**and then this happened:** ![help](https://user-images.githubusercontent.com/69638063/107087413-4fe42e00-67f3-11eb-8e55-f7188db07d0c.png)

I downloaded the files in November 2020 by the way.
ONE MORE THING. If anyone knows if GTX1650 doesn't actually support Cuda then that would be helpful! thank you!

**Comment by JakubPilny** [comment]
I'd suggest to follow this guide instead: https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/

**Comment by blue-fish** [comment]
The Poorly Documented guide is obsolete. Use this one: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

Unless you're training a model, it's not worth the trouble to install Tensorflow 1.x with GPU support. Synthesizer inference is fast even on CPU.

**Comment by LiamCat** [comment]
Just began to fix some issues by downloading necessary files to run datasets and Found out that only my GPU memory is being used when I tested the toolbox, Maybe that is what the GPU is for (GTX 1650)? Here is a screenshot from task manager

![gpu](https://user-images.githubusercontent.com/69638063/107120427-79e63080-6885-11eb-98fb-05fb7d696b0c.png)

Anyway, I just want to say THANK YOU all Contributors and helpers for making such a fantastic project, and the fact that the community is still alive gives me some hope this will get better.

-Liam

**Comment by blue-fish** [comment]
Closing this issue, #472 is merged and removes the dependency on tensorflow.
