### ISSUE TITLE
SV2TTS doesn't open when i enter python demo_toolbox.py

### ISSUE THREAD

**Issue by kanzww** [CorentinJ/Real-Time-Voice-Cloning#659]
Everytime i enter python demo_toolbox.py, even with dataset, It just doesn't open the SV2TTS at all. I tried everything required. I just don't know why it didn't open. Can you help me to make SV2TTS open and run?

**Comment by blue-fish** [comment]
Need more information. What is your operating system? Is there an error message in the terminal?

You can try our detailed setup guides for [Windows](https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542) and [Linux](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/615#issuecomment-740270185).

**Comment by kanzww** [comment]
Windows

**Comment by kanzww** [comment]
![image](https://user-images.githubusercontent.com/56378844/107977765-48eeb580-6f81-11eb-8e98-67159ef60fb3.png)
this is what happened, and it didn't show the toolbox.

**Comment by blue-fish** [comment]
Make sure you are running the command from the folder that contains demo_toolbox.py.

**Comment by kanzww** [comment]
I did that earlier but it still didn't work

**Comment by blue-fish** [comment]
I'll have to refer you to the detailed setup instructions for Windows: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

If you follow the instructions to the letter and it still doesn't work, feel free to ask for help there.

**Comment by BusyBRAINSAILOR** [comment]
mine shows the same after following all the procedures please help
