### ISSUE TITLE
Bug with new version of repo

### ISSUE THREAD

**Issue by zxmanxz** [CorentinJ/Real-Time-Voice-Cloning#663]
Hello! I tried to use this repo with new PyTorch implementation. When the models had been downloaded I tried to run demo_toolbox.py and got the next one error: 
`
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
`
It had been multiplied by many times and after that I couldn't use gui of the program.

**Comment by blue-fish** [comment]
This was first reported in #658. Are you using Python 3.9? If so, try switching to Python 3.8.

**Comment by zxmanxz** [comment]
I'm currently using Python 3.7.7

**Comment by zxmanxz** [comment]
But it is really works with Python 3.8. So, thx :)

**Comment by reza-latifi** [comment]
I'm having the same problem on Python 3.8.10
