### ISSUE TITLE
Insight on the 5 second clips to train

### ISSUE THREAD

**Issue by AdityaJain1030** [CorentinJ/Real-Time-Voice-Cloning#665]
Hey! First of all, I would like to thank you guys for the amazing work you've put into this project! 

I've been recently attracted to Voice Synthesis, and have spent a few days learning about the methodologies behind tacotron (2) and fastspeech. I stumbled across your repo and was intrigued by the 5-second clips needed, rather than a whole dataset. In currently using TensorflowTTS for the models, and am trying to figure out how to train a custom multi-speaker model with limited data.

I would be really grateful for help understanding this process, so I know what I'm looking for inside the code😁.

**Comment by blue-fish** [comment]
Here is a brief overview of the 3 parts that make up SV2TTS. The repo is organized around this structure.
1. **Speaker encoder.** This converts a short audio into a mathematical representation of the voice. We call this an utterance embedding. In this repo, it's a numpy array of shape (256,) composed of floats between 0 and 1.
2. **Modified Tacotron synthesizer.** The utterance embedding from the speaker encoder is concat with the output of Tacotron's text encoder as it enters the decoder. For SV2TTS, Tacotron is trained on a large multi-speaker dataset that helps it learn the relationship between utterance embedding and features in the mel spectrogram that it generates as output. Once the model is trained, it can perform zero-shot voice cloning on voices that are unseen during training.
3. **Vocoder.** This converts the mel spectrograms to audio waveforms that we perceive as speech.

I don't have time to answer further questions, but for more information read the papers and Corentin's thesis linked in README.md. I have some audio samples on my [webpage](https://blue-fish.github.io/experiments/RTVC-7.html) so you can hear how well it works on our pretrained models.
