### ISSUE TITLE
No gui?

### ISSUE THREAD

**Issue by elazzzzyy** [CorentinJ/Real-Time-Voice-Cloning#666]
i run python demo_toolbox.py and what is returned is:

(voice-clone) S:\path\path\path\path\Real-Time-Voice-Cloning-master>python demo_toolbox.py
S:\path\path\path\path\Real-Time-Voice-Cloning-master\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Error: Model files not found. Follow these instructions to get and install the models:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models

which confuses me because no GUI launches and it does not give an error either.

**Comment by blue-fish** [comment]
There is an error but we might need to draw more attention to it. Would it help if the output looked like this instead?
```
(voice-clone) S:\path\path\path\path\Real-Time-Voice-Cloning-master>python demo_toolbox.py
S:\path\path\path\path\Real-Time-Voice-Cloning-master\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
datasets_root: None
enc_models_dir: encoder\saved_models
syn_models_dir: synthesizer\saved_models
voc_models_dir: vocoder\saved_models
cpu: False
seed: None
no_mp3_support: False

********************************************************************************
Error: Model files not found. Follow these instructions to get and install the models:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models
********************************************************************************
```

**Comment by elazzzzyy** [comment]
I think that would help the overall design and be more user friendly if that's what you're asking.

However, I watched a tutorial, did everything they did exactly with no errors and then they ran the demo and it worked and opened the GUI then afterwards they moved the models.

**Comment by blue-fish** [comment]
Thanks for the feedback. We added the model check in July 2020 (#416) so they wouldn't see the error message if they were using an older version of the software.

Please ask for help if you're still stuck on what needs to be done next.
