### ISSUE TITLE
Dataset option is blur(not usable) in GUI

### ISSUE THREAD

**Issue by clonereal** [CorentinJ/Real-Time-Voice-Cloning#667]
![Screenshot (4)](https://user-images.githubusercontent.com/34327216/108250234-dad5fa00-710a-11eb-84a5-21472a3084de.png)
How to enable dataset option ? It is not usable in GUI. Where to extract data sets? <dataset_root> means any folder ?

**Comment by blue-fish** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning#4-optional-download-datasets
