### ISSUE TITLE
ImportError: DLL load failed: Can't find module

### ISSUE THREAD

**Issue by Avepy** [CorentinJ/Real-Time-Voice-Cloning#670]
Hi, I've tried to execute command; _python demo_cli.py_ 
after that I've get an error like;

([Test_Voice]) D:\voice>python demo_cli.py
Traceback (most recent call last):
  File "demo_cli.py", line 4, in <module>
    from synthesizer.inference import Synthesizer
  File "D:\voice\synthesizer\inference.py", line 1, in <module>
    import torch
  File "C:\Users\damia\anaconda3\envs\[Test_Voice]\lib\site-packages\torch\__init__.py", line 190, in <module>
    from torch._C import *
ImportError: DLL load failed: Can't find module

I am trying to fix this issue but don't have any idea
Thanks!

**Comment by blue-fish** [comment]
You're getting that error message because Anaconda does not include the VC runtime DLL, and it's needed to use Pytorch. There's a download link here: https://github.com/pytorch/pytorch/issues/32916#issuecomment-611868780

**Comment by Avepy** [comment]
Still didn't help

**Comment by blue-fish** [comment]
Please try a normal Python install instead of Anaconda.
The Windows setup instructions are here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
