### ISSUE TITLE
No voice generating 

### ISSUE THREAD

**Issue by Jojo-M-C** [CorentinJ/Real-Time-Voice-Cloning#672]
I'm using a colab notebook and for some reason I only get some noise. 

https://user-images.githubusercontent.com/66216869/108493161-4b654e00-72a6-11eb-9da0-cec04228c304.mp4

**Comment by blue-fish** [comment]
Sorry, we're unable to provide support for this issue. We removed the colab notebook from the repo because no one was maintaining it. (#656, #657)
