### ISSUE TITLE
Exception: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by KiwoNtV** [CorentinJ/Real-Time-Voice-Cloning#673]
When I start the program and click on "load" then the following error message appears between the "Loaded DATA" messages: Exception: CUDA error: no kermal image is available for execution on the device

Please help me because' I don't know what I should do to fix that. Because of this error I can't add the 4 points.

![tea](https://user-images.githubusercontent.com/73958071/108550784-4f698e00-72ef-11eb-9e7e-1502daec11d7.PNG)

**Comment by blue-fish** [comment]
Your GPU is too old to use the latest pytorch.

First uninstall pytorch:
```
pip uninstall pytorch
```
Then install an older pytorch:
```
pip install torch==1.2 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by KiwoNtV** [comment]
It's 

> Your GPU is too old to use the latest pytorch.
> 
> First uninstall pytorch:
> 
> ```
> pip uninstall pytorch
> ```
> 
> Then install an older pytorch:
> 
> ```
> pip install torch==1.2 -f https://download.pytorch.org/whl/torch_stable.html
> ```

It's still the same error message

**Comment by blue-fish** [comment]
Try running on CPU instead of GPU:
```
python demo_toolbox.py --cpu
```

**Comment by KiwoNtV** [comment]
Now it sais: 
ImportError: DLL load failed: The specified module was not found.

**Comment by blue-fish** [comment]
This might help: https://github.com/pytorch/pytorch/issues/4518#issuecomment-695346248
