### ISSUE TITLE
Real Time Voice on MacBook

### ISSUE THREAD

**Issue by ddlafouine** [CorentinJ/Real-Time-Voice-Cloning#674]
Hello, I am a mac user and trying to install your "software". 
But when I launched demo_cly I displayed this error...

Traceback (most recent call last):
  File "demo_cli.py", line 1, in <module>
    from encoder.params_model import model_embedding_size as speaker_embedding_size
ModuleNotFoundError: No module named 'encoder.params_model'

Can you help me?

**Comment by blue-fish** [comment]
Are you double-clicking demo_cli.py in the Finder? Make sure you are launching Python from the terminal.
```
python demo_cli.py
```

**Comment by ddlafouine** [comment]
This is what I did 😅

**Comment by inglesuniversal** [comment]
@ddlafouine any luck running this on your Mac? I have a MacBook Air with BIg Sur and I am not sure it this script will run on it.

Can you comment on that?
