### ISSUE TITLE
now ,did it support Chinese language?

### ISSUE THREAD

**Issue by UEBoy2019** [CorentinJ/Real-Time-Voice-Cloning#676]
thank u ,friends!

**Comment by blue-fish** [comment]
Use the zhrtvc fork for Chinese language.
https://github.com/KuangDD/zhrtvc

**Comment by babysor** [comment]
All links to KuangDD's projects now are no longer accessible. I'm currently working on latest fork of this repo to support mandarin and if anyone want to use as reference, please be free to folk and train: https://github.com/babysor/Realtime-Voice-Clone-Chinese

**Comment by fanOfJava** [comment]
> All links to KuangDD's projects now are no longer accessible. I'm currently working on latest fork of this repo to support mandarin and if anyone want to use as reference, please be free to folk and train: https://github.com/babysor/Realtime-Voice-Clone-Chinese

i can not even synthesize ''ni hao' by your repo
