### ISSUE TITLE
small issue in symbols.py

### ISSUE THREAD

**Issue by shuzeZHAO** [CorentinJ/Real-Time-Voice-Cloning#68]
Hi @CorentinJ , thank you for your repo. I had lots of fun with it. :)

I think there is a small mistake in synthesizer\utiles\symbols.py:

`_characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\"\"(),-.:;? "`

it should be 

`_characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\"\'(),-.:;? "`

right?

Thanks,
sz

**Comment by CorentinJ** [comment]
Correct. It's a mistake I inadvertently introduced god knows when and it's hard to tell what impact it's having. I put the fix in 071a6f9eca9393ee302d3bdc8c0c39bce5813cba, but I should be retraining the synthesizer and vocoder. Don't have the hardware nor budget unfortunately.

**Comment by shuzeZHAO** [comment]
@CorentinJ I can share my model if it performs well, but just want to check a few things with you. 
The text in LibreSpeech dataset are all in uppercase and almost doesn't contain any puncturations. Does it impact the training? VCTK is probably better since it's with normal text format? 

Thanks,
Shuze
