### ISSUE TITLE
Model Files Not Found...After Working Perfectly

### ISSUE THREAD

**Issue by JohnJnotFKennedy** [CorentinJ/Real-Time-Voice-Cloning#680]
A few weeks ago I had everything set up and it was working perfectly. Today when working through installing with my Research  Assistant everything ceased working and I got this...

![rtvc issue](https://user-images.githubusercontent.com/43022870/109058555-1fd0d200-76b1-11eb-8fcd-3742e3026aae.JPG)

Ive checked my environment and TF is installed and I've re-dl'ed all the pretrained models and updated any folders. They are all extracted to the right place. No idea why its not working now.

**Comment by JohnJnotFKennedy** [comment]
Update: I've reinstalled umap and the TF error goes away but still same "Model files not found" error at bottom

**Comment by woodrow73** [comment]
There shouldn't be a dependency on tensorflow as of 10 days ago? - https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/652#issuecomment-778798757

Are you using the latest windows install instructions - https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

**Comment by blue-fish** [comment]
Please try this command. Also check the permissions and ownership on the folders.
```
python demo_toolbox.py --enc_models_dir C:\full\path\to\encoder\saved_models --syn_models_dir C:\full\path\to\synthesizer\saved_models --voc_models_dir C:\full\path\to\vocoder\saved_models
```

You can also bypass the model check by commenting out these lines.
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/demo_toolbox.py#L38-L40

**Comment by JohnJnotFKennedy** [comment]
Thanks @woodrow73 and @blue-fish I think as I've set up using the old documents/files I'm going to start from scratch with the new install instructions and updates. Appreciate the help!
