### ISSUE TITLE
Revisiting Dataset GUI

### ISSUE THREAD

**Issue by JohnJnotFKennedy** [CorentinJ/Real-Time-Voice-Cloning#685]
First, thanks for providing the updated Windows instructions. Works perfectly, way more stable, and easy to set up. 

Just wondering (as it was brought up in previous issues like #667 #637 #630 etc.) if there are any ways in which to load our own datasets into this part of the GUI? I only ask because in the previous iteration I was using, I had batches of files (so I could switch between different voices to clone) that was quite easy to cycle through, whereas now I just have the browse and load feature. 

Thanks!

**Comment by JohnJnotFKennedy** [comment]
Sorry this piggy backs off of those who've mentioned that the dataset GUI is "greyed out". I'm just wondering if there's a way so that I can cycle back through datasets that I have under -d "dataset" in the RTVC folder?

**Comment by blue-fish** [comment]
You can try implementing the code changes in https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/527 . It allows for a folder called `UserAudio` in datasets_root to be used as a custom dataset.
