### ISSUE TITLE
Is there any possible way to control intonation?

### ISSUE THREAD

**Issue by StElysse** [CorentinJ/Real-Time-Voice-Cloning#686]
I have trained several models with the program so far, and I am very satisfied with the results.

However, when I synthesize and vocode text, intonation can be somewhat random and uncontrollable. For exmaple, question intonation is hard to reliably produce, and I rely on trial and error to generate phrases with intonation that sounds like a question. 

I've found other utilities that allow controlling the alteration of pitch or intonation in some way:

-[SKVASynth/FastPitch has a very interactive GUI that allows the altering of pitch for individual or several letters.](https://www.nexusmods.com/skyrimspecialedition/mods/44184)
-[Some TTS programs like this one use meta-tags or SSML tags to convey a certain mood, like uncertainty.](https://stackoverflow.com/questions/46953918/using-different-intonations-with-watson-text-to-speech)

Is this sort of thing possible in this repo, or beyond its scope?

Thank you!

**Comment by dorigom06** [comment]
I'm also having a similar problem. I'm using my friends to train the model, and they both have accents. The code isn't particularly good at modeling certain accents.

**Comment by blue-fish** [comment]
@StElysse Not possible with this repo currently. The Tacotron model would need to be modified to support "Global Style Tokens" (#230). A multi-speaker dataset with labeled emotions is also lacking.

@dorigom06 For better accent matching, finetune the model with the process in #437.
