### ISSUE TITLE
5 seconds is not real-time!

### ISSUE THREAD

**Issue by aKamrani** [CorentinJ/Real-Time-Voice-Cloning#687]
5 seconds is not real-time bro!
real-time means under milliseconds order!
may it be happen by using more cpu/gpu resources or not ??!

**Comment by blue-fish** [comment]
In the literature, real-time means that the generation time is less than the audio's duration.
Change the vocoder model to achieve real-time performance, by your definition.

Here are some recommended neural vocoders which offer a good balance of speed and audio quality.
* https://github.com/kan-bayashi/ParallelWaveGAN
* https://github.com/seungwonpark/melgan
* https://github.com/descriptinc/melgan-neurips

**Comment by inconnu11** [comment]
Hi, could you please share the literatures which mentions the definition of real-time generation? Many thanks!
