### ISSUE TITLE
Problem Running Toolbox

### ISSUE THREAD

**Issue by EpicoTortuga** [CorentinJ/Real-Time-Voice-Cloning#690]
Hello, I'm trying to run the toolbox with the train-clean-100 dataset. Every time I run it cmd returns this: 

```
C:\Users\Scanner\Documents\Real Time TTS\Real-Time-Voice-Cloning>python demo_too
lbox.py -d C:\Users\Scanner\Documents\Real Time TTS
usage: demo_toolbox.py [-h] [-d DATASETS_ROOT] [-e ENC_MODELS_DIR]
                       [-s SYN_MODELS_DIR] [-v VOC_MODELS_DIR] [--cpu]
                       [--seed SEED] [--no_mp3_support]
demo_toolbox.py: error: unrecognized arguments: Time TTS
```

I'm pretty new to this so I'm not completely sure how to fix this. Thank you!

**Comment by EpicoTortuga** [comment]
It seems to work fine when I don't use my downloaded dataset.

**Comment by blue-fish** [comment]
Add quotes around the dataset location if there are spaces in the path. Ensure that a supported dataset is in the specified location.
```
python demo_toolbox.py -d "C:\Users\Scanner\Documents\Real Time TTS"
```
