### ISSUE TITLE
Running demo_cli.py fails on new installation

### ISSUE THREAD

**Issue by frohzinn** [CorentinJ/Real-Time-Voice-Cloning#692]
Hi,

I am getting this error.    Summarizing:

**RuntimeError: Error(s) in loading state_dict for Tacotron:**
	Missing key(s) in state_dict: "stop_threshold", "encoder.embedding.weight",   ................................
        Unexpected key(s) in state_dict: "upsample.resnet.conv_in.weight", "upsample.resnet.batch_norm.weight", ....

It seems like the synthesizer state_dict  has a different set of keys than expected.

The pretrained models were downloaded from here:
     https://github.com/blue-fish/Real-Time-Voice-Cloning/releases/download/v1.0/pretrained.zip

Here are the details from the console:

/usr/local/bin/python3.7 /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 62684 --file /Users/7004470/RealTimeVoice/Real-Time-Voice-Cloning-master/demo_cli.py
pydev debugger: process 52660 is connecting

Connected to pydev debugger (build 193.6015.41)
Arguments:
    enc_model_fpath:   encoder/saved_models/pretrained.pt
    syn_model_fpath:   synthesizer/saved_models/pretrained/pretrained.pt
    voc_model_fpath:   vocoder/saved_models/pretrained/pretrained.pt
    cpu:               False
    no_sound:          False
    seed:              None
    no_mp3_support:    False

/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
Running a test of your configuration...

Using CPU for inference.

Preparing the encoder, the synthesizer and the vocoder...
Loaded encoder "pretrained.pt" trained to step 1564501
Synthesizer using device: cpu
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder/saved_models/pretrained/pretrained.pt
Testing your configuration with small inputs.
	Testing the encoder...
	Testing the synthesizer... (loading the model will output a lot of text)
Trainable Parameters: 30.870M
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/7004470/RealTimeVoice/Real-Time-Voice-Cloning-master/demo_cli.py", line 109, in <module>
    mels = synthesizer.synthesize_spectrograms(texts, embeds)
  File "/Users/7004470/RealTimeVoice/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 86, in synthesize_spectrograms
    self.load()
  File "/Users/7004470/RealTimeVoice/Real-Time-Voice-Cloning-master/synthesizer/inference.py", line 64, in load
    self._model.load(self.model_fpath)
  File "/Users/7004470/RealTimeVoice/Real-Time-Voice-Cloning-master/synthesizer/models/tacotron.py", line 497, in load
    self.load_state_dict(checkpoint["model_state"])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
	Missing key(s) in state_dict: "stop_threshold", "encoder.embedding.weight", "encoder.pre_net.fc1.weight", "encoder.pre_net.fc1.bias", "encoder.pre_net.fc2.weight", "encoder.pre_net.fc2.bias", "encoder.cbhg.conv1d_bank.0.conv.weight", "encoder.cbhg.conv1d_bank.0.bnorm.weight", "encoder.cbhg.conv1d_bank.0.bnorm.bias", "encoder.cbhg.conv1d_bank.0.bnorm.running_mean", "encoder.cbhg.conv1d_bank.0.bnorm.running_var", "encoder.cbhg.conv1d_bank.1.conv.weight", "encoder.cbhg.conv1d_bank.1.bnorm.weight", "encoder.cbhg.conv1d_bank.1.bnorm.bias", "encoder.cbhg.conv1d_bank.1.bnorm.running_mean", "encoder.cbhg.conv1d_bank.1.bnorm.running_var", "encoder.cbhg.conv1d_bank.2.conv.weight", "encoder.cbhg.conv1d_bank.2.bnorm.weight", "encoder.cbhg.conv1d_bank.2.bnorm.bias", "encoder.cbhg.conv1d_bank.2.bnorm.running_mean", "encoder.cbhg.conv1d_bank.2.bnorm.running_var", "encoder.cbhg.conv1d_bank.3.conv.weight", "encoder.cbhg.conv1d_bank.3.bnorm.weight", "encoder.cbhg.conv1d_bank.3.bnorm.bias", "encoder.cbhg.conv1d_bank.3.bnorm.running_mean", "encoder.cbhg.conv1d_bank.3.bnorm.running_var", "encoder.cbhg.conv1d_bank.4.conv.weight", "encoder.cbhg.conv1d_bank.4.bnorm.weight", "encoder.cbhg.conv1d_bank.4.bnorm.bias", "encoder.cbhg.conv1d_bank.4.bnorm.running_mean", "encoder.cbhg.conv1d_bank.4.bnorm.running_var", "encoder.cbhg.conv_project1.conv.weight", "encoder.cbhg.conv_project1.bnorm.weight", "encoder.cbhg.conv_project1.bnorm.bias", "encoder.cbhg.conv_project1.bnorm.running_mean", "encoder.cbhg.conv_project1.bnorm.running_var", "encoder.cbhg.conv_project2.conv.weight", "encoder.cbhg.conv_project2.bnorm.weight", "encoder.cbhg.conv_project2.bnorm.bias", "encoder.cbhg.conv_project2.bnorm.running_mean", "encoder.cbhg.conv_project2.bnorm.running_var", "encoder.cbhg.highways.0.W1.weight", "encoder.cbhg.highways.0.W1.bias", "encoder.cbhg.highways.0.W2.weight", "encoder.cbhg.highways.0.W2.bias", "encoder.cbhg.highways.1.W1.weight", "encoder.cbhg.highways.1.W1.bias", "encoder.cbhg.highways.1.W2.weight", "encoder.cbhg.highways.1.W2.bias", "encoder.cbhg.highways.2.W1.weight", "encoder.cbhg.highways.2.W1.bias", "encoder.cbhg.highways.2.W2.weight", "encoder.cbhg.highways.2.W2.bias", "encoder.cbhg.highways.3.W1.weight", "encoder.cbhg.highways.3.W1.bias", "encoder.cbhg.highways.3.W2.weight", "encoder.cbhg.highways.3.W2.bias", "encoder.cbhg.rnn.weight_ih_l0", "encoder.cbhg.rnn.weight_hh_l0", "encoder.cbhg.rnn.bias_ih_l0", "encoder.cbhg.rnn.bias_hh_l0", "encoder.cbhg.rnn.weight_ih_l0_reverse", "encoder.cbhg.rnn.weight_hh_l0_reverse", "encoder.cbhg.rnn.bias_ih_l0_reverse", "encoder.cbhg.rnn.bias_hh_l0_reverse", "encoder_proj.weight", "decoder.r", "decoder.prenet.fc1.weight", "decoder.prenet.fc1.bias", "decoder.prenet.fc2.weight", "decoder.prenet.fc2.bias", "decoder.attn_net.conv.weight", "decoder.attn_net.conv.bias", "decoder.attn_net.L.weight", "decoder.attn_net.W.weight", "decoder.attn_net.W.bias", "decoder.attn_net.v.weight", "decoder.attn_rnn.weight_ih", "decoder.attn_rnn.weight_hh", "decoder.attn_rnn.bias_ih", "decoder.attn_rnn.bias_hh", "decoder.rnn_input.weight", "decoder.rnn_input.bias", "decoder.res_rnn1.weight_ih", "decoder.res_rnn1.weight_hh", "decoder.res_rnn1.bias_ih", "decoder.res_rnn1.bias_hh", "decoder.res_rnn2.weight_ih", "decoder.res_rnn2.weight_hh", "decoder.res_rnn2.bias_ih", "decoder.res_rnn2.bias_hh", "decoder.mel_proj.weight", "decoder.stop_proj.weight", "decoder.stop_proj.bias", "postnet.conv1d_bank.0.conv.weight", "postnet.conv1d_bank.0.bnorm.weight", "postnet.conv1d_bank.0.bnorm.bias", "postnet.conv1d_bank.0.bnorm.running_mean", "postnet.conv1d_bank.0.bnorm.running_var", "postnet.conv1d_bank.1.conv.weight", "postnet.conv1d_bank.1.bnorm.weight", "postnet.conv1d_bank.1.bnorm.bias", "postnet.conv1d_bank.1.bnorm.running_mean", "postnet.conv1d_bank.1.bnorm.running_var", "postnet.conv1d_bank.2.conv.weight", "postnet.conv1d_bank.2.bnorm.weight", "postnet.conv1d_bank.2.bnorm.bias", "postnet.conv1d_bank.2.bnorm.running_mean", "postnet.conv1d_bank.2.bnorm.running_var", "postnet.conv1d_bank.3.conv.weight", "postnet.conv1d_bank.3.bnorm.weight", "postnet.conv1d_bank.3.bnorm.bias", "postnet.conv1d_bank.3.bnorm.running_mean", "postnet.conv1d_bank.3.bnorm.running_var", "postnet.conv1d_bank.4.conv.weight", "postnet.conv1d_bank.4.bnorm.weight", "postnet.conv1d_bank.4.bnorm.bias", "postnet.conv1d_bank.4.bnorm.running_mean", "postnet.conv1d_bank.4.bnorm.running_var", "postnet.conv_project1.conv.weight", "postnet.conv_project1.bnorm.weight", "postnet.conv_project1.bnorm.bias", "postnet.conv_project1.bnorm.running_mean", "postnet.conv_project1.bnorm.running_var", "postnet.conv_project2.conv.weight", "postnet.conv_project2.bnorm.weight", "postnet.conv_project2.bnorm.bias", "postnet.conv_project2.bnorm.running_mean", "postnet.conv_project2.bnorm.running_var", "postnet.pre_highway.weight", "postnet.highways.0.W1.weight", "postnet.highways.0.W1.bias", "postnet.highways.0.W2.weight", "postnet.highways.0.W2.bias", "postnet.highways.1.W1.weight", "postnet.highways.1.W1.bias", "postnet.highways.1.W2.weight", "postnet.highways.1.W2.bias", "postnet.highways.2.W1.weight", "postnet.highways.2.W1.bias", "postnet.highways.2.W2.weight", "postnet.highways.2.W2.bias", "postnet.highways.3.W1.weight", "postnet.highways.3.W1.bias", "postnet.highways.3.W2.weight", "postnet.highways.3.W2.bias", "postnet.rnn.weight_ih_l0", "postnet.rnn.weight_hh_l0", "postnet.rnn.bias_ih_l0", "postnet.rnn.bias_hh_l0", "postnet.rnn.weight_ih_l0_reverse", "postnet.rnn.weight_hh_l0_reverse", "postnet.rnn.bias_ih_l0_reverse", "postnet.rnn.bias_hh_l0_reverse", "post_proj.weight". 
	Unexpected key(s) in state_dict: "upsample.resnet.conv_in.weight", "upsample.resnet.batch_norm.weight", "upsample.resnet.batch_norm.bias", "upsample.resnet.batch_norm.running_mean", "upsample.resnet.batch_norm.running_var", "upsample.resnet.batch_norm.num_batches_tracked", "upsample.resnet.layers.0.conv1.weight", "upsample.resnet.layers.0.conv2.weight", "upsample.resnet.layers.0.batch_norm1.weight", "upsample.resnet.layers.0.batch_norm1.bias", "upsample.resnet.layers.0.batch_norm1.running_mean", "upsample.resnet.layers.0.batch_norm1.running_var", "upsample.resnet.layers.0.batch_norm1.num_batches_tracked", "upsample.resnet.layers.0.batch_norm2.weight", "upsample.resnet.layers.0.batch_norm2.bias", "upsample.resnet.layers.0.batch_norm2.running_mean", "upsample.resnet.layers.0.batch_norm2.running_var", "upsample.resnet.layers.0.batch_norm2.num_batches_tracked", "upsample.resnet.layers.1.conv1.weight", "upsample.resnet.layers.1.conv2.weight", "upsample.resnet.layers.1.batch_norm1.weight", "upsample.resnet.layers.1.batch_norm1.bias", "upsample.resnet.layers.1.batch_norm1.running_mean", "upsample.resnet.layers.1.batch_norm1.running_var", "upsample.resnet.layers.1.batch_norm1.num_batches_tracked", "upsample.resnet.layers.1.batch_norm2.weight", "upsample.resnet.layers.1.batch_norm2.bias", "upsample.resnet.layers.1.batch_norm2.running_mean", "upsample.resnet.layers.1.batch_norm2.running_var", "upsample.resnet.layers.1.batch_norm2.num_batches_tracked", "upsample.resnet.layers.2.conv1.weight", "upsample.resnet.layers.2.conv2.weight", "upsample.resnet.layers.2.batch_norm1.weight", "upsample.resnet.layers.2.batch_norm1.bias", "upsample.resnet.layers.2.batch_norm1.running_mean", "upsample.resnet.layers.2.batch_norm1.running_var", "upsample.resnet.layers.2.batch_norm1.num_batches_tracked", "upsample.resnet.layers.2.batch_norm2.weight", "upsample.resnet.layers.2.batch_norm2.bias", "upsample.resnet.layers.2.batch_norm2.running_mean", "upsample.resnet.layers.2.batch_norm2.running_var", "upsample.resnet.layers.2.batch_norm2.num_batches_tracked", "upsample.resnet.layers.3.conv1.weight", "upsample.resnet.layers.3.conv2.weight", "upsample.resnet.layers.3.batch_norm1.weight", "upsample.resnet.layers.3.batch_norm1.bias", "upsample.resnet.layers.3.batch_norm1.running_mean", "upsample.resnet.layers.3.batch_norm1.running_var", "upsample.resnet.layers.3.batch_norm1.num_batches_tracked", "upsample.resnet.layers.3.batch_norm2.weight", "upsample.resnet.layers.3.batch_norm2.bias", "upsample.resnet.layers.3.batch_norm2.running_mean", "upsample.resnet.layers.3.batch_norm2.running_var", "upsample.resnet.layers.3.batch_norm2.num_batches_tracked", "upsample.resnet.layers.4.conv1.weight", "upsample.resnet.layers.4.conv2.weight", "upsample.resnet.layers.4.batch_norm1.weight", "upsample.resnet.layers.4.batch_norm1.bias", "upsample.resnet.layers.4.batch_norm1.running_mean", "upsample.resnet.layers.4.batch_norm1.running_var", "upsample.resnet.layers.4.batch_norm1.num_batches_tracked", "upsample.resnet.layers.4.batch_norm2.weight", "upsample.resnet.layers.4.batch_norm2.bias", "upsample.resnet.layers.4.batch_norm2.running_mean", "upsample.resnet.layers.4.batch_norm2.running_var", "upsample.resnet.layers.4.batch_norm2.num_batches_tracked", "upsample.resnet.layers.5.conv1.weight", "upsample.resnet.layers.5.conv2.weight", "upsample.resnet.layers.5.batch_norm1.weight", "upsample.resnet.layers.5.batch_norm1.bias", "upsample.resnet.layers.5.batch_norm1.running_mean", "upsample.resnet.layers.5.batch_norm1.running_var", "upsample.resnet.layers.5.batch_norm1.num_batches_tracked", "upsample.resnet.layers.5.batch_norm2.weight", "upsample.resnet.layers.5.batch_norm2.bias", "upsample.resnet.layers.5.batch_norm2.running_mean", "upsample.resnet.layers.5.batch_norm2.running_var", "upsample.resnet.layers.5.batch_norm2.num_batches_tracked", "upsample.resnet.layers.6.conv1.weight", "upsample.resnet.layers.6.conv2.weight", "upsample.resnet.layers.6.batch_norm1.weight", "upsample.resnet.layers.6.batch_norm1.bias", "upsample.resnet.layers.6.batch_norm1.running_mean", "upsample.resnet.layers.6.batch_norm1.running_var", "upsample.resnet.layers.6.batch_norm1.num_batches_tracked", "upsample.resnet.layers.6.batch_norm2.weight", "upsample.resnet.layers.6.batch_norm2.bias", "upsample.resnet.layers.6.batch_norm2.running_mean", "upsample.resnet.layers.6.batch_norm2.running_var", "upsample.resnet.layers.6.batch_norm2.num_batches_tracked", "upsample.resnet.layers.7.conv1.weight", "upsample.resnet.layers.7.conv2.weight", "upsample.resnet.layers.7.batch_norm1.weight", "upsample.resnet.layers.7.batch_norm1.bias", "upsample.resnet.layers.7.batch_norm1.running_mean", "upsample.resnet.layers.7.batch_norm1.running_var", "upsample.resnet.layers.7.batch_norm1.num_batches_tracked", "upsample.resnet.layers.7.batch_norm2.weight", "upsample.resnet.layers.7.batch_norm2.bias", "upsample.resnet.layers.7.batch_norm2.running_mean", "upsample.resnet.layers.7.batch_norm2.running_var", "upsample.resnet.layers.7.batch_norm2.num_batches_tracked", "upsample.resnet.layers.8.conv1.weight", "upsample.resnet.layers.8.conv2.weight", "upsample.resnet.layers.8.batch_norm1.weight", "upsample.resnet.layers.8.batch_norm1.bias", "upsample.resnet.layers.8.batch_norm1.running_mean", "upsample.resnet.layers.8.batch_norm1.running_var", "upsample.resnet.layers.8.batch_norm1.num_batches_tracked", "upsample.resnet.layers.8.batch_norm2.weight", "upsample.resnet.layers.8.batch_norm2.bias", "upsample.resnet.layers.8.batch_norm2.running_mean", "upsample.resnet.layers.8.batch_norm2.running_var", "upsample.resnet.layers.8.batch_norm2.num_batches_tracked", "upsample.resnet.layers.9.conv1.weight", "upsample.resnet.layers.9.conv2.weight", "upsample.resnet.layers.9.batch_norm1.weight", "upsample.resnet.layers.9.batch_norm1.bias", "upsample.resnet.layers.9.batch_norm1.running_mean", "upsample.resnet.layers.9.batch_norm1.running_var", "upsample.resnet.layers.9.batch_norm1.num_batches_tracked", "upsample.resnet.layers.9.batch_norm2.weight", "upsample.resnet.layers.9.batch_norm2.bias", "upsample.resnet.layers.9.batch_norm2.running_mean", "upsample.resnet.layers.9.batch_norm2.running_var", "upsample.resnet.layers.9.batch_norm2.num_batches_tracked", "upsample.resnet.conv_out.weight", "upsample.resnet.conv_out.bias", "upsample.up_layers.1.weight", "upsample.up_layers.3.weight", "upsample.up_layers.5.weight", "I.weight", "I.bias", "rnn1.weight_ih_l0", "rnn1.weight_hh_l0", "rnn1.bias_ih_l0", "rnn1.bias_hh_l0", "rnn2.weight_ih_l0", "rnn2.weight_hh_l0", "rnn2.bias_ih_l0", "rnn2.bias_hh_l0", "fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias", "fc3.weight", "fc3.bias".

**Comment by blue-fish** [comment]
This confusion was bound to happen at some point, because we use `pretrained.pt` as the filename for all the models.

Make sure your `synthesizer/saved_models/pretrained/pretrained.pt` file is from the same path in the zip file. You can also use the following information to ensure the files are located correctly.

```
File size    File path                                            md5 checksum
---------    ---------                                            ------------
 17090379    encoder/saved_models/pretrained.pt                   a2e2a0bf4cc3ac59053d3fe4d67b0c4b
370554559    synthesizer/saved_models/pretrained/pretrained.pt    7485ed2ae3f218819443841159e67b3c
 53845290    vocoder/saved_models/pretrained/pretrained.pt        417fd4c9b98e750764e8b466e777fd48
```

**Comment by frohzinn** [comment]
@blue-fish Thank you so much!  I can't believe I messed that up!  You were right, copying was errant.  Working great now!
