### ISSUE TITLE
Reproducing training - versus new training?  Which python scripts?

### ISSUE THREAD

**Issue by JohnLennons** [CorentinJ/Real-Time-Voice-Cloning#693]
Hi all.

Goal: Use custom sound files to create voices to train with.  

Obstacles: The training guide - https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training, mentions: "you're expected to run all python scripts in their alphabetical order."  Are these scripts in this wiki or are we supposed to figure that out on our own?  For those new to Python, is there somewhere we can find the scripts necessary to train our new voices?  Are we SOL unless we have a good command of Python? What would be our best resources for training voice recordings so that the output is better and closest to the actual voice?  Thank you.

**Comment by blue-fish** [comment]
If you just want to run the toolbox and clone a voice, no training is required. The toolbox allows you to load your own audio files, click the "browse" button.

If following the training guide: All required scripts are in the [repository](https://github.com/CorentinJ/Real-Time-Voice-Cloning). The training guide contains the Python commands needed. It should be possible to reproduce the training of the pretrained models without needing to modify code. If you train with something besides LibriSpeech or LibriTTS, something is likely to break and you'll need to troubleshoot errors in the Python scripts.

You might be interested in my guide on finetuning the pretrained models to better match a single speaker. This is described in #437.
