### ISSUE TITLE
No module named pathlib

### ISSUE THREAD

**Issue by matteopuppis** [CorentinJ/Real-Time-Voice-Cloning#695]
> matteo@MBP-di-matteo Real-Time-Voice-Cloning-master % python demo_cli.py
> Traceback (most recent call last):
>   File "demo_cli.py", line 2, in <module>
>     from utils.argutils import print_args
>   File "/Users/matteo/Real-Time-Voice-Cloning-master/utils/argutils.py", line 22
>     def print_args(args: argparse.Namespace, parser=None):
>                        ^
> SyntaxError: invalid syntax
> matteo@MBP-di-matteo Real-Time-Voice-Cloning-master % python demo_toolbox.py
> Traceback (most recent call last):
>   File "demo_toolbox.py", line 1, in <module>
>     from pathlib import Path
> ImportError: No module named pathlib
> matteo@MBP-di-matteo Real-Time-Voice-Cloning-master % sudo python demo_toolbox.py
> Password:
> Traceback (most recent call last):
>   File "demo_toolbox.py", line 1, in <module>
>     from pathlib import Path
> ImportError: No module named pathlib

What should I do?

**Comment by blue-fish** [comment]
You need a newer version of Python. At this time, 3.6 to 3.8 work.

**Comment by matteopuppis** [comment]
Update now to 3.9.2. Thank you. But a new error appear... Can you help me?

> matteo@MBP-di-matteo Real-Time-Voice-Cloning-master % python --version
> Python 3.9.2
> matteo@MBP-di-matteo Real-Time-Voice-Cloning-master % python demo_cli.py                             
> Traceback (most recent call last):
>   File "/Users/matteo/Real-Time-Voice-Cloning-master/demo_cli.py", line 2, in <module>
>     from utils.argutils import print_args
>   File "/Users/matteo/Real-Time-Voice-Cloning-master/utils/argutils.py", line 2, in <module>
>     import numpy as np
> ModuleNotFoundError: No module named 'numpy'

**Comment by blue-fish** [comment]
Python 3.9 is not supported. You need 3.6, 3.7 or 3.8.

Install the proper Python version, then follow steps 5-7 in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/615#issuecomment-740270185 . You should also install FFmpeg if you want to clone voices from mp3 files.
