### ISSUE TITLE
Error when testing configurations

### ISSUE THREAD

**Issue by ErikaN322** [CorentinJ/Real-Time-Voice-Cloning#698]
I got this when I tried using this project:

> C:\Users\user\Desktop\Real-Time-Voice-Cloning-master>python demo_cli.py
> 
> Traceback (most recent call last):
> 
> File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\self_check.py", line 62, in preload_check
> 
> ctypes.WinDLL(build_info.nvcuda_dll_name)
> 
> File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
> 
> self._handle = _dlopen(self._name, mode)
> 
> OSError: [WinError 126] 指定されたモジュールが見つかりません。
> 

The last line says something along the lines of "Could not find indicated module"

I also got the following:

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "demo_cli.py", line 3, in <module>
>     from synthesizer.inference import Synthesizer
>   File "C:\Users\user\Desktop\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
>     from synthesizer.tacotron2 import Tacotron2
>   File "C:\Users\user\Desktop\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
>     from synthesizer.models import create_model
>   File "C:\Users\user\Desktop\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
>     from .tacotron import Tacotron
>   File "C:\Users\user\Desktop\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 1, in <module>
>     import tensorflow as tf
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
>     self_check.preload_check()
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\self_check.py", line 70, in preload_check
>     % build_info.nvcuda_dll_name)
> ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.
> PS C:\Users\user\Desktop\Real-Time-Voice-Cloning-master>

What does this mean? Do I need a video card to use this?

**Comment by blue-fish** [comment]
Please download the latest version of the code from this site. It no longer uses Tensorflow. We have setup instructions here: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

> Do I need a video card to use this?

A GPU is not required, but inference will run considerably slower.

**Comment by vinamramunot-tech** [comment]
@ErikaN322 The code now uses pytorch instead of tensorflow. Thus, you should not be seeing that error again. A suggestion is to clone this repo again and then start with the demo_cli.py using the new pretrained models.
