### ISSUE TITLE
How to properly change the sample rate from 16000Hz to 24/48000Hz?

### ISSUE THREAD

**Issue by StElysse** [CorentinJ/Real-Time-Voice-Cloning#699]
I just discovered that many of my source audios I am using to train my models are sampled at 48000Hz, and that the default sample rate for the repo is 16000Hz. I figured that this 'downsampling' was part of the cause of lower audio quality of the audios I was generating; I'd like to mitigate that. A bit of research led me to change the hparams in the synthesizer folder like so: 

n_fft=2401
hop_size=600
win_size=2400
sample_rate=48000

I've re-preprepared another dataset and embeds, and put them through about 200 steps of training. When I generate audios with them under the hparams set above, I'm given audio that's played super fast, like someone was pressing 'fast-forward' on a cassette tape player. 

Are the params above correct? Or should I have also changed sample rates in other param files as well like the vocoder or encoder?

Thank you!

**Comment by StElysse** [comment]
Thank you for your suggestions and detailed explanation; I appreciate it a lot. 

I think I'll stick to training a new vocoder from scratch; if the results aren't to my liking, I will stick with just using the improved pretrained 1159k step vocoder that you provided. I will sniff around the tacotron papers too to see where my synthesizer setup can improve.

So far, I'm training the new vocoder and the files named "0k_steps_1_gen_batched_target8000_overlap400" are generating what sounds like television static that matches the diction (profile? speaking?) of the target file associated with it. I'm about 60 epochs in; how can I measure my progress in a more precise way (as compared to the synthesizers' # steps), given that the 'step' counter is measured in 0k, 1k, 2k, etc.?

Thanks again!

**Comment by blue-fish** [comment]
For a more precise display of training step, change this line
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/vocoder/train.py#L121
to:
```
f"steps/s | Step: {step} | "
```
