### ISSUE TITLE
Hello, Librispeech's alignment data is playing a role in training tacotron2, can you briefly introduce, hope to get your reply, thank you

### ISSUE THREAD

**Issue by sunnnnnnnny** [CorentinJ/Real-Time-Voice-Cloning#70]

**Comment by CorentinJ** [comment]
The preprocessing script will split LibriSpeech on long silences using the alignment data. This way, the model can be trained on shorter utterances and converge faster. It also allows me to profile the noise from the silences. In the end, doing this doesn't much of an advantage over using an unaligned dataset, so if that your goal I wouldn't worry.
