### ISSUE TITLE
How to add more time/delay to the next line?

### ISSUE THREAD

**Issue by javaintheuk** [CorentinJ/Real-Time-Voice-Cloning#708]
Hi,

I'd like to know where in the code I should change something(time/duration) to add more time/delay to the next line?

Thanks

**Comment by blue-fish** [comment]
In this line, change `0.15` to the desired number of seconds to add between line breaks.
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/toolbox/__init__.py#L272

**Comment by javaintheuk** [comment]
> In this line, change `0.15` to the desired number of seconds to add between line breaks.
> https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/toolbox/__init__.py#L272

You are a star man! thank you!!! :)
