### ISSUE TITLE
How to use/train the encoder so that we can distinguish between original voice and cloned voice of a person

### ISSUE THREAD

**Issue by ivand17** [CorentinJ/Real-Time-Voice-Cloning#710]
Please can you tell us how to use/train the encoder so that we can distinguish between original voice and cloned voice of a person.

**Comment by blue-fish** [comment]
Make a dataset where the original voice and cloned voice are treated as different speakers. Then train the encoder on this dataset.

[Resemblyzer](https://github.com/resemble-ai/Resemblyzer) has code for evaluating similarity (demo01_similarity.py) if you need it.
