### ISSUE TITLE
how to change demo_cli.py vocoder pretrained to griffinlim

### ISSUE THREAD

**Issue by CrazyPlaysHD** [CorentinJ/Real-Time-Voice-Cloning#714]
how to change demo_cli.py vocoder pretrained to griffinlim

im using CPU and its Slow on pretrained so how can i use griffinlim vocoder?

**Comment by blue-fish** [comment]
Change this line
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/demo_cli.py#L193

To this:
```
generated_wav = Synthesizer.griffin_lim(spec)
```
