### ISSUE TITLE
Error when running vocoder_preprocess

### ISSUE THREAD

**Issue by chankl3579** [CorentinJ/Real-Time-Voice-Cloning#716]
Hello. I was using the old repo and just started trying the new Pytorch repo. 
I tried finetune synthesizer with my data but the quality of generated audio is quite low. 
So I wanted to finetune the vocoder to see if it would help. 
I could do finetuning on both models with the old repo and I used almost the same command this time. 

When I tried to run vocoder_preprocess.py, I got an error. 
The message is like this: 
TypeError: hparams_debug_string() takes 0 positional arguments but 1 was given

I search from Internet, usually people suggest adding "self" as argument like
def hparams_debug_string(self): 

I tried this but another error came up which is "EOFError: Ran out of input.". 
I am not good at programming so I did not change the code anymore as I do not even sure if the "self" argument is a possible solution or not. 
May I ask how do you train the vocoder? Thank you very much.

**Comment by blue-fish** [comment]
You can follow this tutorial which uses the LibriSpeech dataset.
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training
