### ISSUE TITLE
I can't use Dataset/Speaker/Utterance

### ISSUE THREAD

**Issue by HeiseBombe** [CorentinJ/Real-Time-Voice-Cloning#717]
I can't use the upper section in the software. when loading it shows:
Warning: you did not pass a root directory for datasets as argument.
How can I fix this?
Thank you

**Comment by blue-fish** [comment]
```
python demo_toolbox.py -d <datasets_root>
```

Replace `<datasets_root>` with the path to the directory containing the dataset.
