### ISSUE TITLE
How can I use sv2tts with directml ?

### ISSUE THREAD

**Issue by CrazyPlaysHD** [CorentinJ/Real-Time-Voice-Cloning#718]
How can I use sv2tts with directml ?
I have an amd gpu with 8gb vram so I want it run the SV2TTS with directml

**Comment by blue-fish** [comment]
DirectML doesn't support Pytorch at this time. https://github.com/microsoft/DirectML/issues/52

You could spend hours converting the Pytorch model to ONNX, and then run the ONNX model with DirectML. This kind of request is outside the scope of what the current set of developers can provide support for. If you or anyone else is able to get it to work, please share. For now, you can still run this repo on CPU.

**Comment by justinjohn0306** [comment]
> How can I use sv2tts with directml ?
> I have an amd gpu with 8gb vram so I want it run the SV2TTS with directml

Just run it on CPU using Pytorch CPU

**Comment by CrazyPlaysHD** [comment]
> DirectML doesn't support Pytorch at this time. [microsoft/DirectML#52](https://github.com/microsoft/DirectML/issues/52)
> 
> You could spend hours converting the Pytorch model to ONNX, and then run the ONNX model with DirectML. This kind of request is outside the scope of what the current set of developers can provide support for. If you or anyone else is able to get it to work, please share. For now, you can still run this repo on CPU.

https://pypi.org/project/pytorch-directml/
