### ISSUE TITLE
Replacing synthesizer from Tacotron to Non Attentive Tacotron

### ISSUE THREAD

**Issue by Garvit-32** [CorentinJ/Real-Time-Voice-Cloning#719]
Working on it!

**Comment by blue-fish** [comment]
This will be a nice contribution, keep us posted on your progress.

If you need inspiration, look at [ForwardTacotron](https://github.com/as-ideas/ForwardTacotron) as it is somewhat related to NAT and has a similar codebase as our repo. It uses [phonemizer](https://github.com/bootphon/phonemizer) for the grapheme to phoneme conversion.

**Comment by blue-fish** [comment]
See https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/720#issuecomment-822210508 for issue author's reasons for closing this issue.
