### ISSUE TITLE
Many issues while running

### ISSUE THREAD

**Issue by Samuelsar777** [CorentinJ/Real-Time-Voice-Cloning#72]
Can someone show complete steps to run this project using Colab? I am getting a number of issues with this.

**Comment by ak9250** [comment]
what issue are you getting?

**Comment by Samuelsar777** [comment]
Trying to run through colab, cloned project, installed requirements, uploaded and unzipped pretrained models. I am confused what to do next as running init in toolbox isn't working.

**Comment by ak9250** [comment]
are you using this colab notebook? https://github.com/ak9250/Real-Time-Voice-Cloning/blob/master/Real_Time_Voice_Cloning.ipynb?
should be running demo_cli, not demo_toolbox

**Comment by vedchugh** [comment]
I keep getting this error


Reference voice: enter an audio filepath of a voice to be cloned (mp3, wav, m4a, flac, ...):
https://drive.google.com/open?id=11c9rw8-WEwtRdMMsdxTo0ClvoypuptYx
Caught exception: FileNotFoundError(2, 'No such file or directory')
Restarting

**Comment by blue-fish** [comment]
I am going to close this issue out because it is stale. @Samuelsar777 if you are using a colab notebook due to not having a GPU, you will be glad to know that the voice cloning toolbox no longer requires a GPU. Please pull the latest code and give it a try!
