### ISSUE TITLE
how can i got those vocoders like him??

### ISSUE THREAD

**Issue by CrazyPlaysHD** [CorentinJ/Real-Time-Voice-Cloning#721]
how can i got those vocoders like him?? 

image example
https://i.imgur.com/FLDKfrQ.png

**Comment by blue-fish** [comment]
Those look like in-development versions of the original vocoder model released [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models/2cd3887f379d4921b193214973b463043efa5c23).

I [asked about it before](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/162#issuecomment-653872830) and the response is that the vocoder model is identical to what we have. Actually, the current vocoder model has been improved as briefly described in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-650531957 .
