### ISSUE TITLE
It's for sale?

### ISSUE THREAD

**Issue by ks-sav** [CorentinJ/Real-Time-Voice-Cloning#722]
Are you aware of [this](https://realtimevoicecloning.com/)? I found it in the search bar, and it surprised me very much

**Comment by HeliumHead** [comment]
I'll see if I can contact Shopify to get it taken down before anyone gets scammed

**Comment by asaduzzamanR69** [comment]
[kk](url)

**Comment by blue-fish** [comment]
Related: #598

**Comment by MesumRaza** [comment]
Haha man give him an award :D

**Comment by Malte0621** [comment]
I told him to take the website down, on his yt. (He reuploaded the video on his channel (he made it unlisted and put it on the site))

https://www.youtube.com/watch?v=PeFQ_A8B5kQ
