### ISSUE TITLE
Unable to unzip VoxCeleb1 and VoxCeleb2

### ISSUE THREAD

**Issue by namanshah971** [CorentinJ/Real-Time-Voice-Cloning#724]
I follow the instructions to download the datasets - VoxCeleb1 and VoxCeleb2 and concatenate the files using  "cat vox1_dev* > vox1_dev_wav.zip". However, when I get the following error when I try to unzip it:

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains ‘\020\313¨/b\374!8\320\373h’ where numeric off_t value expected
tar: Archive contains ‘V\001W\216A\306R\201\373\231\020\311’ where numeric off_t value expected
tar: Archive contains ‘e\036\363\257N*\225\330[?\242\034’ where numeric off_t value expected
tar: Archive contains ‘\272\r\227:jτ\335CT\277G’ where numeric off_t value expected
tar: Exiting with failure status due to previous errors

Kindly let me know how the datasets are supposed to be downloaded and used. Thank you!

**Comment by chankl3579** [comment]
Just to share my experience. 
I downloaded the file from the Google drive of VoxCeleb directly. 
You may also need to check if the "cat" command is available in your environment. 
As I know, this command is for Unix. 
[https://en.wikipedia.org/wiki/Cat_(Unix)](url)
If your OS does not accept this, maybe please check if there is any equivalent command in your system.

**Comment by namanshah971** [comment]
I am using Unix as well and cat works completely fine. I get the zipped folder but I am unable to unzip it. Anyway if I do not concatenate the files. How can I use them simply?

**Comment by blue-fish** [comment]
Why are you using `tar` instead of `unzip`? Please direct related questions to the VoxCeleb authors.
