### ISSUE TITLE
Directly voice cloning(speech to new speech)

### ISSUE THREAD

**Issue by Numenorean** [CorentinJ/Real-Time-Voice-Cloning#727]
Can I clone speech to new fake speech? Only that I have found, it is that the tool can only clone speech from the text, but not speech to new speech in real time. Am I right about this?

**Comment by blue-fish** [comment]
This is not supported by our repo but I have links to other repos here in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/434#issuecomment-661294839 . There may have been others added since then.
