### ISSUE TITLE
Error while running the app

### ISSUE THREAD

**Issue by 63Amir** [CorentinJ/Real-Time-Voice-Cloning#728]
I get this error `'Tensor' object has no attribute 'repeat_interleave'`. 
I have installed Pytorch and here is the command `conda install pytorch==1.0.1 torchvision==0.2.2 cudatoolkit=10.0 -c pytorch`

**Comment by blue-fish** [comment]
You will need pytorch>=1.1.0 for `repeat_interleave` according to https://stackoverflow.com/a/64153313

I'll leave this issue open until the README is updated. Thanks for reporting the problem.

**Comment by blue-fish** [comment]
Readme updated in #838.
