### ISSUE TITLE
Having an error when executing vocoder_preprocess.py

### ISSUE THREAD

**Issue by JH-lee95** [CorentinJ/Real-Time-Voice-Cloning#729]
I'm trying to train vocoder after training synthesizer. But I have this error when executing vocoder_preprocess.py.

![error](https://user-images.githubusercontent.com/63226383/113960047-cf779300-985e-11eb-991c-b36f6a010fb7.PNG)

So I checked tacotron.py and I realized that the model returns 4 outputs.

![22](https://user-images.githubusercontent.com/63226383/113960401-69d7d680-985f-11eb-9e7e-9922912b528b.PNG)

but  "model" in run_synthesis.py  is supposed to return 3 outputs(look at the first picture).

I guess that the error is resulted from that part.

How can I solve this problem?

**Comment by blue-fish** [comment]
Thanks for reporting this bug. After I added the stop token prediction, I should have updated the GTA synthesis, which I don't normally use.

Change this line:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/synthesizer/synthesize.py#L83

To:
```
_, mels_out, _, _ = model(texts, mels, embeds)
```

**Comment by JH-lee95** [comment]
Thank you!

Cause I solved this problem, I close this issue.
