### ISSUE TITLE
Swedish pretrained pack?

### ISSUE THREAD

**Issue by Archviz360** [CorentinJ/Real-Time-Voice-Cloning#730]
Hello! i wonder if  there are a Swedish pretrained pack somewhere to get? or are there any good service that can let me train my own recordings.

**Comment by blue-fish** [comment]
See https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/400#issuecomment-653830346

You will need commit `5425557` from this repo (tensorflow 1.15) which is old and no longer supported.
