### ISSUE TITLE
Can't load Utterance

### ISSUE THREAD

**Issue by AIKalix** [CorentinJ/Real-Time-Voice-Cloning#731]
Hi
I'm trying to demo this app but it didn't work : (
Here is the error I got.

Arguments:
    datasets_root:    .
    enc_models_dir:   pretrained/encoder/saved_models
    syn_models_dir:   pretrained/synthesizer/saved_models
    voc_models_dir:   pretrained/vocoder/saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 

Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1812
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1812
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1812
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
QObject::killTimer: Timers cannot be stopped from another thread
QObject::startTimer: Timers cannot be started from another thread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
QObject::killTimer: Timers cannot be stopped from another thread
QBasicTimer::start: QBasicTimer can only be used with threads started with

And this is the screenshot.
![Screenshot from 2021-04-10 17-35-52](https://user-images.githubusercontent.com/41188632/114264199-82451e00-9a24-11eb-9c1f-a690cc8edcf6.png)

Can anyone help this issue ??
Thanks.

**Comment by blue-fish** [comment]
What is your operating system version? You can try these instructions for Ubuntu 20.04: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/615#issuecomment-740270185

**Comment by blue-fish** [comment]
Reopen this issue if you still experience this problem after following the above setup instructions.
