### ISSUE TITLE
Number of epochs and steps for encoder

### ISSUE THREAD

**Issue by namanshah971** [CorentinJ/Real-Time-Voice-Cloning#734]
I am new to machine learning and am exploring the encoder model code. I read the thesis behind the code where it is mentioned that the model is trained on 1 million steps. The code for the encoder model just iterates over dataset loader and I wonder if I have to set the number of epochs to 1 million seperately. Any help would be appreciated.

**Comment by blue-fish** [comment]
You just let the encoder continue training until you're satisfied with the results. Then stop the training and use the last saved checkpoint. There is no need to set a target number of steps.
