### ISSUE TITLE
Issue running: python demo_toolbox.py

### ISSUE THREAD

**Issue by alexp-12** [CorentinJ/Real-Time-Voice-Cloning#736]
Hello,

I have satisfied all of my requirements and when I try to run the command

`python demo_toolbox.py`

I get an output that looks something like this:

`ModuleNotFoundError: No module named 'torch'`

I believe this is saying I don't have PyTorch. However, I installed PyTorch a few months ago and have been using programs requiring it since.

When I first installed PyTorch I used this command:

`conda install --yes -c PyTorch pytorch=1.7.1 torchvision cudatoolkit=11.0`

I am doing this all on PowerShell on Windows 10. Additionally, I am running python 3.6.8 

Any thoughts would be great.

**Comment by ichbinvinh** [comment]
try to run this: 
python3 -m pip install torch

**Comment by pilnyjakub** [comment]
Try running this command `pip install torch -f https://download.pytorch.org/whl/torch_stable.html` from https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
