### ISSUE TITLE
synthesizer Training

### ISSUE THREAD

**Issue by mennatallah644** [CorentinJ/Real-Time-Voice-Cloning#737]
if I would like to train the synthesizer from scratch can i train the model with both the datasets libritts and librispeech or can i fine tune the pretrained model on librispeech with libritts dataset and if i can not and i should pick up one of them , which one is better to use so that i can avoid gap problem and get nice voice quality?

**Comment by blue-fish** [comment]
Between the two, LibriTTS is the better dataset. It has higher sample rate (24 khz vs. 16 khz), shorter utterances, punctuation in transcripts, and removes some speakers with noisy recordings.

However, it's essentially the same data as LibriSpeech. If you want to train a better model, you'll need to curate the data, or switch to a better dataset. For reducing gaps, I provide some ideas in #501 which have been implemented in the code.
