### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by jackthenewbie** [CorentinJ/Real-Time-Voice-Cloning#738]
![image](https://user-images.githubusercontent.com/55600733/115086422-10a41e80-9ec1-11eb-8893-29f40861971a.png)
i did some research but still couldn't get how to deal with this error into my head? any idea what i need to avoid?

**Comment by pilnyjakub** [comment]
Try restarting your computer and running only the `demo_toolbox.py`. If that doesn't help, you might need to pass `--cpu` parameters to `demo_toolbox.py`

**Comment by jackthenewbie** [comment]
Is there words limit to how much i can synthesize and vocode at once? I notice it happened because large .flac input or huge amount of words to vocode

> Try restarting your computer and running only the `demo_toolbox.py`. If that doesn't help, you might need to pass `--cpu` parameters to `demo_toolbox.py`

**Comment by blue-fish** [comment]
> Is there words limit to how much i can synthesize and vocode at once?

You'll need to do some exploration to find the limits. It may also depend on your system hardware.
