### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'samples/1320_00000.mp3'`

### ISSUE THREAD

**Issue by GlukXP** [CorentinJ/Real-Time-Voice-Cloning#739]
I followed all the installation instructions. All files are in their places. But the error still pops up about not finding the file, although I personally see it there.

I apologize in advance if something is wrong. I'm not a programmer, I just became interested in this program, but no matter how hard I try, I can't run it on my old PC. It seems like there was no such topic,therefore I ask you.

OC: win10x64 Python 3.9

>  `C:\WINDOWS\system32>python j:\Real-Time-Voice-Cloning-master\demo_cli.py
> 
> Arguments:
>     enc_model_fpath:   encoder\saved_models\pretrained.pt
>     syn_model_fpath:   synthesizer\saved_models\pretrained\pretrained.pt
>     voc_model_fpath:   vocoder\saved_models\pretrained\pretrained.pt
>     cpu:               False
>     no_sound:          False
>     seed:              None
>     no_mp3_support:    False
> 
> C:\Users\Gluk\AppData\Local\Programs\Python\Python38\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
>   warnings.warn("PySoundFile failed. Trying audioread instead.")
> Traceback (most recent call last):
>   File "C:\Users\Gluk\AppData\Local\Programs\Python\Python38\lib\site-packages\librosa\core\audio.py", line 146, in load
>     with sf.SoundFile(path) as sf_desc:
>   File "C:\Users\Gluk\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 629, in __init__
>     self._file = self._open(file, mode_int, closefd)
>   File "C:\Users\Gluk\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 1183, in _open
>     _error_check(_snd.sf_error(file_ptr),
>   File "C:\Users\Gluk\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 1357, in _error_check
>     raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
> RuntimeError: Error opening 'samples/1320_00000.mp3': System error.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "j:\Real-Time-Voice-Cloning-master\demo_cli.py", line 50, in <module>
>     librosa.load("samples/1320_00000.mp3")
>   File "C:\Users\Gluk\AppData\Local\Programs\Python\Python38\lib\site-packages\librosa\core\audio.py", line 163, in load
>     y, sr_native = __audioread_load(path, offset, duration, dtype)
>   File "C:\Users\Gluk\AppData\Local\Programs\Python\Python38\lib\site-packages\librosa\core\audio.py", line 187, in __audioread_load
>     with audioread.audio_open(path) as input_file:
>   File "C:\Users\Gluk\AppData\Local\Programs\Python\Python38\lib\site-packages\audioread\__init__.py", line 111, in audio_open
>     return BackendClass(path)
>   File "C:\Users\Gluk\AppData\Local\Programs\Python\Python38\lib\site-packages\audioread\rawread.py", line 62, in __init__
>     self._fh = open(filename, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'samples/1320_00000.mp3'`

**Comment by blue-fish** [comment]
You need to run `demo_cli.py` out of the directory where it exists.

For your specific case:
```
j:
cd Real-Time-Voice-Cloning-master
python demo_cli.py
```

See these instructions if you need more help: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
