### ISSUE TITLE
Failed to run encoder_train.py

### ISSUE THREAD

**Issue by Johnzxf** [CorentinJ/Real-Time-Voice-Cloning#74]
I am trying to run encoder_train with code:python encoder_train.py my_run <dataset root>. But one question occoured: cannot create RandomCycler from an empty collection. It is happened everytimes. I try to print the length of self.utterance_cycler. It shows sometimes the length is empty(on zero shows), sometimes had a length. Did anyone know how to fixs the problems? Thanks.

**Comment by Chitzi** [comment]
Hello, how did you fix this? I'm testing it from and hour but it stay stuck here with your same error.

**Comment by Johnzxf** [comment]
> Hello, how did you fix this? I'm testing it from and hour but it stay stuck here with your same error.

Well, I just check the dataset. Some datas are not audios,just delet it. Then everything is fine.
