### ISSUE TITLE
 How long do my voice recordings need to be for it to sound good and can there be background noise or anything? How long do my voice recordings need to be and can there be background noise or anything else?

### ISSUE THREAD

**Issue by KiwoNtV** [CorentinJ/Real-Time-Voice-Cloning#741]

**Comment by blue-fish** [comment]
See #57 . It also depends on the voice to be cloned. The speaker encoder is trained with noisy recordings from VoxCeleb so a perfectly clean recording is not needed. You'll need to do some exploration to get an answer.
