### ISSUE TITLE
Program continues to use GPU when --cpu is True

### ISSUE THREAD

**Issue by jmath3912** [CorentinJ/Real-Time-Voice-Cloning#743]
after installing all the necessary dependencies and the requirements.txt, I did `python demo_cli.py --cpu` in hopes that it would do processing on my cpu instead. But the program continued to use the gpu regardless of the `--cpu` argument.
![Screenshot 2021-04-22 213605](https://user-images.githubusercontent.com/51333711/115805392-dfd95300-a3b2-11eb-958c-c65b3021b377.png)

**Comment by blue-fish** [comment]
Does it also happen if you change this line:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/demo_cli.py#L46

to:
```
os.environ["CUDA_VISIBLE_DEVICES"] = "-1" 
```

**Comment by blue-fish** [comment]
Not enough information to troubleshoot issue. Would like to understand why `torch.cuda.is_available()` is unreliable here.

**Comment by jmath3912** [comment]
> Does it also happen if you change this line:
> https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/demo_cli.py#L46
> 
> to:
> 
> ```
> os.environ["CUDA_VISIBLE_DEVICES"] = "-1" 
> ```

Apologies for the late response. Just saw this now. I made the aforementioned change and --cpu seems to be working now. Thanks for the assistance.
