### ISSUE TITLE
CUDA out of memory only in python demo_toolbox.py (python demo_cli.py works)

### ISSUE THREAD

**Issue by AjaxFB** [CorentinJ/Real-Time-Voice-Cloning#746]
`python demo_toolbox.py

UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Warning: you did not pass a root directory for datasets as argument.
The recognized datasets are:
        LibriSpeech/dev-clean
        LibriSpeech/dev-other
        LibriSpeech/test-clean
        LibriSpeech/test-other
        LibriSpeech/train-clean-100
        LibriSpeech/train-clean-360
        LibriSpeech/train-other-500
        LibriTTS/dev-clean
        LibriTTS/dev-other
        LibriTTS/test-clean
        LibriTTS/test-other
        LibriTTS/train-clean-100
        LibriTTS/train-clean-360
        LibriTTS/train-other-500
        LJSpeech-1.1
        VoxCeleb1/wav
        VoxCeleb1/test_wav
        VoxCeleb2/dev/aac
        VoxCeleb2/test/aac
        VCTK-Corpus/wav48
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Loaded encoder "pretrained.pt" trained to step 1564501
Synthesizer using device: cuda
Trainable Parameters: 30.870M
Loaded synthesizer "pretrained.pt" trained to step 295000
+----------+---+
| Tacotron | r |
+----------+---+
|   295k   | 2 |
+----------+---+

| Generating 1/1
Traceback (most recent call last):
  File "C:\python\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 120, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "C:\python\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 227, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "C:\python\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 124, in synthesize_spectrograms
    _, mels, alignments = self._model.generate(chars, speaker_embeddings)
  File "C:\python\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 464, in generate
    postnet_out = self.postnet(mel_outputs)
  File "C:\python\pyto\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\python\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 142, in forward
    conv_bank = torch.cat(conv_bank, dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 2.00 GiB total capacity; 1.07 GiB already allocated; 0 bytes free; 1.11 GiB reserved in total by PyTorch)`

I mean that demo_toolbox dont able a % free of memory...
Someone can help me how i can reserve memory to app?

**Comment by blue-fish** [comment]
Try using the toolbox in CPU mode:
```
python demo_toolbox.py --cpu
```

**Comment by blue-fish** [comment]
You will need a GPU with mo
