### ISSUE TITLE
is it possible to use hifi gan vocoder on sv2tts?

### ISSUE THREAD

**Issue by CrazyPlaysHD** [CorentinJ/Real-Time-Voice-Cloning#748]
is it possible to use hifi gan vocoder on sv2tts?

**Comment by blue-fish** [comment]
Yes, it is possible. Both our WaveRNN vocoder and HiFi-GAN take a mel spectrogram as input.

**Comment by CrazyPlaysHD** [comment]
> Yes, it is possible. Both our WaveRNN vocoder and HiFi-GAN take a mel spectrogram as input.

How can I get a hifi gan model for sv2tts?

**Comment by blue-fish** [comment]
I may have misunderstood the intent of your question.

What you ask is technically quite feasible, but requires integrating the code of the new vocoder into this repo, and possibly training a new model. It has not been done before, so if you will need to do this yourself if the capability is needed. This may or may not be possible depending on your level of experience with Python and machine learning.

**Comment by ymzlygw** [comment]
@blue-fish 
Can I ask some question about integrating new vocoder? 
I know that in vocoder_preprocess, it use trained synthesizer model and generated GTA mel-specs, here it did feed it to waveRNN and clip it to [-1,-1]:
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/7432046efc23cabf176f9fdc8d2fd67020059478/vocoder/vocoder_dataset.py#L28

**And for feeding new vocoder, is the same to use this way?** 
I mean, use generated GTA mel-specs directly and load it in the same way as followings:
 **mel = np.load(mel_path).T.astype(np.float32) / hp.mel_max_abs_value** ,     
**wav = np.clip(wav, -1, 1)**.

Is there any other preprocess for gta mel-specs.npy and wav.npy before feeding to new vocoder? Thanks for your reply!
