### ISSUE TITLE
stuck at encoder

### ISSUE THREAD

**Issue by ytty-tyyt** [CorentinJ/Real-Time-Voice-Cloning#752]
when i try to record my voice every thing goes well untill it says "loading the encoder encoder\saved_models\pretrained.pt" the path is C:\Users\ytty\OneDrive\Bureaublad\voice clone\Real-Time_Voice_Cloning\Real-Time-Voice-Cloning-master\encoder\saved_models, how can this be fixed? (says SV2TTS is not responding)

**Comment by blue-fish** [comment]
This appears to be a problem with your system configuration. Most likely the operating system, memory, or GPU if you have one. Unfortunately we are not able to help troubleshoot. I can only recommend this:

1. Follow these instructions to set up the toolbox: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
2. If the problem still occurs, add breakpoints to find out specifically which line of code is responsible for the program freezing. Then troubleshoot from there.
