### ISSUE TITLE
longer sentences and higher sample rate downloads?

### ISSUE THREAD

**Issue by mindblowingaiart** [CorentinJ/Real-Time-Voice-Cloning#753]
Hi just wondering how long of an audio clip you need to record which would allow you to write longer sentences to generate? secondly when i download the file its only at 16khz, is there a way to download at higher sample rates like 44.1 or 48khz?

**Comment by mindblowingaiart** [comment]
it seems like shorter phrases seem to work better too, and for some reason when i train with shorter recordings it works better. i thought if you train with more data it works better, because training is more accurate

**Comment by blue-fish** [comment]
1. The sentence length should not depend on the duration of the audio clip used to make the embedding. You will have to work around this by generating shorter sentences.
2. The vocoder is trained to output at 16 kHz. Without retraining the model, the best one can do is to edit the code to save the wav at a higher sample rate. However, that will not improve the sound quality.
