### ISSUE TITLE
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

### ISSUE THREAD

**Issue by JohnJnotFKennedy** [CorentinJ/Real-Time-Voice-Cloning#755]
Some files are loading out of the user directory and others are not despite same naming style and .flac file type.

**Comment by JohnJnotFKennedy** [comment]
The largest clip is 60 seconds, ive loaded up 10 min clips with no issue in the past

**Comment by chmodsss** [comment]
@JohnJnotFKennedy Could you please comment on how the issue got resolved. I am facing the same issue.
