### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by HiloTakenaka** [CorentinJ/Real-Time-Voice-Cloning#759]
I've installed all the required files and programs to execute it, but I can't seem to make it run
Here is my error:

`C:\Users\Owner>python` Documents\Real-Time-Voice-Cloning-master\demo_toolbox.py
Traceback (most recent call last):
  File "C:\Users\Owner\Documents\Real-Time-Voice-Cloning-master\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\Owner\Documents\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\Owner\Documents\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'`

And since it's been a source of my issues for a while, here is my path directory:
![image](https://user-images.githubusercontent.com/84254202/118381629-0eec8880-b630-11eb-931f-49bbdece05c1.png)

I'm not entirely sure what the error is, since I followed everything to the letter
The version of pyTorch I installed is: pip3 install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by AyseEe501** [comment]
matplotlib library in requirements.txt 
Did you save it as matplotlib> = 3.2.2

**Comment by RakshithRAcharya** [comment]
Can I take up this issue?
Try doing **pip install matplotlib**

**Comment by blue-fish** [comment]
Try following these instructions to the letter instead: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

Also use Python 3.7.
