### ISSUE TITLE
How can I train a model for the Turkish language with the Mozilla Common Voice Dataset?

### ISSUE THREAD

**Issue by AyseEe501** [CorentinJ/Real-Time-Voice-Cloning#761]
First of all, hello;

I want to implement synthesizer, vocoder and encoder models with Mozilla Comman Voice dataset for Turkish language. But I am quite confused about how to proceed. I would love it if you can help me with this. Thank you very much in advance.

**Comment by baturayp** [comment]
see #677

**Comment by blue-fish** [comment]
Start by processing the Mozilla CommonVoice dataset so the folder and file structure looks like LibriSpeech. Something like this: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538

Then our preprocessing tools should work.

**Comment by AyseEe501** [comment]
> Klasör ve dosya yapısının LibriSpeech gibi görünmesi için Mozilla CommonVoice veri kümesini işleyerek başlayın. Bunun gibi bir şey: [#437 (yorum)](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538)
> 
> O zaman ön işleme araçlarımız çalışmalıdır.

First of all, thank you for your reply.I started to design the dataset as you said. Right now I have close to 400 sounds, but this is not enough. Estimated how much more sound should I add and is there a place where I should add the txt file I prepared in the code?

**Comment by AyseEe501** [comment]
I also get an error like this in the train part of the synthesizer ->EOFError:Ran out of input .I would also like to mention that I got this for LibriSpeech in the synthesizer both in German and the original git clone. I would appreciate it if you could help me on how to solve this problem. Thank you in advance :)
![image](https://user-images.githubusercontent.com/81026327/120107131-76debb00-c168-11eb-879a-31af9fed3f10.png)

**Comment by AyseEe501** [comment]
> [#677'ye](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/677) bakın[](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/677)


Thanks for this :+1:

**Comment by blue-fish** [comment]
To solve `EOFError: Ran out of input` on Windows, try the suggestion in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/669#issuecomment-781130738

**Comment by 5l1v3r1** [comment]
> I also get an error like this in the train part of the synthesizer ->EOFError:Ran out of input .I would also like to mention that I got this for LibriSpeech in the synthesizer both in German and the original git clone. I would appreciate it if you could help me on how to solve this problem. Thank you in advance :) ![image](https://user-images.githubusercontent.com/81026327/120107131-76debb00-c168-11eb-879a-31af9fed3f10.png)

low memory, try to increase the swap size at windows settings or better add more ram to your pc.

**Comment by 5l1v3r1** [comment]
btw i have trained a few models for turkish language but i can say, if i share them they might be "abused" for known purposes amongst the huge "scraper" culture in the country.

**Comment by AyseEe501** [comment]
> bu arada türkçe için birkaç model yetiştirdim ama bunları paylaşırsam ülkedeki devasa "kazıyıcı" kültür arasında bilinen amaçlarla "suistimal edilebilir" diyebilirim.

Did you create your own dataset or did you go with common voice?
