### ISSUE TITLE
Error when running synthesizer_train.py > line 35, in <module>

### ISSUE THREAD

**Issue by Highpressure** [CorentinJ/Real-Time-Voice-Cloning#762]
So I have used this git + made my own additions based on padmalcom´s branch to build a fit for me and my german sets.

Anaconda + Enviornment Python on 3.7 with all the pre req´s 

I have successfully trained it on the german books padmalcom uses too, but converted them to flac instead using wav´s via batch process in flic flac

**I went first with** 
python encoder_preprocess.py 
python encoder_train.py GermanBookMale
python synthesizer_preprocess_audio.py 
python synthesizer_preprocess_embeds.py 
**successfully.**

Now i am failing at 

(GerVoice3.7) E:\DeepFakes\cleanRTVC>**python synthesizer_train.py GermanBookMale** E:\DeepFakes\cleanRTVC\SV2TTS\synthesizer\
Arguments:
    run_id:          GermanBookMale
    syn_dir:         E:\DeepFakes\cleanRTVC\SV2TTS\synthesizer\
    models_dir:      synthesizer/saved_models/
    save_every:      1000
    backup_every:    25000
    force_restart:   False
    hparams:

Checkpoint path: synthesizer\saved_models\GermanBookMale\GermanBookMale.pt **_EXISTS, 117mb_**
Loading training data from: E:\DeepFakes\cleanRTVC\SV2TTS\synthesizer\train.txt **_EXISTS, 2,85mb_**
Using model: Tacotron
Using device: cuda **_<<< 1080 Ti 11GB_**

Initialising Tacotron Model...

Trainable Parameters: 30.874M

Loading weights at synthesizer\saved_models\GermanBookMale\GermanBookMale.pt
Tacotron weights loaded from step 0
Using inputs from:
        E:\DeepFakes\cleanRTVC\SV2TTS\synthesizer\train.txt **_EXISTS, 2,85mb_**
        E:\DeepFakes\cleanRTVC\SV2TTS\synthesizer\mels **_EXISTS, 2,10gb_**
        E:\DeepFakes\cleanRTVC\SV2TTS\synthesizer\embeds **_EXISTS, 54mb_**

**Found 13847 samples**
+----------------+------------+---------------+------------------+
| Steps with r=2 | Batch Size | Learning Rate | Outputs/Step (r) |
+----------------+------------+---------------+------------------+
|   20k Steps    |     12     |     0.001     |        2         |
+----------------+------------+---------------+------------------+

Traceback (most recent call last):
  **File "synthesizer_train.py", line 35, in <module>
    train(STAR-STAR-SYMBOLvars(args))**
  File "E:\DeepFakes\cleanRTVC\synthesizer\train.py", line 158, in train
    for i, (texts, mels, embeds, idx) in enumerate(data_loader, 1):
  File "C:\Users\User\anaconda3\envs\GerVoice3.7\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\User\anaconda3\envs\GerVoice3.7\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "C:\Users\User\anaconda3\envs\GerVoice3.7\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\User\anaconda3\envs\GerVoice3.7\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\User\anaconda3\envs\GerVoice3.7\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\User\anaconda3\envs\GerVoice3.7\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\User\anaconda3\envs\GerVoice3.7\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
**AttributeError: Can't pickle local object 'train.<locals>.<lambda>'**

(GerVoice3.7) E:\DeepFakes\cleanRTVC>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\anaconda3\envs\GerVoice3.7\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\User\anaconda3\envs\GerVoice3.7\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
**EOFError: Ran out of input**

as add on info:
(GerVoice3.7) E:\DeepFakes\cleanRTVC>conda list torch
 Name                    Version                   Build  Channel
**pytorch**                   **1.2.0**           py3.7**_cuda100_cudnn7_1**    pytorch
torchfile                 0.1.0                    pypi_0    pypi
torchvision               0.4.0                py37_cu100    pytorch

any hint of what could go wrong here? cant point out an error?

**Comment by blue-fish** [comment]
Try this: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/669#issuecomment-781130738
