### ISSUE TITLE
2 small questions about the toolbox

### ISSUE THREAD

**Issue by simteraplications** [CorentinJ/Real-Time-Voice-Cloning#763]
Hello. I found this toolbox a while ago and this is a really interesting thing to play with. But i could not figure out too functions off it. This may be stupid but i could not find any thing to it. 

1. What does the random seed field change? Something notable or just in the way it is beeing generated? Or does it change anything if i only use a simple utterance and not a dataset?
2. can i add multiple utterances using the browse button? I tried importing like 3 utterances of the same speaker but i could not note any difference, in fact i think it just used the second one i imported.

Thanks in advance, and shoutout for making this, simter.

**Comment by blue-fish** [comment]
1. "Random seed" makes the generation deterministic. Mostly used for troubleshooting and benchmarking.
2. No. Whenever an utterance is loaded, the embedding is recalculated using that utterance only. It makes no difference what order the utterances are loaded. Only the last one loaded matters.

**Comment by simteraplications** [comment]
Thanks for the answer. So i understood right, random sid shouldnt affect the input at all, neither in negative or positive way?

**Comment by blue-fish** [comment]
With "random seed" enabled, you will always get the same output for a given combination of speaker embedding and input text.
