### ISSUE TITLE
Question: Do you offer a trained model for Mexican Spanish (male/female)

### ISSUE THREAD

**Issue by inglesuniversal** [CorentinJ/Real-Time-Voice-Cloning#764]
If non-existent please tell me how I can help or contribute.

**Comment by blue-fish** [comment]
There is not a Spanish model at this time.

If you have a GPU and wish to contribute:
1. Learn synthesizer training by following the tutorial to train an English model using the LibriSpeech dataset. https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training
2. Find a Spanish dataset. https://openslr.org/resources.php
3. Preprocess the dataset. Arrange the files so it looks like LibriSpeech. You do not need alignment files. https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538
4. Train the synthesizer model from scratch. It may take multiple attempts to get a good model.
