### ISSUE TITLE
Training on custom data

### ISSUE THREAD

**Issue by tranmanhdat** [CorentinJ/Real-Time-Voice-Cloning#766]
I rewrite code and training on my custom data, but audios generated from model are the same with any input audio samples.
I think i made a mistake in custom dataset.
My custom dataset are merger togother without speaker identify, does it make model failure to genenrate new audio?
should i split data to each folder for each speaker for encoder, synthesizer and vocoder?
Sorry about questions, im newbie in this field.

**Comment by blue-fish** [comment]
> should i split data to each folder for each speaker for encoder, synthesizer and vocoder?

For encoder training only, it is necessary to make separate folders for each speaker.
It doesn't matter for the synthesizer or vocoder.

**Comment by tranmanhdat** [comment]
> > should i split data to each folder for each speaker for encoder, synthesizer and vocoder?
> 
> For encoder training only, it is necessary to make separate folders for each speaker.
> It doesn't matter for the synthesizer or vocoder.

thank, i will try
