### ISSUE TITLE
demo_toolbox.py stops responding as soon as opened

### ISSUE THREAD

**Issue by MightyElemental** [CorentinJ/Real-Time-Voice-Cloning#767]
Upon opening demo_toolbox.py, it spits out the following errors in the command line multiple times:
`QBasicTimer::start: QBasicTimer can only be used with threads started with QThread`
`QObject::killTimer: Timers cannot be stopped from another thread`

All requirements have been installed. This happens with and without the training data as an argument.

**Comment by MightyElemental** [comment]
Running Manjaro Arch Linux

version numbers
Python 3.9.5
pip 21.0.1
numpy 1.20.3 (received errors* with 1.19.4)
scipy 1.6.3
torch 1.8.1


*`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

**Comment by Hroddric** [comment]
The same issues happened to me. I created a virtual environment with Python 3.6 and it worked perfectly. See #615

**Comment by MightyElemental** [comment]
> The same issues happened to me. I created a virtual environment with Python 3.6 and it works without issues. See #615

Thanks, that sorted the issue. Now I just need to figure out how to use it :P
