### ISSUE TITLE
Error training in Spanish

### ISSUE THREAD

**Issue by necrcon** [CorentinJ/Real-Time-Voice-Cloning#768]
Hello, I am trying to train in Spanish, I don't know how to solve this error.
Windows 10, rtx 3090. use a dataset to LibriTTS, modify to spanish syntetize-utils-simbol,  and in hparams.py I changed it to basic_cleaners
The first step he did well I think, he did not make any mistakes.
![syntetizador](https://user-images.githubusercontent.com/68554553/120906721-2251a900-c65c-11eb-878d-294d9358ec18.jpg)
In this step I had to modify the texts since the vowels in upper case "Á" at the beginning of a word gave me an error, in lower case "á" worked well.

The second step using: python synthesizer_preprocess_embeds.py datasets_root/SV2TTS/synthesizer
I get the following error:
![error](https://user-images.githubusercontent.com/68554553/120906761-807e8c00-c65c-11eb-9055-fb0befb75c09.jpg)

I am a beginner in self-taught programming, and I spent hours in google and did not find how to solve it.

**Comment by blue-fish** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/synthesizer/preprocess.py#L250

Change this line to:

```
with metadata_fpath.open("r", encoding="utf-8") as metadata_file:
```

Reference: https://stackoverflow.com/a/49562606

**Comment by necrcon** [comment]
thank you very much, it worked. I assumed it was to add encoding = 'utf-8', but I didn't know exactly where. When you learn well and have a decent speaking in Spanish, I will share it with you. Thanks.
