### ISSUE TITLE
Do you have this code available on a Google Colab VM?

### ISSUE THREAD

**Issue by inglesuniversal** [CorentinJ/Real-Time-Voice-Cloning#769]
I'm new to Python so I just found out that it makes no sense touching apps which make use of CUDA configurations (specially Macs which are not compatible with Nvidia drivers as of  MacOS Catalina 10.15.x

Any suggestions... If you help me get going I can devote more time to train an spanish version of this amazing script.

Best regards.

**Comment by blue-fish** [comment]
Unfortunately, training is not available for Google Colab, and there are no plans to support it in this repo.

My recommendation is to get proper hardware if you're serious about training a model. You'll need to assess whether you have sufficient enthusiasm and computer skill to justify the expense.

**Comment by FlashlightET** [comment]
> Unfortunately, training is not available for Google Colab, and there are no plans to support it in this repo.
> 
> My recommendation is to get proper hardware if you're serious about training a model. You'll need to assess whether you have sufficient enthusiasm and computer skill to justify the expense.

um, gpu shortage?
