### ISSUE TITLE
Automatisation on Synthesizer without GUI 

### ISSUE THREAD

**Issue by Anas-eladili** [CorentinJ/Real-Time-Voice-Cloning#774]
Hello, thank you for this amazing work that has been done. I'm currently working on automizing the  synthisization of texts without Gui. Please, is there a way to run the synthesizer without Gui interface ? in the easiest and light way. :)
 Thank you in advance

Best regard,

**Comment by blue-fish** [comment]
You can use [`demo_cli.py`](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/demo_cli.py) as a template. The comments explain how to synthesize texts.
