### ISSUE TITLE
Strange synthesizer result from time to time

### ISSUE THREAD

**Issue by padmalcom** [CorentinJ/Real-Time-Voice-Cloning#775]
Hi, I trained my own synthesizer with the new pytorch architecture on a German dataset. From time to time (in approx. 7/10 cases) the synthesizer creates a mel spectrogram that has a long pause at the beginning. I added an image for illustration. I'm not sure why this is happinging. Do you have any idea?
![strange spectrogram](https://user-images.githubusercontent.com/3961950/122243674-98f46f00-cec4-11eb-8262-8abc02008481.png)

**Comment by blue-fish** [comment]
Perhaps your synthesizer is trying to predict the silence that sometimes occurs at the start of your training utterances. In your screenshot, the spectrogram at top has some silence at the beginning. This seems a plausible explanation if it is representative of your training dataset.

After experiencing this issue myself, I added a "trim silence" feature to the synthesizer preprocessing. It is discussed somewhat in #501.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/synthesizer/preprocess.py#L206-L208

**Comment by padmalcom** [comment]
Hi @blue-fish, thanks for your reply. That was exactly my assumption, I found out that in my older scripts the silence trimming was not used. I started the training for the synthesizer again yesterday, let's see if results improve.

**Comment by padmalcom** [comment]
After 2 days of training I can confirm that the behavior is the result of not trimming silences.
