### ISSUE TITLE
Encoder converging extremely fast 

### ISSUE THREAD

**Issue by ARKEYTECT** [CorentinJ/Real-Time-Voice-Cloning#776]
Hi there, I used VoxCeleb1 &2 dataset to train an encoder with Adam and init_lr set to 1e-4, but the algorithm converges way too fast, loss decreased below 1 in under 1000 steps. I used a batch size of 64x10. Is there something I am missing or should I just further decrease the lr.

**Comment by blue-fish** [comment]
The loss for a good model is 0.01 or lower. You'll also want to inspect the UMAP projections during training to verify that the model is able to distinguish between speakers. From https://matheo.uliege.be/handle/2268.2/6801

![image](https://user-images.githubusercontent.com/67130644/122472587-a3227600-cf75-11eb-92f0-901ddcd701c2.png)

**Comment by ARKEYTECT** [comment]
Hi blue-fish:
Sorry for late reply, I started a training job with lr1e-4and the loss hits 0.0000 after 250k iterations, here is the umap illustration. 
![trial_lr1e-4_umap_249000](https://user-images.githubusercontent.com/18693148/122694214-ae420400-d20a-11eb-817c-c33232c0f661.png)

Would you be so kind and point out what could be wrong in this scenario? 

Best

**Comment by blue-fish** [comment]
Something is not right there, but I haven't experienced this issue before. Make sure there is 1 folder per speaker in `<datasets_root>/SV2TTS/encoder`. If you understand the preprocessing, inspect the spectrograms in the .npy files. You can also try preprocessing again. I'm out of ideas if that doesn't solve it.

**Comment by ARKEYTECT** [comment]
Thanks blue-fish, let me take a look at the mel-spectrograms.
