### ISSUE TITLE
error in loading state_dict

### ISSUE THREAD

**Issue by necrcon** [CorentinJ/Real-Time-Voice-Cloning#779]
When doing a fine tuning for Spanish, when executing the toolbox, there is a mismatch with the weights.
What parameters must be changed to solve this error. Try to look for information for a few days but I can't solve it.

![fallo](https://user-images.githubusercontent.com/68554553/122685586-94a1bc00-d20c-11eb-92cd-7e1379d83970.jpg)

**Comment by blue-fish** [comment]
The list of symbols in `synthesizer/utils/symbols.py` needs to match the version used to train the model file.

**Comment by necrcon** [comment]
had modified, expanded synthesizer/utils/symbols.py for the Spanish alphabet
#_characters = "AÁBCDEÉFGHIÍJKLMNÑOÓPQRSTUÚÜVWXYZaábcdeéfghiíjklmnñoópqrstuúüvwxyz!,.:;?¡¿-|\'()\"° "
_characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\'\"(),-.:;? "
I made a fine adjustment and thought that I should leave the alphabet of my language.
If I put the preset symbols.py it no longer gives that error.
It is not necessary to use the symbols in Spanish when executing the toolbox, so that the pronunciation is good for another language, and detects well the "Ñ" for example?

**Comment by blue-fish** [comment]
Yes, the additional symbols are needed. But you can't add new symbols when finetuning. If using the pretrained English model, you're stuck with the original symbol set.

For best results you should train a new model on the expanded symbol set.
