### ISSUE TITLE
Questions about pretrained model

### ISSUE THREAD

**Issue by byuns9334** [CorentinJ/Real-Time-Voice-Cloning#78]
Hi Corentin, thanks for your great work !

So I've set up all environments for this project and downloaded the pretrained models (pretrained.zip) to see if they clone my voice well too. And I got some questions about this procedure: (I've already read all docs in wiki but still can't grasp how this all works)

1. Are these pre-trained encoder/synthesizer/vocoder models trained on Librispeech&VoxCeleb1&VoxCeleb2/Librispeech&Librispeech_alignments/  ? So did you use all these 1TB data for training these entire models?

2. How do I actually synthesize the new wave cloning my voice from these pre-trained models? Do I have to run encoder, synthesizer, and vocoder in order?  Could you let me know the example of command lines for these?

Thanks in advance!

**Comment by cheulyop** [comment]
@byuns9334 Did you find answers to your questions? In particular, on which data the provided encoder was pretrained?

If not, could you please confirm if the encoder was pretrained on a combination of LibriSpeech and VoxCeleb 1 & 2, as mentioned in the thesis? @CorentinJ
![스크린샷 2022-03-02 오후 10 35 49](https://user-images.githubusercontent.com/36708385/156371892-3df5767b-527f-4a4a-84db-d60fca04cb0b.png)

In our case, we are taking the pretrained encoder (`encoder.pt`) and looking to fine-tune its last linear layer and similarity scaling parameters with a dataset of our interest.

Knowing on which data the encoder was pretrained would be of much help.
