### ISSUE TITLE
is there a tutprial on how to train my own models

### ISSUE THREAD

**Issue by Archviz360** [CorentinJ/Real-Time-Voice-Cloning#783]
hello! i would like to know if there are any tutorials on how to train my own models. i would like to train own models in swedish and other language

**Comment by pilnyjakub** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training

**Comment by babysor** [comment]
I'm currently working on latest fork of this repo to support mandarin and if anyone want to use as reference, please be free to folk and train: https://github.com/babysor/Realtime-Voice-Clone-Chinese
