### ISSUE TITLE
caffe2_detectron_ops.dll not loading

### ISSUE THREAD

**Issue by norman-kraft** [CorentinJ/Real-Time-Voice-Cloning#784]
When I install this (Windows 10, Anadonda), everything installs fine. I used conda for PyTorch and pip install -r requirements.txt, but when I try to run "python demo_cli.py" I get:

Error loading "C:\Users\[username]\anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.

But the dll file is there. right where it should be. Is there some step missing from the Windows install process or did I miss something?

**Comment by blue-fish** [comment]
Please follow the directions here to set up the repo without Anaconda: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

**Comment by GOOGOL666** [comment]
Did you use Anaconda for environment creating?  ( I faced the same question without using Anaconda, and the f-ing caffe2_detectron_ops.dll is right where it should be.) Then I tried to use Anaconda.navigator to creat the environment and conda install torch. Bingo, I finally got everything fine.

**Comment by GOOGOL666** [comment]
Still, don know what's problem behind the method to creat environment with Anaconda, but I guess maybe it's because some connetion between files can only make by the system?
