### ISSUE TITLE
LibriTTS & older models

### ISSUE THREAD

**Issue by ThePowerOfMonkeys** [CorentinJ/Real-Time-Voice-Cloning#787]
Hey - I've been playing with the Tensorflow version of this repo with a LibriTTS model for some time now & have had some good results from it.  The model i've been using was from here & had a partial train of a LibriTTS dataset which was really good for punctuation etc.

Just upgraded my GPU to a 3080ti (rare I know!) & tried to get the repo working with this GPU.. the cuda sdk doesn't appear to work unfortunately (10.1) & every time I try to load an audio file to clone the toolkit just hangs.. 

So i've ended up pulling the latest repo & pretrained models, but noticed there's no punctuation - which is a real shame...

Would appreciate any thoughts on either getting the older repo working or how to get LibriTTS into the mix?  

()Also if needed I can provide a 5950x and GPU to train models if it would help restore some of the functionality around this)

**Comment by blue-fish** [comment]
As you've noticed, the old Tensorflow 1.x repo is not compatible with latest hardware. We tried upgrading to TF2 (see #370) but the automatic conversion tool failed.

There are 2 options:
1. Train a model with LibriTTS on the new repo (either using CPU, or your old GPU if you still have it, or ask for help)
2. Rewrite the old synthesizer model in Pytorch

I would be willing to do the Pytorch rewrite if someone out there wants to sponsor the work. It would also include a conversion utility to make TF model checkpoint files usable.
