### ISSUE TITLE
Works in Spanish?

### ISSUE THREAD

**Issue by johnfelipe** [CorentinJ/Real-Time-Voice-Cloning#789]

**Comment by Wrongtown** [comment]
There's information on other people's attempts at this on existing issue [Support for other languages #30](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/30#issuecomment-831992614).

**Comment by pilnyjakub** [comment]
There is no Spanish model yet.

**Comment by johnfelipe** [comment]
How can collaborate?

**Comment by babysor** [comment]
You can check the file diff in my repo for reference. Mine works for Chinese and I think you can do the similar modification.
https://github.com/babysor/Realtime-Voice-Clone-Chinese

**Comment by AlexSteveChungAlvarez** [comment]
Trying to train the synthesizer with tux-100h (valid) dataset and cv-corpus-7.0-2021 (validated) dataset is giving me the following:
![image](https://user-images.githubusercontent.com/42816278/141061539-b88003b3-9450-48fe-9c02-fae707d1b08e.png)
In the image, it is the message from tux-100h, but the same appears for cv-corpus.
Both datasets are already structured as mentioned in previous issues:
![image](https://user-images.githubusercontent.com/42816278/141061719-c6cf7e5e-6a43-4f46-a869-05f186da0bd4.png)
I don't know why the audios are not being recognised, I think that is what is happening there...

**Comment by blue-fish** [comment]
For audios to be detected, the directory structure must match this exactly including the "speaker" and "book_dir" levels. https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/437#issuecomment-666099538

**Comment by AlexSteveChungAlvarez** [comment]
With the same names, too?

**Comment by blue-fish** [comment]
It is not necessary to use the same names, except `datasets_root`, `LibriTTS` and `train-clean-100` if you are using the preprocessing command that I give.

However, please try matching the names before reporting a problem, or when asking for help to troubleshoot an issue like this.

**Comment by AlexSteveChungAlvarez** [comment]
I did it both with their own names and with the names you give as example. 
![image](https://user-images.githubusercontent.com/42816278/141408227-c03f6ed5-3464-4e0f-8544-fabc7c5ef81e.png)

However, I got some errors:

1. With tux-100h (https://discourse.mozilla.org/t/sharing-my-100h-of-single-speaker-spanish/45288):
`python synthesizer_preprocess_audio.py datasets_root -n 6 --datasets_name LibriTTS --subfolders train-clean-100 --no_alignments --no_trim
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    datasets_root:   datasets_root
    out_dir:         datasets_root\SV2TTS\synthesizer2
    n_processes:     6
    skip_existing:   False
    hparams:
    no_alignments:   True
    datasets_name:   LibriTTS
    subfolders:      train-clean-100

Using data from:
    datasets_root\LibriTTS\train-clean-100
LibriTTS:   0%|                                                                                                             | 0/1 [00:00<?, ?speakers/s]D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.  
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. 
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
LibriTTS:   0%|                                                                                                             | 0/1 [00:02<?, ?speakers/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Programas\Python3.7\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 76, in preprocess_speaker
    assert text_fpath.exists()
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 35, in preprocess_dataset
    for speaker_metadata in tqdm(job, datasets_name, len(speaker_dirs), unit="speakers"):
  File "D:\tesis2\voiceclonenv\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "D:\Programas\Python3.7\lib\multiprocessing\pool.py", line 748, in next
    raise value
AssertionError`

2. With cv-corpus 7.0 (https://commonvoice.mozilla.org/es/datasets):
`python synthesizer_preprocess_audio.py datasets_root -n 6 --datasets_name tux100h-cvcorpus --subfolders valid --no_trim --no_alignments
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    datasets_root:   datasets_root
    out_dir:         datasets_root\SV2TTS\synthesizer
    n_processes:     6
    skip_existing:   True
    hparams:
    no_alignments:   True
    datasets_name:   tux100h-cvcorpus
    subfolders:      valid

Using data from:
    datasets_root\tux100h-cvcorpus\valid
tux100h-cvcorpus:   0%|                                                                                                     | 0/1 [00:00<?, ?speakers/s]D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.  
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. 
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. 
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. 
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. 
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. 
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\voiceclonenv\lib\site-packages\librosa\core\audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
D:\tesis2\voiceclonenv\lib\site-packages\librosa\core\audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
tux100h-cvcorpus:   0%|                                                                                                     | 0/1 [50:24<?, ?speakers/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Programas\Python3.7\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 78, in preprocess_speaker
    text = "".join([line for line in text_file])
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 78, in <listcomp>
    text = "".join([line for line in text_file])
  File "D:\Programas\Python3.7\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 99: character maps to <undefined>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 35, in preprocess_dataset
    for speaker_metadata in tqdm(job, datasets_name, len(speaker_dirs), unit="speakers"):
  File "D:\tesis2\voiceclonenv\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "D:\Programas\Python3.7\lib\multiprocessing\pool.py", line 748, in next
    raise value
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 99: character maps to <undefined>`

With cv-corpus it processed some of the files (1 625/271 010), but then stopped (after at least 30 minutes) and displayed that UnicodeDecodeError.

**Comment by pilnyjakub** [comment]
For the 1st issue: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/841#issuecomment-915287653

For the 2nd issue, in `synthesizer/preprocess.py` and `synthesizer/train.py`, use the same encoding as your dataset. e.g. encoding="utf-8"

**Comment by AlexSteveChungAlvarez** [comment]
Thank you @pilnyjakub  for the fast response, I turned on again my laptop as soon as I saw it. I figured out that the files names for the tux-100h dataset are just numbers, I just changed the first txt and wav files from "0" to "audio-0" and now it is running. Hope it goes well until the end.
For the 2nd one I was thinking on that, too, I will have to search in the code wherever it opens files. I will come up with updates later. Good night.

**Comment by AlexSteveChungAlvarez** [comment]
I have been training since Monday on tux100h dataset for approximately 32-50h the model for the synthetizer have been saved with 50k steps, but I have stopped the training in 57k steps, there's a loss of 0.21-0.24 approximately. However, I have tried to clone my voice using that model in the demo_cli.py and the output does sound like a human, but it sounds like one from the dataset, not like my voice, which is the input. Any recommendations? I am using encoder and vocoder pre-trained models given in the repo.

**Comment by AlexSteveChungAlvarez** [comment]
> 

I found out tux100h has the same voice or a very similar voice in all audios. That may be the problem. Then, I started the preprocessing on cvcorpus dataset which has multiple speakers, but I got the following error:
```
(voiceclonenv) D:\tesis2\Real-Time-Voice-Cloning>python synthesizer_preprocess_audio.py datasets_root -n 6 -s --no_trim --no_alignments --datasets_name 
tux100h-cvcorpus --subfolders valid
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    datasets_root:   datasets_root
    out_dir:         datasets_root\SV2TTS\synthesizer
    n_processes:     6
    skip_existing:   True
    hparams:
    no_alignments:   True
    datasets_name:   tux100h-cvcorpus
    subfolders:      valid

Using data from:
    datasets_root\tux100h-cvcorpus\valid
tux100h-cvcorpus:   0%|                                                                                                    | 0/1 [00:00<?, ?speakers/s]D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended. 
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\Real-Time-Voice-Cloning\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
D:\tesis2\voiceclonenv\lib\site-packages\librosa\core\audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
D:\tesis2\voiceclonenv\lib\site-packages\librosa\core\audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
D:\tesis2\Real-Time-Voice-Cloning\synthesizer\preprocess.py:72: RuntimeWarning: invalid value encountered in true_divide
  wav = wav / np.abs(wav).max() * hparams.rescaling_max
tux100h-cvcorpus:   0%|                                                                                                 | 0/1 [44:54:59<?, ?speakers/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Programas\Python3.7\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 88, in preprocess_speaker
    skip_existing, hparams))
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 219, in process_utterance
    mel_spectrogram = audio.melspectrogram(wav, hparams).astype(np.float32)
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\audio.py", line 60, in melspectrogram
    D = _stft(preemphasis(wav, hparams.preemphasis, hparams.preemphasize), hparams)
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\audio.py", line 121, in _stft
    return librosa.stft(y=y, n_fft=hparams.n_fft, hop_length=get_hop_size(hparams), win_length=hparams.win_size)
  File "D:\tesis2\voiceclonenv\lib\site-packages\librosa\core\spectrum.py", line 217, in stft
    util.valid_audio(y)
  File "D:\tesis2\voiceclonenv\lib\site-packages\librosa\util\utils.py", line 310, in valid_audio
    raise ParameterError("Audio buffer is not finite everywhere")
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "D:\tesis2\Real-Time-Voice-Cloning\synthesizer\preprocess.py", line 35, in preprocess_dataset
    for speaker_metadata in tqdm(job, datasets_name, len(speaker_dirs), unit="speakers"):
  File "D:\tesis2\voiceclonenv\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "D:\Programas\Python3.7\lib\multiprocessing\pool.py", line 748, in next
    raise value
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
```

**Comment by AlexSteveChungAlvarez** [comment]
Please I need some help here, with cv-corpus dataset I tried using less data and I could made it preprocess and train, but the results were very bad. 
By the way, all the process from preprocessing until training took me about a week each time I tried on a different dataset or dataset subsample. I am using a laptop with a NVidia GeForce RTX-2060 gpu, so I think it shouldn't be that slow. Any help? I am considering using another different dataset since both cv-corpus and tux100h didn't give me results compared to the original release of the project, but I don't know which one to choose now and just have 1 month to finish this.

**Comment by johnfelipe** [comment]
I want to collaborate I have 2 GPU 3060, pls send me all steps and I bring
u power of compute
Stay alert.

**Comment by AlexSteveChungAlvarez** [comment]
Thank you very much @johnfelipe, I sent you an email.

**Comment by AlexSteveChungAlvarez** [comment]
I trained the synthesizer with this dataset: http://openslr.org/73/ .
The models obtained until 50k steps are here: https://drive.google.com/drive/folders/1pYc0YK6YfdikMONkR-29054_uMxTgy_g?usp=sharing . Though, the results are not even near to the target voice to clone. Any suggestions? 
It does sound like a human, but not like the target.

**Comment by raul-parada** [comment]
Hi. Any update in here? thanks

**Comment by AlexSteveChungAlvarez** [comment]
> Hi. Any update in here? thanks

https://github.com/AlexSteveChungAlvarez/Real-Time-Voice-Cloning-Spanish

**Comment by raul-parada** [comment]
Thank @AlexSteveChungAlvarez s. I have some questions: 1) where should I locate my datasets? 2) the synthesis phase is included when running demo_toolbox.py? 3) is there a maximum length of text to synthesize? If you have a tutorial/documentation beside the paper is welcome. Thank you again

**Comment by AlexSteveChungAlvarez** [comment]
If you want to train your own model, you should follow the instructions given in this repo, the toolbox does the synthesis when you click on the button it has to generate voice (there's a video in this repo explaining that), there isn't a maximum length of text to synthesize, but the recommended length is to synthesize an audio of a similar length to the original (if not, it happens sometimes that it has some kind of silences or noise). If you train your own model, please share it to me, since my college team is working now on a web interface to calculate the MOS of the Spanish models shared by the community!

**Comment by raul-parada** [comment]
Sure! I'll share my model with you. As recommendation, I would like to generate synthesize audios of approximately 10 min, hence, do you recommend me to train with audio files of length 10 min? Or which is, in your experience, the most efficient length for an excellent quality?

**Comment by AlexSteveChungAlvarez** [comment]
No need to train with audio files of the wanted length to produce, just try to use a reference (target) audio to clone of that length and it will work.

**Comment by johnfelipe** [comment]
Pls share in here results for try later...

**Comment by raul-parada** [comment]
Another question, I don't have an NVIDIA GPU, can I use the CPU instead?

**Comment by AlexSteveChungAlvarez** [comment]
Yes, you can use your CPU.

**Comment by raul-parada** [comment]
I've followed this [video ](https://www.youtube.com/watch?v=vHSulnOxfGo)and could run the program. However:
1- It only selects the default, Encoder, Synthesizer and vocoder. I've copy&paste the latest version of these folders into the Git content (it had save_models folder).
2- I've run the program already 4 times and the voice still cannot talk properly. How many times do you think should I run the program? The wav files has a length of 23 minutes. 

I add a screenshort of the program:
![image](https://user-images.githubusercontent.com/8438920/182149150-b293b333-475c-4db8-94e1-3b702d92b767.png)

I just added the wav file and click on Synthesize and vocode. Is this the procedure so far?

**Comment by raul-parada** [comment]
Now, I've used the code from the spanish version and, I can see the pretrained options. However, I get this error:
![image](https://user-images.githubusercontent.com/8438920/182183685-9cc66b76-fc8f-4500-aeb6-0fb79aca74a2.png)


Any clue?

**Comment by AlexSteveChungAlvarez** [comment]
I also get the same error when I use first one model and then change it to the other, I just downloaded everything again and made sure to run the correct one from the beginning to overcome it, so whenever I want to use any model, I do it from its respective folder (I have like 2-3 different folders to run different models). I don't know what should be the correct way to fix that error.

**Comment by raul-parada** [comment]
Thanks, @AlexSteveChungAlvarez, I've solved by changing the type of Synthesizer. I'm confused right now. I've used the pretrained models and used an audio file of 23 minutes, however, I cannot synthesize correctly my voice using simple sentences in Spanish. What I'm doing wrong? Should I train a specific model with my own voices?

**Comment by AlexSteveChungAlvarez** [comment]
I haven't tried with an audio of that length since my objective of using this code was to clone voices from few length speech audios and few target audios from the people I wanted to clone. When you have access to more audios from the person you want to clone, you will get better results by fine-tuning the model (there is a guide somewhere in the repo on how to do this). I haven't done this, but yeah, you need to train the model with your own voices, by applying transfer learning in the pre-trained model. I think it would be a better solution in your case (if you have many audios of the target voice). If not, try sharing the process you are doing in order to clone with your 23 min audio, maybe you are writing with periods (".") at the end of each sentence and it does make the synthesis go wrong, try using commas instead of periods!
