### ISSUE TITLE
Difference about speaker_embedding part in Synthesizer?

### ISSUE THREAD

**Issue by ymzlygw** [CorentinJ/Real-Time-Voice-Cloning#790]
Hi, firstly thanks for your work!
I find that in model.py of Synthesizer, it use Tacotron but, in forward part  of that , the "speaker_embedding default ==None", so it don't use speaker_embedding when train synthesizer? 
I remember that in older version, the speaker_embedding is used in model Tacotron2. Could you please tell me why and what's the difference, effect on result?

**Comment by blue-fish** [comment]
Our code always passes the speaker_embedding argument so the default value is never used. However, it is there for a reason.

The synthesizer is Tacotron 1 (from fatchord's repo). When I was working on #472, I set the default speaker_embedding=None so I could test the code using fatchord's pretrained **single-speaker** synthesizer model. This was necessary until I could train a working model from scratch.
