### ISSUE TITLE
train using mutiple GPUs

### ISSUE THREAD

**Issue by tranmanhdat** [CorentinJ/Real-Time-Voice-Cloning#791]
i try using mutiple GPUs for faster train, i have 4 RTX 2080, but when i run encoder train, it only uses 1 GPUs, i tried to using " CUDA_VISIBLE_DEVICES=0,1,2,3" but it didn't work

**Comment by blue-fish** [comment]
Encoder training does not support multiple GPUs currently. It is possible but requires some updates to the code. Please submit a pull request if you figure this out.

Closing this issue as a duplicate of #664 .

**Comment by blue-fish** [comment]
The GPU may not be the bottleneck for encoder training. Check the GPU utilization and diagnostic output to find out. The main advantage of multiple GPUs is ability to use a larger batch size.
