### ISSUE TITLE
Datasets_Root

### ISSUE THREAD

**Issue by C4l1b3r** [CorentinJ/Real-Time-Voice-Cloning#792]
In the instructions to run the preprocess. With the datasets how to I figure where the dataset root is. What is the command line needed to do so.

I'm using Windows 10 BTW.
It launches and works without any dataset_root listed but I want to make it work better. And without the datasets I can't

**Comment by C4l1b3r** [comment]
![Screenshot_20210708-131322_VNC Viewer](https://user-images.githubusercontent.com/17440115/124971077-62ef6a00-dfee-11eb-8ddc-87d187dae9d4.jpg)

**Comment by C4l1b3r** [comment]
I am pretty sure it's a windows issue. I'm trying to get it working on a virtual Box.

**Comment by pilnyjakub** [comment]
This is full path to training audio `E:\Speech\[my_dataset]\audio\[speaker_id]\[book_id]\[audio]` that means my datasets_root is `E:\Speech`

**Comment by C4l1b3r** [comment]
Oh ok. I so messed that up lol I'll try thank you

**Comment by C4l1b3r** [comment]
![Screenshot_20210710-164244_VNC Viewer](https://user-images.githubusercontent.com/17440115/125176986-e1d6d500-e19d-11eb-8df9-90ffb6f8f212.jpg)

**Comment by pilnyjakub** [comment]
The folder you specified does not exist. And there are only these default datasets: librispeech_other, voxceleb1, voxceleb2

**Comment by C4l1b3r** [comment]
so if i have librispeech train-clean 100 what do i use

**Comment by pilnyjakub** [comment]
Sorry, my bad, I should have shown it better on the dataset you are using. `E:\[datasets_root]\LibriSpeech\train-clean-100` is the structure you should have. Then just run `python encoder_preprocess.py E:\[datasets_root]`. I'd also suggest not having the datasets_root in the save directory as this application.

**Comment by C4l1b3r** [comment]
ok i managed to get the preprocess to do all 30 gigs.. phew.  now to figure out the rest ecoder_train is next?

**Comment by pilnyjakub** [comment]
Yes, it should be easier now, as you've got the dataset.
