### ISSUE TITLE
Confusion : What is a model ?

### ISSUE THREAD

**Issue by Itlink75** [CorentinJ/Real-Time-Voice-Cloning#793]
Hello, sorry for being a newbie in this Git . I try to understand how the git works and i encounter a serious understanding problem . Before starting , soft loads 3 elements : encoder, synthesizer and vocoder .
All three represent a model.
 As far as i understood , those are the bricks that allow the user to recreate a voice . What is then a voice model ? By voice model i mean a model trained on a specific voice. How is this instance called, how to save and retrieve it ?
Thanx for any help

**Comment by pilnyjakub** [comment]
Models are trained on multiple voices. They can then be used on any voice.

**Comment by KuroChu** [comment]
the saving of a "single voice model" would interest me too

**Comment by pilnyjakub** [comment]
As we're talking about using and not training the model, there is no saving at this stage. When using a model on a voice, the result is unpredicteble unless you set random seed to specific value.

**Comment by blue-fish** [comment]
Here is a brief overview. If you need more information, please refer to the [SV2TTS paper](https://arxiv.org/pdf/1806.04558.pdf) and the code in this repo.

### Encoder model
* Input = mel spectrogram (2-D array with 40 channels and other dimension equal to number of timesteps)
* Output = speaker embedding (1-D array with 256 elements)

### Synthesizer model
* Input 1 = speaker embedding
* Input 2 = text (represented as 1-D array)
* Output = mel spectrogram (2-D array with 80 channels and other dimension equal to number of timesteps)

### Vocoder model
* Input = mel spectrogram
* Output = audio (16000 samples per second)
