### ISSUE TITLE
Question about pre-trained models

### ISSUE THREAD

**Issue by byuns9334** [CorentinJ/Real-Time-Voice-Cloning#80]
Hi Corentin, first of all thank you for this great implementation. 

My question is : 

Are these pre-trained encoder/synthesizer/vocoder models trained on Librispeech&VoxCeleb1&VoxCeleb2/Librispeech&Librispeech_alignments/ ? So did you use all these 1TB data for training these entire models?

Thanks!

**Comment by CorentinJ** [comment]
Yes
