### ISSUE TITLE
Missing __init__.py in vocoder directory

### ISSUE THREAD

**Issue by Rainer2465** [CorentinJ/Real-Time-Voice-Cloning#802]
I just cloned your repo, as I tried to run i was getting a No module named 'vocoder.display' error, I realized that a __init__.py was missing at /vocoder/ directory

**Comment by pilnyjakub** [comment]
What exactly are you trying to run? Because that file isn't a problem.

**Comment by Rainer2465** [comment]
as I tried to run the demo_toolbox.py I was getting the "No module named 'vocoder.display'" error, comming from the Syntheziser/interface.py line 7 "from vocoder.display import simple_table". it only worked as i created the /vocoder/__init__.py file

**Comment by blue-fish** [comment]
This seems specific to your Python installation. Are there any other users that experience this problem?
