### ISSUE TITLE
Errors trying to execute demo_toolbox.py

### ISSUE THREAD

**Issue by IbaiMtnz05** [CorentinJ/Real-Time-Voice-Cloning#803]
![Captura de pantalla 2021-07-18 130931](https://user-images.githubusercontent.com/77854404/126064934-4e4d6a8c-bc70-4043-9f31-b1139a0251c5.png)
I have tried to
• Reinstall python
• Reinstall requierements
• Reinstall other versions

**Comment by robertwt7** [comment]
Yeah same with me here.. it says `no module named torch`

**Comment by HeroTheEmperor** [comment]
Same. but it says No module named 'matplotlib' I think we need to download something

**Comment by HeroTheEmperor** [comment]
YO I found the solution go to Anacando (or whatever command thing ur using) and type. "C:\Users\(UR USERNAME)\Desktop\Real-Time-Voice-Cloning-master> ls" (Or the directory you saved it in but this will work if u are using the default one aka u ignored everything and just pressed accept during installation)

Once that, you should see something like this
![Screenshot 2021-07-23 212349](https://user-images.githubusercontent.com/87876721/126837686-10b866dd-5293-4530-9317-3588bc226db0.png)

Type "pip install -r .\requirements.txt" and press enter it should look something like this
![Screenshot 2021-07-23 212546](https://user-images.githubusercontent.com/87876721/126837941-9b28878f-977a-4347-ad9e-637890a03c3f.png)

After that finishes installing give the proagram another go. It should work.

**Comment by robertwt7** [comment]
I came across [this](https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542) that they never end up merging the new docs, however there are some stuff missing for windows...

Follow that then it works (missing pytorch and several others)

**Comment by Sueda48870** [comment]
Guys, if you couldn't solve the problem, write the name of that module/package with "install" to Google. Install it, then try to write "demo_toolbox.py" again.
