### ISSUE TITLE
Need help to clone specific voices

### ISSUE THREAD

**Issue by aithammd** [CorentinJ/Real-Time-Voice-Cloning#805]
Hello , i just wanted to know how to use the tool to mimic a certain number of voices (n) by training the encoder/vocoder/synth to those 4 voices if possible since i dont quite understand how training the models work and what i should train (rn i am using the demo_cli code to clone a voice with an embed of a 5 sec audio but a single audio wont give as much accurate results as many audios of the same speaker , so i am wondering how to make the embed's  quality better by using more audios or training the models to those audios ) , thank you

**Comment by aithammd** [comment]
another question , if i ihad intention to only use the tool for 5 voices, does training the models help to get better results  or  ican work the current ones (pretrained.pt) ?

**Comment by blue-fish** [comment]
For a small number of voices, you don't need an encoder. You can use a numeric speaker ID (1, 2, 3, 4, ...) as the embedding. If you do this, the synthesizer model will need to be trained from scratch. You will need hours of speech data to train a good model.

If you have a limited amount of training data, use the finetuning method I propose in #437. Train a separate model to each speaker.
