### ISSUE TITLE
[Question] Can i use tool from command line?

### ISSUE THREAD

**Issue by SaraDark** [CorentinJ/Real-Time-Voice-Cloning#806]
[Question] Can i use tool from command line? 

Eg. tool -voice "VoicesToUsageToSpeach/example.mp3" -test "text to speach" -o /save_file.ogg

Or smoethink like that? Test to speatch in selected voices and maybe emotion voices?

**Comment by aithammd** [comment]
yes you can , you just need to do some code modification /get inspired by the demo_cli.py for example and u will be fine !

**Comment by SaraDark** [comment]
sounds cool :) thx
