### ISSUE TITLE
[Question] TTS - 3 question of generation voices?

### ISSUE THREAD

**Issue by SaraDark** [CorentinJ/Real-Time-Voice-Cloning#807]
I have questions about voice generation:

1) TTS, Can i change speed of speatch, faster/slower?
2) TTS, Can i change emotion eg; Neutral, Espressive, Anger, Fear, happy, Sad, Shouting?
3) TTS, Dictionary edit world equivalents  to Pronuciation?

Thx :)

**Comment by blue-fish** [comment]
You can't do 1 or 2 with this repo.

There is a limited ability to do 3, by defining a [text cleaner](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/synthesizer/utils/cleaners.py) to replace words in your input text. However, all you can do is substitute words in the input. It cannot be used to change the language.
