### ISSUE TITLE
TypeError: can only concatenate list (not "dict_keys") to list

### ISSUE THREAD

**Issue by Sueda48870** [CorentinJ/Real-Time-Voice-Cloning#808]
I get "TypeError: can only concatenate list (not "dict_keys") to list" when I write "demo_toolbox.py" on the last step. What should I do? (Sorry for bad English.)

**Comment by blue-fish** [comment]
Please share the traceback accompanying the error message. Also check that you're using a supported version of Python (currently 3.6, 3.7, 3.8).
