### ISSUE TITLE
Hello, it seems that the training speed of tacotron is really slow. Is there any problem with my equipment?

### ISSUE THREAD

**Issue by sunnnnnnnny** [CorentinJ/Real-Time-Voice-Cloning#81]
Step    4000 [3.131 sec/step, loss=1.05912,before_loss=0.37384,after_loss=0.21408,stok_token_loss=0.01239,regula_loss=0.00058,linear_loss=0.45822, avg_loss=1.08960

On average 3s/step, I didn't modify hparams.py too much, I just used two graphics cards.

**Comment by sunnnnnnnny** [comment]
Forgot to say, is the tacotron model

**Comment by CorentinJ** [comment]
Yeah that seems within the range of what it should be. Nothing trains really fast in this repo.

**Comment by sunnnnnnnny** [comment]
Thank you for replying so quickly, I get it.
