### ISSUE TITLE
utterances_per_speaker affect

### ISSUE THREAD

**Issue by swel4ik** [CorentinJ/Real-Time-Voice-Cloning#810]
Hi, guys! I have a question:
What does the utterances_per_speaker affect? Only to accelerate training, because we use a bigger batch? 
Thanks!

**Comment by blue-fish** [comment]
You are correct. The `utterances_per_speaker` setting in [encoder/params_model.py](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/95adc699c1deb637f485e85a5107d40da0ad94fc/encoder/params_model.py) only affects the batch size for training. It has no effect for inference.
