### ISSUE TITLE
Trying to run the toolbox is stuck doing nothing

### ISSUE THREAD

**Issue by AceOfSpadesProduc100** [CorentinJ/Real-Time-Voice-Cloning#813]
I followed the instructions in the readme, and also added ffmpeg.exe to the root folder, but when I run `python demo_toolbox.py`, it's just stuck there.

**Comment by AceOfSpadesProduc100** [comment]
Should I just use the notebook instead? https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/RealTimeVoiceCloning.ipynb

**Comment by babysor** [comment]
What's the error message?

**Comment by AceOfSpadesProduc100** [comment]
None, the terminal is just stuck doing nothing. For some reason, the problem only happens on native instead of venv.

**Comment by babysor** [comment]
I strongly recommend you use the venv, which is a much better practice unless you want to mess up the projects with others and your system.
