### ISSUE TITLE
Can someone link me some resources about model training?

### ISSUE THREAD

**Issue by hopkuba** [CorentinJ/Real-Time-Voice-Cloning#815]
I have polish voice database that is maybe not the best but I still want to try to make polish model.
I have loaded my database into encoder training and there were some errors connected with "visdom_server"
Please help me find some resources to train it. Some kind of tutorial or guide?

**Comment by pilnyjakub** [comment]
Run `visdom` in seperate console window. Then run `encoder_train.py`. Also you can check which files to edit #819 and only other guide is [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training).

**Comment by bryant0918** [comment]
> I have polish voice database that is maybe not the best but I still want to try to make polish model. I have loaded my database into encoder training and there were some errors connected with "visdom_server" Please help me find some resources to train it. Some kind of tutorial or guide?

Can you share the Polish database you're using as well as the model if you ever completed it?
