### ISSUE TITLE
Is this supposed to happen? am I supposed to put an audio file next to this?

### ISSUE THREAD

**Issue by Hi-ip** [CorentinJ/Real-Time-Voice-Cloning#816]
Hello, I get this error in Ubuntu on my WSL 2 implementation and Ubuntu Docker  NOVNC container. Please place more details or a pathway in documentation to help with error resolution

See below 
############

**gitpod /workspace/Real-Time-Voice-Cloning $** python demo_cli.py 
Arguments:
    enc_model_fpath:   encoder/saved_models/pretrained.pt
    syn_model_fpath:   synthesizer/saved_models/pretrained/pretrained.pt
    voc_model_fpath:   vocoder/saved_models/pretrained/pretrained.pt
    cpu:               False
    no_sound:          False
    seed:              None
    no_mp3_support:    False

Traceback (most recent call last):
  File "demo_cli.py", line 42, in <module>
    import sounddevice as sd
  File "/workspace/.pip-modules/lib/python3.8/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found
**gitpod /workspace/Real-Time-Voice-Cloning $** 

###########

**Comment by pilnyjakub** [comment]
Try installing `sudo apt-get install libportaudio2` or `sudo apt-get install libasound-dev`
