### ISSUE TITLE
Training Tutorial

### ISSUE THREAD

**Issue by pilnyjakub** [CorentinJ/Real-Time-Voice-Cloning#819]
# Preprocess Data
I've written script to preprocess [Mozilla Common Voice](https://drive.google.com/file/d/1ogQcnq43DtEPJUklHjEYG2cXyH1vGba0/).

Also when running `synthesizer_preprocess_audio.py` include `--no_alignments` argument.

Of course you can use your own dataset, but don't forget the data structure (based on LibriSpeech):
```
<datasets_root>
    LibriSpeech
        train-clean-100
            <speaker>
                <book_id>
                  <utterance>
                  <utterance>
            <speaker>
                <book_id>
                  <utterance>
                <book_id>
                  <utterance>
```
I recommend converting audio files to `.flac` for better program functionality. 

# Editing Files
## Encoder

When using other audio format, change `.flac` in `encoder/preprocess.py` to your format. 

## Synthesizer

When using other audio format, add value to extensions in `synthesizer/preprocess.py` (formats recognized by default `.wav`, `.flac`, `.mp3`)

If you've trained custom encoder model, run `synthesizer_preprocess_embeds.py -e encoder/saved_models/<run_name>.pt`

Wherever you're opening files, use the same encoding as your dataset. e.g. `encoding="utf-8"` (synthesizer/preprocess.py, synthesizer/train.py)

`synthesizer/hparams.py`
```
tts_cleaner_names = ["basic_cleaners"],
```
`synthesizer/symbols.py`
Add chacters used by your language.

## Vocoder

If you've trained custom synthesizer model, run `vocoder_preprocess.py --model_dir synthesizer/saved_models/<run_name>/`

**Comment by blue-fish** [comment]
Instead of updating the preprocessing scripts to support other datasets, we should write programs to reformat the datasets so they resemble LibriSpeech in folder structure.

**Comment by ireneb612** [comment]
I agree with blue-fish! I wanted to use the The M-AILABS Speech Dataset in italian. Is there an implementation for it?

**Comment by pilnyjakub** [comment]
@blue-fish So you want the data structure to be `LibriSpeech/train-clean-100/spekers...` and then contain data from other datasets? Otherwise you'd have to edit those files (technically only `encoder/config.py` and `synthesizer/symbols.py`).

**Comment by ireneb612** [comment]
@pilnyjakub I got this error:
 Error opening 'D:\\data\\cloning\\dataset\\cv-corpus-7.0-2021-07-21\\it\\audio\\train1\\000507c663409bb1796c90a583f52209f5e08870240424f8eb0ac861e194a97c07bfe6ece88a7129d4c51
bc8a8895d61516a2dad5a89bdc45c8a216c0207bb49\\0\\common_voice_it_20041619.mp3': File contains data in an unknown format.

do I have to convert everything to flac? It seems quite expensive

**Comment by pilnyjakub** [comment]
@ireneb612 This is probably due to an older version of librosa, try upgrading it or try one of these https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/395, https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/214, https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/198

**Comment by ireneb612** [comment]
@pilnyjakub  I trasformed all the files to flac format, I also got some problems with this Error:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6 audio5: character maps to <undefined>

This is due to the fact that the encoding for the italian language is "latin-1". After changing that the synthetizer_prepocessing_audio.py seems to work!

**Comment by blue-fish** [comment]
> @blue-fish So you want the data structure to be `LibriSpeech/train-clean-100/spekers...` and then contain data from other datasets?

Yes, that's what I have in mind.

**Comment by pilnyjakub** [comment]
Ok, will update.

**Comment by blue-fish** [comment]
I'm going to close this issue as we will no longer provide support for any datasets not already incorporated into the repo. The end user is expected to reformat any dataset to resemble LibriSpeech/LibriTTS in structure.

@pilnyjakub If you would like to share dataset conversion scripts, please open a new issue.
