### ISSUE TITLE
Parameter tuning for cross language training

### ISSUE THREAD

**Issue by satan17** [CorentinJ/Real-Time-Voice-Cloning#822]
Hi,

I've been trying to extend the current model functionality with different languages. I've used your current pre-trained models and given Spanish audio as an input. I didn't changed any code in symbols.py or in any other files and given English text in vocoder textbox. The output is not good but it's not bad either. 

Could you please suggest me how to proceed with the training. My objective is to give spanish audio as an input and get the output audio in English. I don't need to train encoder, I get that now and I think vocoder also don't need training (NOT SURE ?). I'm confused in the synthesizer training. 

Should I change the symbols.py and replace english characters with spanish alphabets (which ideally we should do because synthesizer tries to map each word's utterance with the letters in corresponding text file) and retrain the model ?

**Comment by satan17** [comment]
@blue-fish Could you please share your thoughts on this one if possible ?

**Comment by pilnyjakub** [comment]
The current pretrained models output english audio sounding like input audio. There's only one way to make it sound better and that is to use a larger dataset and train the models as much as possible. The problem is that the quality would increase only a little in an awfully long time.

**Comment by blue-fish** [comment]
> I think vocoder also don't need training (NOT SURE ?).

Try using the pretrained vocoder, trained on English speech. It should also work for Spanish since the input is a mel spectrogram.

> Should I change the symbols.py and replace english characters with spanish alphabets

Yes. You will need to train a new model, using a dataset with Spanish audio.
