### ISSUE TITLE
How to improve voice cloning?

### ISSUE THREAD

**Issue by ishaghodgaonkar** [CorentinJ/Real-Time-Voice-Cloning#824]
To improve voice cloning, what is the recommended avenue? I mainly want to clone 3rd party voices, not fine-tune the model for a single speaker. I see that the latter has already been done in #437, and I also see that LibriTTS is a better dataset than LibriSpeech. Would the recommended avenue be to then train the synthesizer only on LibriTTS, and then replace the pretrained model (the one trained on LibriSpeech + fine-tuned on LibriTTS) with this new one? Has this already been done? Are there any other recommendations for high ROI ways to improve generalization quality? Thanks!

**Comment by pilnyjakub** [comment]
You can simply enlarge the dataset (or enhance it with better recordings) and train the model longer.

**Comment by ishaghodgaonkar** [comment]
Do you mean fine-tuning the existing model? Is this worth the effort/ do you think there will be a significant performance improvement?

**Comment by pilnyjakub** [comment]
Basically, yes. The model is pretty much at its best, so if you would train it for long enough (like 2mil. steps at largest possible batch size) it would sound better.

**Comment by ishaghodgaonkar** [comment]
Thanks!

**Comment by ishaghodgaonkar** [comment]
@blue-fish would appreciate your thoughts here too!

**Comment by blue-fish** [comment]
@ishaghodgaonkar Our open-source SV2TTS implementation already performs nearly as well as Google’s published samples, when it comes to similarity for unseen voices. However, Google still has the better TTS which results in higher overall quality.

I’ve tried numerous things to improve the TTS, with limited success. Some of the remaining low-hanging fruit includes:
1. Train the synthesizer with more voices
2. Improve quality of training audios (synthesizer + vocoder)
3. Change attention paradigm
4. Better vocoder model
5. Switching the synthesizer model back to Tacotron 2 is also an obvious thing to try, but not trivial.

To further improve voice similarity, you need to look beyond SV2TTS and consider different model architectures. One example is Attentron ([paper](https://arxiv.org/pdf/2005.08484), [audio samples](https://hyperconnect.github.io/Attentron/)). However, this involves a lot of effort and experimentation, and is not the high ROI activity you are looking for.
