### ISSUE TITLE
Module not found: No module named 'numba.core'

### ISSUE THREAD

**Issue by Lanev** [CorentinJ/Real-Time-Voice-Cloning#826]
![numbacore](https://user-images.githubusercontent.com/63927672/130689677-d750dfb5-7bdd-45da-bfff-f80abc42bc2e.png)
When I try to run the demo_toolbox this error prevents me from opening it. Does anyone know what is going on?

**Comment by alfredtofu** [comment]
here is my solution:
```
pip uninstall numba
pip install llvmlite --ignore-installed
pip install numba==0.52
```
