### ISSUE TITLE
program keeps freezing

### ISSUE THREAD

**Issue by speedsterbird** [CorentinJ/Real-Time-Voice-Cloning#831]
hello! so i'm using this for some personal projects but every time i try to load in a voice the program says not responding. i really dont know whats wrong i followed a tutorial and everything. i am really new to programming and have little to no idea what some references are Im just playing it by ear as i go. if someone could please help me thatd be great thanks!

**Comment by blue-fish** [comment]
Please follow my [Windows setup tutorial](https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542) to the letter, and open a new issue if you continue to have problems.
