### ISSUE TITLE
Cannot solve for 437

### ISSUE THREAD

**Issue by schae43** [CorentinJ/Real-Time-Voice-Cloning#841]
Hello,

I am still having an issue following 437.  I keep getting an assertion error for the filepath where the utterances are kept (code/error below).  

I created 4 wav files and 4 text files. (see screenshot below)
![image](https://user-images.githubusercontent.com/90283008/132401592-d3101aa6-61da-466e-8e6a-00784a38ca8d.png)

I'm not sure what else I need to do to get these files for the model to train on.

(deepvoice) C:\Users\Family\Desktop\Real-Time-Voice-Cloning-master>python synthesizer_preprocess_audio.py synthesizer/saved_models/logs-singlespeaker/datasets_root --datasets_name LibriTTS --no_alignments
Arguments:
    datasets_root:   synthesizer\saved_models\logs-singlespeaker\datasets_root
    out_dir:         synthesizer\saved_models\logs-singlespeaker\datasets_root\SV2TTS\synthesizer
    n_processes:     None
    skip_existing:   False
    hparams:
    no_alignments:   True
    datasets_name:   LibriTTS
    subfolders:      train-clean-100, train-clean-360

Using data from:
    synthesizer\saved_models\logs-singlespeaker\datasets_root\LibriTTS\train-clean-100
    synthesizer\saved_models\logs-singlespeaker\datasets_root\LibriTTS\train-clean-360
LibriTTS:   0%|                                                                                                                                                                      | 0/1 [00:07<?, ?speakers/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Family\Anaconda3\envs\deepvoice\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Family\Desktop\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 76, in preprocess_speaker
    assert text_fpath.exists()
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 59, in <module>
    preprocess_dataset(**vars(args))
  File "C:\Users\Family\Desktop\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py", line 35, in preprocess_dataset
    for speaker_metadata in tqdm(job, datasets_name, len(speaker_dirs), unit="speakers"):
  File "C:\Users\Family\Anaconda3\envs\deepvoice\lib\site-packages\tqdm\std.py", line 1185, in __iter__
    for obj in iterable:
  File "C:\Users\Family\Anaconda3\envs\deepvoice\lib\multiprocessing\pool.py", line 748, in next
    raise value
AssertionError

(deepvoice) C:\Users\Family\Desktop\Real-Time-Voice-Cloning-master>

**Comment by blue-fish** [comment]
It is unable to find the corresponding .txt file for one or more wavs. Try checking file permissions.

You can apply [these changes](https://github.com/blue-fish/Real-Time-Voice-Cloning/commit/008cf9602e4162e72a38d24ac81db37a1e03b6f3) to make the synthesizer preprocess single-threaded. This will make it easier to troubleshoot issues.

**Comment by schae43** [comment]
Well, I got a new error(below).  I couldn't figure this one out either.  I appreciate any help you can provide.


(deepvoice) C:\Users\Family\Desktop\Real-Time-Voice-Cloning-master>python synthesizer_preprocess_audio.py synthesizer/saved_models/logs-singlespeaker/datasets_root --datasets_name LibriTTS --no_alignments
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 1, in <module>
    from synthesizer.preprocess import preprocess_dataset
ImportError: cannot import name 'preprocess_dataset' from 'synthesizer.preprocess' (C:\Users\Family\Desktop\Real-Time-Voice-Cloning-master\synthesizer\preprocess.py)

**Comment by blue-fish** [comment]
Unfortunately, we're unable to provide assistance for these sorts of issues. I hope you are able to resolve the error message.
