### ISSUE TITLE
SV-EER calculation

### ISSUE THREAD

**Issue by cnu1439** [CorentinJ/Real-Time-Voice-Cloning#842]
Hi,

I'm trying to do the evaluation on test datasets. How can I calculate SV-EER for synthesizer. I did following steps, correct me if I'm wrong.

- run synthesizer on test data get melspectrums.
- did inverse melspectrum to get wav data
- get embeds for the wav data
- calculate similarity matrix and EER

Thanks,
Srinivas.

**Comment by blue-fish** [comment]
In 1806.04558 SV-EER is calculated for the encoder, not the synthesizer. Please refer to section 3.3.3 of Corentin's thesis for more details on how EER is determined in this repo.
