### ISSUE TITLE
Zsh: parse error near '\n'

### ISSUE THREAD

**Issue by Arnau97** [CorentinJ/Real-Time-Voice-Cloning#845]
OS: Kali Linux

When I try to open the ''program'' with the command python demo_toolbox.py -d <datasets_root>

It says this error: 
![image](https://user-images.githubusercontent.com/68655033/132904332-0d0795f5-997f-4673-a96d-ab3af53e943e.png)

**Comment by blue-fish** [comment]
Replace `<datasets_root>` with the actual path to the directory containing datasets. If you did not download a dataset, simply run `python demo_toolbox.py`

**Comment by script-sudo** [comment]
Hello i have same issue like that but i couldnt solve it. Can you help me pls?

**Comment by sharkman4813** [comment]
Try this,

python3 demo_toolbox.py -d '<datasets_root>'
