### ISSUE TITLE
Performance in fatchord_version and deepmind_version of waveRNN model?

### ISSUE THREAD

**Issue by ymzlygw** [CorentinJ/Real-Time-Voice-Cloning#846]
Hi, I want to know is there any Performance defferent in factron_version and deepmind_version  of waveRNN model?
Can I use deepmind version to train a waveRNN model rather than fatchord version?

**Comment by blue-fish** [comment]
I have not tried the deepmind version, which is not compatible with the training code (see https://github.com/fatchord/WaveRNN/issues/152).

This topic is out of scope, you are encouraged to open the issue in the fatchord/WaveRNN repo.
