### ISSUE TITLE
Can I do based on TensorFlow with DirectML to work with AMD video cards?

### ISSUE THREAD

**Issue by pin240** [CorentinJ/Real-Time-Voice-Cloning#847]
Сan I do it on the basis of Tensorflow with DirectML to work with AMD graphics cards? CPUs are slow and Nvidia cards are almost unavaimable. 
I have 3 AMD graphics cards (2pcs - R9 Nano and Vega64) and a big 19GB set.
I'm even willing to give it up for common use.
As I understood, you need a video card with CUDA for training, but I do not have one. A lot of rummaging through the Internet and ran into an article
https://docs.microsoft.com/en-us/windows/ai/directml/gpu-tensorflow-windows 
Is it difficult to remake for it and train the model?
How to train a model for Russian language?

**Comment by blue-fish** [comment]
What you describe is possible, but difficult as the repo needs to be rewritten in Tensorflow. Instead, it would be less work to run Pytorch for ROCm, or modify the repo to work with Google Colab. Still, my recommendation is to get a Nvidia GPU if at all possible if you have a serious interest in this.

There are no instructions for training on a language other than English, but this might be helpful: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/431#issuecomment-673555684

**Comment by pin240** [comment]
Thanks for the quick response. You have a problematic video card. And I myself do not care about programming. And main machine on win10 :(

**Comment by blue-fish** [comment]
Can you use a cloud GPU? This person figured out how to use this repo with Amazon Sagemaker. https://github.com/rustygentile/Real-Time-Voice-Cloning

**Comment by pin240** [comment]
I understood about what article. But there is no such possibility.  I wanted to use it for audio books. I can give you a link to the Date Set for Training?

**Comment by blue-fish** [comment]
Go ahead and share the dataset if you wish, but someone else will have to train the models.

**Comment by pin240** [comment]
Valid 14 days (from 13.09) [https://dropmefiles.com/aA2xF](url)

**Comment by fancat-programer** [comment]
> 
> 
> Valid 14 days (from 13.09) [https://dropmefiles.com/aA2xF](url) If you need to leave again.

I want to train a model for Russian, but I don't have enough data for the synthesizer. Can you share the dataset again?

**Comment by pin240** [comment]
> I want to train a model for Russian, but I don't have enough data for the synthesizer. Can you share the dataset again?

https://dropmefiles.com/DZY79

Give your mail. It's more reliable.
Will you send me a model in the mail? pin240@mail.ru

**Comment by fancat-programer** [comment]
I'll post the model in the public domain, I recently found a HUGE dataset of Russian speech(https://github.com/snakers4/open_stt), but thanks anyway.

**Comment by pin240** [comment]
I'm just afraid to forget about it) In a couple of hours to unload

**Comment by pin240** [comment]
> I want to train a model for Russian, but I don't have enough data for the synthesizer. Can you share the dataset again?

PC  PC went to hibernation when unloading :( New link https://dropmefiles.com/uhoQX

**Comment by blue-fish** [comment]
@pin240 Pytorch now supports ROCm 4.2 on Linux.
```
pip3 install torch torchvision==0.10.1 -f https://download.pytorch.org/whl/rocm4.2/torch_stable.html
```

**Comment by pin240** [comment]
I'll take note.
I have win7 and I can't switch to Linux. Many programs that only under Windows 7
