### ISSUE TITLE
Training Time Estimate

### ISSUE THREAD

**Issue by Noskid1999** [CorentinJ/Real-Time-Voice-Cloning#848]
I am running a training for the Encoder for Nepali language with 527 speakers and approximately 200~hours of audio data. All the training parameters used are default parameters.
How can I estimate the total training time for this?
(Forgive me if this is something simple enough to ask. I am new to this whole thing and am enthusiastic to learn further about this.) Thank you!

**Comment by blue-fish** [comment]
With only 527 speakers the default embedding size of 256 is much too large. Changing it to 64 should produce a better model for voice cloning. The SV2TTS authors used an embedding size of 64 for their smaller datasets with 1200 speakers.

![image](https://user-images.githubusercontent.com/67130644/132529669-85359535-bcba-4450-aeb7-50588550fc93.png) 

The encoder training loop continues indefinitely until stopped by the user. You'll have to decide when you are satisfied with the quality of the model. See section 3.3.3 of [Corentin's thesis](https://matheo.uliege.be/handle/2268.2/6801) for more details on encoder training. 

Training time depends on several variables, including: number of speakers, data quality, GPU speed, dataset stored on SSD vs. HDD, success criteria. The pretrained encoder was trained in 20 days on a GTX 1080 Ti with a batch size of 64. However, with fewer speakers you might find it to converge much faster, perhaps 2-3 days.

**Comment by Noskid1999** [comment]
Noted. Thank you!
