### ISSUE TITLE
After running python demo_cli.py  getting traceback 

### ISSUE THREAD

**Issue by bhaskarkumar1** [CorentinJ/Real-Time-Voice-Cloning#849]
traceback in line 108, 86, 64, 496, and  366. reffered to the tutorial https://www.youtube.com/watch?v=_4ySXTe5iyQ
if you can help me to solve this issue, then it will be great!
![voice cloning](https://user-images.githubusercontent.com/84345649/133657544-7c571b90-580c-4a7a-8bf9-0dc195b9ce0f.png)

**Comment by akromatikus** [comment]
It looks like the pre-trained file for the synthesizer folder was loaded incorrectly. Make sure it's exactly the same as the tutorial.

**Comment by bhaskarkumar1** [comment]
Hey, I tried the 2 pretrained model of different versions one by one but it's showing the issue in synthesizer part code.

**Comment by blue-fish** [comment]
It's not finding the model file in the expected location. Follow steps 11 and 12 from this link very carefully.
https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
