### ISSUE TITLE
Controlling batch size

### ISSUE THREAD

**Issue by tt-cube** [CorentinJ/Real-Time-Voice-Cloning#85]
Hi, I was able to get the program running in conda. I noticed that the batch size played a big difference in my output quality, but each time I ran the synthesis the batch size changed. Is there any way to explicitly set it?

**Comment by CorentinJ** [comment]
The batch size has no effect on the quality, rather what you're seeing is related to the length of the sentence you're generating. You can change the overlap and target parameters of the vocoder though, which will influence the batched inference.
