### ISSUE TITLE
Encoder zero output

### ISSUE THREAD

**Issue by ARKEYTECT** [CorentinJ/Real-Time-Voice-Cloning#850]
Hi blue-fish:
     Follow up on# 776. I set up an environment on Linux according to the guidance post here and re-processed everything and started training on LibriSpeech train other and vox1, vox2 with 768/256. The loss converges slightly faster than some other folks result here. But then I examined the embed output after 160000 iterations and found out that the embed consists of zeroes dominantly. Is it normal? I uploaded a UMAP.
![vanilla_run_01_umap_171000](https://user-images.githubusercontent.com/18693148/133677871-75fb8c61-0638-4b90-96a4-c85911ddbefd.png)

**Comment by blue-fish** [comment]
Select an utterance, and generate the embed using Corentin's model and yours. Compare the results. I recall the embeds tend to be sparse due to use of ReLU activation in the model. You can try removing it.
