### ISSUE TITLE
How can I improve the quality of speech generation if the reference voice speaks a different language?

### ISSUE THREAD

**Issue by fancat-programer** [CorentinJ/Real-Time-Voice-Cloning#859]
How can I improve the quality of speech generation if the reference voice speaks a different language?

**Comment by ireneb612** [comment]
retrain on your language data!

**Comment by fancat-programer** [comment]
I want to train a model with a dataset for my language and clone the American voice.

**Comment by blue-fish** [comment]
Not much work has been done in this area. You can try training a speaker encoder on multiple languages. Here is a pretrained example of a [multi-language encoder](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-535936275) (use these [hparams](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/126#issuecomment-573523609) with that model).
