### ISSUE TITLE
getting massive error when getting webrtcvad

### ISSUE THREAD

**Issue by nanogram** [CorentinJ/Real-Time-Voice-Cloning#86]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\NAME\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NAME\\AppData\\Local\\Temp\\pip-install-sd3z4nr3\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\NAME\\AppData\\Local\\Temp\\pip-install-sd3z4nr3\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\NAME\AppData\Local\Temp\pip-record-405orggd\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\NAME\AppData\Local\Temp\pip-install-sd3z4nr3\webrtcvad\
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying webrtcvad.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_webrtcvad' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\cbits
    creating build\temp.win-amd64-3.7\Release\cbits\webrtc
    creating build\temp.win-amd64-3.7\Release\cbits\webrtc\common_audio
    creating build\temp.win-amd64-3.7\Release\cbits\webrtc\common_audio\signal_processing
    creating build\temp.win-amd64-3.7\Release\cbits\webrtc\common_audio\vad
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -D_WIN32 -Icbits -Ic:\users\NAME\appdata\local\programs\python\python37\include -Ic:\users\NAME\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include" /Tccbits\pywebrtcvad.c /Fobuild\temp.win-amd64-3.7\Release\cbits\pywebrtcvad.obj
    pywebrtcvad.c
    c:\users\NAME\appdata\local\programs\python\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\NAME\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NAME\\AppData\\Local\\Temp\\pip-install-sd3z4nr3\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\NAME\\AppData\\Local\\Temp\\pip-install-sd3z4nr3\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\NAME\AppData\Local\Temp\pip-record-405orggd\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by CorentinJ** [comment]
#4
