### ISSUE TITLE
There is no speaker id in my dataset, what should I do?

### ISSUE THREAD

**Issue by fancat-programer** [CorentinJ/Real-Time-Voice-Cloning#861]

**Comment by blue-fish** [comment]
Familiarize yourself with the LibriSpeech dataset format. Then reformat your dataset to resemble LibriSpeech. This requires you to separate your audio files by speaker.

Hopefully you are provided enough information to do this. If not, you will need a different dataset.

**Comment by fancat-programer** [comment]
Unfortunately, no... I will try to teach the encoder to LibriSpeech, LibriTTS, voxforge(1,2) and mozilla common voice(Russian, Belarusian, English)

**Comment by blue-fish** [comment]
If the symbols in your languages are mutually exclusive, it should be possible. However, I wouldn't recommend it until you have a lot of experience with training models.
