### ISSUE TITLE
GLaDOS voice effects transfer

### ISSUE THREAD

**Issue by fancat-programer** [CorentinJ/Real-Time-Voice-Cloning#863]
How do I make a model speak with a GLaDOS voice?

**Comment by blue-fish** [comment]
Train your synthesizer with similar voices.

**Comment by blue-fish** [comment]
It should, if your speaker encoder can differentiate between the normal and target voice styles. If not, you can try appending a one-hot voice style element to the usual speaker embedding when training the synthesizer.

**Comment by fancat-programer** [comment]
Are you saying that I need to add a record of similar voices to the regular recordings?

**Comment by fancat-programer** [comment]
Would I just need to increase the values in hparams or change the code?
