### ISSUE TITLE
Training models questions

### ISSUE THREAD

**Issue by augustkimo** [CorentinJ/Real-Time-Voice-Cloning#87]
Hi,

I hold my own but I'm not a developer I am just discovering the program for fun. I am currently using the program with all pretrained settings and some audio clips I uploaded myself, but the results haven't come out good using numerous different voices.

Is the training model meant to make the results better? Sorry I don't really understand it yet, but if you run the training for your audio clips, it will help you get a better result? Thanks. Just asking before I download all the huge training files.

**Comment by CorentinJ** [comment]
No it won't. What you're thinking of is finetuning, whereas this is voice cloning. Both achieve the same objective but with a different order of data/time.
