### ISSUE TITLE
Request: Arabic model

### ISSUE THREAD

**Issue by ghost** [CorentinJ/Real-Time-Voice-Cloning#871]
is there arabic model?

_Originally posted by @mennatallah644 in https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/400#issuecomment-721017841_

**Comment by vfxgfx** [comment]
نيج  نيج  نيج  نيج  نيج  نيج  نيج  نيج نيج نيج نيج

**Comment by tunisvesx** [comment]
السلام عليكم
