### ISSUE TITLE
Pretrained Models Using Datasets Other Than LibriSpeech?

### ISSUE THREAD

**Issue by Tomcattwo** [CorentinJ/Real-Time-Voice-Cloning#877]
Hello all,
@blue-fish , I had very good success on my project to clone 14 voices from a computer simulation ([samples available here](https://drive.google.com/drive/mobile/folders/1lh6wjIvXUImmqdF2LndSrwb8iwTOcKVx/142ZimENWa6Mxfd_lbK4G3xVbg9P0L3ft/16jxQ7jI1ZDJJaRFYrhaQIPxupk4HNQSy?sort=13&direction=a) ) using single-voice training (5000 additional steps) on the LibriSpeech pretrained synthesizer (295K) and Vocoder. 

However, I would like to see if another model (in English) might provide better output reproducibility, and perhaps punctuation recognition and some better degree of emotion (perhaps with LibriTTS or some newer corpus that I am not aware of yet). Are you aware of any pretrained speech encoder/synthesizer/vocoder models built on another dataset that might be available for download? I tried building synthesizer and vocoder single voice training on the synthesizer LibriTTS model from your single voice training instructions, but only got garbled output in the demo_toolbox, probably due to the fact that the speech encoder was built on LibriSpeech and not on LibriTTS . Any info you or anyone else might have on a potential model-set download would be greatly appreciated.
Thanks in advance,
Tomcattwo

**Comment by blue-fish** [comment]
You can reuse the existing encoder and vocoder models. When training the synthesizer, make sure not to change the audio settings in the synthesizer hparams.

Our observations on LibriTTS are in #449.

Since this is your first time training a model from scratch, I suggest decreasing the model dimensions, and use a larger reduction factor. This will help the model train faster, at the expense of quality. When you are confident things are working, revert to the defaults.

```
tts_embed_dims = 256,
tts_postnet_dims = 256,
tts_lstm_dims = 512,

tts_schedule = [(5,  1e-3,  20_000,  26),   # Progressive training schedule
                (5,  5e-4,  40_000,  26),   # (r, lr, step, batch_size)
                (5,  2e-4,  80_000,  26),   #
                (5,  1e-4, 160_000,  26),   # r = reduction factor (# of mel frames
                (5,  3e-5, 320_000,  26),   #     synthesized for each decoder iteration)
                (5,  1e-5, 640_000,  26)],  # lr = learning rate
```

**Comment by blue-fish** [comment]
You can also decrease `max_mel_frames` to a lower number (like 500) to discard longer utterances. This will also increase training speed.

**Comment by Tomcattwo** [comment]
@blue-fish , thanks for the reply. If I decide to go forward on this effort, I would plan to use train-clean-360. Easier to download, smaller size. After reading #449 ,  I agree that limiting max_mel_frames to 500 is a good idea. Thanks also for the accelerated training hparams info.
R/
TC2

**Comment by blue-fish** [comment]
I suggest using both train-clean-100 and 360 to more closely match the training of the pretrained models. If you decide to pursue this, good luck and please consider sharing your models.

**Comment by Tomcattwo** [comment]
@blue-fish said: #I suggest using both train-clean-100 and 360 to more closely match the training of the pretrained models.#

How can I use both? Do I run training for 100k steps on train-cleanl100 then train another 200k steps using train-clean-360 on top of that? Or can I simply combine them both together in my datasets_root and train the combination once to 300k steps?

#If you decide to pursue this, good luck and please consider sharing your models.#
Absolutely, assuming that the models come out sounding good. Happy to share plots, mid-training .wavs etc. upon request.
Regards, 
TC2

**Comment by blue-fish** [comment]
> How can I use both? Combine them both together in my datasets_root and train the combination once to 300k steps?

Exactly.

**Comment by blue-fish** [comment]
@Tomcattwo Did you end up pursuing this? If yes, how is the training coming along?

**Comment by Tomcattwo** [comment]
@blue-fish , I have not started on this project yet. I have a few other projects (semi-related) working now. I read the TTS Corpus paper and it sounds interesting. Frankly I have gotten very good results from the single voice trained models I am using for my current prohect, but there's always room for improvement. I would love to be able to "help" the synthesizer using punctuation to tell it where to place the emphasis on a syllable or syllables in multi-syllabic a word...
I would like to give a TTS-built-from-scratch synthesizer base a try once I get some of these other projects behind me. I will let you know when I start and I will keep you apprised of progress. No doubt I will hit some snags and will solicit your always-helpful advice.
Regards,
Tomcattwo

**Comment by blue-fish** [comment]
Pleased to know that you are satisfied with the single voice models. Please reopen this issue if you start training a model from scratch.
