### ISSUE TITLE
Two errors Importerror and ignoring 2 things

### ISSUE THREAD

**Issue by fiachrab1** [CorentinJ/Real-Time-Voice-Cloning#880]
Hi, there I'm having issues regarding installing and running the Real-Time Voice Cloning Master tool from GitHub. everytime I try to install and run I get this error
importerror: DLL load failed: The specified module could not found

and I also have an error to do with "ignoring numpy/webrtcvad:- Don't match your environment
more details below
[github details.txt](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/7446454/github.details.txt)
![anaconda3 CMD 1](https://user-images.githubusercontent.com/93345484/139532287-f8e10ee1-8b9b-4dd6-9e1f-d6fcaed9980c.png)
![anaconda3 CMD 2](https://user-images.githubusercontent.com/93345484/139532288-e79e0ea2-64fa-4ada-a36b-7db8b8336d2c.png)
![anaconda3 CMD 3](https://user-images.githubusercontent.com/93345484/139532289-0d46b153-80d1-44ef-83f2-e132bfd1422b.png)
![anaconda3 CMD 4](https://user-images.githubusercontent.com/93345484/139532290-6558f627-f964-47c7-b5ee-f500703e36ba.png)

**Comment by blue-fish** [comment]
These setup instructions have worked very well for the community, if they are followed to the letter: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542
