### ISSUE TITLE
Followed your webpage instructions and receive ERROR after ERROR trying to install - final is 'sounddevice'

### ISSUE THREAD

**Issue by Mremenar** [CorentinJ/Real-Time-Voice-Cloning#882]
I followed the instructions to the letter at https://poorlydocumented.com/2019/11/installing-corentinjs-real-time-voice-cloning-project-on-windows-10-from-scratch/
I tried running " python demo_toolbox.py" and
I received the error "ModuleNotFoundError: No module named 'matplotlib'" -- fixed it by installing "python .\get-pip.py"
I tried running " python demo_toolbox.py" again and
I then received the error "ModuleNotFoundError: No module named 'matplotlib'" AGAIN and fixed it by "pip install matplotlib"
I tried running " python demo_toolbox.py" and received "ImportError: Failed to import any qt binding"
Fixed that by " pip install PyQt5"
I tried running " python demo_toolbox.py" again and received the error "ModuleNotFoundError: No module named 'scipy'"
Fixed that by "pip install scipy"
I tried running " python demo_toolbox.py" again and received the error "ModuleNotFoundError: No module named 'sklearn'"
Fixed that by "pip3 install -U scikit-learn scipy matplotlib"
I tried running " python demo_toolbox.py" again and received the error "ModuleNotFoundError: No module named 'librosa'"
Fixed that by running " pip install librosa"
I tried running " python demo_toolbox.py" again and received the error "ModuleNotFoundError: No module named 'sounddevice'"

What do I do now?  This is really frustrating.

**Comment by Bebaam** [comment]
Did the command "pip install -r requirements.txt" mentioned on the instruction site not work properly? It should have installed the neccessary packages.

**Comment by Mremenar** [comment]
Yes, I did it in the order indicated on the webpage.


“Fall seven times; stand up eight.”
—Japanese proverb

**Comment by Ca-ressemble-a-du-fake** [comment]
Hi,

Don't know what your system is, but did you try `python3` instead of `python` in `python demo_toolbox.py`?

**Comment by blue-fish** [comment]
The poorlydocumented.com instructions were written at a time when this repo required obsolete dependencies (Tensorflow 1.15) that made installation very difficult.

Since #472 we have removed the Tensorflow 1.x requirement which makes installation a lot easier. I suggest following this set of installation instructions for Windows: https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/642#issuecomment-768900542

**Comment by Mremenar** [comment]
Thank you blue-fish.  Can I use the #642 instructions like a band-aid for the previous install?  Or should I slate clean my PC from the previous python/cuda installation before attempt?

**Comment by Mremenar** [comment]
Sorry, I responded before reading #642.  I'll start from scratch.

**Comment by Mremenar** [comment]
I made it to number 8 on #642:

C:\Users\Dad>cd C:\Real-Time-Voice-Cloning-master

C:\Real-Time-Voice-Cloning-master>python -m venv venv

C:\Real-Time-Voice-Cloning-master>venv\Scripts\activate.bat

(venv) C:\Real-Time-Voice-Cloning-master>pip install --upgrade pip
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\Dad\\AppData\\Local\\Temp\\pip-uninstall-gezy930h\\pip.exe'
Consider using the `--user` option or check the permissions.


(venv) C:\Real-Time-Voice-Cloning-master>

**Comment by blue-fish** [comment]
@Mremenar Try running the Windows command prompt as administrator.

**Comment by Mremenar** [comment]
I did so.  It worked.  BUT... the link for ffmpeg in those instructions leads to an otherwise blank page with "Not Found" printed on it.
I did the previous version of ffmpeg and made it all the way to #13 of #642 and then received this error:

(venv) C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\toolbox\ui.py", line 6, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
ModuleNotFoundError: No module named 'torch'

(venv) C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>

**Comment by Mremenar** [comment]
and yes, I was running the command prompt as an administrator.

**Comment by Mremenar** [comment]
(venv) C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>pip install torch
Collecting torch
  Downloading torch-1.10.0-cp37-cp37m-win_amd64.whl (226.6 MB)
     |████████████████████████████████| 226.6 MB 70 kB/s
Collecting typing-extensions
  Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.10.0 typing-extensions-3.10.0.2

(venv) C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>python demo_toolbox.py
C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Librosa will be unable to open mp3 files if additional software is not installed.
Please install ffmpeg or add the '--no_mp3_support' option to proceed without support for mp3 files.

(venv) C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>pip install webrtcvad
Collecting webrtcvad
  Downloading webrtcvad-2.0.10.tar.gz (66 kB)
     |████████████████████████████████| 66 kB 1.5 MB/s
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for webrtcvad, since package 'wheel' is not installed.
Installing collected packages: webrtcvad
    Running setup.py install for webrtcvad ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\real-time-voice-cloning-master\venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dad\\AppData\\Local\\Temp\\pip-install-c1zgdi5d\\webrtcvad_10269592aace4f04b275a145791bf471\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dad\\AppData\\Local\\Temp\\pip-install-c1zgdi5d\\webrtcvad_10269592aace4f04b275a145791bf471\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dad\AppData\Local\Temp\pip-record-cdezpg5m\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\real-time-voice-cloning-master\venv\include\site\python3.7\webrtcvad'
         cwd: C:\Users\Dad\AppData\Local\Temp\pip-install-c1zgdi5d\webrtcvad_10269592aace4f04b275a145791bf471\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying webrtcvad.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_webrtcvad' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\real-time-voice-cloning-master\venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dad\\AppData\\Local\\Temp\\pip-install-c1zgdi5d\\webrtcvad_10269592aace4f04b275a145791bf471\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dad\\AppData\\Local\\Temp\\pip-install-c1zgdi5d\\webrtcvad_10269592aace4f04b275a145791bf471\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dad\AppData\Local\Temp\pip-record-cdezpg5m\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\real-time-voice-cloning-master\venv\include\site\python3.7\webrtcvad' Check the logs for full command output.

(venv) C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master>


And with that I'm going to bed.

**Comment by blue-fish** [comment]
> BUT... the link for ffmpeg in those instructions leads to an otherwise blank page with "Not Found" printed on it.

Thanks for reporting this. I have updated the ffmpeg link.

The instructions need to be followed to the letter to work. The extraction path in step 1 was messed up creating a nested folder. The simplest fix at this point is to move the ffmpeg.exe to `C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master` so Python can see it.

The `python demo_toolbox.py` command failed because it couldn't find ffmpeg. You do not need to install webrtcvad. If you really want it, you can avoid installing the Build Tools for Visual Studio by switching the command to `pip install webrtcvad-wheels`.

**Comment by Mremenar** [comment]
So I should move ffmpeg. exe (and ffplay.exe and ffprobe.exe?) from C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\ffmpeg-2021-10-21-git-2aa343bb6f-essentials_build\ffmpeg-2021-10-21-git-2aa343bb6f-essentials_build\bin and move them to C:\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master?
what about the bin doc and presets folders?

Thank you for your help, and additional thanks for your ongoing help.  It is appreciated!

**Comment by Mremenar** [comment]
(Sorry I updated the last comment,  I've been updating as maneuvering around through the software.  Still need your help!)

**Comment by blue-fish** [comment]
> The voices sound NOTHING like the originals.
> Hoping you have some directions for me to improve the output quality.

The quality is really hit and miss. Keep in mind the training data came from audiobooks. The model will struggle with background noise, music, or sound effects. The quality is something I am trying to improve, but it is difficult within the limitations of the SV2TTS framework, consumer hardware, and publicly-available datasets.

To better match a particular voice, you can try the single-speaker finetuning method I have described in #437. It involves making a labeled dataset and continuing the training of the pretrained models.

**Comment by blue-fish** [comment]
Closing this issue as the original problem has been resolved. Open a new issue to report other bugs or problems.
