### ISSUE TITLE
Using a different speaker encoder

### ISSUE THREAD

**Issue by AhmedHashish123** [CorentinJ/Real-Time-Voice-Cloning#884]
Hello, I really appreciate the work on display here. I was just wondering if I could use a different speaker encoder. If someone used a different encoder, could you explain the difficulties of replacing the encoder and how the results were different from the speaker encoder already in use?

**Comment by blue-fish** [comment]
The speaker encoder is the easiest part of the model to swap out. All you need to ensure is that the inference produces an output of the same size.

I'm still experimenting with the encoder and so far have only made small tweaks to architecture. One thing that surprises me is how similar the voice cloning output sounds compared to our pretrained models, even when the new encoder model produces a completely different embedding for the same utterance. It must all even out in the synthesizer training.

**Comment by AhmedHashish123** [comment]
Thank you, I will search the code for the inference part to check how the input goes into the model and where the output is passed to. When I find this part, I will replace it and make sure my output is a vector with the same size as the output of the original model.

**Comment by AhmedHashish123** [comment]
I found the inference inside toolbox in __init__.py:
embed, partial_embeds, _ = encoder.embed_utterance(encoder_wav, return_partials=True)

This function is called two times. What are "partial_embeds"? Do I need them? Or can I just pass them as none?

**Comment by blue-fish** [comment]
Partial embeds are described in section 3.3.2 of Corentin's thesis (link in README.md).

The toolbox does not use partial_embeds, so you can substitute None when making the Utterance namedtuple.

**Comment by AhmedHashish123** [comment]
Thank you, I replaced the speaker encoder with UniSpeech-SAT, but the results are very bad (it just outputs noise). I'll try to figure out what the problem is, could UniSpeech-SAT really change the output that much?

**Comment by blue-fish** [comment]
A synthesizer model is only compatible with the speaker encoder that generated the embeds used for training. So our pretrained synthesizer cannot be used with UniSpeech-SAT.

You'll need to train a new synthesizer from scratch (making sure to generate the embed data using your UniSpeech-SAT encoder model).

**Comment by AhmedHashish123** [comment]
Ok, thank you for the clarification.
