### ISSUE TITLE
generated audio file with maximum length of 25 seconds

### ISSUE THREAD

**Issue by Marcophono2** [CorentinJ/Real-Time-Voice-Cloning#885]
Hello!
Today I was surprised that the audio file for a long text was cut exactly after 25 seconds. I could reproduce this with other long text block too. Is this a known issue/restriction? I am using the griffin synthesizer and a Python api.

Best regards
Marc

**Comment by blue-fish** [comment]
It's this line of code. You can change `steps=2000` to a higher value to increase maximum generation time. This is a safeguard to prevent the synthesizer from getting stuck in an infinite loop. Each step is equal to 0.0125 sec.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/7432046efc23cabf176f9fdc8d2fd67020059478/synthesizer/models/tacotron.py#L417

**Comment by Marcophono2** [comment]
Aaaah! Thank you very much! I was sure that 25 (or 25,000) is a product of two parameters but I couldn't find them. Thank you, blue-fish!

Best regards
Marc

**Comment by OpeyemiOsakuade** [comment]
Thank you @blue-fish 

My own issue is that after about 5secs, the audio generated is no longer audible.
see sample below
[https://drive.google.com/file/d/1ktjdp_-mwxFul3UbWBTkfx8gkEpoky_-/view?usp=sharing](url)

**Comment by blue-fish** [comment]
@OpeyemiOsakuade If the synthesizer model is bad, or if the voice is very different from those seen in training data, it will cause problems. You can try training again, after improving the quality and possibly the quantity of your dataset.  You can also work around it by synthesizing shorter utterances and stitching those together.

**Comment by OpeyemiOsakuade** [comment]
Thank you @blue-fish

**Comment by bamel-yashvander** [comment]
Hey @Marcophono2 did you try to increase the sample size in order to generate longer texts? Did it work?

@CorentinJ When I increased the sample size, the voice quality got degraded and whole words started to end up in noise. Is this normal behaviour? Also can you suggest a way where longer texts can be generated from this?

BTW very nice work. I really appreciate it :)

**Comment by Marcophono2** [comment]
@bamel-yashvander Sorry that I'm so late! I didn't try it. I just accepted to use shorter texts. Not the best solution but acceptable in my case.

Best regards
Marc
