### ISSUE TITLE
Expression 'paInvalidSampleRate' failed 

### ISSUE THREAD

**Issue by rushic24** [CorentinJ/Real-Time-Voice-Cloning#887]
My headphones are working in demo_cli.py but not in demo_toolbox.

Can anyone help me debug this
```
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2050
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->playback, outParams, self->primeBuffers, hwParamsPlayback, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2724
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2845
Error opening OutputStream: Invalid sample rate [PaErrorCode -9997]



```

Thanks

**Comment by rushic24** [comment]
![image](https://user-images.githubusercontent.com/6279035/140625519-1084a399-139f-42bf-b4a9-32a633b161df.png)

**Comment by blue-fish** [comment]
This section of code is used to detect valid audio output devices. It is possible that the line 172 warning is not being displayed because your headphones have an integrated microphone and are considered an "input device".
https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/7432046efc23cabf176f9fdc8d2fd67020059478/toolbox/ui.py#L154-L172

**Comment by blue-fish** [comment]
@rushic24 Can you remove the `if not device["name"] in input_devices: ` on line 171 of [toolbox/ui.py](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/7432046efc23cabf176f9fdc8d2fd67020059478/toolbox/ui.py#L171) and let us know what warnings you see when starting up the toolbox?

**Comment by rushic24** [comment]
Thanks  @blue-fish , I have no idea why but it is working today

**Comment by blue-fish** [comment]
Thanks for the update @rushic24 . If it stops working, please reopen the issue and provide the warning message.
