### ISSUE TITLE
The voice is way too different can anyone explain how to improve?

### ISSUE THREAD

**Issue by rushic24** [CorentinJ/Real-Time-Voice-Cloning#888]
I was trying an audio from this clip https://youtu.be/ZZuWSkuqjPA downloaded and converted to wav.
There is a lot of krrrr krrr noise in the output.

I tried passing a 30sec, 5 min, 10min clips, and also cleaned the WAV files with noise reduction in audacity and gave them as input; still no difference

**Comment by blue-fish** [comment]
In #437, I describe a method to finetune the pretrained models to a single target voice. It requires making a dataset of short audios and transcripts.
