### ISSUE TITLE
Training Tacotron2

### ISSUE THREAD

**Issue by e0xextazy** [CorentinJ/Real-Time-Voice-Cloning#889]
Hi. I am still trying to successfully train the second tacotron. I took your advice and got rid of the bottle neck that was the line layer. At the moment I'm trying to train the architecture taken from Nvidia, but I only extended the input for the attention layer from 512 to 768 and added a speaker vector there, everything else I left unchanged. 
I also changed the batch size to 12 so that everything would fit on the GPU.
I now have 49k steps in about 48 hours, that's about a full 2 epochs.
As data I took open datasets in English LibriTTS, HiFi TTS and VCTK.
Attached are the graphs I have so far.
Would love to get some feedback or advice from you. If any other information is needed for your opinion, I am willing to provide it.
Thanks for maintaining the repository and answering questions.
![Снимок экрана 2021-11-12 в 19 23 26](https://user-images.githubusercontent.com/49094658/141501872-b1695851-d695-4110-884b-76962c13ea17.png)
![Снимок экрана 2021-11-12 в 19 23 46](https://user-images.githubusercontent.com/49094658/141501881-ed996a7b-59ce-4d5d-881c-f8db5c40d571.png)
![Снимок экрана 2021-11-12 в 19 25 27](https://user-images.githubusercontent.com/49094658/141501887-dadb7557-1f5d-4936-aaee-635ea55ad541.png)
![Снимок экрана 2021-11-12 в 19 25 33](https://user-images.githubusercontent.com/49094658/141501888-cd4f6171-0810-4c83-b943-3c65814843fe.png)
![Снимок экрана 2021-11-12 в 19 26 28](https://user-images.githubusercontent.com/49094658/141501889-87fb9ccb-f6c8-4131-9b1b-964a73bcc94d.png)
![Снимок экрана 2021-11-12 в 19 26 36](https://user-images.githubusercontent.com/49094658/141501891-a3a20c4e-c495-43ff-a681-7da84ecdd42d.png)

**Comment by blue-fish** [comment]
I will help you with this when our repo supports Tacotron2.

**Comment by blue-fish** [comment]
Please retry the training with our code.
https://github.com/blue-fish/Real-Time-Voice-Cloning/tree/878_tacotron2

It is very difficult to learn attention with no reduction factor, as explained [here](https://erogol.com/gradual-training-with-tacotron-for-faster-convergence/). I recommend `hparams.n_frames_per_step=2` or higher.

**Comment by e0xextazy** [comment]
Thank you very much! I think we can close the issue.

**Comment by inji0129** [comment]
> Thank you very much! I think we can close the issue.

Is it possible for you to share synthesizer code with Tacotron2 model?

**Comment by Raha304** [comment]
> > Thank you very much! I think we can close the issue.
> 
> @e0xextazy Is it possible for you to share synthesizer code with Tacotron2 model?

@inji0129 Can you get me this code please, if you can get this?
