### ISSUE TITLE
Can I train on TPU ?

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [CorentinJ/Real-Time-Voice-Cloning#896]
Hi,

Tensor processing units (TPU) are available on Colab. Does it make sense to train on TPU ?
I tried to run the original code but it was very slow (much much slower than on GPU). There is a [library](https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/getting-started.ipynb) that allows PyTorch code to run on TPU.

I am very new to neural network and I am not skilled enough to deeply modify code. Would the following changes be enough, or more deep changes are required :

In `train.py` add

`\# imports pytorch

import torch

\# imports the torch_xla package
import torch_xla
import torch_xla.core.xla_model as xm`

And then instead of using `device = torch.device("cpu")` use `device = xm.xla_device()`.
Would this be the only locations where code needs to be changed ?

**Comment by Ca-ressemble-a-du-fake** [comment]
According to [PyTorchXLA documentation](https://pytorch.org/xla/release/1.9/index.html#) there is only a "couple lines" to convert vanilla PyTorch code to TPU capable code :

> This snippet highlights how easy it is to switch your model to run on XLA. The model definition, dataloader, optimizer and training loop can work on any device. The only XLA-specific code is a couple lines that acquire the XLA device and mark the step. Calling xm.mark_step() at the end of each training iteration causes XLA to execute its current graph and update the model’s parameters.

**Comment by Ontopic** [comment]
I was able to run it on a TPU, but I'm not sure if I actualy used the TPU. I had a small dataset for some preliminary testing, so didn't explore any potential speed upgrades. I would unless it's not running not mess with the devices in a "strange codebase". XLA is probably the module I had the most issues ever with in my entire life of development (the versioning and different environments and everything being more cuda oriented, can become tough to find matching versions that play nice.

Still, for large scale training I'd like to know as well. Not expecting an answer here tbh (little experience with TPU) But let's post our findings here. Hope to get some tests in later today, will post what I find.

**Comment by Ca-ressemble-a-du-fake** [comment]
Thanks @Ontopic for sharing your experience with XLA. That's too bad if it is hard to set up. Looking forward to reading more about your tests !

**Comment by Ca-ressemble-a-du-fake** [comment]
So I tried to use the TPU but it is not trivial now. It looks like the training process stops on the first [forward pass](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/7432046efc23cabf176f9fdc8d2fd67020059478/synthesizer/train.py#L178 ) 

Maybe the problem stems from XLA using PyTorch 1.9 whereas I was using PyTorch 1.10 so far.

**Comment by Ca-ressemble-a-du-fake** [comment]
Oh no, it is actually working. But after 17 minutes not a single step has been computed!

**Comment by Ca-ressemble-a-du-fake** [comment]
After 4 hours the process is not running anymore. TPU use looks more complicated than my first approach as depicted there https://huggingface.co/blog/pytorch-xla
