### ISSUE TITLE
assertion error regarding to the  data set root

### ISSUE THREAD

**Issue by mithisha** [CorentinJ/Real-Time-Voice-Cloning#901]
![Screenshot (207)](https://user-images.githubusercontent.com/56795863/142745540-17019fe0-ff39-4597-8724-ba35659d4ae7.png)

**Comment by Ca-ressemble-a-du-fake** [comment]
You did not specify a datasets_root. Look at [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Training#preprocessing-and-training) for a guide.
