### ISSUE TITLE
Synthesizer fine-tuning ruined the output

### ISSUE THREAD

**Issue by Fzr2k** [CorentinJ/Real-Time-Voice-Cloning#903]
We were trying to fine-tune the existing model on some of our own data. We were faced with this error. 

![error1_before_traiining](https://user-images.githubusercontent.com/94923576/143072345-fb8cd809-c8c5-4288-84a2-fd265681c006.png)

We went into the synthesizer/train.py file and commented out the line 192(which was an if condition)
After that, the model started training but after training(for 2k steps), we were getting no output at all. Can you please identify what might have caused this? Thank you.

**Comment by blue-fish** [comment]
Synthesizer model fine-tuning is not a supported function of this repo, so I am going to close this issue and any similar ones that are opened in the future. However, I will make one quick comment to help point you in the right direction. Pay attention to this part of the screen output:

```
Loading weights at synthesizer\saved_models\my_run\my_run.pt
Tacotron weights loaded from step 0
```

Make sure that the name you are assigning to the run (here `my_run`) has a pretrained model located at `synthesizer\saved_models\<name_of_run>`. If it can't find a model, it trains a new one from scratch. That is what is happening here, with a new model initialized at step 0.

Try copying the `synthesizer\saved_models\pretrained\pretrained.pt` over to `synthesizer\saved_models\my_run\my_run.pt` and start the training again. You should see weights initialized at step 295000.

**Comment by Fzr2k** [comment]
Thank you so much for your help.
