### ISSUE TITLE
We do we need Librispeech alignments when training synthesizer and the vocoder?

### ISSUE THREAD

**Issue by jjl1994** [CorentinJ/Real-Time-Voice-Cloning#91]
Hi, I'm confused. For training synthesizer (tacotron2) we should only need transcript and mel-spectrogram. For training vocoder we should only need the mel-spectrogram and the raw wave form. Why do we need to generate force alignments of librispeech for training synthesizer and the vocoder?

**Comment by CorentinJ** [comment]
They're not mandatory, simply they allow to split long sentences into shorter ones and to profile the unvoiced regions for noise.

From the [SV2TTS paper](https://arxiv.org/pdf/1806.04558.pdf), section 3:
> We resegmented the data into shorter utterances by force aligning the audio to the transcript using an ASR model and breaking segments on silence, reducing the median duration from 14 to 5 seconds
