### ISSUE TITLE
Help requested while refactoring code to PyTorch Lightning 

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [CorentinJ/Real-Time-Voice-Cloning#910]
Hi,
I've [refactored the code from PyTorch to PyTorch Lightning](https://github.com/Ca-ressemble-a-du-fake/Real-Time-Voice-Cloning/blob/lightning/synthesizer/train.py), because Lightning brings up features I wanted to try such as :
- training on CPU / GPU / multi GPUs / TPU without code changes, 
- progress bar
- use of 16 bit precision automatically
- automatically finding the fitting hyperparameters

According to [Lightning guide](https://pytorch-lightning.readthedocs.io/en/stable/starter/new-project.html), converting PyTorch code to PyTorch Lightning consists in moving parts of the code into some specific functions. 

So the changes have been made in `synthesizer/model/tacotron`, and in `synthesizer/train.py`. 

But since I am not experienced with deep learning I may have made some mistakes while porting code to Lightning. **So if anyone experienced with DL is interested in that port to Lightning, I would love to get a peer review from them**. By the way I don't know if the Lightning version should come on this repo (@blue-fish should I start a pull request) ? 

So here are the changes I am really not sure about : 

1. In the training step (the "meat" as they call it), the [`stop_loss` computation](https://github.com/Ca-ressemble-a-du-fake/Real-Time-Voice-Cloning/blob/dbabdd64eb2a878103ed733c7325b2731be93c71/synthesizer/models/tacotron.py#L579) was changed  from `binary_cross_entropy` to `binary_cross_entropy_with_logits` because Lightning was complaining. Is it compatible ?
2. I removed that part of original code because it did not seem to be part of the training step. Where should it go to ?
>             if hparams.tts_clip_grad_norm is not None:
>                   grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), hparams.tts_clip_grad_norm)
>                    if np.isnan(grad_norm.cpu()):
>                      print("grad_norm was NaN!")
3. In the [validation step ](https://github.com/Ca-ressemble-a-du-fake/Real-Time-Voice-Cloning/blob/4da69910d54758ca10ef51543ef69ef4fd0d88da/synthesizer/models/tacotron.py#L622) the  `eval_model` was added, but I am not sure it's the right location.

Hope this is the right place to post this help request, otherwise feel free to close it!

**Comment by Fzr2k** [comment]
Were you successful in refactoring the code to pyTorch lightning?

**Comment by Ca-ressemble-a-du-fake** [comment]
I refactored to be able to run on TPU but wasn't successful with it. Otherwise as far as I remember training could run on GPU. Have a look at https://github.com/Ca-ressemble-a-du-fake/Real-Time-Voice-Cloning/tree/lightning .
