### ISSUE TITLE
I meet a prolem aoubt encoder_processes.py for voxcel2

### ISSUE THREAD

**Issue by sunnnnnnnny** [CorentinJ/Real-Time-Voice-Cloning#92]
Hello, I need your help. I have been dealing with voxcel2 for two days in encoder_processes.py. I really don't know how to do it. Multithreading can be successfully completed when processing voxcel1. When processing from voxcel2, the program will be stuck there and will not generate npy files. Can you give me some help?

voxceleb1:   0%|                                          | 3/1252 [04:03<47:00:25, 135.49s/speakers]
This is the process of voxcel1 processing, the progress bar is moving

while 
voxceleb2:   0%|                                                      | 0/5994 [00:00<?, ?speakers/s]
Waiting for one day is the result, and no npy file is generated.

The directory of my voxcel2 file is as follows：
‘’voxceleb2/dev/aac/id01223/Eiloi2m6nYw/00107.m4a‘’

**Comment by CorentinJ** [comment]
Are you running voxceleb2 independently from voxceleb1 (with `--datasets=voxceleb2`)?

**Comment by sunnnnnnnny** [comment]
yes,it is.
parser.add_argument("-d", "--datasets", type=str,default="voxceleb2")
Does it may cause some bad case?

**Comment by CorentinJ** [comment]
You can run the preprocessing in a single thread to be able to debug issues better. Replace [these lines](https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/encoder/preprocess.py#L113-L116) by:
`list(tqdm(map(preprocess_speaker, speaker_dirs), dataset_name, len(speaker_dirs), unit="speakers"))`

**Comment by sunnnnnnnny** [comment]
What you mean is to also remove this line “with ThreadPool(30) as pool:” and only use ：
`list(tqdm(map(preprocess_speaker, speaker_dirs), dataset_name, len(speaker_dirs), unit="speakers"))`

**Comment by sunnnnnnnny** [comment]
It’s really weird, I’ve done it according to you, and abandoning multithreaded programs is working fine.
`voxceleb2:   0%|                                                       | 5/5994 [01:21<26:39:08, 16.02s/speakers]`
The speed is a bit slow, but it is already very good, thank you for your patience.
