### ISSUE TITLE
This project needs a maintainer

### ISSUE THREAD

**Issue by ghost** [CorentinJ/Real-Time-Voice-Cloning#928]
This is blue-fish. Unfortunately, I cannot participate in open source anymore. It has been my pleasure to contribute to this project. I wish you all the best!

**Comment by Dannypeja** [comment]
Dear Mr. Blue-Fish, 

if you ever read this I want to tell you how much your experiments meaned to me as they helps so much in understanding how different parameters work and therefore opened the door to deeper understanding of this project. 

Whatever the reasons are you put everything offline, I wanted to really kindly ask if there was any possibility to reupload your experiments. With those files less work needs to be done to contribute to the project and to get a new maintainer. 
I would be really happy hearing from you some way in the future. 
If you want you can leave me a message at doctolibforme@gmail.com.

Wishing you all the very best, 
Dape

**Comment by DoubleF3lix** [comment]
Man, this makes me sad.

I wish you the best wherever you go.
