### ISSUE TITLE
Can't execute

### ISSUE THREAD

**Issue by santaonholidays** [CorentinJ/Real-Time-Voice-Cloning#935]
(base) PS D:\Real-Time-Voice-Cloning> python demo_toolbox.py
>>
Traceback (most recent call last):
  File "D:\Real-Time-Voice-Cloning\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\Real-Time-Voice-Cloning\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "D:\Real-Time-Voice-Cloning\toolbox\ui.py", line 6, in <module>
    from encoder.inference import plot_embedding_as_heatmap
ModuleNotFoundError: No module named 'encoder.inference'

What am i doing wrong?

**Comment by AlexSteveChungAlvarez** [comment]
Check if you have this directory inside the Real-Time-Voice-Cloning directory:
![image](https://user-images.githubusercontent.com/42816278/144909170-7719a479-fab3-4bd5-aad9-bb994666c227.png)

**Comment by santaonholidays** [comment]
Im not sure which directory youre pointing at

**Comment by AlexSteveChungAlvarez** [comment]
The one with name "encoder"

**Comment by santaonholidays** [comment]
hmm,all i have in my "encoder" is one file saved_models

**Comment by AlexSteveChungAlvarez** [comment]
Well, the project actually has all the files I showed you in the image. Try cloning again the project or pulling it to your local branch.

**Comment by santaonholidays** [comment]
I dragged it into the local branch,ran the demobox once again and got this 

No module named 'torch'

i installed pytorch too.do i have to deinstall it?
