### ISSUE TITLE
Can someone help he with this error

### ISSUE THREAD

**Issue by EkinUstundag** [CorentinJ/Real-Time-Voice-Cloning#937]
Hi, I'm trying to train on my dataset. It's from Mozilla datasets. However, when I start preprocessing, ıt gives this error. What should I do?
![Screenshot_14](https://user-images.githubusercontent.com/47627265/144708888-0c152c89-2a8e-44d7-a272-7b5430262896.png)

**Comment by D4RKH0R1Z0N** [comment]
SAY ME HOW TO TRAIN!?!?!?!

**Comment by D4RKH0R1Z0N** [comment]
I tried to clone my friends voice to prank him but I uploaded 2 to 3 minutes of his voice and just did Synthesize and Vocode to every audio file I had 3 of them

**Comment by EkinUstundag** [comment]
you don't need to train with your friends voice. If English just train with the datasets given, then give your friends voice to clone them.

**Comment by AlexSteveChungAlvarez** [comment]
If this issue is already fixed, don't forget to close it. Thanks!

**Comment by Bebaam** [comment]
U could try using utf-8, which is standard for me in linux instead of charmap, which is apparently standard in windows. Change line 77 in synthesizer/preprocess.py to:
with text_fpath.open("r",encoding="utf-8") as text_file:

Maybe you'll have this problem later again, I think you will always get the information in the error, so just repeat this step there, too. Let me know if that helps.

**Comment by EkinUstundag** [comment]
> U could try using utf-8, which is standard for me in linux instead of charmap, which is apparently standard in windows. Change line 77 in synthesizer/preprocess.py to: with text_fpath.open("r",encoding="utf-8") as text_file:
> 
> Maybe you'll have this problem later again, I think you will always get the information in the error, so just repeat this step there, too. Let me know if that helps.

I think it solved that issue thanks. However, it still says "UserWarning: PySoundFile failed. Trying audioread instead."
Do you know how to solve this or I do not need it since it is just a warning?

**Comment by Bebaam** [comment]
ok. Yeah, u can ignore it, I also get this warning.
