### ISSUE TITLE
Can not find the three Pretrained model

### ISSUE THREAD

**Issue by ZSTUMathSciLab** [CorentinJ/Real-Time-Voice-Cloning#939]
![image](https://user-images.githubusercontent.com/41334152/144902001-52e45a9e-4c78-4c1d-90c2-7a8037df96df.png)

I intended to download these models, but find nothing.

encoder\saved_models\pretrained.pt
synthesizer\saved_models\pretrained\pretrained.pt
vocoder\saved_models\pretrained\pretrained.pt
Any guys know why?  Or can somebody just share them with me?
Thank you.

**Comment by AlexSteveChungAlvarez** [comment]
I put them in a drive, check this: https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/929#issuecomment-984159090
