### ISSUE TITLE
Pretrained Models link is dead

### ISSUE THREAD

**Issue by DimensionWarped** [CorentinJ/Real-Time-Voice-Cloning#942]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models

The download links on this page are giving me page not found errors.

This link is specifically dead - https://github.com/blue-fish/Real-Time-Voice-Cloning/releases/download/v1.0/pretrained.zip

**Comment by Dannypeja** [comment]
blue-fish "died" seven days ago :( 

#928

**Comment by francisco-renteria** [comment]
I have uploaded a copy of July 21 https://drive.google.com/drive/folders/1aPYBbabQGNFHp6DegcKhfwNyLTXcKg5f?usp=sharing

**Comment by tadam98** [comment]
https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models link is dead,

**Comment by tadam98** [comment]
The code is not yet running so I cannot tell.

There is a set of pre-trained models here: https://drive.google.com/file/d/1n1sPXvT34yXFLT47QZA6FIRGrwMeSsZc/view which is in the github.

**Comment by rohitdavas** [comment]
Please see : https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/929#issuecomment-984159090 

I checked. All .pt files are in the drive. 
#929
