### ISSUE TITLE
Re-Building Blue-Fish's Legacy

### ISSUE THREAD

**Issue by Dannypeja** [CorentinJ/Real-Time-Voice-Cloning#944]
I find it so incredibly sad that blue-fish not only left as the maintainer but also took all of his experiments with him. Now we don't have anything to compare against when retraining our own models. 
Some of us where lucky to download his RTVC 7 Model. Out of pure chance I copied the description of how it was trained. 
If there are any more informations and comparisons on previous models I would be so happy to read and especially hear about the. The audio samples were priceless for learning...

Hopefully more information will flow into this in the future.
@Blue-fish: If you every come back we will greet you with fanfares and confetti!

<h2>RTVC-7 Model Overview</h2>

  | Name | Model | Steps | Batch Size | Datasets Used | Speakers | Audio Duration
-- | -- | -- | -- | -- | -- | -- | --
Speaker Encoder: | Pretrained | GE2E | 1,564,501 | 64 | LibriSpeech train-other-500VoxCeleb1 Dev A-DVoxCeleb2 Dev A-H | 8371 | 3201 hours
Synthesizer: | LS_Taco1_295k | Tacotron 1 | 285,000 | 12 | LibriSpeech train-clean-100LibriSpeech train-clean-360 | 1172 | 436 hours
Synthesizer: | LS_Taco1_295k | Tacotron 1 |10,000 | 12 | LibriTTS train-clean-100LibriTTS train-clean-360 | 1172 | 245 hours
Vocoder: | LS_GTA_1159k | WaveRNN | 1,159,000 | 50 | LibriSpeech train-clean-100LibriSpeech train-clean-360 | 1172 | 436 hours

## Download: 
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/942#issuecomment-989265348
This overlaps with what I downloaded as RTVC 7 so it should be the latest english model.

**Comment by laavender1** [comment]
Do you have the pretrained.pt models that was on this link?

https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models

Unfortunately, it went down, and I can't get the files

**Comment by sveneschlbeck** [comment]
@Dannypeja I already contacted Corentin about this. This project definitely needs a maintainer, otherwise it will be undocumented, crowded with issues and out-fashioned in a short period of time...
