### ISSUE TITLE
Missing synthesizer pretrained.pt

### ISSUE THREAD

**Issue by AsterTheWanderer** [CorentinJ/Real-Time-Voice-Cloning#948]
I already tried these files
https://drive.google.com/drive/folders/1aPYBbabQGNFHp6DegcKhfwNyLTXcKg5f?usp=sharing from Francisco
https://drive.google.com/drive/folders/1lb-LlS8Sx9RqcGzuV6GxvKHk-PC9TqQx?usp=sharing  from Alex
https://drive.google.com/file/d/1n1sPXvT34yXFLT47QZA6FIRGrwMeSsZc/view from RobbeW

I still get the `FileNotFoundError: [Errno 2] No such file or directory: 'synthesizer\\saved_models\\pretrained\\pretrained.pt'` any help?

**Comment by daddyzilla148** [comment]
For a price I can make it work

**Comment by AsterTheWanderer** [comment]
it's already been fixed

**Comment by AsterTheWanderer** [comment]
**Installation overly simplified **  by Aster

**Step 1**
> all you need to do is download the whole folder in the google drive it's the whole repo and the models are already included so you don't need to download it separately.

**Link:** https://drive.google.com/drive/folders/1couiJINgIAaT3R73_i1rkIFnSxl7reOh?usp=sharing

**Step 2** 
> You **MUST** run it using python 3.6 or 3.7
> run cd command to the folder 

**Example:** `cd  C:\Users\Asus\Downloads\Real-Time-Voice-Cloning-master`

**Step 3**
> check your numpy ver.
> You **MUST** have numpy ver below 1.20

> if you're using conda and doesn't have pip yet run `conda install pip`

> if you have numpy ver above 1.20 run command `pip uninstall numpy` 
> then run the command `pip install numpy==1.20` after uninstalling the numpy

> after that install pytorch (https://pytorch.org/get-started/locally/)

> pick in these options in the pytorch website
> **PyTorch Build** = Stable (1.10)
> **Your OS** = [pick the OS that you're using]
> **Package** = [pick the package you're using ex. Conda, pip, LibTorch, or Source]
> **Language** = Python
> **Compute Platform** = CUDA 10.2
> **Run this Command** = [a command should appear here. The command that appears here depends on your choices]

>  copy the command that appeared in the 'Run this command' 

**Example: **`conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`

**Step 4**
> install ffmpeg 
> run pip `install ffmpeg`

**Step 5**
> run `pip install -r requirements.txt` to install the remaining necessary packages. 

**Step 6 (completely optional)**
> run `python demo_cli.py` to check if there's any error. If there's none you're good to go.

**Step 7 **
> run the program
> run the command `python demo_toolbox.py`

Then you're done it should've run by now.

**Comment by alishkaDooblin** [comment]
,
I'm trying to run the Real-Time-Voice-Cloning project, but I can't find a working download link for the synthesizer.pt file.
I already have the encoder and vocoder models, but the synthesizer.pt (around ~71MB) is missing.
The link in the code tries to auto-download it from Google Drive, but that no longer works.

Could anyone please reupload the correct pretrained.zip (or just synthesizer.pt) file or share a working mirror?

Much appreciated! 🙏

**Comment by AsterTheWanderer** [comment]
this might be late but just fol

> **Installation overly simplified** by Aster
> 
> **Step 1**
> 
> > all you need to do is download the whole folder in the google drive it's the whole repo and the models are already included so you don't need to download it separately.
> 
> **Link:** https://drive.google.com/drive/folders/1couiJINgIAaT3R73_i1rkIFnSxl7reOh?usp=sharing
> 
> **Step 2**
> 
> > You **MUST** run it using python 3.6 or 3.7
> > run cd command to the folder
> 
> **Example:** `cd C:\Users\Asus\Downloads\Real-Time-Voice-Cloning-master`
> 
> **Step 3**
> 
> > check your numpy ver.
> > You **MUST** have numpy ver below 1.20
> 
> > if you're using conda and doesn't have pip yet run `conda install pip`
> 
> > if you have numpy ver above 1.20 run command `pip uninstall numpy`
> > then run the command `pip install numpy==1.20` after uninstalling the numpy
> 
> > after that install pytorch (https://pytorch.org/get-started/locally/)
> 
> > pick in these options in the pytorch website
> > **PyTorch Build** = Stable (1.10)
> > **Your OS** = [pick the OS that you're using]
> > **Package** = [pick the package you're using ex. Conda, pip, LibTorch, or Source]
> > **Language** = Python
> > **Compute Platform** = CUDA 10.2
> > **Run this Command** = [a command should appear here. The command that appears here depends on your choices]
> 
> > copy the command that appeared in the 'Run this command' then run it
> 
> **Example:** `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`
> 
> **Step 4**
> 
> > install ffmpeg
> > run `pip install ffmpeg`
> 
> **Step 5**
> 
> > run `pip install -r requirements.txt` to install the remaining necessary packages.
> 
> **Step 6 (completely optional)**
> 
> > run `python demo_cli.py` to check if there's any error. If there's none you're good to go.
> 
> **Step 7 **
> 
> > run the program
> > run the command `python demo_toolbox.py`
> 
> Then you're done it should've run by now.

this may be late but just follow this simplified guide I made
