### ISSUE TITLE
some files from the source have been removed

### ISSUE THREAD

**Issue by Aatularyan** [CorentinJ/Real-Time-Voice-Cloning#950]
some files from the source have been removed, unable to run the file after cloning the repository

**Comment by AsterTheWanderer** [comment]
have you tried downloading it directly?

**Comment by Aatularyan** [comment]
> have you tried downloading it directly?

Yes, i have tried.
The pretrained model page is displaying message "Not Found"

**Comment by raccoonML** [comment]
You can find the pretrained models in my copy of the repo.
https://github.com/raccoonML/Real-Time-Voice-Cloning/releases/tag/RTVC-7
