### ISSUE TITLE
Need mirror of vocoder.pt

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [CorentinJ/Real-Time-Voice-Cloning#968]
Try for 4 hourts to runt his repo

https://drive.google.com/drive/folders/1fU6umc5uQAVR2udZdHX-lDgXYzTyqG_j

then manual download and what **limits** 

Sorry, you can&#39;t view or download this file at this time.Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

**Comment by raccoonML** [comment]
If an alternative download location is needed, download the pretrained models zip file from this link and rename `vocoder/saved_models/pretrained/pretrained.pt` to vocoder.pt.

https://github.com/raccoonML/Real-Time-Voice-Cloning/releases/tag/RTVC-7

**Comment by gotshadowbantempaccount** [comment]
thank you, will be nice to have this link also in error when say please manually download from Gdrive, save lot of time
