### ISSUE TITLE
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

### ISSUE THREAD

**Issue by andkirby** [CorentinJ/Real-Time-Voice-Cloning#971]
Not sure how it can be solved. This is happened during installation `pip install -r requirements.txt`.

I've installed 
- build tools: https://visualstudio.microsoft.com/visual-cpp-build-tools/
- Visual C++ https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

What did I miss?

Env:
OS: Win 11, CLI: git-bash, Python: 3.9 (venv)

build tools install window:
![image](https://user-images.githubusercontent.com/1828532/148664530-a52647a3-8701-476c-957b-6778fff0518e.png)

**Comment by andkirby** [comment]
It works with "Desktop Development with C++". Not sure if everything is needed, but I finally completed installation.

![image](https://user-images.githubusercontent.com/1828532/148664790-f6cee607-f4f5-4a39-bfec-48436d233aea.png)

Possibly, you could mention this in installation guide.

**Comment by CorentinJ** [comment]
Guh, this is still a problem?
Do you know which package it was? Probably `webrtcvad`?

**Comment by andkirby** [comment]
Sorry, I don't know what is `webrtcvad`.
Just googled... This one https://github.com/wiseman/py-webrtcvad ?
What should I check?

**Comment by mfaizsyahmi** [comment]
I've had the same error and yes, it's webrtcvad.

**Comment by SuhruthY** [comment]
Yes! it's webrtcvad... I'm also having the same error

**Comment by mriamnobody** [comment]
> It works with "Desktop Development with C++". Not sure if everything is needed, but I finally completed installation.
> 
> ![image](https://user-images.githubusercontent.com/1828532/148664790-f6cee607-f4f5-4a39-bfec-48436d233aea.png)
> 
> Possibly, you could mention this in installation guide.

This worked for me. Thanks a lot @andkirby
