### ISSUE TITLE
Link to the `synthesizer.pt` from default_model.py is broken

### ISSUE THREAD

**Issue by daniil-lyakhov** [CorentinJ/Real-Time-Voice-Cloning#972]
Greetings! 
Can't launch `demo_cli.py` due to broken link to the default synthetizer checkpoint:

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/master/utils/default_models.py#L11

https://www.dropbox.com/s/r37koa6ho5prz7w/synthesizer.pt?dl=1

![image](https://user-images.githubusercontent.com/74656388/148679214-ec07aeea-26e9-4062-8a5b-15fb88c8c9d4.png)

Workaround: have downloaded checkpoint from [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models)

**Comment by CorentinJ** [comment]
Thanks for reporting.
Yeah dropbox won't let me keep this public link this size with this much traffic.
Google drive doesn't allow for direct download for files larger than 100mb. I tried to split the file in parts at some point but eventually gave up on that idea.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
> Thanks for reporting.
> Yeah dropbox won't let me keep this public link this size with this much traffic.
> Google drive doesn't allow for direct download for files larger than 100mb. I tried to split the file in parts at some point but eventually gave up on that idea.

use a cdn, proxied using cloudflare. 
a 10$ vps should do the work.


currently if you are not able to download the files, i have my own server: m.trycs.net/synthesizer.pt [1G uplink]

m.trycs.net/vocoder.pt
m.trycs.net/encoder.pt

**Comment by Rishi0812** [comment]
Solved the issue! Check out https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/1030
