### ISSUE TITLE
webrtcvad==2.0.10 isn't installing

### ISSUE THREAD

**Issue by BG-Cypo** [CorentinJ/Real-Time-Voice-Cloning#979]
Whenever I tried to install webrtcvad, it always shows this.

Collecting webrtcvad==2.0.10
  Using cached webrtcvad-2.0.10.tar.gz (66 kB)
Using legacy setup.py install for webrtcvad, since package 'wheel' is not installed.
Installing collected packages: webrtcvad
    Running setup.py install for webrtcvad ... error
    ERROR: Command errored out with exit status 1:
     command: 'e:\admin\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-mfsfwidn\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-mfsfwidn\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-gt0xgplv\install-record.txt' --single-version-externally-managed --compile --install-headers 'e:\admin\appdata\local\programs\python\python37\Include\webrtcvad'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-mfsfwidn\webrtcvad\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying webrtcvad.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_webrtcvad' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'e:\admin\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-mfsfwidn\\webrtcvad\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-mfsfwidn\\webrtcvad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-gt0xgplv\install-record.txt' --single-version-externally-managed --compile --install-headers 'e:\admin\appdata\local\programs\python\python37\Include\webrtcvad' Check the logs for full command output.

is there a way to solve this?

**Comment by BG-Cypo** [comment]
I figured it out.

**Comment by LongEcho** [comment]
For anyone who also encounters this problem:
I solved the Problem with installing the C++ Compiler. Her is how to do it on Ubuntu:
Install G++ with this command:
`sudo apt install g++`
Then install the Build essentails:
`sudo apt install build-essential`

I didn' t try it on Windows but it should work:
https://techdecodetutorials.com/c/how-to-install-c-compiler-in-windows-10/
