### ISSUE TITLE
Proper video poster image

### ISSUE THREAD

**Issue by szepeviktor** [CorentinJ/Real-Time-Voice-Cloning#98]
![image](https://user-images.githubusercontent.com/952007/63739966-85ab8600-c88f-11e9-8e58-99f54876a55c.png)

made by resizing my browser window to 882px and disabling `display:none` of the YouTube button

**Comment by CorentinJ** [comment]
Cool, thanks.

**Comment by szepeviktor** [comment]
You're welcome.

Could it be that while copying this new image its dimensions has changed???

# 650px × 364px

**Comment by CorentinJ** [comment]
I shrunk it to not occupy too much space, did you have something else in mind?

**Comment by szepeviktor** [comment]
It was made to be the same width as GitHub's README on desktop :(

**Comment by szepeviktor** [comment]
882 px

**Comment by CorentinJ** [comment]
Eh that's too big, I don't like that
