### ISSUE TITLE
If possible, change the title of the repository - as it is misleading 

### ISSUE THREAD

**Issue by un33k** [CorentinJ/Real-Time-Voice-Cloning#988]
Hello, 

I have asked a few of my ML friends for any reference to a "real-time" voice cloning software and they keep sending me the link to this repo.

"Real time" voice cloning is when I speak into a microphone, and someone else's voice comes out of a virtual audio interface in "real-time".

This is a "text-to-speach + clone" and has nothing to do with a "real-time" voice cloning. Am I wrong?

If I am wrong, I apologize, as I am hoping that I am directed to the right documentation. 

If I am right, then please remove the "real-time" from the title of the repository, so all google searches don't end up here.

Thanks, 
Val

**Comment by CorentinJ** [comment]
You're thinking of voice conversion, which transforms the voice in a given audio clip. Voice cloning means that you can reproduce the voice in general, i.e. on any text input. 

Faster than real time means that the audio generated is longer than the time it took to generate, which is generally true for this repo under some mild assumptions. What you're thinking of is online vs. offline, where an online version of TTS is able to playback speech as the remainder of the audio is still generating. Inference is fully offline for this repo, but could be made online with some development work.

**Comment by un33k** [comment]
@CorentinJ Thanks for the clarification!
