### ISSUE TITLE
what languages are supported

### ISSUE THREAD

**Issue by freecui** [CorentinJ/Real-Time-Voice-Cloning#99]
which data and languages do you use to pretrained model?  do that support Chinese

**Comment by CorentinJ** [comment]
English only. #30

**Comment by babysor** [comment]
Some projects of chinese pretrain model now are no longer accessible. I'm currently working on latest fork of this repo to support mandarin and if anyone want to use as reference, please be free to folk and train: https://github.com/babysor/Realtime-Voice-Clone-Chinese
