### ISSUE TITLE
Error in loading state_dict for SpeakerEncoder: size mismatch

### ISSUE THREAD

**Issue by EkinUstundag** [CorentinJ/Real-Time-Voice-Cloning#992]
Hi! I trained a synthesizer a month ago and I could synthesize my voice, too mechanical though, but now I got this error. How can I fix this?
![Screenshot_1](https://user-images.githubusercontent.com/47627265/150686315-da6761f9-e323-4538-8e70-66ccb0be40d7.png)

**Comment by Bebaam** [comment]
check if the embedding size of the encoder does fit to the size of your model in encoder/params_model.py
