### ISSUE TITLE
Use it to morph voice live

### ISSUE THREAD

**Issue by schuesslerf** [CorentinJ/Real-Time-Voice-Cloning#993]
Hello,

I'm wondering if this could somehow be used to morph the own voice live while speaking, like when doing a call.. Sounds phishy? That's because it is - I'm searching for a solution to use it in penetration testing, so I can use a voice sample of somebody and after training the model, I can talk with that voice in telephone calls... Any plan to implement such a feature or an idea how to use this repository to achieve that?

**Comment by CorentinJ** [comment]
This is a speech synthesis (voice cloning) repo, for voice conversion find open source projects here:
https://paperswithcode.com/task/voice-conversion
